CREATE TABLE Project_Dropdown_Task_FINAL_Ver_1_11_1_1 (
    `Column_1` VARCHAR(28) CHARACTER SET utf8,
    `Column_2` VARCHAR(17) CHARACTER SET utf8
);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Abbot',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Admiral','Adm.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Ambassador','Amb.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Baron',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Baroness',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Bishop',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Brigadier General','Brig. Gen.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Brother',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Captain (Army)','Cpt.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Captain (Navy)','Capt.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Chancellor','Chan.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Chaplain','Chapln.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Chief Petty Officer','CPO');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Commander','Cmdr.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Colonel','Col.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Colonel (Retired)','Col. (Ret.)');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Corporal','Cpl.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Count',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Countess',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Dame',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Dean',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Dr.',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Dr. & Mr.',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Dr. & Mrs.',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Duchess',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Duke',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Ensign','Ens.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Father',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Friar',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Frau',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('General','Gen.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Governor','Gov.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Judge',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Justice',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Lady',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Lord',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Lieutenant','Lt.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('2nd Lieutenant (Army)','2Lt.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('2nd Lieutenant (Marine/A.F.)','2dLt.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Lieutenant Commander','Lt. Cmdr. or Ltc.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Lieutenant Colonel','Lt. Col. or Ltc.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Lieutenant General','Lt. Gen. or Ltg.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Lieutenant junior grade','Lt. j.g.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Mademoiselle','Mlle.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Major','Maj.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Master',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Master Sergeant','Master Sgt.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Miss',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Madame','Mme.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Monsieur','M.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Monsignor','Msgr.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Mr.',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Mrs.',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Ms.',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('President','Pres.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Prince',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Princess',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Professor','Prof.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Rabbi',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Rear Admiral','R. Adm.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Representative','Rep.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Reverend','Rev.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Right Reverend','Rt. Rev.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Sergeant','Sgt.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Senator','Sen.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Senor','Sr.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Senora','Sra.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Senorita','Srta.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Sheikh',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Sir',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Sister','Sr.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Staff Sergeant','S. Sgt.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('The Honorable','The Hon.');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('The Venerable',NULL);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Vice Admiral','V. Adm.');
