CREATE TABLE data_animals (
    `Animals` VARCHAR(27) CHARACTER SET utf8
);
INSERT INTO data_animals VALUES ('Aardvark    ');
INSERT INTO data_animals VALUES ('Aardwolf    ');
INSERT INTO data_animals VALUES ('Albatross    ');
INSERT INTO data_animals VALUES ('Alligator    ');
INSERT INTO data_animals VALUES ('Alpaca    ');
INSERT INTO data_animals VALUES ('Amphibian    ');
INSERT INTO data_animals VALUES ('Anaconda    ');
INSERT INTO data_animals VALUES ('Angelfish    ');
INSERT INTO data_animals VALUES ('Anglerfish    ');
INSERT INTO data_animals VALUES ('Ant    ');
INSERT INTO data_animals VALUES ('Anteater    ');
INSERT INTO data_animals VALUES ('Antelope    ');
INSERT INTO data_animals VALUES ('Antlion    ');
INSERT INTO data_animals VALUES ('Ape    ');
INSERT INTO data_animals VALUES ('Aphid    ');
INSERT INTO data_animals VALUES ('Armadillo    ');
INSERT INTO data_animals VALUES ('Asp    ');
INSERT INTO data_animals VALUES ('Ass (donkey)   ');
INSERT INTO data_animals VALUES ('Baboon    ');
INSERT INTO data_animals VALUES ('Badger    ');
INSERT INTO data_animals VALUES ('Bandicoot    ');
INSERT INTO data_animals VALUES ('Barnacle    ');
INSERT INTO data_animals VALUES ('Barracuda    ');
INSERT INTO data_animals VALUES ('Basilisk    ');
INSERT INTO data_animals VALUES ('Bass    ');
INSERT INTO data_animals VALUES ('Bat    ');
INSERT INTO data_animals VALUES ('Bat, fruit  ');
INSERT INTO data_animals VALUES ('Bat, vampire  ');
INSERT INTO data_animals VALUES ('Bear    ');
INSERT INTO data_animals VALUES ('Bear, grizzly  ');
INSERT INTO data_animals VALUES ('Bear, polar  ');
INSERT INTO data_animals VALUES ('Beaver    ');
INSERT INTO data_animals VALUES ('Bedbug    ');
INSERT INTO data_animals VALUES ('Bee    ');
INSERT INTO data_animals VALUES ('Beetle    ');
INSERT INTO data_animals VALUES ('Beetle, dung  ');
INSERT INTO data_animals VALUES ('Bird    ');
INSERT INTO data_animals VALUES ('Bird, blue  ');
INSERT INTO data_animals VALUES ('Bison    ');
INSERT INTO data_animals VALUES ('Blackbird    ');
INSERT INTO data_animals VALUES ('Boa    ');
INSERT INTO data_animals VALUES ('Boa, water  ');
INSERT INTO data_animals VALUES ('Boar (wild pig)  ');
INSERT INTO data_animals VALUES ('Bobcat    ');
INSERT INTO data_animals VALUES ('Bobolink    ');
INSERT INTO data_animals VALUES ('Bonobo    ');
INSERT INTO data_animals VALUES ('Booby    ');
INSERT INTO data_animals VALUES ('Bovid    ');
INSERT INTO data_animals VALUES ('Buffalo, african   ');
INSERT INTO data_animals VALUES ('Buffalo, american (bison)  ');
INSERT INTO data_animals VALUES ('Buffalo, cape  ');
INSERT INTO data_animals VALUES ('Buffalo, water  ');
INSERT INTO data_animals VALUES ('Bug    ');
INSERT INTO data_animals VALUES ('Butterfly    ');
INSERT INTO data_animals VALUES ('Buzzard    ');
INSERT INTO data_animals VALUES ('Camel    ');
INSERT INTO data_animals VALUES ('Canid    ');
INSERT INTO data_animals VALUES ('Capybara    ');
INSERT INTO data_animals VALUES ('Cardinal    ');
INSERT INTO data_animals VALUES ('Caribou    ');
INSERT INTO data_animals VALUES ('Carp    ');
INSERT INTO data_animals VALUES ('Cat    ');
INSERT INTO data_animals VALUES ('Cat, saber-toothed  ');
INSERT INTO data_animals VALUES ('Caterpillar    ');
INSERT INTO data_animals VALUES ('Catfish    ');
INSERT INTO data_animals VALUES ('Catshark    ');
INSERT INTO data_animals VALUES ('Cattle    ');
INSERT INTO data_animals VALUES ('Centipede    ');
INSERT INTO data_animals VALUES ('Cephalopod    ');
INSERT INTO data_animals VALUES ('Chameleon    ');
INSERT INTO data_animals VALUES ('Cheetah    ');
INSERT INTO data_animals VALUES ('Chickadee    ');
INSERT INTO data_animals VALUES ('Chicken    ');
INSERT INTO data_animals VALUES ('Chimpanzee    ');
INSERT INTO data_animals VALUES ('Chinchilla    ');
INSERT INTO data_animals VALUES ('Chipmunk    ');
INSERT INTO data_animals VALUES ('Cicada    ');
INSERT INTO data_animals VALUES ('Clam    ');
INSERT INTO data_animals VALUES ('Clownfish    ');
INSERT INTO data_animals VALUES ('Cobra    ');
INSERT INTO data_animals VALUES ('Cockroach    ');
INSERT INTO data_animals VALUES ('Cod    ');
INSERT INTO data_animals VALUES ('Condor    ');
INSERT INTO data_animals VALUES ('Constrictor    ');
INSERT INTO data_animals VALUES ('Coral    ');
INSERT INTO data_animals VALUES ('Cougar    ');
INSERT INTO data_animals VALUES ('Cow    ');
INSERT INTO data_animals VALUES ('Coyote    ');
INSERT INTO data_animals VALUES ('Crab    ');
INSERT INTO data_animals VALUES ('Crab, arrow  ');
INSERT INTO data_animals VALUES ('Crab, hermit  ');
INSERT INTO data_animals VALUES ('Crane    ');
INSERT INTO data_animals VALUES ('Crane, whooping  ');
INSERT INTO data_animals VALUES ('Crawdad    ');
INSERT INTO data_animals VALUES ('Crayfish    ');
INSERT INTO data_animals VALUES ('Cricket    ');
INSERT INTO data_animals VALUES ('Crocodile    ');
INSERT INTO data_animals VALUES ('Crow    ');
INSERT INTO data_animals VALUES ('Cuckoo    ');
INSERT INTO data_animals VALUES ('Damselfly    ');
INSERT INTO data_animals VALUES ('Deer    ');
INSERT INTO data_animals VALUES ('Devil, tasmanian  ');
INSERT INTO data_animals VALUES ('Dingo    ');
INSERT INTO data_animals VALUES ('Dinosaur    ');
INSERT INTO data_animals VALUES ('Dog    ');
INSERT INTO data_animals VALUES ('Dog, prairie  ');
INSERT INTO data_animals VALUES ('Dolphin    ');
INSERT INTO data_animals VALUES ('Donkey    ');
INSERT INTO data_animals VALUES ('Dormouse    ');
INSERT INTO data_animals VALUES ('Dove    ');
INSERT INTO data_animals VALUES ('Dragon    ');
INSERT INTO data_animals VALUES ('Dragon, komodo  ');
INSERT INTO data_animals VALUES ('Dragonfly    ');
INSERT INTO data_animals VALUES ('Duck    ');
INSERT INTO data_animals VALUES ('Eagle    ');
INSERT INTO data_animals VALUES ('Eagle, bald  ');
INSERT INTO data_animals VALUES ('Earthworm    ');
INSERT INTO data_animals VALUES ('Earwig    ');
INSERT INTO data_animals VALUES ('Echidna    ');
INSERT INTO data_animals VALUES ('Eel    ');
INSERT INTO data_animals VALUES ('Egret    ');
INSERT INTO data_animals VALUES ('Elephant    ');
INSERT INTO data_animals VALUES ('Elephant, african  ');
INSERT INTO data_animals VALUES ('Elk    ');
INSERT INTO data_animals VALUES ('Emu    ');
INSERT INTO data_animals VALUES ('Ermine    ');
INSERT INTO data_animals VALUES ('Falcon    ');
INSERT INTO data_animals VALUES ('Falcon, peregrine  ');
INSERT INTO data_animals VALUES ('Ferret    ');
INSERT INTO data_animals VALUES ('Finch    ');
INSERT INTO data_animals VALUES ('Finch, zebra  ');
INSERT INTO data_animals VALUES ('Firefly    ');
INSERT INTO data_animals VALUES ('Fish    ');
INSERT INTO data_animals VALUES ('Fish, x-ray  ');
INSERT INTO data_animals VALUES ('Flamingo    ');
INSERT INTO data_animals VALUES ('Flea    ');
INSERT INTO data_animals VALUES ('Fly    ');
INSERT INTO data_animals VALUES ('Fly, crane  ');
INSERT INTO data_animals VALUES ('Flyingfish    ');
INSERT INTO data_animals VALUES ('Fowl    ');
INSERT INTO data_animals VALUES ('Fox    ');
INSERT INTO data_animals VALUES ('Fox, arctic  ');
INSERT INTO data_animals VALUES ('Frog    ');
INSERT INTO data_animals VALUES ('Frog, tree  ');
INSERT INTO data_animals VALUES ('Galliform    ');
INSERT INTO data_animals VALUES ('Gamefowl    ');
INSERT INTO data_animals VALUES ('Gazelle    ');
INSERT INTO data_animals VALUES ('Gecko    ');
INSERT INTO data_animals VALUES ('Gerbil    ');
INSERT INTO data_animals VALUES ('Gibbon    ');
INSERT INTO data_animals VALUES ('Giraffe    ');
INSERT INTO data_animals VALUES ('Glider, sugar  ');
INSERT INTO data_animals VALUES ('Goat    ');
INSERT INTO data_animals VALUES ('Goat, mountain  ');
INSERT INTO data_animals VALUES ('Goldfish    ');
INSERT INTO data_animals VALUES ('Goose    ');
INSERT INTO data_animals VALUES ('Gopher    ');
INSERT INTO data_animals VALUES ('Gorilla    ');
INSERT INTO data_animals VALUES ('Grasshopper    ');
INSERT INTO data_animals VALUES ('Grouse    ');
INSERT INTO data_animals VALUES ('Guan    ');
INSERT INTO data_animals VALUES ('Guanaco    ');
INSERT INTO data_animals VALUES ('Guineafowl    ');
INSERT INTO data_animals VALUES ('Gull    ');
INSERT INTO data_animals VALUES ('Guppy    ');
INSERT INTO data_animals VALUES ('Haddock    ');
INSERT INTO data_animals VALUES ('Halibut    ');
INSERT INTO data_animals VALUES ('Hamster    ');
INSERT INTO data_animals VALUES ('Hare    ');
INSERT INTO data_animals VALUES ('Harrier    ');
INSERT INTO data_animals VALUES ('Hawk    ');
INSERT INTO data_animals VALUES ('Hedgehog    ');
INSERT INTO data_animals VALUES ('Heron    ');
INSERT INTO data_animals VALUES ('Heron, great blue ');
INSERT INTO data_animals VALUES ('Herring    ');
INSERT INTO data_animals VALUES ('Hippopotamus    ');
INSERT INTO data_animals VALUES ('Hookworm    ');
INSERT INTO data_animals VALUES ('Hornet    ');
INSERT INTO data_animals VALUES ('Horse    ');
INSERT INTO data_animals VALUES ('Hoverfly    ');
INSERT INTO data_animals VALUES ('Hummingbird    ');
INSERT INTO data_animals VALUES ('Hybrid, panthera  ');
INSERT INTO data_animals VALUES ('Hyena    ');
INSERT INTO data_animals VALUES ('Iguana    ');
INSERT INTO data_animals VALUES ('Impala    ');
INSERT INTO data_animals VALUES ('Insect, scale  ');
INSERT INTO data_animals VALUES ('Jackal    ');
INSERT INTO data_animals VALUES ('Jaguar    ');
INSERT INTO data_animals VALUES ('Jay    ');
INSERT INTO data_animals VALUES ('Jay, blue  ');
INSERT INTO data_animals VALUES ('Jellyfish    ');
INSERT INTO data_animals VALUES ('Jellyfish, box  ');
INSERT INTO data_animals VALUES ('Jellyfish, irukandji  ');
INSERT INTO data_animals VALUES ('Junglefowl    ');
INSERT INTO data_animals VALUES ('Kangaroo    ');
INSERT INTO data_animals VALUES ('Kingfisher    ');
INSERT INTO data_animals VALUES ('Kite    ');
INSERT INTO data_animals VALUES ('Kiwi    ');
INSERT INTO data_animals VALUES ('Koala    ');
INSERT INTO data_animals VALUES ('Koi    ');
INSERT INTO data_animals VALUES ('Krill    ');
INSERT INTO data_animals VALUES ('Ladybug    ');
INSERT INTO data_animals VALUES ('Lamprey    ');
INSERT INTO data_animals VALUES ('Landfowl    ');
INSERT INTO data_animals VALUES ('Lark    ');
INSERT INTO data_animals VALUES ('Leech    ');
INSERT INTO data_animals VALUES ('Lemming    ');
INSERT INTO data_animals VALUES ('Lemur    ');
INSERT INTO data_animals VALUES ('Leopard    ');
INSERT INTO data_animals VALUES ('Leopard, african  ');
INSERT INTO data_animals VALUES ('Leopard, arabian  ');
INSERT INTO data_animals VALUES ('Leopard, snow  ');
INSERT INTO data_animals VALUES ('Leopon    ');
INSERT INTO data_animals VALUES ('Limpet    ');
INSERT INTO data_animals VALUES ('Lion    ');
INSERT INTO data_animals VALUES ('Lion, sea  ');
INSERT INTO data_animals VALUES ('Lizard    ');
INSERT INTO data_animals VALUES ('Lizard, monitor  ');
INSERT INTO data_animals VALUES ('Llama    ');
INSERT INTO data_animals VALUES ('Lobster    ');
INSERT INTO data_animals VALUES ('Locust    ');
INSERT INTO data_animals VALUES ('Loon    ');
INSERT INTO data_animals VALUES ('Louse    ');
INSERT INTO data_animals VALUES ('Lungfish    ');
INSERT INTO data_animals VALUES ('Lynx    ');
INSERT INTO data_animals VALUES ('Macaw    ');
INSERT INTO data_animals VALUES ('Mackerel    ');
INSERT INTO data_animals VALUES ('Magpie    ');
INSERT INTO data_animals VALUES ('Mammal    ');
INSERT INTO data_animals VALUES ('Manatee    ');
INSERT INTO data_animals VALUES ('Mandrill    ');
INSERT INTO data_animals VALUES ('Mantis, praying  ');
INSERT INTO data_animals VALUES ('Marlin    ');
INSERT INTO data_animals VALUES ('Marmoset    ');
INSERT INTO data_animals VALUES ('Marmot    ');
INSERT INTO data_animals VALUES ('Marsupial    ');
INSERT INTO data_animals VALUES ('Marten    ');
INSERT INTO data_animals VALUES ('Mastodon    ');
INSERT INTO data_animals VALUES ('Meadowlark    ');
INSERT INTO data_animals VALUES ('Meerkat    ');
INSERT INTO data_animals VALUES ('Mink    ');
INSERT INTO data_animals VALUES ('Minnow    ');
INSERT INTO data_animals VALUES ('Mite    ');
INSERT INTO data_animals VALUES ('Mockingbird    ');
INSERT INTO data_animals VALUES ('Mole    ');
INSERT INTO data_animals VALUES ('Mole, star-nosed  ');
INSERT INTO data_animals VALUES ('Mollusk    ');
INSERT INTO data_animals VALUES ('Mongoose    ');
INSERT INTO data_animals VALUES ('Monkey    ');
INSERT INTO data_animals VALUES ('Monkey, spider  ');
INSERT INTO data_animals VALUES ('Monster, gila  ');
INSERT INTO data_animals VALUES ('Moose    ');
INSERT INTO data_animals VALUES ('Mosquito    ');
INSERT INTO data_animals VALUES ('Moth    ');
INSERT INTO data_animals VALUES ('Mouse    ');
INSERT INTO data_animals VALUES ('Mouse, kangaroo  ');
INSERT INTO data_animals VALUES ('Mule    ');
INSERT INTO data_animals VALUES ('Muskox    ');
INSERT INTO data_animals VALUES ('Narwhal    ');
INSERT INTO data_animals VALUES ('Newt    ');
INSERT INTO data_animals VALUES ('Nightingale    ');
INSERT INTO data_animals VALUES ('Ocelot    ');
INSERT INTO data_animals VALUES ('Octopus    ');
INSERT INTO data_animals VALUES ('Opossum    ');
INSERT INTO data_animals VALUES ('Orangutan    ');
INSERT INTO data_animals VALUES ('Orca    ');
INSERT INTO data_animals VALUES ('Ostrich    ');
INSERT INTO data_animals VALUES ('Otter    ');
INSERT INTO data_animals VALUES ('Owl    ');
INSERT INTO data_animals VALUES ('Ox    ');
INSERT INTO data_animals VALUES ('Panda    ');
INSERT INTO data_animals VALUES ('Panda, giant  ');
INSERT INTO data_animals VALUES ('Panda, red  ');
INSERT INTO data_animals VALUES ('Panther    ');
INSERT INTO data_animals VALUES ('Panther, black  ');
INSERT INTO data_animals VALUES ('Parakeet    ');
INSERT INTO data_animals VALUES ('Parrot    ');
INSERT INTO data_animals VALUES ('Parrotfish    ');
INSERT INTO data_animals VALUES ('Partridge    ');
INSERT INTO data_animals VALUES ('Peacock    ');
INSERT INTO data_animals VALUES ('Peafowl    ');
INSERT INTO data_animals VALUES ('Pelican    ');
INSERT INTO data_animals VALUES ('Penguin    ');
INSERT INTO data_animals VALUES ('Perch    ');
INSERT INTO data_animals VALUES ('Perch, yellow  ');
INSERT INTO data_animals VALUES ('Pheasant    ');
INSERT INTO data_animals VALUES ('Pig    ');
INSERT INTO data_animals VALUES ('Pig, guinea  ');
INSERT INTO data_animals VALUES ('Pigeon    ');
INSERT INTO data_animals VALUES ('Pike    ');
INSERT INTO data_animals VALUES ('Pinniped    ');
INSERT INTO data_animals VALUES ('Piranha    ');
INSERT INTO data_animals VALUES ('Planarian    ');
INSERT INTO data_animals VALUES ('Platypus    ');
INSERT INTO data_animals VALUES ('Pony    ');
INSERT INTO data_animals VALUES ('Porcupine    ');
INSERT INTO data_animals VALUES ('Porpoise    ');
INSERT INTO data_animals VALUES ('Portuguese man o'' war ');
INSERT INTO data_animals VALUES ('Possum    ');
INSERT INTO data_animals VALUES ('Prawn    ');
INSERT INTO data_animals VALUES ('Primate    ');
INSERT INTO data_animals VALUES ('Ptarmigan    ');
INSERT INTO data_animals VALUES ('Puffin    ');
INSERT INTO data_animals VALUES ('Puma    ');
INSERT INTO data_animals VALUES ('Python    ');
INSERT INTO data_animals VALUES ('Quail    ');
INSERT INTO data_animals VALUES ('Quail, new world ');
INSERT INTO data_animals VALUES ('Quail, old world ');
INSERT INTO data_animals VALUES ('Quelea    ');
INSERT INTO data_animals VALUES ('Quokka    ');
INSERT INTO data_animals VALUES ('Rabbit    ');
INSERT INTO data_animals VALUES ('Raccoon    ');
INSERT INTO data_animals VALUES ('Rat    ');
INSERT INTO data_animals VALUES ('Rat, kangaroo  ');
INSERT INTO data_animals VALUES ('Rattlesnake    ');
INSERT INTO data_animals VALUES ('Raven    ');
INSERT INTO data_animals VALUES ('Ray (batoidea)   ');
INSERT INTO data_animals VALUES ('Ray (rajiformes)   ');
INSERT INTO data_animals VALUES ('Ray, manta  ');
INSERT INTO data_animals VALUES ('Reindeer    ');
INSERT INTO data_animals VALUES ('Reptile    ');
INSERT INTO data_animals VALUES ('Rhinoceros    ');
INSERT INTO data_animals VALUES ('Roadrunner    ');
INSERT INTO data_animals VALUES ('Robin, american  ');
INSERT INTO data_animals VALUES ('Rodent    ');
INSERT INTO data_animals VALUES ('Rook    ');
INSERT INTO data_animals VALUES ('Rooster    ');
INSERT INTO data_animals VALUES ('Roundworm    ');
INSERT INTO data_animals VALUES ('Sailfish    ');
INSERT INTO data_animals VALUES ('Salamander    ');
INSERT INTO data_animals VALUES ('Salmon    ');
INSERT INTO data_animals VALUES ('Salmon, sockeye  ');
INSERT INTO data_animals VALUES ('Sawfish    ');
INSERT INTO data_animals VALUES ('Scallop    ');
INSERT INTO data_animals VALUES ('Scorpion    ');
INSERT INTO data_animals VALUES ('Seahorse    ');
INSERT INTO data_animals VALUES ('Seal, elephant  ');
INSERT INTO data_animals VALUES ('Shark    ');
INSERT INTO data_animals VALUES ('Shark, great white ');
INSERT INTO data_animals VALUES ('Shark, ground  ');
INSERT INTO data_animals VALUES ('Shark, hammerhead  ');
INSERT INTO data_animals VALUES ('Shark, tiger  ');
INSERT INTO data_animals VALUES ('Sheep    ');
INSERT INTO data_animals VALUES ('Shrew    ');
INSERT INTO data_animals VALUES ('Shrimp    ');
INSERT INTO data_animals VALUES ('Silkworm    ');
INSERT INTO data_animals VALUES ('Silverfish    ');
INSERT INTO data_animals VALUES ('Skink    ');
INSERT INTO data_animals VALUES ('Skunk    ');
INSERT INTO data_animals VALUES ('Sloth    ');
INSERT INTO data_animals VALUES ('Sloth, ground  ');
INSERT INTO data_animals VALUES ('Slug    ');
INSERT INTO data_animals VALUES ('Slug, sea  ');
INSERT INTO data_animals VALUES ('Smelt    ');
INSERT INTO data_animals VALUES ('Snail    ');
INSERT INTO data_animals VALUES ('Snail, land  ');
INSERT INTO data_animals VALUES ('Snail, sea  ');
INSERT INTO data_animals VALUES ('Snake    ');
INSERT INTO data_animals VALUES ('Snipe    ');
INSERT INTO data_animals VALUES ('Sole    ');
INSERT INTO data_animals VALUES ('Sparrow    ');
INSERT INTO data_animals VALUES ('Spider    ');
INSERT INTO data_animals VALUES ('Spider, black widow ');
INSERT INTO data_animals VALUES ('Spider, trapdoor  ');
INSERT INTO data_animals VALUES ('Spoonbill    ');
INSERT INTO data_animals VALUES ('Squid    ');
INSERT INTO data_animals VALUES ('Squid, giant  ');
INSERT INTO data_animals VALUES ('Squid, vampire  ');
INSERT INTO data_animals VALUES ('Squirrel    ');
INSERT INTO data_animals VALUES ('Starfish    ');
INSERT INTO data_animals VALUES ('Stingray    ');
INSERT INTO data_animals VALUES ('Stoat    ');
INSERT INTO data_animals VALUES ('Stork    ');
INSERT INTO data_animals VALUES ('Sturgeon    ');
INSERT INTO data_animals VALUES ('Swallow    ');
INSERT INTO data_animals VALUES ('Swan    ');
INSERT INTO data_animals VALUES ('Swift    ');
INSERT INTO data_animals VALUES ('Swordfish    ');
INSERT INTO data_animals VALUES ('Swordtail    ');
INSERT INTO data_animals VALUES ('Tahr    ');
INSERT INTO data_animals VALUES ('Takin    ');
INSERT INTO data_animals VALUES ('Tapir    ');
INSERT INTO data_animals VALUES ('Tarantula    ');
INSERT INTO data_animals VALUES ('Tarsier    ');
INSERT INTO data_animals VALUES ('Termite    ');
INSERT INTO data_animals VALUES ('Tern    ');
INSERT INTO data_animals VALUES ('Thrush    ');
INSERT INTO data_animals VALUES ('Tick    ');
INSERT INTO data_animals VALUES ('Tiger    ');
INSERT INTO data_animals VALUES ('Tiglon    ');
INSERT INTO data_animals VALUES ('Toad    ');
INSERT INTO data_animals VALUES ('Tortoise    ');
INSERT INTO data_animals VALUES ('Toucan    ');
INSERT INTO data_animals VALUES ('Trout    ');
INSERT INTO data_animals VALUES ('Trout, rainbow  ');
INSERT INTO data_animals VALUES ('Trout, steelhead  ');
INSERT INTO data_animals VALUES ('Tuna    ');
INSERT INTO data_animals VALUES ('Turkey    ');
INSERT INTO data_animals VALUES ('Turtle    ');
INSERT INTO data_animals VALUES ('Urial    ');
INSERT INTO data_animals VALUES ('Vicuna    ');
INSERT INTO data_animals VALUES ('Viper    ');
INSERT INTO data_animals VALUES ('Vole    ');
INSERT INTO data_animals VALUES ('Vulture    ');
INSERT INTO data_animals VALUES ('Wallaby    ');
INSERT INTO data_animals VALUES ('Walrus    ');
INSERT INTO data_animals VALUES ('Warbler    ');
INSERT INTO data_animals VALUES ('Wasp    ');
INSERT INTO data_animals VALUES ('Weasel    ');
INSERT INTO data_animals VALUES ('Whale    ');
INSERT INTO data_animals VALUES ('Whale, beaked  ');
INSERT INTO data_animals VALUES ('Whale, blue  ');
INSERT INTO data_animals VALUES ('Whale, humpback  ');
INSERT INTO data_animals VALUES ('Whale, pilot  ');
INSERT INTO data_animals VALUES ('Whale, right  ');
INSERT INTO data_animals VALUES ('Whale, sperm  ');
INSERT INTO data_animals VALUES ('Whippet    ');
INSERT INTO data_animals VALUES ('Whitefish    ');
INSERT INTO data_animals VALUES ('Wildcat    ');
INSERT INTO data_animals VALUES ('Wildebeest    ');
INSERT INTO data_animals VALUES ('Wildfowl    ');
INSERT INTO data_animals VALUES ('Wolf    ');
INSERT INTO data_animals VALUES ('Wolf, arctic  ');
INSERT INTO data_animals VALUES ('Wolverine    ');
INSERT INTO data_animals VALUES ('Wombat    ');
INSERT INTO data_animals VALUES ('Woodpecker    ');
INSERT INTO data_animals VALUES ('Worm    ');
INSERT INTO data_animals VALUES ('Wren    ');
INSERT INTO data_animals VALUES ('Xerinae    ');
INSERT INTO data_animals VALUES ('Yak    ');
INSERT INTO data_animals VALUES ('Zebra    ');
