CREATE TABLE data_musicians (
    `Column_1` VARCHAR(37) CHARACTER SET utf8
);
INSERT INTO data_musicians VALUES ('*NSYNC');
INSERT INTO data_musicians VALUES ('10,000 Maniacs');
INSERT INTO data_musicians VALUES ('10cc');
INSERT INTO data_musicians VALUES ('2 Chainz');
INSERT INTO data_musicians VALUES ('3 Doors Down');
INSERT INTO data_musicians VALUES ('30 Seconds to Mars');
INSERT INTO data_musicians VALUES ('50 Cent');
INSERT INTO data_musicians VALUES ('A Day To Remember');
INSERT INTO data_musicians VALUES ('A Tribe Called Quest');
INSERT INTO data_musicians VALUES ('A. R. Rahman');
INSERT INTO data_musicians VALUES ('Abba');
INSERT INTO data_musicians VALUES ('Above & Beyond');
INSERT INTO data_musicians VALUES ('AC/DC');
INSERT INTO data_musicians VALUES ('Accept');
INSERT INTO data_musicians VALUES ('Adam and The Ants');
INSERT INTO data_musicians VALUES ('Adam Lambert');
INSERT INTO data_musicians VALUES ('Adam Levine');
INSERT INTO data_musicians VALUES ('Adele');
INSERT INTO data_musicians VALUES ('Adolf von Henselt');
INSERT INTO data_musicians VALUES ('Aerosmith');
INSERT INTO data_musicians VALUES ('Afrojack');
INSERT INTO data_musicians VALUES ('Agnes');
INSERT INTO data_musicians VALUES ('Aimee Mann');
INSERT INTO data_musicians VALUES ('Akon');
INSERT INTO data_musicians VALUES ('Al Di Meola');
INSERT INTO data_musicians VALUES ('Al Green');
INSERT INTO data_musicians VALUES ('Al Jolson');
INSERT INTO data_musicians VALUES ('Al Stewart');
INSERT INTO data_musicians VALUES ('Alabama');
INSERT INTO data_musicians VALUES ('Alanis Morissette');
INSERT INTO data_musicians VALUES ('Alex M.O.R.P.H.');
INSERT INTO data_musicians VALUES ('Alice Cooper');
INSERT INTO data_musicians VALUES ('Alice in Chains');
INSERT INTO data_musicians VALUES ('Alicia Keys');
INSERT INTO data_musicians VALUES ('Alison Haislip');
INSERT INTO data_musicians VALUES ('Alison Krauss');
INSERT INTO data_musicians VALUES ('All Time Low');
INSERT INTO data_musicians VALUES ('Allstar Weekend');
INSERT INTO data_musicians VALUES ('Alter Bridge');
INSERT INTO data_musicians VALUES ('Alt-J');
INSERT INTO data_musicians VALUES ('Ambrosia');
INSERT INTO data_musicians VALUES ('America');
INSERT INTO data_musicians VALUES ('Amon Düül II');
INSERT INTO data_musicians VALUES ('Amy Macdonald');
INSERT INTO data_musicians VALUES ('Amy Winehouse');
INSERT INTO data_musicians VALUES ('Anastacia');
INSERT INTO data_musicians VALUES ('André 3000');
INSERT INTO data_musicians VALUES ('Andrea Bocelli');
INSERT INTO data_musicians VALUES ('Andreas Vollenweider');
INSERT INTO data_musicians VALUES ('Andrés Calamaro ');
INSERT INTO data_musicians VALUES ('Andrew Latimer');
INSERT INTO data_musicians VALUES ('Andrew W.K.');
INSERT INTO data_musicians VALUES ('Andy McKee');
INSERT INTO data_musicians VALUES ('Angel');
INSERT INTO data_musicians VALUES ('Ani DiFranco');
INSERT INTO data_musicians VALUES ('Anita Baker');
INSERT INTO data_musicians VALUES ('Annie Lennox');
INSERT INTO data_musicians VALUES ('Anthrax');
INSERT INTO data_musicians VALUES ('Anton Bruckner');
INSERT INTO data_musicians VALUES ('Antonín Dvořák');
INSERT INTO data_musicians VALUES ('Antonio Vivaldi');
INSERT INTO data_musicians VALUES ('Aphex Twin');
INSERT INTO data_musicians VALUES ('April Wine');
INSERT INTO data_musicians VALUES ('Arash');
INSERT INTO data_musicians VALUES ('Arcade Fire');
INSERT INTO data_musicians VALUES ('Arcangelo Corelli');
INSERT INTO data_musicians VALUES ('Archive');
INSERT INTO data_musicians VALUES ('Arctic Monkeys');
INSERT INTO data_musicians VALUES ('Aretha Franklin');
INSERT INTO data_musicians VALUES ('Ariana Grande');
INSERT INTO data_musicians VALUES ('Armando Manzanero');
INSERT INTO data_musicians VALUES ('Armin van Buuren');
INSERT INTO data_musicians VALUES ('Arnold Schoenberg');
INSERT INTO data_musicians VALUES ('ASAP Rocky');
INSERT INTO data_musicians VALUES ('Ashlee Simpson');
INSERT INTO data_musicians VALUES ('Asia');
INSERT INTO data_musicians VALUES ('Asking Alexandria');
INSERT INTO data_musicians VALUES ('Atari Teenage Riot');
INSERT INTO data_musicians VALUES ('Atmosphere');
INSERT INTO data_musicians VALUES ('Atomic Rooster');
INSERT INTO data_musicians VALUES ('Austin Mahone');
INSERT INTO data_musicians VALUES ('Avenged Sevenfold');
INSERT INTO data_musicians VALUES ('Avicii');
INSERT INTO data_musicians VALUES ('Avril Lavigne');
INSERT INTO data_musicians VALUES ('AZ');
INSERT INTO data_musicians VALUES ('Azad');
INSERT INTO data_musicians VALUES ('B.B. King');
INSERT INTO data_musicians VALUES ('B.o.B');
INSERT INTO data_musicians VALUES ('Babe Ruth');
INSERT INTO data_musicians VALUES ('babyface');
INSERT INTO data_musicians VALUES ('Bachman–Turner Overdrive');
INSERT INTO data_musicians VALUES ('Backstreet Boys');
INSERT INTO data_musicians VALUES ('Bad Company');
INSERT INTO data_musicians VALUES ('Bad Religion');
INSERT INTO data_musicians VALUES ('Barbra Streisand');
INSERT INTO data_musicians VALUES ('Barry Gibb');
INSERT INTO data_musicians VALUES ('Barry White');
INSERT INTO data_musicians VALUES ('Bastille');
INSERT INTO data_musicians VALUES ('Bauhaus');
INSERT INTO data_musicians VALUES ('Beastie Boys');
INSERT INTO data_musicians VALUES ('Beck Hansen');
INSERT INTO data_musicians VALUES ('Becky G');
INSERT INTO data_musicians VALUES ('Bedrich Smetana');
INSERT INTO data_musicians VALUES ('Bee Gees');
INSERT INTO data_musicians VALUES ('Belle & Sebastian');
INSERT INTO data_musicians VALUES ('Benny Goodman');
INSERT INTO data_musicians VALUES ('Berliner Philharmoniker');
INSERT INTO data_musicians VALUES ('Beyoncé Knowles');
INSERT INTO data_musicians VALUES ('Big Country');
INSERT INTO data_musicians VALUES ('Big Sean');
INSERT INTO data_musicians VALUES ('Big Star');
INSERT INTO data_musicians VALUES ('Big Time Rush');
INSERT INTO data_musicians VALUES ('Bill Haley & His Comets');
INSERT INTO data_musicians VALUES ('Bill Monroe');
INSERT INTO data_musicians VALUES ('Billie Holiday');
INSERT INTO data_musicians VALUES ('Billy Cobham');
INSERT INTO data_musicians VALUES ('Billy Idol');
INSERT INTO data_musicians VALUES ('Billy Joel');
INSERT INTO data_musicians VALUES ('Billy Ray Cyrus');
INSERT INTO data_musicians VALUES ('Billy Squier');
INSERT INTO data_musicians VALUES ('Billy Talent');
INSERT INTO data_musicians VALUES ('Bing Crosby');
INSERT INTO data_musicians VALUES ('Björk');
INSERT INTO data_musicians VALUES ('Black Flag');
INSERT INTO data_musicians VALUES ('Black Sabbath');
INSERT INTO data_musicians VALUES ('Black Science Orchestra');
INSERT INTO data_musicians VALUES ('Blackmore''s Night');
INSERT INTO data_musicians VALUES ('Blake Shelton');
INSERT INTO data_musicians VALUES ('Blind Faith');
INSERT INTO data_musicians VALUES ('Blind Guardian');
INSERT INTO data_musicians VALUES ('Blind Lemon Jefferson');
INSERT INTO data_musicians VALUES ('Blink-182');
INSERT INTO data_musicians VALUES ('Blitzen Trapper');
INSERT INTO data_musicians VALUES ('Blondie');
INSERT INTO data_musicians VALUES ('Blood, Sweat & Tears');
INSERT INTO data_musicians VALUES ('Bloodrock');
INSERT INTO data_musicians VALUES ('Blue Öyster Cult');
INSERT INTO data_musicians VALUES ('Blur');
INSERT INTO data_musicians VALUES ('Bo Diddley');
INSERT INTO data_musicians VALUES ('Bob Dylan');
INSERT INTO data_musicians VALUES ('Bob Marley');
INSERT INTO data_musicians VALUES ('Bob Seger');
INSERT INTO data_musicians VALUES ('Bob Seger & the Silver Bullet Band');
INSERT INTO data_musicians VALUES ('Bob Sinclar');
INSERT INTO data_musicians VALUES ('Bobby Darin');
INSERT INTO data_musicians VALUES ('Bobby Rydell');
INSERT INTO data_musicians VALUES ('Bobby Vee');
INSERT INTO data_musicians VALUES ('Bobby Womack');
INSERT INTO data_musicians VALUES ('Bon Jovi');
INSERT INTO data_musicians VALUES ('Bone Thugs-N-Harmony');
INSERT INTO data_musicians VALUES ('Bonnie Raitt');
INSERT INTO data_musicians VALUES ('Bonnie Tyler');
INSERT INTO data_musicians VALUES ('Booker T. & the M.G.''s');
INSERT INTO data_musicians VALUES ('Boston');
INSERT INTO data_musicians VALUES ('Boy George');
INSERT INTO data_musicians VALUES ('Boz Scaggs');
INSERT INTO data_musicians VALUES ('Brad Paisley');
INSERT INTO data_musicians VALUES ('Brainiac');
INSERT INTO data_musicians VALUES ('Bread');
INSERT INTO data_musicians VALUES ('Breaking Benjamin');
INSERT INTO data_musicians VALUES ('Brenda Lee');
INSERT INTO data_musicians VALUES ('Brian Eno');
INSERT INTO data_musicians VALUES ('Britney Spears');
INSERT INTO data_musicians VALUES ('Brooks & Dunn');
INSERT INTO data_musicians VALUES ('Brother Ali');
INSERT INTO data_musicians VALUES ('Bruce Springsteen');
INSERT INTO data_musicians VALUES ('Bruno Mars');
INSERT INTO data_musicians VALUES ('Bryan Adams');
INSERT INTO data_musicians VALUES ('Buddy Holly');
INSERT INTO data_musicians VALUES ('Budgie');
INSERT INTO data_musicians VALUES ('Buffalo');
INSERT INTO data_musicians VALUES ('Buffy Sainte-Marie');
INSERT INTO data_musicians VALUES ('Buhurizade Mustafa Itri');
INSERT INTO data_musicians VALUES ('Bullet for My Valentine');
INSERT INTO data_musicians VALUES ('Burt Bacharach');
INSERT INTO data_musicians VALUES ('Bush');
INSERT INTO data_musicians VALUES ('Busta Rhymes');
INSERT INTO data_musicians VALUES ('Byron Stingily');
INSERT INTO data_musicians VALUES ('Ca$his');
INSERT INTO data_musicians VALUES ('Cake');
INSERT INTO data_musicians VALUES ('Calvin Harris');
INSERT INTO data_musicians VALUES ('Camel');
INSERT INTO data_musicians VALUES ('Camille Saint-Saδns');
INSERT INTO data_musicians VALUES ('CAN');
INSERT INTO data_musicians VALUES ('Candlebox');
INSERT INTO data_musicians VALUES ('Candlemass');
INSERT INTO data_musicians VALUES ('Canibus');
INSERT INTO data_musicians VALUES ('Caravan');
INSERT INTO data_musicians VALUES ('Carl Cox');
INSERT INTO data_musicians VALUES ('Carl Perkins');
INSERT INTO data_musicians VALUES ('Carl Philipp Emanuel Bach');
INSERT INTO data_musicians VALUES ('Carla Bruni');
INSERT INTO data_musicians VALUES ('Carlos Santana');
INSERT INTO data_musicians VALUES ('Carly Rae Jepsen');
INSERT INTO data_musicians VALUES ('Carly Simon');
INSERT INTO data_musicians VALUES ('Carole King');
INSERT INTO data_musicians VALUES ('Carrie Underwood');
INSERT INTO data_musicians VALUES ('Cascada');
INSERT INTO data_musicians VALUES ('Cathedral Quartet');
INSERT INTO data_musicians VALUES ('Cee Lo Green');
INSERT INTO data_musicians VALUES ('Celine Dion');
INSERT INTO data_musicians VALUES ('Chaka Khan');
INSERT INTO data_musicians VALUES ('Charles Mingus');
INSERT INTO data_musicians VALUES ('Charlie Parker');
INSERT INTO data_musicians VALUES ('Chavela Vargas');
INSERT INTO data_musicians VALUES ('Cheap Trick');
INSERT INTO data_musicians VALUES ('Cher');
INSERT INTO data_musicians VALUES ('Cheryl Cole');
INSERT INTO data_musicians VALUES ('Chet Baker');
INSERT INTO data_musicians VALUES ('Chicago');
INSERT INTO data_musicians VALUES ('Chico Buarque');
INSERT INTO data_musicians VALUES ('Chiddy Bang');
INSERT INTO data_musicians VALUES ('Chief Keef');
INSERT INTO data_musicians VALUES ('Chino XL');
INSERT INTO data_musicians VALUES ('Chris Brown');
INSERT INTO data_musicians VALUES ('Christina Aguilera');
INSERT INTO data_musicians VALUES ('Christina Milian');
INSERT INTO data_musicians VALUES ('Christina Perri');
INSERT INTO data_musicians VALUES ('Christoph Willibald Gluck');
INSERT INTO data_musicians VALUES ('Christy Moore');
INSERT INTO data_musicians VALUES ('Chrome');
INSERT INTO data_musicians VALUES ('Chuck Berry');
INSERT INTO data_musicians VALUES ('Ciara');
INSERT INTO data_musicians VALUES ('Cinderella');
INSERT INTO data_musicians VALUES ('Cindy Bullens');
INSERT INTO data_musicians VALUES ('Cirith Ungol');
INSERT INTO data_musicians VALUES ('Civil Twilight');
INSERT INTO data_musicians VALUES ('Claude Debussy');
INSERT INTO data_musicians VALUES ('Claudio Monteverdi');
INSERT INTO data_musicians VALUES ('Cobra Starship');
INSERT INTO data_musicians VALUES ('Cocteau Twins');
INSERT INTO data_musicians VALUES ('Coldplay');
INSERT INTO data_musicians VALUES ('Cole Porter');
INSERT INTO data_musicians VALUES ('Coleman Hawkins');
INSERT INTO data_musicians VALUES ('Collective Soul');
INSERT INTO data_musicians VALUES ('Commodores');
INSERT INTO data_musicians VALUES ('Comsat Angels');
INSERT INTO data_musicians VALUES ('Connie Francis');
INSERT INTO data_musicians VALUES ('Counting Crows');
INSERT INTO data_musicians VALUES ('Cowboy Junkies');
INSERT INTO data_musicians VALUES ('Crack the Sky');
INSERT INTO data_musicians VALUES ('Cream');
INSERT INTO data_musicians VALUES ('Creed');
INSERT INTO data_musicians VALUES ('Creedence Clearwater Revival');
INSERT INTO data_musicians VALUES ('Crimson Glory');
INSERT INTO data_musicians VALUES ('Crosby, Stills, Nash & Young');
INSERT INTO data_musicians VALUES ('CunninLynguists');
INSERT INTO data_musicians VALUES ('Curtis Mayfield');
INSERT INTO data_musicians VALUES ('Cyndi Lauper');
INSERT INTO data_musicians VALUES ('D12');
INSERT INTO data_musicians VALUES ('Daft Punk');
INSERT INTO data_musicians VALUES ('Damien Rice');
INSERT INTO data_musicians VALUES ('Dan Fogelberg');
INSERT INTO data_musicians VALUES ('Dark Moor');
INSERT INTO data_musicians VALUES ('Darlene Love');
INSERT INTO data_musicians VALUES ('Daughter');
INSERT INTO data_musicians VALUES ('Dave Matthews Band');
INSERT INTO data_musicians VALUES ('David Bowie');
INSERT INTO data_musicians VALUES ('David Gilmour');
INSERT INTO data_musicians VALUES ('David Gray');
INSERT INTO data_musicians VALUES ('David Guetta');
INSERT INTO data_musicians VALUES ('Dcmusiccro');
INSERT INTO data_musicians VALUES ('De La Soul');
INSERT INTO data_musicians VALUES ('Dead Can Dance');
INSERT INTO data_musicians VALUES ('Dead Kennedys');
INSERT INTO data_musicians VALUES ('Dead Prez');
INSERT INTO data_musicians VALUES ('Deadmau5');
INSERT INTO data_musicians VALUES ('Dean Martin');
INSERT INTO data_musicians VALUES ('Death');
INSERT INTO data_musicians VALUES ('Deep Forest');
INSERT INTO data_musicians VALUES ('Deep Purple');
INSERT INTO data_musicians VALUES ('Deerpeople');
INSERT INTO data_musicians VALUES ('Def Leppard');
INSERT INTO data_musicians VALUES ('Del Shannon');
INSERT INTO data_musicians VALUES ('Demi Lovato');
INSERT INTO data_musicians VALUES ('Depeche Mode');
INSERT INTO data_musicians VALUES ('Devo');
INSERT INTO data_musicians VALUES ('Diamond Head');
INSERT INTO data_musicians VALUES ('Diamond Rio');
INSERT INTO data_musicians VALUES ('Diana Krall');
INSERT INTO data_musicians VALUES ('Diana Ross');
INSERT INTO data_musicians VALUES ('Dieterich Buxtehude');
INSERT INTO data_musicians VALUES ('Dimitri from Paris');
INSERT INTO data_musicians VALUES ('Dinah Washington');
INSERT INTO data_musicians VALUES ('Dio');
INSERT INTO data_musicians VALUES ('Dion');
INSERT INTO data_musicians VALUES ('Dion DiMucci');
INSERT INTO data_musicians VALUES ('Dire Straits');
INSERT INTO data_musicians VALUES ('Disturbed');
INSERT INTO data_musicians VALUES ('DJ Snake');
INSERT INTO data_musicians VALUES ('Dmitri Shostakovich');
INSERT INTO data_musicians VALUES ('DMX');
INSERT INTO data_musicians VALUES ('Dokken');
INSERT INTO data_musicians VALUES ('Dolly Parton');
INSERT INTO data_musicians VALUES ('Domenico Scarlatti');
INSERT INTO data_musicians VALUES ('Don McLean');
INSERT INTO data_musicians VALUES ('Don Van Vliet');
INSERT INTO data_musicians VALUES ('Don Willliams');
INSERT INTO data_musicians VALUES ('Donna Summer');
INSERT INTO data_musicians VALUES ('Donny Hathaway');
INSERT INTO data_musicians VALUES ('Dr. Dre');
INSERT INTO data_musicians VALUES ('Dream Theater');
INSERT INTO data_musicians VALUES ('Duffy');
INSERT INTO data_musicians VALUES ('Duke Ellington');
INSERT INTO data_musicians VALUES ('Duran Duran');
INSERT INTO data_musicians VALUES ('Dusty Springfield');
INSERT INTO data_musicians VALUES ('E Street Band');
INSERT INTO data_musicians VALUES ('Eagles');
INSERT INTO data_musicians VALUES ('Earl Sweatshirt');
INSERT INTO data_musicians VALUES ('Earth, Wind & Fire');
INSERT INTO data_musicians VALUES ('Ed Sheeran');
INSERT INTO data_musicians VALUES ('Edgar Winter');
INSERT INTO data_musicians VALUES ('Edgard Varese');
INSERT INTO data_musicians VALUES ('Edvard Grieg');
INSERT INTO data_musicians VALUES ('Edward Elgar');
INSERT INTO data_musicians VALUES ('Edward Maya');
INSERT INTO data_musicians VALUES ('Electric Light Orchestra');
INSERT INTO data_musicians VALUES ('Elena Paparizou');
INSERT INTO data_musicians VALUES ('Ella Fitzgerald');
INSERT INTO data_musicians VALUES ('Ellie Goulding');
INSERT INTO data_musicians VALUES ('Elliott Smith');
INSERT INTO data_musicians VALUES ('Eloy');
INSERT INTO data_musicians VALUES ('Elton John');
INSERT INTO data_musicians VALUES ('Elvis Costello');
INSERT INTO data_musicians VALUES ('Elvis Presley');
INSERT INTO data_musicians VALUES ('Emeli Sandé');
INSERT INTO data_musicians VALUES ('Emerson, Lake & Palmer');
INSERT INTO data_musicians VALUES ('Eminem');
INSERT INTO data_musicians VALUES ('England Dan & John Ford Coley');
INSERT INTO data_musicians VALUES ('Enigma');
INSERT INTO data_musicians VALUES ('Ennio Morricone');
INSERT INTO data_musicians VALUES ('Enrique Iglesias');
INSERT INTO data_musicians VALUES ('Enrique Urquijo');
INSERT INTO data_musicians VALUES ('Enya');
INSERT INTO data_musicians VALUES ('Eric B. & Rakim');
INSERT INTO data_musicians VALUES ('Eric Burdon & the Animals');
INSERT INTO data_musicians VALUES ('Eric Clapton');
INSERT INTO data_musicians VALUES ('Erik Satie');
INSERT INTO data_musicians VALUES ('Etta James');
INSERT INTO data_musicians VALUES ('Europe');
INSERT INTO data_musicians VALUES ('Eurythmics');
INSERT INTO data_musicians VALUES ('Evanescence');
INSERT INTO data_musicians VALUES ('Everything but the Girl');
INSERT INTO data_musicians VALUES ('Fabolous');
INSERT INTO data_musicians VALUES ('Faith No More');
INSERT INTO data_musicians VALUES ('Fall Out Boy');
INSERT INTO data_musicians VALUES ('Far East Movement');
INSERT INTO data_musicians VALUES ('Fates Warning');
INSERT INTO data_musicians VALUES ('Fats Domino');
INSERT INTO data_musicians VALUES ('Felix Mendelssohn-Bartholdy');
INSERT INTO data_musicians VALUES ('Fergie');
INSERT INTO data_musicians VALUES ('Ferry Corsten');
INSERT INTO data_musicians VALUES ('Fifth Harmony');
INSERT INTO data_musicians VALUES ('Fine Young Cannibals');
INSERT INTO data_musicians VALUES ('Fish');
INSERT INTO data_musicians VALUES ('Fito & Fitipaldis');
INSERT INTO data_musicians VALUES ('Five Finger Death Punch');
INSERT INTO data_musicians VALUES ('Fleet Foxes');
INSERT INTO data_musicians VALUES ('Fleetwood Mac');
INSERT INTO data_musicians VALUES ('Flo Rida');
INSERT INTO data_musicians VALUES ('Flower Travellin'' Band');
INSERT INTO data_musicians VALUES ('Focus');
INSERT INTO data_musicians VALUES ('Foghat');
INSERT INTO data_musicians VALUES ('Foo Fighters');
INSERT INTO data_musicians VALUES ('Foreigner');
INSERT INTO data_musicians VALUES ('Fort Minor');
INSERT INTO data_musicians VALUES ('Foster the People');
INSERT INTO data_musicians VALUES ('Four Tops');
INSERT INTO data_musicians VALUES ('Foxes');
INSERT INTO data_musicians VALUES ('Frank Ocean');
INSERT INTO data_musicians VALUES ('Frank Sinatra');
INSERT INTO data_musicians VALUES ('Frank Zappa');
INSERT INTO data_musicians VALUES ('Frankie Avalon');
INSERT INTO data_musicians VALUES ('Frankie Beverly');
INSERT INTO data_musicians VALUES ('Frankie Goes to Hollywood');
INSERT INTO data_musicians VALUES ('Franz Ferdinand');
INSERT INTO data_musicians VALUES ('Franz Liszt');
INSERT INTO data_musicians VALUES ('Franz Schubert');
INSERT INTO data_musicians VALUES ('Franτois Couperin');
INSERT INTO data_musicians VALUES ('Fredrik Karlsson');
INSERT INTO data_musicians VALUES ('Free');
INSERT INTO data_musicians VALUES ('French Montana');
INSERT INTO data_musicians VALUES ('FrΘdΘric Chopin');
INSERT INTO data_musicians VALUES ('Fugazi');
INSERT INTO data_musicians VALUES ('Fun');
INSERT INTO data_musicians VALUES ('Funky Green Dogs');
INSERT INTO data_musicians VALUES ('Gabriel Fauré');
INSERT INTO data_musicians VALUES ('Gabriella Cilmi');
INSERT INTO data_musicians VALUES ('Garbage');
INSERT INTO data_musicians VALUES ('Garth Brooks');
INSERT INTO data_musicians VALUES ('Gary Lewis & The Playboys');
INSERT INTO data_musicians VALUES ('Gary Moore');
INSERT INTO data_musicians VALUES ('Gene Pitney');
INSERT INTO data_musicians VALUES ('Genesis');
INSERT INTO data_musicians VALUES ('Gentle Giant');
INSERT INTO data_musicians VALUES ('Georg Philipp Telemann');
INSERT INTO data_musicians VALUES ('George Frideric Handel');
INSERT INTO data_musicians VALUES ('George Harrison');
INSERT INTO data_musicians VALUES ('George Michael');
INSERT INTO data_musicians VALUES ('George Strait');
INSERT INTO data_musicians VALUES ('Georges Bizet');
INSERT INTO data_musicians VALUES ('Georges Brassens');
INSERT INTO data_musicians VALUES ('Georges Moustaki');
INSERT INTO data_musicians VALUES ('Gerry & the Pacemakers');
INSERT INTO data_musicians VALUES ('Ghostface Killah');
INSERT INTO data_musicians VALUES ('Giacomo Puccini');
INSERT INTO data_musicians VALUES ('Gioacchino Rossini');
INSERT INTO data_musicians VALUES ('Giorgos Mazonakis');
INSERT INTO data_musicians VALUES ('Giovanni Battista Pergolesi');
INSERT INTO data_musicians VALUES ('Giovanni Pierluigi da Palestrina');
INSERT INTO data_musicians VALUES ('Giuseppe Verdi');
INSERT INTO data_musicians VALUES ('Gladys Knight & the Pips');
INSERT INTO data_musicians VALUES ('Glenn Miller');
INSERT INTO data_musicians VALUES ('Gloria Estefan');
INSERT INTO data_musicians VALUES ('Gloria Gaynor');
INSERT INTO data_musicians VALUES ('Gnarls Barkley');
INSERT INTO data_musicians VALUES ('Goblin');
INSERT INTO data_musicians VALUES ('Godsmack');
INSERT INTO data_musicians VALUES ('Goin'' Through');
INSERT INTO data_musicians VALUES ('Golden Earring');
INSERT INTO data_musicians VALUES ('Gomez');
INSERT INTO data_musicians VALUES ('Goo Goo Dolls');
INSERT INTO data_musicians VALUES ('Good Charlotte');
INSERT INTO data_musicians VALUES ('Goodie Mob');
INSERT INTO data_musicians VALUES ('Gordon Lightfoot');
INSERT INTO data_musicians VALUES ('Gorillaz');
INSERT INTO data_musicians VALUES ('Gotye');
INSERT INTO data_musicians VALUES ('Gram Parsons');
INSERT INTO data_musicians VALUES ('Grand Funk Railroad');
INSERT INTO data_musicians VALUES ('Grateful Dead');
INSERT INTO data_musicians VALUES ('Green Day');
INSERT INTO data_musicians VALUES ('Gregorio Allegri');
INSERT INTO data_musicians VALUES ('Gucci Mane');
INSERT INTO data_musicians VALUES ('Guided by Voices');
INSERT INTO data_musicians VALUES ('Guillaume de Machaut');
INSERT INTO data_musicians VALUES ('Guillaume Dufay');
INSERT INTO data_musicians VALUES ('Guns N'' Roses');
INSERT INTO data_musicians VALUES ('Gustav Mahler');
INSERT INTO data_musicians VALUES ('Gwen Stefani');
INSERT INTO data_musicians VALUES ('Gym Class Heroes');
INSERT INTO data_musicians VALUES ('GZA');
INSERT INTO data_musicians VALUES ('Hall & Oates');
INSERT INTO data_musicians VALUES ('Hank Williams');
INSERT INTO data_musicians VALUES ('Hans Zimmer');
INSERT INTO data_musicians VALUES ('Harry Chapin');
INSERT INTO data_musicians VALUES ('Harry Nilsson');
INSERT INTO data_musicians VALUES ('Hawkwind');
INSERT INTO data_musicians VALUES ('Hayley Williams');
INSERT INTO data_musicians VALUES ('He Is We');
INSERT INTO data_musicians VALUES ('Heart');
INSERT INTO data_musicians VALUES ('Heaven 17');
INSERT INTO data_musicians VALUES ('Hector Berlioz');
INSERT INTO data_musicians VALUES ('Heinrich Ignaz Franz von Biber');
INSERT INTO data_musicians VALUES ('Helloween');
INSERT INTO data_musicians VALUES ('Henry Mancini');
INSERT INTO data_musicians VALUES ('Henry Purcell');
INSERT INTO data_musicians VALUES ('Herman''s Hermits');
INSERT INTO data_musicians VALUES ('Hildegard of Bingen');
INSERT INTO data_musicians VALUES ('Hole');
INSERT INTO data_musicians VALUES ('Hollywood Undead');
INSERT INTO data_musicians VALUES ('Howie Day');
INSERT INTO data_musicians VALUES ('Howlin'' Wolf');
INSERT INTO data_musicians VALUES ('Huddie William Ledbetter');
INSERT INTO data_musicians VALUES ('Huey Lewis & the News');
INSERT INTO data_musicians VALUES ('Hunter Hayes');
INSERT INTO data_musicians VALUES ('Hüsker Dü');
INSERT INTO data_musicians VALUES ('Iced Earth');
INSERT INTO data_musicians VALUES ('Icehouse');
INSERT INTO data_musicians VALUES ('Iggy Azalea');
INSERT INTO data_musicians VALUES ('Iggy Pop');
INSERT INTO data_musicians VALUES ('Igor Stravinsky');
INSERT INTO data_musicians VALUES ('Ike & Tina Turner');
INSERT INTO data_musicians VALUES ('Imagine Dragons');
INSERT INTO data_musicians VALUES ('In Flames');
INSERT INTO data_musicians VALUES ('Incubus');
INSERT INTO data_musicians VALUES ('Infected Mushroom');
INSERT INTO data_musicians VALUES ('Information Society');
INSERT INTO data_musicians VALUES ('INXS');
INSERT INTO data_musicians VALUES ('Iron Maiden');
INSERT INTO data_musicians VALUES ('Iva Davies');
INSERT INTO data_musicians VALUES ('Ivi Adamou');
INSERT INTO data_musicians VALUES ('J. Cole');
INSERT INTO data_musicians VALUES ('Ja Rule');
INSERT INTO data_musicians VALUES ('Jack Teagarden');
INSERT INTO data_musicians VALUES ('Jackie Evancho');
INSERT INTO data_musicians VALUES ('Jackie Wilson');
INSERT INTO data_musicians VALUES ('Jackson Browne');
INSERT INTO data_musicians VALUES ('Jackson C Franks');
INSERT INTO data_musicians VALUES ('Jacques Brel');
INSERT INTO data_musicians VALUES ('Jake Shimabukuro');
INSERT INTO data_musicians VALUES ('James Blunt');
INSERT INTO data_musicians VALUES ('James Brown');
INSERT INTO data_musicians VALUES ('James Gang');
INSERT INTO data_musicians VALUES ('James Ingram');
INSERT INTO data_musicians VALUES ('James Morrison');
INSERT INTO data_musicians VALUES ('James Taylor');
INSERT INTO data_musicians VALUES ('Jamie xx');
INSERT INTO data_musicians VALUES ('Jan and Dean');
INSERT INTO data_musicians VALUES ('Jane''s Addiction');
INSERT INTO data_musicians VALUES ('Janet Jackson');
INSERT INTO data_musicians VALUES ('Janis Joplin');
INSERT INTO data_musicians VALUES ('Jason Derulo');
INSERT INTO data_musicians VALUES ('Jayceon Terrell Taylor');
INSERT INTO data_musicians VALUES ('Jayhawks');
INSERT INTO data_musicians VALUES ('Jay-Z');
INSERT INTO data_musicians VALUES ('Jazmine Sullivan');
INSERT INTO data_musicians VALUES ('Jean Michel Jarre');
INSERT INTO data_musicians VALUES ('Jean Sibelius');
INSERT INTO data_musicians VALUES ('Jean-Baptiste Lully');
INSERT INTO data_musicians VALUES ('Jean-Luc Ponty');
INSERT INTO data_musicians VALUES ('Jean-Philippe Rameau');
INSERT INTO data_musicians VALUES ('Jedi Mind Tricks');
INSERT INTO data_musicians VALUES ('Jeff Beck');
INSERT INTO data_musicians VALUES ('Jeff Buckley');
INSERT INTO data_musicians VALUES ('Jeff Mangum');
INSERT INTO data_musicians VALUES ('Jefferson Airplane');
INSERT INTO data_musicians VALUES ('Jennifer Hudson');
INSERT INTO data_musicians VALUES ('Jennifer Lopez');
INSERT INTO data_musicians VALUES ('Jerry Lee Lewis');
INSERT INTO data_musicians VALUES ('Jessica Simpson');
INSERT INTO data_musicians VALUES ('Jessie J');
INSERT INTO data_musicians VALUES ('Jethro Tull');
INSERT INTO data_musicians VALUES ('Jim Croce');
INSERT INTO data_musicians VALUES ('Jimi Hendrix');
INSERT INTO data_musicians VALUES ('Jimmy Page');
INSERT INTO data_musicians VALUES ('Joan Baez');
INSERT INTO data_musicians VALUES ('Joan Jett');
INSERT INTO data_musicians VALUES ('Joan Manuel Serrat');
INSERT INTO data_musicians VALUES ('Joaquφn Sabina');
INSERT INTO data_musicians VALUES ('Joe Cocker');
INSERT INTO data_musicians VALUES ('Joe Jackson');
INSERT INTO data_musicians VALUES ('Joe Jonas');
INSERT INTO data_musicians VALUES ('Joe Satriani');
INSERT INTO data_musicians VALUES ('Joe Walsh');
INSERT INTO data_musicians VALUES ('Joey Negro');
INSERT INTO data_musicians VALUES ('Johann Pachelbel');
INSERT INTO data_musicians VALUES ('Johann Sebastian Bach');
INSERT INTO data_musicians VALUES ('Johann Strauss II');
INSERT INTO data_musicians VALUES ('Johannes Brahms');
INSERT INTO data_musicians VALUES ('John Cafferty & The Beaver Brown Band');
INSERT INTO data_musicians VALUES ('John Cage');
INSERT INTO data_musicians VALUES ('John Cena');
INSERT INTO data_musicians VALUES ('John Coltrane');
INSERT INTO data_musicians VALUES ('John Denver');
INSERT INTO data_musicians VALUES ('John Farnham');
INSERT INTO data_musicians VALUES ('John Lee Hooker');
INSERT INTO data_musicians VALUES ('John Legend');
INSERT INTO data_musicians VALUES ('John Lennon');
INSERT INTO data_musicians VALUES ('John Mayer');
INSERT INTO data_musicians VALUES ('John Waite');
INSERT INTO data_musicians VALUES ('John Williams');
INSERT INTO data_musicians VALUES ('Johnny Cash');
INSERT INTO data_musicians VALUES ('Johnny Mathis');
INSERT INTO data_musicians VALUES ('Johnny Winter');
INSERT INTO data_musicians VALUES ('JoJo');
INSERT INTO data_musicians VALUES ('Jon Anderson');
INSERT INTO data_musicians VALUES ('Jon Bon Jovi');
INSERT INTO data_musicians VALUES ('Jon Lord');
INSERT INTO data_musicians VALUES ('Joni Mitchell');
INSERT INTO data_musicians VALUES ('Joseph Haydn');
INSERT INTO data_musicians VALUES ('Josh Groban');
INSERT INTO data_musicians VALUES ('Joss Stone');
INSERT INTO data_musicians VALUES ('Journey');
INSERT INTO data_musicians VALUES ('Joy Division');
INSERT INTO data_musicians VALUES ('Judas Priest');
INSERT INTO data_musicians VALUES ('Judy Garland');
INSERT INTO data_musicians VALUES ('Julio Iglesias');
INSERT INTO data_musicians VALUES ('Justin Bieber');
INSERT INTO data_musicians VALUES ('Justin Timberlake');
INSERT INTO data_musicians VALUES ('k.d. lang');
INSERT INTO data_musicians VALUES ('Kansas');
INSERT INTO data_musicians VALUES ('Kanye West');
INSERT INTO data_musicians VALUES ('Kasabian');
INSERT INTO data_musicians VALUES ('Kate Bush');
INSERT INTO data_musicians VALUES ('Katy Perry');
INSERT INTO data_musicians VALUES ('KC and the Sunshine Band');
INSERT INTO data_musicians VALUES ('Keith Richards');
INSERT INTO data_musicians VALUES ('Kelly Clarkson');
INSERT INTO data_musicians VALUES ('Kelly Rowland');
INSERT INTO data_musicians VALUES ('Kendrick Lamar');
INSERT INTO data_musicians VALUES ('Kenny Chesney');
INSERT INTO data_musicians VALUES ('Kenny G');
INSERT INTO data_musicians VALUES ('Kenny Loggins');
INSERT INTO data_musicians VALUES ('Kent');
INSERT INTO data_musicians VALUES ('Keri Hilson');
INSERT INTO data_musicians VALUES ('Kesha');
INSERT INTO data_musicians VALUES ('Keyshia Cole');
INSERT INTO data_musicians VALUES ('Kid Cudi');
INSERT INTO data_musicians VALUES ('Kid Rock');
INSERT INTO data_musicians VALUES ('Killswitch Engage');
INSERT INTO data_musicians VALUES ('Kim Wilde');
INSERT INTO data_musicians VALUES ('King Crimson');
INSERT INTO data_musicians VALUES ('Kings of Leon');
INSERT INTO data_musicians VALUES ('King''s X');
INSERT INTO data_musicians VALUES ('Kirk Franklin');
INSERT INTO data_musicians VALUES ('Kiss');
INSERT INTO data_musicians VALUES ('Kissing the Pink New Wave');
INSERT INTO data_musicians VALUES ('Kitaro');
INSERT INTO data_musicians VALUES ('Kool & the Gang');
INSERT INTO data_musicians VALUES ('Korn');
INSERT INTO data_musicians VALUES ('Kraftwerk');
INSERT INTO data_musicians VALUES ('Kreator');
INSERT INTO data_musicians VALUES ('Krokus');
INSERT INTO data_musicians VALUES ('KRS-One');
INSERT INTO data_musicians VALUES ('Kurdo');
INSERT INTO data_musicians VALUES ('Kylie Minogue');
INSERT INTO data_musicians VALUES ('La Roux');
INSERT INTO data_musicians VALUES ('Labrinth');
INSERT INTO data_musicians VALUES ('Lady Antebellum');
INSERT INTO data_musicians VALUES ('Lady Gaga');
INSERT INTO data_musicians VALUES ('Lamb of God');
INSERT INTO data_musicians VALUES ('Lana Del Rey');
INSERT INTO data_musicians VALUES ('Laura Nyro');
INSERT INTO data_musicians VALUES ('Lauryn Hill');
INSERT INTO data_musicians VALUES ('LCD Soundsystem');
INSERT INTO data_musicians VALUES ('Led Zeppelin');
INSERT INTO data_musicians VALUES ('Lefty Frizzell');
INSERT INTO data_musicians VALUES ('Lenny Kravitz');
INSERT INTO data_musicians VALUES ('Leona Lewis');
INSERT INTO data_musicians VALUES ('Leonard Cohen');
INSERT INTO data_musicians VALUES ('Leonardo DiCaprio');
INSERT INTO data_musicians VALUES ('Les Claypool');
INSERT INTO data_musicians VALUES ('Lesley Gore');
INSERT INTO data_musicians VALUES ('Lester Flatt & Earl Scruggs');
INSERT INTO data_musicians VALUES ('Levert');
INSERT INTO data_musicians VALUES ('Lil B');
INSERT INTO data_musicians VALUES ('Lil Boosie');
INSERT INTO data_musicians VALUES ('Lil'' C');
INSERT INTO data_musicians VALUES ('Lil Dicky');
INSERT INTO data_musicians VALUES ('Lil'' Fate');
INSERT INTO data_musicians VALUES ('Lil'' Flip');
INSERT INTO data_musicians VALUES ('Lil Jon');
INSERT INTO data_musicians VALUES ('Lil'' Kim');
INSERT INTO data_musicians VALUES ('Lil'' Mama');
INSERT INTO data_musicians VALUES ('Lil Romeo');
INSERT INTO data_musicians VALUES ('Lil'' Scrappy');
INSERT INTO data_musicians VALUES ('Lil Twist');
INSERT INTO data_musicians VALUES ('Lil Wyte');
INSERT INTO data_musicians VALUES ('Lily Allen');
INSERT INTO data_musicians VALUES ('Linda Ronstadt');
INSERT INTO data_musicians VALUES ('Lindsey Stirling');
INSERT INTO data_musicians VALUES ('Linkin Park');
INSERT INTO data_musicians VALUES ('Lionel Hampton');
INSERT INTO data_musicians VALUES ('Lionel Richie');
INSERT INTO data_musicians VALUES ('Little Mix');
INSERT INTO data_musicians VALUES ('Little Richard');
INSERT INTO data_musicians VALUES ('Living Colour');
INSERT INTO data_musicians VALUES ('Liz Phair');
INSERT INTO data_musicians VALUES ('LL Cool J');
INSERT INTO data_musicians VALUES ('Lloyd Banks');
INSERT INTO data_musicians VALUES ('Lloyd Cole and the Commotions');
INSERT INTO data_musicians VALUES ('Lluís Llach');
INSERT INTO data_musicians VALUES ('LMFAO');
INSERT INTO data_musicians VALUES ('London Symphony Orchestra');
INSERT INTO data_musicians VALUES ('Loretta Lynn');
INSERT INTO data_musicians VALUES ('Los Rodríguez');
INSERT INTO data_musicians VALUES ('Los Secretos');
INSERT INTO data_musicians VALUES ('Lou Christie');
INSERT INTO data_musicians VALUES ('Lou Rawls');
INSERT INTO data_musicians VALUES ('Lou Reed');
INSERT INTO data_musicians VALUES ('Louis Armstrong');
INSERT INTO data_musicians VALUES ('Love');
INSERT INTO data_musicians VALUES ('Luciano Berio');
INSERT INTO data_musicians VALUES ('Luciano Pavarotti');
INSERT INTO data_musicians VALUES ('Ludacris');
INSERT INTO data_musicians VALUES ('Ludwig van Beethoven');
INSERT INTO data_musicians VALUES ('Luigi Boccherini');
INSERT INTO data_musicians VALUES ('Luis Eduardo Aute');
INSERT INTO data_musicians VALUES ('Luis Miguel');
INSERT INTO data_musicians VALUES ('Lupe Fiasco');
INSERT INTO data_musicians VALUES ('Luther Vandross');
INSERT INTO data_musicians VALUES ('Lynyrd Skynyrd');
INSERT INTO data_musicians VALUES ('Macklemore');
INSERT INTO data_musicians VALUES ('Madness');
INSERT INTO data_musicians VALUES ('Madonna');
INSERT INTO data_musicians VALUES ('Magma');
INSERT INTO data_musicians VALUES ('Mahalia Jackson');
INSERT INTO data_musicians VALUES ('Mahogany Rush');
INSERT INTO data_musicians VALUES ('Mala Rodríguez');
INSERT INTO data_musicians VALUES ('Manic Street Preachers');
INSERT INTO data_musicians VALUES ('Manilla Road');
INSERT INTO data_musicians VALUES ('Manowar');
INSERT INTO data_musicians VALUES ('Marc Anthony');
INSERT INTO data_musicians VALUES ('Marc with a C');
INSERT INTO data_musicians VALUES ('Mariah Carey');
INSERT INTO data_musicians VALUES ('Marianne Faithfull');
INSERT INTO data_musicians VALUES ('Marillion');
INSERT INTO data_musicians VALUES ('Marilyn Manson');
INSERT INTO data_musicians VALUES ('Marnie Stern');
INSERT INTO data_musicians VALUES ('Maroon 5');
INSERT INTO data_musicians VALUES ('Marty Robbins');
INSERT INTO data_musicians VALUES ('Marvin Gaye');
INSERT INTO data_musicians VALUES ('Mary J. Blige');
INSERT INTO data_musicians VALUES ('Mary Mary');
INSERT INTO data_musicians VALUES ('Massive Attack');
INSERT INTO data_musicians VALUES ('Masters At Work');
INSERT INTO data_musicians VALUES ('Mastodon');
INSERT INTO data_musicians VALUES ('Matchbox Twenty');
INSERT INTO data_musicians VALUES ('Matisyahu');
INSERT INTO data_musicians VALUES ('Maurice Ravel');
INSERT INTO data_musicians VALUES ('Maxwell');
INSERT INTO data_musicians VALUES ('Mayday Parade');
INSERT INTO data_musicians VALUES ('Maze');
INSERT INTO data_musicians VALUES ('Mazzy Star');
INSERT INTO data_musicians VALUES ('Meat Beat Manifesto');
INSERT INTO data_musicians VALUES ('Meat Loaf');
INSERT INTO data_musicians VALUES ('Megadeth');
INSERT INTO data_musicians VALUES ('Melanie');
INSERT INTO data_musicians VALUES ('Melissa Etheridge');
INSERT INTO data_musicians VALUES ('Men at Work');
INSERT INTO data_musicians VALUES ('Menudo');
INSERT INTO data_musicians VALUES ('Mercyful Fate');
INSERT INTO data_musicians VALUES ('Metallica');
INSERT INTO data_musicians VALUES ('MGK');
INSERT INTO data_musicians VALUES ('MGMT');
INSERT INTO data_musicians VALUES ('Michael Bolton');
INSERT INTO data_musicians VALUES ('Michael Bublé');
INSERT INTO data_musicians VALUES ('Michael Hutchence');
INSERT INTO data_musicians VALUES ('Michael Jackson');
INSERT INTO data_musicians VALUES ('Michael Schenker Group');
INSERT INTO data_musicians VALUES ('Mick Jagger');
INSERT INTO data_musicians VALUES ('Midnight Oil');
INSERT INTO data_musicians VALUES ('Mighty Clouds of Joy');
INSERT INTO data_musicians VALUES ('Mika');
INSERT INTO data_musicians VALUES ('Mike Oldfield');
INSERT INTO data_musicians VALUES ('Mike Posner');
INSERT INTO data_musicians VALUES ('Mike Rutherford');
INSERT INTO data_musicians VALUES ('Mike Shinoda');
INSERT INTO data_musicians VALUES ('Miles Davis');
INSERT INTO data_musicians VALUES ('Miley Cyrus');
INSERT INTO data_musicians VALUES ('Ministry');
INSERT INTO data_musicians VALUES ('Miranda Cosgrove');
INSERT INTO data_musicians VALUES ('Miranda Lambert');
INSERT INTO data_musicians VALUES ('Misfits');
INSERT INTO data_musicians VALUES ('Missing Persons');
INSERT INTO data_musicians VALUES ('Missy Elliott');
INSERT INTO data_musicians VALUES ('Mobb Deep');
INSERT INTO data_musicians VALUES ('Moby');
INSERT INTO data_musicians VALUES ('Modest Petrovich Mussorgsky');
INSERT INTO data_musicians VALUES ('Montrose');
INSERT INTO data_musicians VALUES ('Morrissey');
INSERT INTO data_musicians VALUES ('Mos Def');
INSERT INTO data_musicians VALUES ('Mötley Crüe');
INSERT INTO data_musicians VALUES ('Motörhead');
INSERT INTO data_musicians VALUES ('Mott the Hoople');
INSERT INTO data_musicians VALUES ('Mountain');
INSERT INTO data_musicians VALUES ('Muddy Waters');
INSERT INTO data_musicians VALUES ('Mumford & Sons');
INSERT INTO data_musicians VALUES ('Muse');
INSERT INTO data_musicians VALUES ('My Bloody Valentine');
INSERT INTO data_musicians VALUES ('My Chemical Romance');
INSERT INTO data_musicians VALUES ('N.W.A');
INSERT INTO data_musicians VALUES ('Napoleón Solo');
INSERT INTO data_musicians VALUES ('Nas');
INSERT INTO data_musicians VALUES ('Nash the Slash');
INSERT INTO data_musicians VALUES ('Nat King Cole');
INSERT INTO data_musicians VALUES ('Natalie Imbruglia');
INSERT INTO data_musicians VALUES ('Nate Dogg');
INSERT INTO data_musicians VALUES ('Naughty by Nature');
INSERT INTO data_musicians VALUES ('Nazareth');
INSERT INTO data_musicians VALUES ('Needtobreathe');
INSERT INTO data_musicians VALUES ('Neil Diamond');
INSERT INTO data_musicians VALUES ('Neil Sedaka');
INSERT INTO data_musicians VALUES ('Neil Young');
INSERT INTO data_musicians VALUES ('Nelly');
INSERT INTO data_musicians VALUES ('Nelly Furtado');
INSERT INTO data_musicians VALUES ('Neutral Milk Hotel');
INSERT INTO data_musicians VALUES ('New Edition');
INSERT INTO data_musicians VALUES ('New Order');
INSERT INTO data_musicians VALUES ('New York Dolls');
INSERT INTO data_musicians VALUES ('Ne-Yo');
INSERT INTO data_musicians VALUES ('Nick Drake');
INSERT INTO data_musicians VALUES ('Nickelback');
INSERT INTO data_musicians VALUES ('Nicki Minaj');
INSERT INTO data_musicians VALUES ('Nico');
INSERT INTO data_musicians VALUES ('Nicole Scherzinger');
INSERT INTO data_musicians VALUES ('Nightwish');
INSERT INTO data_musicians VALUES ('Nik Kershaw');
INSERT INTO data_musicians VALUES ('Nikolai Rimsky-Korsakov');
INSERT INTO data_musicians VALUES ('Nina Simone');
INSERT INTO data_musicians VALUES ('Nine Inch Nails');
INSERT INTO data_musicians VALUES ('Nirvana');
INSERT INTO data_musicians VALUES ('No Doubt');
INSERT INTO data_musicians VALUES ('NOFX');
INSERT INTO data_musicians VALUES ('Norah Jones');
INSERT INTO data_musicians VALUES ('Nusrat Fateh Ali Khan');
INSERT INTO data_musicians VALUES ('Oasis');
INSERT INTO data_musicians VALUES ('Odd Future');
INSERT INTO data_musicians VALUES ('Of Monsters and Men');
INSERT INTO data_musicians VALUES ('Olivia Newton-John');
INSERT INTO data_musicians VALUES ('Omega');
INSERT INTO data_musicians VALUES ('One Direction');
INSERT INTO data_musicians VALUES ('OneRepublic');
INSERT INTO data_musicians VALUES ('Opeth');
INSERT INTO data_musicians VALUES ('Orianthi');
INSERT INTO data_musicians VALUES ('Otis Redding');
INSERT INTO data_musicians VALUES ('Outkast');
INSERT INTO data_musicians VALUES ('Overkill');
INSERT INTO data_musicians VALUES ('Owl City');
INSERT INTO data_musicians VALUES ('Ozzy Osbourne');
INSERT INTO data_musicians VALUES ('P!nk');
INSERT INTO data_musicians VALUES ('Paco Ibáñez');
INSERT INTO data_musicians VALUES ('Panic! at the Disco');
INSERT INTO data_musicians VALUES ('Pantera');
INSERT INTO data_musicians VALUES ('Papa Roach');
INSERT INTO data_musicians VALUES ('Parachute');
INSERT INTO data_musicians VALUES ('Paramore');
INSERT INTO data_musicians VALUES ('Paris Hilton');
INSERT INTO data_musicians VALUES ('Parliament-Funkadelic');
INSERT INTO data_musicians VALUES ('Pat Benatar');
INSERT INTO data_musicians VALUES ('Pat McGee Band');
INSERT INTO data_musicians VALUES ('Patrick Stump');
INSERT INTO data_musicians VALUES ('Patsy Cline');
INSERT INTO data_musicians VALUES ('Patti LaBelle');
INSERT INTO data_musicians VALUES ('Patti Smith');
INSERT INTO data_musicians VALUES ('Patty Smyth');
INSERT INTO data_musicians VALUES ('Paul McCartney');
INSERT INTO data_musicians VALUES ('Paul Oakenfold');
INSERT INTO data_musicians VALUES ('Paul Simon');
INSERT INTO data_musicians VALUES ('Paul Stanley');
INSERT INTO data_musicians VALUES ('Paul van Dyk');
INSERT INTO data_musicians VALUES ('Pavement');
INSERT INTO data_musicians VALUES ('Pavlov''s Dog');
INSERT INTO data_musicians VALUES ('Peabo Bryson');
INSERT INTO data_musicians VALUES ('Pearl Jam');
INSERT INTO data_musicians VALUES ('Pentagram');
INSERT INTO data_musicians VALUES ('Pet Shop Boys');
INSERT INTO data_musicians VALUES ('Pete Rock & CL Smooth');
INSERT INTO data_musicians VALUES ('Pete Yorn');
INSERT INTO data_musicians VALUES ('Peter and Gordon');
INSERT INTO data_musicians VALUES ('Peter Frampton');
INSERT INTO data_musicians VALUES ('Peter Gabriel');
INSERT INTO data_musicians VALUES ('Peter Tosh');
INSERT INTO data_musicians VALUES ('Peter, Paul and Mary');
INSERT INTO data_musicians VALUES ('Pharrell Williams');
INSERT INTO data_musicians VALUES ('Phil Collins');
INSERT INTO data_musicians VALUES ('Phil Spector');
INSERT INTO data_musicians VALUES ('Philip Glass');
INSERT INTO data_musicians VALUES ('Philip Wesley');
INSERT INTO data_musicians VALUES ('Phillip Phillips');
INSERT INTO data_musicians VALUES ('Phish');
INSERT INTO data_musicians VALUES ('Pink Floyd');
INSERT INTO data_musicians VALUES ('Pitbull');
INSERT INTO data_musicians VALUES ('Pixie Lott');
INSERT INTO data_musicians VALUES ('Pixies');
INSERT INTO data_musicians VALUES ('PJ Harvey');
INSERT INTO data_musicians VALUES ('Placebo');
INSERT INTO data_musicians VALUES ('Pooh');
INSERT INTO data_musicians VALUES ('Porcupine Tree');
INSERT INTO data_musicians VALUES ('Porno for Pyros');
INSERT INTO data_musicians VALUES ('Portishead');
INSERT INTO data_musicians VALUES ('Pretenders');
INSERT INTO data_musicians VALUES ('Primus');
INSERT INTO data_musicians VALUES ('Prince');
INSERT INTO data_musicians VALUES ('Prodigy');
INSERT INTO data_musicians VALUES ('Protest the Hero');
INSERT INTO data_musicians VALUES ('Psy');
INSERT INTO data_musicians VALUES ('Public Enemy');
INSERT INTO data_musicians VALUES ('Pusha T');
INSERT INTO data_musicians VALUES ('Pyotr Ilyich Tchaikovsky');
INSERT INTO data_musicians VALUES ('Queen');
INSERT INTO data_musicians VALUES ('Queen Latifah');
INSERT INTO data_musicians VALUES ('Queens of the Stone Age');
INSERT INTO data_musicians VALUES ('Queensr che');
INSERT INTO data_musicians VALUES ('Quiet Riot');
INSERT INTO data_musicians VALUES ('Quincy Jones');
INSERT INTO data_musicians VALUES ('R. Kelly');
INSERT INTO data_musicians VALUES ('R.E.M.');
INSERT INTO data_musicians VALUES ('Radiohead');
INSERT INTO data_musicians VALUES ('Rage Against the Machine');
INSERT INTO data_musicians VALUES ('Rainbow');
INSERT INTO data_musicians VALUES ('Ramones');
INSERT INTO data_musicians VALUES ('Randy Savage');
INSERT INTO data_musicians VALUES ('Randy Travis');
INSERT INTO data_musicians VALUES ('Ratt');
INSERT INTO data_musicians VALUES ('Ray Charles');
INSERT INTO data_musicians VALUES ('Ray Price');
INSERT INTO data_musicians VALUES ('Reba McEntire');
INSERT INTO data_musicians VALUES ('Red Hot Chili Peppers');
INSERT INTO data_musicians VALUES ('Regina Belle');
INSERT INTO data_musicians VALUES ('Renaissance');
INSERT INTO data_musicians VALUES ('Return to Forever');
INSERT INTO data_musicians VALUES ('Rhapsody of Fire');
INSERT INTO data_musicians VALUES ('Ricardo Montaner');
INSERT INTO data_musicians VALUES ('Richard Strauss');
INSERT INTO data_musicians VALUES ('Richard Wagner');
INSERT INTO data_musicians VALUES ('Rick Astley');
INSERT INTO data_musicians VALUES ('Rick James');
INSERT INTO data_musicians VALUES ('Rick Ross');
INSERT INTO data_musicians VALUES ('Rick Wakeman');
INSERT INTO data_musicians VALUES ('Ricky Martin');
INSERT INTO data_musicians VALUES ('Rihanna');
INSERT INTO data_musicians VALUES ('Ringo Starr');
INSERT INTO data_musicians VALUES ('Rise Against');
INSERT INTO data_musicians VALUES ('Rita Ora');
INSERT INTO data_musicians VALUES ('Ritchie Blackmore');
INSERT INTO data_musicians VALUES ('Robbie Williams');
INSERT INTO data_musicians VALUES ('Robert Alexander Schumann');
INSERT INTO data_musicians VALUES ('Robert Johnson');
INSERT INTO data_musicians VALUES ('Robert Plant');
INSERT INTO data_musicians VALUES ('Robin Trower');
INSERT INTO data_musicians VALUES ('Rod Stewart');
INSERT INTO data_musicians VALUES ('Rodriguez');
INSERT INTO data_musicians VALUES ('Ron Korb');
INSERT INTO data_musicians VALUES ('Roni Size');
INSERT INTO data_musicians VALUES ('Ronnie jordan');
INSERT INTO data_musicians VALUES ('Ronnie Milsap');
INSERT INTO data_musicians VALUES ('Ronnie Spector');
INSERT INTO data_musicians VALUES ('Rory Gallagher');
INSERT INTO data_musicians VALUES ('Roxy Music');
INSERT INTO data_musicians VALUES ('Roy Orbison');
INSERT INTO data_musicians VALUES ('Run-D.M.C.');
INSERT INTO data_musicians VALUES ('Rush');
INSERT INTO data_musicians VALUES ('Ryan Adams');
INSERT INTO data_musicians VALUES ('RZA');
INSERT INTO data_musicians VALUES ('Sade Adu');
INSERT INTO data_musicians VALUES ('Salsoul Orchestra');
INSERT INTO data_musicians VALUES ('Salt-N-Pepa');
INSERT INTO data_musicians VALUES ('Sam Cooke');
INSERT INTO data_musicians VALUES ('Sammy Hagar');
INSERT INTO data_musicians VALUES ('Santana');
INSERT INTO data_musicians VALUES ('Sarah Brightman');
INSERT INTO data_musicians VALUES ('Sarah McLachlan');
INSERT INTO data_musicians VALUES ('Schoolboy Q');
INSERT INTO data_musicians VALUES ('Scorpions');
INSERT INTO data_musicians VALUES ('Scott Joplin');
INSERT INTO data_musicians VALUES ('Seal');
INSERT INTO data_musicians VALUES ('Seals and Crofts');
INSERT INTO data_musicians VALUES ('Sean Combs');
INSERT INTO data_musicians VALUES ('Sean Kingston');
INSERT INTO data_musicians VALUES ('Secondhand Serenade');
INSERT INTO data_musicians VALUES ('Seether');
INSERT INTO data_musicians VALUES ('Selena Gomez');
INSERT INTO data_musicians VALUES ('Sergei Prokofiev');
INSERT INTO data_musicians VALUES ('Sergei Rachmaninoff');
INSERT INTO data_musicians VALUES ('Sex Pistols');
INSERT INTO data_musicians VALUES ('Shane MacGowan');
INSERT INTO data_musicians VALUES ('Shania Twain');
INSERT INTO data_musicians VALUES ('Sheryl Crow');
INSERT INTO data_musicians VALUES ('Shirley Caesar');
INSERT INTO data_musicians VALUES ('Sigur Rós');
INSERT INTO data_musicians VALUES ('Silversun Pickups');
INSERT INTO data_musicians VALUES ('Simon and Garfunkel');
INSERT INTO data_musicians VALUES ('Simon O''Shine');
INSERT INTO data_musicians VALUES ('Simple Minds');
INSERT INTO data_musicians VALUES ('Simply Red');
INSERT INTO data_musicians VALUES ('Sinéad O''Connor');
INSERT INTO data_musicians VALUES ('Skid Row');
INSERT INTO data_musicians VALUES ('Skrillex');
INSERT INTO data_musicians VALUES ('Skunk Anansie');
INSERT INTO data_musicians VALUES ('Skylar Grey');
INSERT INTO data_musicians VALUES ('Slaughterhouse');
INSERT INTO data_musicians VALUES ('Slayer');
INSERT INTO data_musicians VALUES ('Sleater-Kinney');
INSERT INTO data_musicians VALUES ('Slick Rick');
INSERT INTO data_musicians VALUES ('Slint');
INSERT INTO data_musicians VALUES ('Sly & the Family Stone');
INSERT INTO data_musicians VALUES ('Smog');
INSERT INTO data_musicians VALUES ('Smokey Robinson');
INSERT INTO data_musicians VALUES ('Snoop Dogg');
INSERT INTO data_musicians VALUES ('Social Distortion');
INSERT INTO data_musicians VALUES ('Solomon Burke');
INSERT INTO data_musicians VALUES ('Son House');
INSERT INTO data_musicians VALUES ('Sonic Youth');
INSERT INTO data_musicians VALUES ('Soul Asylum');
INSERT INTO data_musicians VALUES ('Soundgarden');
INSERT INTO data_musicians VALUES ('Split Enz');
INSERT INTO data_musicians VALUES ('Spooky Tooth');
INSERT INTO data_musicians VALUES ('Squarepusher');
INSERT INTO data_musicians VALUES ('Stacey Kent');
INSERT INTO data_musicians VALUES ('Steely Dan');
INSERT INTO data_musicians VALUES ('Steppenwolf');
INSERT INTO data_musicians VALUES ('Stereophonics');
INSERT INTO data_musicians VALUES ('Steve Hackett');
INSERT INTO data_musicians VALUES ('Steve Hogarth');
INSERT INTO data_musicians VALUES ('Steve Miller Band');
INSERT INTO data_musicians VALUES ('Steve Reich');
INSERT INTO data_musicians VALUES ('Steve Winwood');
INSERT INTO data_musicians VALUES ('Steven Tyler');
INSERT INTO data_musicians VALUES ('Stevie Nicks');
INSERT INTO data_musicians VALUES ('Stevie Ray Vaughan');
INSERT INTO data_musicians VALUES ('Stevie Wonder');
INSERT INTO data_musicians VALUES ('Sting');
INSERT INTO data_musicians VALUES ('Stone Temple Pilots');
INSERT INTO data_musicians VALUES ('Strawbs');
INSERT INTO data_musicians VALUES ('Styx');
INSERT INTO data_musicians VALUES ('Sublime');
INSERT INTO data_musicians VALUES ('Suede');
INSERT INTO data_musicians VALUES ('Sufjan Stevens');
INSERT INTO data_musicians VALUES ('Suicide Silence');
INSERT INTO data_musicians VALUES ('Sum 41');
INSERT INTO data_musicians VALUES ('Superchunk');
INSERT INTO data_musicians VALUES ('Supertramp');
INSERT INTO data_musicians VALUES ('Susanna Hoffs');
INSERT INTO data_musicians VALUES ('Swedish House Mafia');
INSERT INTO data_musicians VALUES ('Sweet');
INSERT INTO data_musicians VALUES ('Swizz Beatz');
INSERT INTO data_musicians VALUES ('System of a Down');
INSERT INTO data_musicians VALUES ('T. Rex');
INSERT INTO data_musicians VALUES ('T.I.');
INSERT INTO data_musicians VALUES ('Taio Cruz');
INSERT INTO data_musicians VALUES ('Talib Kweli');
INSERT INTO data_musicians VALUES ('Talking Heads');
INSERT INTO data_musicians VALUES ('Tangerine Dream');
INSERT INTO data_musicians VALUES ('Tanita Tikaram');
INSERT INTO data_musicians VALUES ('Taylor Swift');
INSERT INTO data_musicians VALUES ('Tchaikovsky');
INSERT INTO data_musicians VALUES ('Tears for Fears');
INSERT INTO data_musicians VALUES ('Teenage Fanclub');
INSERT INTO data_musicians VALUES ('Television');
INSERT INTO data_musicians VALUES ('Tequila');
INSERT INTO data_musicians VALUES ('Terry Riley');
INSERT INTO data_musicians VALUES ('Testament');
INSERT INTO data_musicians VALUES ('The Afghan Whigs');
INSERT INTO data_musicians VALUES ('The Alan Parsons Project');
INSERT INTO data_musicians VALUES ('The Allman Brothers Band');
INSERT INTO data_musicians VALUES ('The Andrew Lloyd Webber Orchestra');
INSERT INTO data_musicians VALUES ('The Angels');
INSERT INTO data_musicians VALUES ('The B-52''s');
INSERT INTO data_musicians VALUES ('The Band');
INSERT INTO data_musicians VALUES ('The Bangles');
INSERT INTO data_musicians VALUES ('The Beach Boys');
INSERT INTO data_musicians VALUES ('The Beatles');
INSERT INTO data_musicians VALUES ('The Black Crowes');
INSERT INTO data_musicians VALUES ('The Black Eyed Peas');
INSERT INTO data_musicians VALUES ('The Black Keys');
INSERT INTO data_musicians VALUES ('The Bloody Hollies');
INSERT INTO data_musicians VALUES ('The Breeders');
INSERT INTO data_musicians VALUES ('The Byrds');
INSERT INTO data_musicians VALUES ('The Cars');
INSERT INTO data_musicians VALUES ('The Charlatans');
INSERT INTO data_musicians VALUES ('The Charlie Daniels Band');
INSERT INTO data_musicians VALUES ('The Chocolate Watchband');
INSERT INTO data_musicians VALUES ('The Clancy Brothers');
INSERT INTO data_musicians VALUES ('The Clash');
INSERT INTO data_musicians VALUES ('The Cranberries');
INSERT INTO data_musicians VALUES ('The Cult');
INSERT INTO data_musicians VALUES ('The Cure');
INSERT INTO data_musicians VALUES ('The Damned');
INSERT INTO data_musicians VALUES ('The Dave Brubeck Quartet');
INSERT INTO data_musicians VALUES ('The Dave Clark Five');
INSERT INTO data_musicians VALUES ('The Doobie Brothers');
INSERT INTO data_musicians VALUES ('The Doors');
INSERT INTO data_musicians VALUES ('The Drifters');
INSERT INTO data_musicians VALUES ('The Dubliners');
INSERT INTO data_musicians VALUES ('The Everly Brothers');
INSERT INTO data_musicians VALUES ('The Fall');
INSERT INTO data_musicians VALUES ('The Feelies');
INSERT INTO data_musicians VALUES ('The Firm');
INSERT INTO data_musicians VALUES ('The Four Seasons');
INSERT INTO data_musicians VALUES ('The Fray');
INSERT INTO data_musicians VALUES ('The Future Sound of London');
INSERT INTO data_musicians VALUES ('The Go-Go''s');
INSERT INTO data_musicians VALUES ('The Guess Who');
INSERT INTO data_musicians VALUES ('The Hollies');
INSERT INTO data_musicians VALUES ('The Human League');
INSERT INTO data_musicians VALUES ('The Imperials');
INSERT INTO data_musicians VALUES ('The Isley Brothers');
INSERT INTO data_musicians VALUES ('The J. Geils Band');
INSERT INTO data_musicians VALUES ('The Jackson 5');
INSERT INTO data_musicians VALUES ('The Jam');
INSERT INTO data_musicians VALUES ('The Jesus Lizard');
INSERT INTO data_musicians VALUES ('The Jimi Hendrix Experience');
INSERT INTO data_musicians VALUES ('The Kelly Family');
INSERT INTO data_musicians VALUES ('The Killers');
INSERT INTO data_musicians VALUES ('The Kinks');
INSERT INTO data_musicians VALUES ('The Lonely Island');
INSERT INTO data_musicians VALUES ('The Louvin Brothers');
INSERT INTO data_musicians VALUES ('The Lovin'' Spoonful');
INSERT INTO data_musicians VALUES ('The Mahavishnu Orchestra');
INSERT INTO data_musicians VALUES ('The Mamas & the Papas');
INSERT INTO data_musicians VALUES ('The Manhattan Transfer');
INSERT INTO data_musicians VALUES ('The Mighty Lemon Drops');
INSERT INTO data_musicians VALUES ('The Miracles');
INSERT INTO data_musicians VALUES ('The Misfits');
INSERT INTO data_musicians VALUES ('The Monkees');
INSERT INTO data_musicians VALUES ('The Moody Blues');
INSERT INTO data_musicians VALUES ('The New Raemon');
INSERT INTO data_musicians VALUES ('The Notorious B.I.G.');
INSERT INTO data_musicians VALUES ('The O''Jays');
INSERT INTO data_musicians VALUES ('The Orb');
INSERT INTO data_musicians VALUES ('The Outlaws');
INSERT INTO data_musicians VALUES ('The Platters');
INSERT INTO data_musicians VALUES ('The Police');
INSERT INTO data_musicians VALUES ('The Presidents of the United S...');
INSERT INTO data_musicians VALUES ('The Prodigy');
INSERT INTO data_musicians VALUES ('The Protomen');
INSERT INTO data_musicians VALUES ('The Psychedelic Furs');
INSERT INTO data_musicians VALUES ('The Pussycat Dolls');
INSERT INTO data_musicians VALUES ('The Rasmus');
INSERT INTO data_musicians VALUES ('The Red Jumpsuit Apparatus');
INSERT INTO data_musicians VALUES ('The Replacements');
INSERT INTO data_musicians VALUES ('The Reverend Horton Heat');
INSERT INTO data_musicians VALUES ('The Righteous Brothers');
INSERT INTO data_musicians VALUES ('The Rolling Stones');
INSERT INTO data_musicians VALUES ('The Romantics');
INSERT INTO data_musicians VALUES ('The Ronettes');
INSERT INTO data_musicians VALUES ('The Roots');
INSERT INTO data_musicians VALUES ('The Script');
INSERT INTO data_musicians VALUES ('The Searchers');
INSERT INTO data_musicians VALUES ('The Shirelles');
INSERT INTO data_musicians VALUES ('The Smashing Pumpkins');
INSERT INTO data_musicians VALUES ('The Smithereens');
INSERT INTO data_musicians VALUES ('The Smiths');
INSERT INTO data_musicians VALUES ('The Stone Roses');
INSERT INTO data_musicians VALUES ('The Stooges');
INSERT INTO data_musicians VALUES ('The Stranglers');
INSERT INTO data_musicians VALUES ('The Strokes');
INSERT INTO data_musicians VALUES ('The Sugarcubes');
INSERT INTO data_musicians VALUES ('The Sugarhill Gang');
INSERT INTO data_musicians VALUES ('The Supremes');
INSERT INTO data_musicians VALUES ('The Temptations');
INSERT INTO data_musicians VALUES ('The Three Degrees');
INSERT INTO data_musicians VALUES ('The Time');
INSERT INTO data_musicians VALUES ('The Tremeloes');
INSERT INTO data_musicians VALUES ('The Turtles');
INSERT INTO data_musicians VALUES ('The Vaccines');
INSERT INTO data_musicians VALUES ('The Velvet Underground');
INSERT INTO data_musicians VALUES ('The Wanted');
INSERT INTO data_musicians VALUES ('The Waterboys');
INSERT INTO data_musicians VALUES ('The Weeknd');
INSERT INTO data_musicians VALUES ('The White Stripes');
INSERT INTO data_musicians VALUES ('The Who');
INSERT INTO data_musicians VALUES ('The xx');
INSERT INTO data_musicians VALUES ('The Yardbirds');
INSERT INTO data_musicians VALUES ('Thelonious Monk');
INSERT INTO data_musicians VALUES ('Therion');
INSERT INTO data_musicians VALUES ('Thin Lizzy');
INSERT INTO data_musicians VALUES ('Third Eye Blind');
INSERT INTO data_musicians VALUES ('Thomas Tallis');
INSERT INTO data_musicians VALUES ('Thompson Twins');
INSERT INTO data_musicians VALUES ('Three Days Grace');
INSERT INTO data_musicians VALUES ('Three Dog Night');
INSERT INTO data_musicians VALUES ('Tiesto');
INSERT INTO data_musicians VALUES ('Tiffany Alvord');
INSERT INTO data_musicians VALUES ('Timbaland');
INSERT INTO data_musicians VALUES ('Tina Turner');
INSERT INTO data_musicians VALUES ('Tinie Tempah');
INSERT INTO data_musicians VALUES ('Todd Rundgren');
INSERT INTO data_musicians VALUES ('Tokio Hotel');
INSERT INTO data_musicians VALUES ('Tom Jones');
INSERT INTO data_musicians VALUES ('Tom Petty');
INSERT INTO data_musicians VALUES ('Tom Petty and the Heartbreakers');
INSERT INTO data_musicians VALUES ('Tom Waits');
INSERT INTO data_musicians VALUES ('Tomaso Albinoni');
INSERT INTO data_musicians VALUES ('Tommy James & the Shondells');
INSERT INTO data_musicians VALUES ('Tony Banks');
INSERT INTO data_musicians VALUES ('Tony Bennett');
INSERT INTO data_musicians VALUES ('Tony Yayo');
INSERT INTO data_musicians VALUES ('Tool');
INSERT INTO data_musicians VALUES ('Tori Amos');
INSERT INTO data_musicians VALUES ('Tori Kelly');
INSERT INTO data_musicians VALUES ('Tortoise');
INSERT INTO data_musicians VALUES ('Toto');
INSERT INTO data_musicians VALUES ('T-Pain');
INSERT INTO data_musicians VALUES ('Tracy Chapman');
INSERT INTO data_musicians VALUES ('Train');
INSERT INTO data_musicians VALUES ('Trans-Siberian Orchestra');
INSERT INTO data_musicians VALUES ('Travis Barker');
INSERT INTO data_musicians VALUES ('Trey Songz');
INSERT INTO data_musicians VALUES ('Tricky');
INSERT INTO data_musicians VALUES ('Triumph');
INSERT INTO data_musicians VALUES ('Trouble');
INSERT INTO data_musicians VALUES ('Tupac Shakur');
INSERT INTO data_musicians VALUES ('Two Door Cinema Club');
INSERT INTO data_musicians VALUES ('Tyga');
INSERT INTO data_musicians VALUES ('Tyler, the Creator');
INSERT INTO data_musicians VALUES ('U2');
INSERT INTO data_musicians VALUES ('UFO');
INSERT INTO data_musicians VALUES ('UK');
INSERT INTO data_musicians VALUES ('Ultravox');
INSERT INTO data_musicians VALUES ('Uriah Heep');
INSERT INTO data_musicians VALUES ('Usher');
INSERT INTO data_musicians VALUES ('Vampire Weekend');
INSERT INTO data_musicians VALUES ('Van der Graaf Generator');
INSERT INTO data_musicians VALUES ('Van Halen');
INSERT INTO data_musicians VALUES ('Van Morrison');
INSERT INTO data_musicians VALUES ('Vangelis');
INSERT INTO data_musicians VALUES ('Vanilla Ice');
INSERT INTO data_musicians VALUES ('Velvet Revolver');
INSERT INTO data_musicians VALUES ('Victoria Justice');
INSERT INTO data_musicians VALUES ('Virginia Coalition');
INSERT INTO data_musicians VALUES ('Visage');
INSERT INTO data_musicians VALUES ('Waka Flocka Flame');
INSERT INTO data_musicians VALUES ('Wale');
INSERT INTO data_musicians VALUES ('Walk Off the Earth');
INSERT INTO data_musicians VALUES ('Walter Klien');
INSERT INTO data_musicians VALUES ('War');
INSERT INTO data_musicians VALUES ('Warren Zevon');
INSERT INTO data_musicians VALUES ('Waylon Jennings');
INSERT INTO data_musicians VALUES ('We Are the In Crowd');
INSERT INTO data_musicians VALUES ('We Came as Romans');
INSERT INTO data_musicians VALUES ('Whitesnake');
INSERT INTO data_musicians VALUES ('Whitney Houston');
INSERT INTO data_musicians VALUES ('Wilco');
INSERT INTO data_musicians VALUES ('Will Hoge');
INSERT INTO data_musicians VALUES ('Will Smith');
INSERT INTO data_musicians VALUES ('Will.i.am');
INSERT INTO data_musicians VALUES ('William Byrd');
INSERT INTO data_musicians VALUES ('William Orbit');
INSERT INTO data_musicians VALUES ('Willie Nelson');
INSERT INTO data_musicians VALUES ('Wilson Pickett');
INSERT INTO data_musicians VALUES ('Wishbone Ash');
INSERT INTO data_musicians VALUES ('Witchfynde');
INSERT INTO data_musicians VALUES ('Wiz Khalifa');
INSERT INTO data_musicians VALUES ('Wolfe Tones');
INSERT INTO data_musicians VALUES ('Wolfgang Amadeus Mozart');
INSERT INTO data_musicians VALUES ('Woody Guthrie');
INSERT INTO data_musicians VALUES ('Wu-Tang Clan');
INSERT INTO data_musicians VALUES ('X Japan');
INSERT INTO data_musicians VALUES ('Xatar');
INSERT INTO data_musicians VALUES ('XTC');
INSERT INTO data_musicians VALUES ('Yanni');
INSERT INTO data_musicians VALUES ('Yazoo');
INSERT INTO data_musicians VALUES ('Yelawolf');
INSERT INTO data_musicians VALUES ('Yes');
INSERT INTO data_musicians VALUES ('Yiruma');
INSERT INTO data_musicians VALUES ('Yngwie Malmsteen');
INSERT INTO data_musicians VALUES ('Yo La Tengo');
INSERT INTO data_musicians VALUES ('Yusuf Islam');
INSERT INTO data_musicians VALUES ('Z.Z. Hill');
INSERT INTO data_musicians VALUES ('Zakaria Abdulla');
INSERT INTO data_musicians VALUES ('Zayn Malik');
INSERT INTO data_musicians VALUES ('Zebra');
INSERT INTO data_musicians VALUES ('ZZ Top');
