CREATE TABLE data_religion (
    `Column_1` VARCHAR(94) CHARACTER SET utf8
);
INSERT INTO data_religion VALUES ('RELIGION');
INSERT INTO data_religion VALUES ('Christianity');
INSERT INTO data_religion VALUES ('Catholicism');
INSERT INTO data_religion VALUES ('Western');
INSERT INTO data_religion VALUES ('Chinese Patriotic Catholic Association');
INSERT INTO data_religion VALUES ('Independent Catholic Churches');
INSERT INTO data_religion VALUES ('Brazilian Catholic Apostolic Church');
INSERT INTO data_religion VALUES ('Philippine Independent Church (In communion with the Anglican Church and the Union of Utrecht)');
INSERT INTO data_religion VALUES ('Polish National Catholic Church');
INSERT INTO data_religion VALUES ('Union of Utrecht (In communion with the Anglican Church)');
INSERT INTO data_religion VALUES ('Old Catholicism');
INSERT INTO data_religion VALUES ('Liberal Catholic Church');
INSERT INTO data_religion VALUES ('Roman Catholicism');
INSERT INTO data_religion VALUES ('Sui iuris (including Byzantine Rite churches)');
INSERT INTO data_religion VALUES ('Traditionalist Catholicism');
INSERT INTO data_religion VALUES ('Eastern');
INSERT INTO data_religion VALUES ('Eastern Catholic Churches');
INSERT INTO data_religion VALUES ('Eastern Orthodoxy');
INSERT INTO data_religion VALUES ('Greek Orthodox Church');
INSERT INTO data_religion VALUES ('Russian Orthodox Church');
INSERT INTO data_religion VALUES ('Oriental Orthodoxy');
INSERT INTO data_religion VALUES ('Coptic Orthodox Church');
INSERT INTO data_religion VALUES ('Ethiopian Orthodox Church');
INSERT INTO data_religion VALUES ('Syriac Christianity');
INSERT INTO data_religion VALUES ('Assyrian Church of the East');
INSERT INTO data_religion VALUES ('Indian Orthodox Church');
INSERT INTO data_religion VALUES ('Malankara Orthodox Syrian Church');
INSERT INTO data_religion VALUES ('Syriac Orthodox Church');
INSERT INTO data_religion VALUES ('Mar Thoma Church');
INSERT INTO data_religion VALUES ('Syriac Catholic Church');
INSERT INTO data_religion VALUES ('Protestantism');
INSERT INTO data_religion VALUES ('Anglicanism (via media between the Roman Catholic Church and Protestantism)');
INSERT INTO data_religion VALUES ('Anglican Communion');
INSERT INTO data_religion VALUES ('Church of England');
INSERT INTO data_religion VALUES ('Church of Ireland');
INSERT INTO data_religion VALUES ('Church of Wales');
INSERT INTO data_religion VALUES ('Episcopal Church (United States)');
INSERT INTO data_religion VALUES ('Scottish Episcopal Church');
INSERT INTO data_religion VALUES ('Pre-Lutheran Protestants');
INSERT INTO data_religion VALUES ('Hussites');
INSERT INTO data_religion VALUES ('Lollards');
INSERT INTO data_religion VALUES ('Waldensians');
INSERT INTO data_religion VALUES ('Anabaptists');
INSERT INTO data_religion VALUES ('Amish');
INSERT INTO data_religion VALUES ('Brethren in Christ');
INSERT INTO data_religion VALUES ('Church of the Brethren');
INSERT INTO data_religion VALUES ('Hutterites');
INSERT INTO data_religion VALUES ('Mennonites');
INSERT INTO data_religion VALUES ('Old German Baptist Brethren');
INSERT INTO data_religion VALUES ('Baptists');
INSERT INTO data_religion VALUES ('Brethren');
INSERT INTO data_religion VALUES ('Catholic Apostolic Church');
INSERT INTO data_religion VALUES ('Charismatic movement');
INSERT INTO data_religion VALUES ('Christadelphians');
INSERT INTO data_religion VALUES ('Christian Israelite Church');
INSERT INTO data_religion VALUES ('Christian New Religious Movements');
INSERT INTO data_religion VALUES ('Unification Church (Moonies)');
INSERT INTO data_religion VALUES ('Christian Science');
INSERT INTO data_religion VALUES ('Children of God');
INSERT INTO data_religion VALUES ('Peoples Temple');
INSERT INTO data_religion VALUES ('Eckankar');
INSERT INTO data_religion VALUES ('Esoteric Christianity');
INSERT INTO data_religion VALUES ('Free Presbyterian Church of Ulster');
INSERT INTO data_religion VALUES ('Lutheranism');
INSERT INTO data_religion VALUES ('Methodism');
INSERT INTO data_religion VALUES ('Messianic Judaism');
INSERT INTO data_religion VALUES ('Most Holy Church of God in Christ Jesus');
INSERT INTO data_religion VALUES ('New Thought');
INSERT INTO data_religion VALUES ('Pentecostalism');
INSERT INTO data_religion VALUES ('Oneness Pentecostalism');
INSERT INTO data_religion VALUES ('Pietism');
INSERT INTO data_religion VALUES ('Holiness movement');
INSERT INTO data_religion VALUES ('Reformed churches');
INSERT INTO data_religion VALUES ('Puritans');
INSERT INTO data_religion VALUES ('Presbyterianism');
INSERT INTO data_religion VALUES ('Congregational church');
INSERT INTO data_religion VALUES ('Religious Society of Friends');
INSERT INTO data_religion VALUES ('Spiritism');
INSERT INTO data_religion VALUES ('Espiritismo');
INSERT INTO data_religion VALUES ('Swedenborgianism');
INSERT INTO data_religion VALUES ('Christian Spiritualism');
INSERT INTO data_religion VALUES ('United and uniting churches');
INSERT INTO data_religion VALUES ('Unitarianism');
INSERT INTO data_religion VALUES ('Universalism');
INSERT INTO data_religion VALUES ('Restorationism');
INSERT INTO data_religion VALUES ('Adventism');
INSERT INTO data_religion VALUES ('Millerites');
INSERT INTO data_religion VALUES ('Sabbatarianism');
INSERT INTO data_religion VALUES ('Seventh-day Adventists');
INSERT INTO data_religion VALUES ('Christadelphians');
INSERT INTO data_religion VALUES ('Latter Day Saint movement (Mormonism)');
INSERT INTO data_religion VALUES ('Church of Christ (Temple Lot)');
INSERT INTO data_religion VALUES ('Community of Christ');
INSERT INTO data_religion VALUES ('Rigdonites');
INSERT INTO data_religion VALUES ('The Church of Jesus Christ (Bickertonite)');
INSERT INTO data_religion VALUES ('The Church of Jesus Christ of Latter-day Saints');
INSERT INTO data_religion VALUES ('Fundamentalist Church of Jesus Christ of Latter Day Saints');
INSERT INTO data_religion VALUES ('The Church of Jesus Christ of Latter Day Saints (Strangite)');
INSERT INTO data_religion VALUES ('Iglesia ni Cristo');
INSERT INTO data_religion VALUES ('New Apostolic church');
INSERT INTO data_religion VALUES ('Jehovah''s Witnesses');
INSERT INTO data_religion VALUES ('Restoration Movement');
INSERT INTO data_religion VALUES ('Gnosticism');
INSERT INTO data_religion VALUES ('Christian Gnosticism');
INSERT INTO data_religion VALUES ('Ebionites');
INSERT INTO data_religion VALUES ('Cerdonians');
INSERT INTO data_religion VALUES ('Marcionism (not entirely Gnostic)');
INSERT INTO data_religion VALUES ('Colorbasians');
INSERT INTO data_religion VALUES ('Simonians');
INSERT INTO data_religion VALUES ('Early Gnosticism');
INSERT INTO data_religion VALUES ('Borborites');
INSERT INTO data_religion VALUES ('Cainites');
INSERT INTO data_religion VALUES ('Carpocratians');
INSERT INTO data_religion VALUES ('Ophites');
INSERT INTO data_religion VALUES ('Hermeticism');
INSERT INTO data_religion VALUES ('Medieval Gnosticism');
INSERT INTO data_religion VALUES ('Cathars');
INSERT INTO data_religion VALUES ('Bogomils');
INSERT INTO data_religion VALUES ('Paulicianism');
INSERT INTO data_religion VALUES ('Tondrakians');
INSERT INTO data_religion VALUES ('Persian Gnosticism');
INSERT INTO data_religion VALUES ('Mandaeanism');
INSERT INTO data_religion VALUES ('Manichaeism');
INSERT INTO data_religion VALUES ('Bagnolians');
INSERT INTO data_religion VALUES ('Syrian-Egyptic Gnosticism');
INSERT INTO data_religion VALUES ('Sethians');
INSERT INTO data_religion VALUES ('Basilidians');
INSERT INTO data_religion VALUES ('Thomasines');
INSERT INTO data_religion VALUES ('Valentinians');
INSERT INTO data_religion VALUES ('Bardesanites');
INSERT INTO data_religion VALUES ('Islam');
INSERT INTO data_religion VALUES ('Kalam Schools');
INSERT INTO data_religion VALUES ('Ash''ari');
INSERT INTO data_religion VALUES ('Kalam');
INSERT INTO data_religion VALUES ('Maturidi');
INSERT INTO data_religion VALUES ('Murji''ah');
INSERT INTO data_religion VALUES ('Mu''tazili');
INSERT INTO data_religion VALUES ('Kharijite');
INSERT INTO data_religion VALUES ('Ibadi');
INSERT INTO data_religion VALUES ('Azraqi');
INSERT INTO data_religion VALUES ('Haruriyya');
INSERT INTO data_religion VALUES ('Sufri');
INSERT INTO data_religion VALUES ('Shi''ism');
INSERT INTO data_religion VALUES ('Ismailis');
INSERT INTO data_religion VALUES ('Nizari / Aga Khani');
INSERT INTO data_religion VALUES ('Mustaali / Bohra');
INSERT INTO data_religion VALUES ('Jafari');
INSERT INTO data_religion VALUES ('Twelvers');
INSERT INTO data_religion VALUES ('Alawites');
INSERT INTO data_religion VALUES ('Alevi / Bektashi');
INSERT INTO data_religion VALUES ('Zaiddiyah');
INSERT INTO data_religion VALUES ('Sufism');
INSERT INTO data_religion VALUES ('Bektashi');
INSERT INTO data_religion VALUES ('Chishti');
INSERT INTO data_religion VALUES ('Mevlevi');
INSERT INTO data_religion VALUES ('Naqshbandi');
INSERT INTO data_religion VALUES ('Tariqah');
INSERT INTO data_religion VALUES ('Quadiriyyah');
INSERT INTO data_religion VALUES ('Suhrawardiyya');
INSERT INTO data_religion VALUES ('Tijani');
INSERT INTO data_religion VALUES ('Universal Sufism');
INSERT INTO data_religion VALUES ('Dances of Universal Peace');
INSERT INTO data_religion VALUES ('Sunnism');
INSERT INTO data_religion VALUES ('Hanafi');
INSERT INTO data_religion VALUES ('Berailvi');
INSERT INTO data_religion VALUES ('Deobandi');
INSERT INTO data_religion VALUES ('Hanbali');
INSERT INTO data_religion VALUES ('Wahhabi');
INSERT INTO data_religion VALUES ('Maliki');
INSERT INTO data_religion VALUES ('Shafi''i');
INSERT INTO data_religion VALUES ('Restorationism');
INSERT INTO data_religion VALUES ('Ghair muqallidism');
INSERT INTO data_religion VALUES ('Salafism');
INSERT INTO data_religion VALUES ('Muwahhidism');
INSERT INTO data_religion VALUES ('Quranism');
INSERT INTO data_religion VALUES ('Groups sometimes considered non-Islamic');
INSERT INTO data_religion VALUES ('Ahl-e Haqq (Yarsan)');
INSERT INTO data_religion VALUES ('Ahl-e Hadith');
INSERT INTO data_religion VALUES ('Ahl-e Qur''an');
INSERT INTO data_religion VALUES ('Ahmadiyya');
INSERT INTO data_religion VALUES ('Druze');
INSERT INTO data_religion VALUES ('Nation of Islam');
INSERT INTO data_religion VALUES ('Nazati Muslim');
INSERT INTO data_religion VALUES ('Moorish Science Temple of America');
INSERT INTO data_religion VALUES ('United Submitters International');
INSERT INTO data_religion VALUES ('Zikri');
INSERT INTO data_religion VALUES ('Judaism');
INSERT INTO data_religion VALUES ('Rabbinic Judaism');
INSERT INTO data_religion VALUES ('Conservative Judaism');
INSERT INTO data_religion VALUES ('Masorti');
INSERT INTO data_religion VALUES ('Conservadox Judaism');
INSERT INTO data_religion VALUES ('Union for Traditional Judaism');
INSERT INTO data_religion VALUES ('Orthodox Judaism');
INSERT INTO data_religion VALUES ('Haredi Judaism');
INSERT INTO data_religion VALUES ('Hasidic Judaism');
INSERT INTO data_religion VALUES ('Modern Orthodox Judaism');
INSERT INTO data_religion VALUES ('Reform Judaism');
INSERT INTO data_religion VALUES ('Progressive Judaism');
INSERT INTO data_religion VALUES ('Liberal Judaism');
INSERT INTO data_religion VALUES ('Non-Rabbinic Judaism');
INSERT INTO data_religion VALUES ('Alternative Judaism');
INSERT INTO data_religion VALUES ('Humanistic Judaism');
INSERT INTO data_religion VALUES ('Jewish Renewal');
INSERT INTO data_religion VALUES ('Karaite Judaism');
INSERT INTO data_religion VALUES ('Reconstructionist Judaism');
INSERT INTO data_religion VALUES ('Historical groups');
INSERT INTO data_religion VALUES ('Essenes');
INSERT INTO data_religion VALUES ('Pharisees (ancestor of Rabbinic Judaism)');
INSERT INTO data_religion VALUES ('Sadducees');
INSERT INTO data_religion VALUES ('Zealots');
INSERT INTO data_religion VALUES ('Sicarii');
INSERT INTO data_religion VALUES ('Other sects');
INSERT INTO data_religion VALUES ('Ebionites');
INSERT INTO data_religion VALUES ('Elkasites');
INSERT INTO data_religion VALUES ('Nazarenes');
INSERT INTO data_religion VALUES ('Sabbateans');
INSERT INTO data_religion VALUES ('Frankists');
INSERT INTO data_religion VALUES ('Others');
INSERT INTO data_religion VALUES ('Bábism');
INSERT INTO data_religion VALUES ('Azali');
INSERT INTO data_religion VALUES ('Bahá''í Faith');
INSERT INTO data_religion VALUES ('Mandaeism');
INSERT INTO data_religion VALUES ('Rastafari movement');
INSERT INTO data_religion VALUES ('Sabians');
INSERT INTO data_religion VALUES ('Samaritanism');
INSERT INTO data_religion VALUES ('Other');
