CREATE TABLE data_pets (
    `Column_1` VARCHAR(50) CHARACTER SET utf8
);
INSERT INTO data_pets VALUES ('Alpaca');
INSERT INTO data_pets VALUES ('Anole, green');
INSERT INTO data_pets VALUES ('Boa, rosy');
INSERT INTO data_pets VALUES ('Boa, sand');
INSERT INTO data_pets VALUES ('Budgie');
INSERT INTO data_pets VALUES ('Buffalo');
INSERT INTO data_pets VALUES ('Canary');
INSERT INTO data_pets VALUES ('Cat, Abyssinian');
INSERT INTO data_pets VALUES ('Cat, American bobtail');
INSERT INTO data_pets VALUES ('Cat, American curl');
INSERT INTO data_pets VALUES ('Cat, American shorthair');
INSERT INTO data_pets VALUES ('Cat, American wirehair');
INSERT INTO data_pets VALUES ('Cat, Applehead siamese');
INSERT INTO data_pets VALUES ('Cat, Balinese');
INSERT INTO data_pets VALUES ('Cat, Bengal');
INSERT INTO data_pets VALUES ('Cat, Birman');
INSERT INTO data_pets VALUES ('Cat, Bobtail');
INSERT INTO data_pets VALUES ('Cat, Bombay');
INSERT INTO data_pets VALUES ('Cat, British shorthair');
INSERT INTO data_pets VALUES ('Cat, Burmese');
INSERT INTO data_pets VALUES ('Cat, Burmilla');
INSERT INTO data_pets VALUES ('Cat, Calico');
INSERT INTO data_pets VALUES ('Cat, Canadian hairless');
INSERT INTO data_pets VALUES ('Cat, Chartreux');
INSERT INTO data_pets VALUES ('Cat, Chausie');
INSERT INTO data_pets VALUES ('Cat, Chinchilla');
INSERT INTO data_pets VALUES ('Cat, Cornish rex');
INSERT INTO data_pets VALUES ('Cat, Cymric');
INSERT INTO data_pets VALUES ('Cat, Devon rex');
INSERT INTO data_pets VALUES ('Cat, Dilute calico');
INSERT INTO data_pets VALUES ('Cat, Dilute tortoiseshell');
INSERT INTO data_pets VALUES ('Cat, Domestic long hair');
INSERT INTO data_pets VALUES ('Cat, Domestic medium hair');
INSERT INTO data_pets VALUES ('Cat, Domestic short hair');
INSERT INTO data_pets VALUES ('Cat, Egyptian mau');
INSERT INTO data_pets VALUES ('Cat, Exotic shorthair');
INSERT INTO data_pets VALUES ('Cat, Extra-toes (hemingway polydactyl)');
INSERT INTO data_pets VALUES ('Cat, Havana brown');
INSERT INTO data_pets VALUES ('Cat, Himalayan');
INSERT INTO data_pets VALUES ('Cat, Japanese bobtail');
INSERT INTO data_pets VALUES ('Cat, Javanese');
INSERT INTO data_pets VALUES ('Cat, Korat');
INSERT INTO data_pets VALUES ('Cat, Laperm');
INSERT INTO data_pets VALUES ('Cat, Maine coon');
INSERT INTO data_pets VALUES ('Cat, Manx');
INSERT INTO data_pets VALUES ('Cat, Munchkin');
INSERT INTO data_pets VALUES ('Cat, Nebelung');
INSERT INTO data_pets VALUES ('Cat, Norwegian forest');
INSERT INTO data_pets VALUES ('Cat, Ocicat');
INSERT INTO data_pets VALUES ('Cat, Oriental');
INSERT INTO data_pets VALUES ('Cat, Oriental long hair');
INSERT INTO data_pets VALUES ('Cat, Oriental short hair');
INSERT INTO data_pets VALUES ('Cat, Oriental tabby');
INSERT INTO data_pets VALUES ('Cat, Persian');
INSERT INTO data_pets VALUES ('Cat, Pixie-bob');
INSERT INTO data_pets VALUES ('Cat, Ragamuffin');
INSERT INTO data_pets VALUES ('Cat, Ragdoll');
INSERT INTO data_pets VALUES ('Cat, Russian blue');
INSERT INTO data_pets VALUES ('Cat, Scottish fold');
INSERT INTO data_pets VALUES ('Cat, Selkirk rex');
INSERT INTO data_pets VALUES ('Cat, Siamese');
INSERT INTO data_pets VALUES ('Cat, Siberian');
INSERT INTO data_pets VALUES ('Cat, Silver');
INSERT INTO data_pets VALUES ('Cat, Singapura');
INSERT INTO data_pets VALUES ('Cat, Snowshoe');
INSERT INTO data_pets VALUES ('Cat, Somali');
INSERT INTO data_pets VALUES ('Cat, Sphynx');
INSERT INTO data_pets VALUES ('Cat, Sphynx (hairless)');
INSERT INTO data_pets VALUES ('Cat, Tabby');
INSERT INTO data_pets VALUES ('Cat, Tiger');
INSERT INTO data_pets VALUES ('Cat, Tonkinese');
INSERT INTO data_pets VALUES ('Cat, Torbie');
INSERT INTO data_pets VALUES ('Cat, Tortoiseshell');
INSERT INTO data_pets VALUES ('Cat, Turkish angora');
INSERT INTO data_pets VALUES ('Cat, Turkish van');
INSERT INTO data_pets VALUES ('Cat, Tuxedo');
INSERT INTO data_pets VALUES ('Chameleon');
INSERT INTO data_pets VALUES ('Chicken');
INSERT INTO data_pets VALUES ('Chinchilla');
INSERT INTO data_pets VALUES ('Cockatiel');
INSERT INTO data_pets VALUES ('Cockatoo');
INSERT INTO data_pets VALUES ('Cow');
INSERT INTO data_pets VALUES ('Crab, hermit');
INSERT INTO data_pets VALUES ('Dog, Affenpinscher');
INSERT INTO data_pets VALUES ('Dog, Afghan hound');
INSERT INTO data_pets VALUES ('Dog, Airedale terrier');
INSERT INTO data_pets VALUES ('Dog, Akbash');
INSERT INTO data_pets VALUES ('Dog, Akita');
INSERT INTO data_pets VALUES ('Dog, Alaskan malamute');
INSERT INTO data_pets VALUES ('Dog, American bulldog');
INSERT INTO data_pets VALUES ('Dog, American english coonhound');
INSERT INTO data_pets VALUES ('Dog, American eskimo dog');
INSERT INTO data_pets VALUES ('Dog, American foxhound');
INSERT INTO data_pets VALUES ('Dog, American hairless terrier');
INSERT INTO data_pets VALUES ('Dog, American pit bull terrier');
INSERT INTO data_pets VALUES ('Dog, American staffordshire terrier');
INSERT INTO data_pets VALUES ('Dog, American water spaniel');
INSERT INTO data_pets VALUES ('Dog, Anatolian shepherd dog');
INSERT INTO data_pets VALUES ('Dog, Appenzell mountain dog');
INSERT INTO data_pets VALUES ('Dog, Appenzeller sennenhunde');
INSERT INTO data_pets VALUES ('Dog, Australian cattle dog');
INSERT INTO data_pets VALUES ('Dog, Australian kelpie');
INSERT INTO data_pets VALUES ('Dog, Australian shepherd');
INSERT INTO data_pets VALUES ('Dog, Australian terrier');
INSERT INTO data_pets VALUES ('Dog, Australiantle dog (blue heeler)');
INSERT INTO data_pets VALUES ('Dog, Azawakh');
INSERT INTO data_pets VALUES ('Dog, Barbet');
INSERT INTO data_pets VALUES ('Dog, Basenji');
INSERT INTO data_pets VALUES ('Dog, Basset hound');
INSERT INTO data_pets VALUES ('Dog, Beagle');
INSERT INTO data_pets VALUES ('Dog, Bearded collie');
INSERT INTO data_pets VALUES ('Dog, Beauceron');
INSERT INTO data_pets VALUES ('Dog, Bedlington terrier');
INSERT INTO data_pets VALUES ('Dog, Belgian malinois');
INSERT INTO data_pets VALUES ('Dog, Belgian shepherd dog sheepdog');
INSERT INTO data_pets VALUES ('Dog, Belgian shepherd laekenois');
INSERT INTO data_pets VALUES ('Dog, Belgian shepherd malinois');
INSERT INTO data_pets VALUES ('Dog, Belgian shepherd tervuren');
INSERT INTO data_pets VALUES ('Dog, Belgian tervuren');
INSERT INTO data_pets VALUES ('Dog, Berger picard');
INSERT INTO data_pets VALUES ('Dog, Bernese mountain dog');
INSERT INTO data_pets VALUES ('Dog, Bichon frise');
INSERT INTO data_pets VALUES ('Dog, Black and tan coonhound');
INSERT INTO data_pets VALUES ('Dog, Black labrador retriever');
INSERT INTO data_pets VALUES ('Dog, Black mouth cur');
INSERT INTO data_pets VALUES ('Dog, Black russian terrier');
INSERT INTO data_pets VALUES ('Dog, Bloodhound');
INSERT INTO data_pets VALUES ('Dog, Blue lacy');
INSERT INTO data_pets VALUES ('Dog, Bluetick coonhound');
INSERT INTO data_pets VALUES ('Dog, Boerboel');
INSERT INTO data_pets VALUES ('Dog, Bolognese');
INSERT INTO data_pets VALUES ('Dog, Border collie');
INSERT INTO data_pets VALUES ('Dog, Border terrier');
INSERT INTO data_pets VALUES ('Dog, Borzoi');
INSERT INTO data_pets VALUES ('Dog, Boston terrier');
INSERT INTO data_pets VALUES ('Dog, Bouvier des flanders');
INSERT INTO data_pets VALUES ('Dog, Boxer');
INSERT INTO data_pets VALUES ('Dog, Boykin spaniel');
INSERT INTO data_pets VALUES ('Dog, Bracco italiano');
INSERT INTO data_pets VALUES ('Dog, Briard');
INSERT INTO data_pets VALUES ('Dog, Brittany spaniel');
INSERT INTO data_pets VALUES ('Dog, Brussels griffon');
INSERT INTO data_pets VALUES ('Dog, Bull terrier');
INSERT INTO data_pets VALUES ('Dog, Bulldog');
INSERT INTO data_pets VALUES ('Dog, Bullmastiff');
INSERT INTO data_pets VALUES ('Dog, Cairn terrier');
INSERT INTO data_pets VALUES ('Dog, Canaan dog');
INSERT INTO data_pets VALUES ('Dog, Cane corso mastiff');
INSERT INTO data_pets VALUES ('Dog, Cardigan welsh corgi');
INSERT INTO data_pets VALUES ('Dog, Carolina dog');
INSERT INTO data_pets VALUES ('Dog, Catahoula leopard dog');
INSERT INTO data_pets VALUES ('Dog, Cattle dog');
INSERT INTO data_pets VALUES ('Dog, Caucasian sheepdog (caucasian ovtcharka)');
INSERT INTO data_pets VALUES ('Dog, Cavalier king charles spaniel');
INSERT INTO data_pets VALUES ('Dog, Cesky terrier');
INSERT INTO data_pets VALUES ('Dog, Chesapeake bay retriever');
INSERT INTO data_pets VALUES ('Dog, Chihuahua');
INSERT INTO data_pets VALUES ('Dog, Chinese crested dog');
INSERT INTO data_pets VALUES ('Dog, Chinese foo dog');
INSERT INTO data_pets VALUES ('Dog, Chinese shar-pei');
INSERT INTO data_pets VALUES ('Dog, Chinook');
INSERT INTO data_pets VALUES ('Dog, Chocolate labrador retriever');
INSERT INTO data_pets VALUES ('Dog, Chow chow');
INSERT INTO data_pets VALUES ('Dog, Cirneco dell''etna');
INSERT INTO data_pets VALUES ('Dog, Clumber spaniel');
INSERT INTO data_pets VALUES ('Dog, Cockapoo');
INSERT INTO data_pets VALUES ('Dog, Cocker spaniel');
INSERT INTO data_pets VALUES ('Dog, Collie');
INSERT INTO data_pets VALUES ('Dog, Coonhound');
INSERT INTO data_pets VALUES ('Dog, Corgi');
INSERT INTO data_pets VALUES ('Dog, Coton de tulear');
INSERT INTO data_pets VALUES ('Dog, Curly-coated retriever');
INSERT INTO data_pets VALUES ('Dog, Dachshund');
INSERT INTO data_pets VALUES ('Dog, Dalmatian');
INSERT INTO data_pets VALUES ('Dog, Dandie dinmont terrier');
INSERT INTO data_pets VALUES ('Dog, Doberman pinscher');
INSERT INTO data_pets VALUES ('Dog, Dogo argentino');
INSERT INTO data_pets VALUES ('Dog, Dogue de bordeaux');
INSERT INTO data_pets VALUES ('Dog, Dutch shepherd');
INSERT INTO data_pets VALUES ('Dog, English bulldog');
INSERT INTO data_pets VALUES ('Dog, English cocker spaniel');
INSERT INTO data_pets VALUES ('Dog, English coonhound');
INSERT INTO data_pets VALUES ('Dog, English foxhound');
INSERT INTO data_pets VALUES ('Dog, English pointer');
INSERT INTO data_pets VALUES ('Dog, English setter');
INSERT INTO data_pets VALUES ('Dog, English shepherd');
INSERT INTO data_pets VALUES ('Dog, English springer spaniel');
INSERT INTO data_pets VALUES ('Dog, English toy spaniel');
INSERT INTO data_pets VALUES ('Dog, Entlebucher');
INSERT INTO data_pets VALUES ('Dog, Entlebucher mountain dog');
INSERT INTO data_pets VALUES ('Dog, Eskimo dog');
INSERT INTO data_pets VALUES ('Dog, Feist');
INSERT INTO data_pets VALUES ('Dog, Field spaniel');
INSERT INTO data_pets VALUES ('Dog, Fila brasileiro');
INSERT INTO data_pets VALUES ('Dog, Finnish lapphund');
INSERT INTO data_pets VALUES ('Dog, Finnish spitz');
INSERT INTO data_pets VALUES ('Dog, Flat-coated retriever');
INSERT INTO data_pets VALUES ('Dog, Fox terrier');
INSERT INTO data_pets VALUES ('Dog, Foxhound');
INSERT INTO data_pets VALUES ('Dog, French bulldog');
INSERT INTO data_pets VALUES ('Dog, Galgo spanish greyhound');
INSERT INTO data_pets VALUES ('Dog, German pinscher');
INSERT INTO data_pets VALUES ('Dog, German shepherd dog');
INSERT INTO data_pets VALUES ('Dog, German shorthaired pointer');
INSERT INTO data_pets VALUES ('Dog, German spitz');
INSERT INTO data_pets VALUES ('Dog, German wirehaired pointer');
INSERT INTO data_pets VALUES ('Dog, Giant schnauzer');
INSERT INTO data_pets VALUES ('Dog, Glen of imaal terrier');
INSERT INTO data_pets VALUES ('Dog, Goldador');
INSERT INTO data_pets VALUES ('Dog, Golden retriever');
INSERT INTO data_pets VALUES ('Dog, Goldendoodle');
INSERT INTO data_pets VALUES ('Dog, Gordon setter');
INSERT INTO data_pets VALUES ('Dog, Great dane');
INSERT INTO data_pets VALUES ('Dog, Great pyrenees');
INSERT INTO data_pets VALUES ('Dog, Greater swiss mountain dog');
INSERT INTO data_pets VALUES ('Dog, Greyhound');
INSERT INTO data_pets VALUES ('Dog, Harrier');
INSERT INTO data_pets VALUES ('Dog, Havanese');
INSERT INTO data_pets VALUES ('Dog, Hound');
INSERT INTO data_pets VALUES ('Dog, Hovawart');
INSERT INTO data_pets VALUES ('Dog, Husky');
INSERT INTO data_pets VALUES ('Dog, Ibizan hound');
INSERT INTO data_pets VALUES ('Dog, Icelandic sheepdog');
INSERT INTO data_pets VALUES ('Dog, Illyrian sheepdog');
INSERT INTO data_pets VALUES ('Dog, Irish red and white setter');
INSERT INTO data_pets VALUES ('Dog, Irish setter');
INSERT INTO data_pets VALUES ('Dog, Irish terrier');
INSERT INTO data_pets VALUES ('Dog, Irish water spaniel');
INSERT INTO data_pets VALUES ('Dog, Irish wolfhound');
INSERT INTO data_pets VALUES ('Dog, Italian greyhound');
INSERT INTO data_pets VALUES ('Dog, Italian spinone');
INSERT INTO data_pets VALUES ('Dog, Jack russell terrier (parson russell terrier)');
INSERT INTO data_pets VALUES ('Dog, Japanese chin');
INSERT INTO data_pets VALUES ('Dog, Jindo');
INSERT INTO data_pets VALUES ('Dog, Kai dog');
INSERT INTO data_pets VALUES ('Dog, Karelian bear dog');
INSERT INTO data_pets VALUES ('Dog, Keeshond');
INSERT INTO data_pets VALUES ('Dog, Kerry blue terrier');
INSERT INTO data_pets VALUES ('Dog, Kishu');
INSERT INTO data_pets VALUES ('Dog, Klee kai');
INSERT INTO data_pets VALUES ('Dog, Komondor');
INSERT INTO data_pets VALUES ('Dog, Kooikerhondje');
INSERT INTO data_pets VALUES ('Dog, Korean jindo dog');
INSERT INTO data_pets VALUES ('Dog, Kuvasz');
INSERT INTO data_pets VALUES ('Dog, Kyi leo');
INSERT INTO data_pets VALUES ('Dog, Labradoodle');
INSERT INTO data_pets VALUES ('Dog, Labrador retriever');
INSERT INTO data_pets VALUES ('Dog, Lakeland terrier');
INSERT INTO data_pets VALUES ('Dog, Lancashire heeler');
INSERT INTO data_pets VALUES ('Dog, Leonberger');
INSERT INTO data_pets VALUES ('Dog, Lhasa apso');
INSERT INTO data_pets VALUES ('Dog, Lowchen');
INSERT INTO data_pets VALUES ('Dog, Maltese');
INSERT INTO data_pets VALUES ('Dog, Maltese shih tzu');
INSERT INTO data_pets VALUES ('Dog, Maltipoo');
INSERT INTO data_pets VALUES ('Dog, Manchester terrier');
INSERT INTO data_pets VALUES ('Dog, Maremma sheepdog');
INSERT INTO data_pets VALUES ('Dog, Mastiff');
INSERT INTO data_pets VALUES ('Dog, Mcnab');
INSERT INTO data_pets VALUES ('Dog, Miniature pinscher');
INSERT INTO data_pets VALUES ('Dog, Miniature schnauzer');
INSERT INTO data_pets VALUES ('Dog, Mountain cur');
INSERT INTO data_pets VALUES ('Dog, Mountain dog');
INSERT INTO data_pets VALUES ('Dog, Munsterlander');
INSERT INTO data_pets VALUES ('Dog, Mutt');
INSERT INTO data_pets VALUES ('Dog, Neapolitan mastiff');
INSERT INTO data_pets VALUES ('Dog, New guinea singing dog');
INSERT INTO data_pets VALUES ('Dog, Newfoundland dog');
INSERT INTO data_pets VALUES ('Dog, Norfolk terrier');
INSERT INTO data_pets VALUES ('Dog, Norwegian buhund');
INSERT INTO data_pets VALUES ('Dog, Norwegian elkhound');
INSERT INTO data_pets VALUES ('Dog, Norwegian lundehund');
INSERT INTO data_pets VALUES ('Dog, Norwich terrier');
INSERT INTO data_pets VALUES ('Dog, Nova scotia duck-tolling retriever');
INSERT INTO data_pets VALUES ('Dog, Old english sheepdog');
INSERT INTO data_pets VALUES ('Dog, Otterhound');
INSERT INTO data_pets VALUES ('Dog, Papillon');
INSERT INTO data_pets VALUES ('Dog, Patterdale terrier (fell terrier)');
INSERT INTO data_pets VALUES ('Dog, Peekapoo');
INSERT INTO data_pets VALUES ('Dog, Pekingese');
INSERT INTO data_pets VALUES ('Dog, Pembroke welsh corgi');
INSERT INTO data_pets VALUES ('Dog, Peruvian inca orchid');
INSERT INTO data_pets VALUES ('Dog, Petit basset griffon vendeen');
INSERT INTO data_pets VALUES ('Dog, Pharaoh hound');
INSERT INTO data_pets VALUES ('Dog, Pit bull terrier');
INSERT INTO data_pets VALUES ('Dog, Plott hound');
INSERT INTO data_pets VALUES ('Dog, Pocket beagle');
INSERT INTO data_pets VALUES ('Dog, Podengo portugueso');
INSERT INTO data_pets VALUES ('Dog, Pointer');
INSERT INTO data_pets VALUES ('Dog, Polish lowland sheepdog');
INSERT INTO data_pets VALUES ('Dog, Pomeranian');
INSERT INTO data_pets VALUES ('Dog, Poodle');
INSERT INTO data_pets VALUES ('Dog, Portuguese water dog');
INSERT INTO data_pets VALUES ('Dog, Presa canario');
INSERT INTO data_pets VALUES ('Dog, Pug');
INSERT INTO data_pets VALUES ('Dog, Puggle');
INSERT INTO data_pets VALUES ('Dog, Puli');
INSERT INTO data_pets VALUES ('Dog, Pumi');
INSERT INTO data_pets VALUES ('Dog, Pyrenean shepherd');
INSERT INTO data_pets VALUES ('Dog, Rat terrier');
INSERT INTO data_pets VALUES ('Dog, Redbone coonhound');
INSERT INTO data_pets VALUES ('Dog, Retriever');
INSERT INTO data_pets VALUES ('Dog, Rhodesian ridgeback');
INSERT INTO data_pets VALUES ('Dog, Rottweiler');
INSERT INTO data_pets VALUES ('Dog, Saint bernard st. Bernard');
INSERT INTO data_pets VALUES ('Dog, Saluki');
INSERT INTO data_pets VALUES ('Dog, Samoyed');
INSERT INTO data_pets VALUES ('Dog, Sarplaninac');
INSERT INTO data_pets VALUES ('Dog, Schipperke');
INSERT INTO data_pets VALUES ('Dog, Schnauzer');
INSERT INTO data_pets VALUES ('Dog, Schnoodle');
INSERT INTO data_pets VALUES ('Dog, Scottish deerhound');
INSERT INTO data_pets VALUES ('Dog, Scottish terrier scottie');
INSERT INTO data_pets VALUES ('Dog, Sealyham terrier');
INSERT INTO data_pets VALUES ('Dog, Setter');
INSERT INTO data_pets VALUES ('Dog, Shar pei');
INSERT INTO data_pets VALUES ('Dog, Sheep dog');
INSERT INTO data_pets VALUES ('Dog, Shepherd');
INSERT INTO data_pets VALUES ('Dog, Shetland sheepdog sheltie');
INSERT INTO data_pets VALUES ('Dog, Shiba inu');
INSERT INTO data_pets VALUES ('Dog, Shih tzu');
INSERT INTO data_pets VALUES ('Dog, Siberian husky');
INSERT INTO data_pets VALUES ('Dog, Silky terrier');
INSERT INTO data_pets VALUES ('Dog, Skye terrier');
INSERT INTO data_pets VALUES ('Dog, Sloughi');
INSERT INTO data_pets VALUES ('Dog, Small munsterlander pointer');
INSERT INTO data_pets VALUES ('Dog, Smooth fox terrier');
INSERT INTO data_pets VALUES ('Dog, Soft coated wheaten terrier');
INSERT INTO data_pets VALUES ('Dog, South russian ovtcharka');
INSERT INTO data_pets VALUES ('Dog, Spaniel');
INSERT INTO data_pets VALUES ('Dog, Spitz');
INSERT INTO data_pets VALUES ('Dog, Stabyhoun');
INSERT INTO data_pets VALUES ('Dog, Staffordshire bull terrier');
INSERT INTO data_pets VALUES ('Dog, Standard poodle');
INSERT INTO data_pets VALUES ('Dog, Standard schnauzer');
INSERT INTO data_pets VALUES ('Dog, Sussex spaniel');
INSERT INTO data_pets VALUES ('Dog, Swedish vallhund');
INSERT INTO data_pets VALUES ('Dog, Terrier');
INSERT INTO data_pets VALUES ('Dog, Thai ridgeback');
INSERT INTO data_pets VALUES ('Dog, Tibetan mastiff');
INSERT INTO data_pets VALUES ('Dog, Tibetan spaniel');
INSERT INTO data_pets VALUES ('Dog, Tibetan terrier');
INSERT INTO data_pets VALUES ('Dog, Tosa inu');
INSERT INTO data_pets VALUES ('Dog, Toy fox terrier');
INSERT INTO data_pets VALUES ('Dog, Treeing tennessee brindle');
INSERT INTO data_pets VALUES ('Dog, Treeing walker coonhound');
INSERT INTO data_pets VALUES ('Dog, Vizsla');
INSERT INTO data_pets VALUES ('Dog, Weimaraner');
INSERT INTO data_pets VALUES ('Dog, Welsh corgi');
INSERT INTO data_pets VALUES ('Dog, Welsh springer spaniel');
INSERT INTO data_pets VALUES ('Dog, Welsh terrier');
INSERT INTO data_pets VALUES ('Dog, West highland white terrier westie');
INSERT INTO data_pets VALUES ('Dog, Wheaten terrier');
INSERT INTO data_pets VALUES ('Dog, Whippet');
INSERT INTO data_pets VALUES ('Dog, White german shepherd');
INSERT INTO data_pets VALUES ('Dog, Wire fox terrier');
INSERT INTO data_pets VALUES ('Dog, Wire-haired pointing griffon');
INSERT INTO data_pets VALUES ('Dog, Wirehaired terrier');
INSERT INTO data_pets VALUES ('Dog, Xoloitzcuintle (mexican hairless)');
INSERT INTO data_pets VALUES ('Dog, Yellow labrador retriever');
INSERT INTO data_pets VALUES ('Dog, Yorkipoo');
INSERT INTO data_pets VALUES ('Dog, Yorkshire terrier yorkie');
INSERT INTO data_pets VALUES ('Donkey');
INSERT INTO data_pets VALUES ('Dove');
INSERT INTO data_pets VALUES ('Dragon, bearded');
INSERT INTO data_pets VALUES ('Dragon, chinese water');
INSERT INTO data_pets VALUES ('Dragon, frilled');
INSERT INTO data_pets VALUES ('Duck');
INSERT INTO data_pets VALUES ('Elephant');
INSERT INTO data_pets VALUES ('Emu');
INSERT INTO data_pets VALUES ('Ferret');
INSERT INTO data_pets VALUES ('Finch');
INSERT INTO data_pets VALUES ('Fish, barb');
INSERT INTO data_pets VALUES ('Fish, betta');
INSERT INTO data_pets VALUES ('Fish, guppy');
INSERT INTO data_pets VALUES ('Fish, koi');
INSERT INTO data_pets VALUES ('Fish, siamese fighting');
INSERT INTO data_pets VALUES ('Fox, silver');
INSERT INTO data_pets VALUES ('Frog, american green tree');
INSERT INTO data_pets VALUES ('Frog, argentine horned');
INSERT INTO data_pets VALUES ('Frog, barking tree');
INSERT INTO data_pets VALUES ('Frog, chubby & tomato');
INSERT INTO data_pets VALUES ('Frog, pac man');
INSERT INTO data_pets VALUES ('Frog, pixie');
INSERT INTO data_pets VALUES ('Frog, tree');
INSERT INTO data_pets VALUES ('Frog, white’s dumpy tree');
INSERT INTO data_pets VALUES ('Gecko');
INSERT INTO data_pets VALUES ('Gecko, leopard');
INSERT INTO data_pets VALUES ('Gecko, panther');
INSERT INTO data_pets VALUES ('Geese');
INSERT INTO data_pets VALUES ('Gerbil');
INSERT INTO data_pets VALUES ('Goat');
INSERT INTO data_pets VALUES ('Goldfish');
INSERT INTO data_pets VALUES ('Goose');
INSERT INTO data_pets VALUES ('Guinea fowl');
INSERT INTO data_pets VALUES ('Hamster');
INSERT INTO data_pets VALUES ('Horse, Appaloosa');
INSERT INTO data_pets VALUES ('Horse, Arabian');
INSERT INTO data_pets VALUES ('Horse, Belgian');
INSERT INTO data_pets VALUES ('Horse, Clydesdale');
INSERT INTO data_pets VALUES ('Horse, Curly horse');
INSERT INTO data_pets VALUES ('Horse, Donkey');
INSERT INTO data_pets VALUES ('Horse, Draft');
INSERT INTO data_pets VALUES ('Horse, Gaited');
INSERT INTO data_pets VALUES ('Horse, Grade');
INSERT INTO data_pets VALUES ('Horse, Lipizzan');
INSERT INTO data_pets VALUES ('Horse, Miniature horse');
INSERT INTO data_pets VALUES ('Horse, Missouri foxtrotter');
INSERT INTO data_pets VALUES ('Horse, Morgan');
INSERT INTO data_pets VALUES ('Horse, Mule');
INSERT INTO data_pets VALUES ('Horse, Mustang');
INSERT INTO data_pets VALUES ('Horse, Paint/pinto');
INSERT INTO data_pets VALUES ('Horse, Palomino');
INSERT INTO data_pets VALUES ('Horse, Paso fino');
INSERT INTO data_pets VALUES ('Horse, Percheron');
INSERT INTO data_pets VALUES ('Horse, Peruvian paso');
INSERT INTO data_pets VALUES ('Horse, Pony');
INSERT INTO data_pets VALUES ('Horse, Quarterhorse');
INSERT INTO data_pets VALUES ('Horse, Saddlebred');
INSERT INTO data_pets VALUES ('Horse, Shetland pony');
INSERT INTO data_pets VALUES ('Horse, Standardbred');
INSERT INTO data_pets VALUES ('Horse, Tennessee walker');
INSERT INTO data_pets VALUES ('Horse, Thoroughbred');
INSERT INTO data_pets VALUES ('Horse, Warmblood');
INSERT INTO data_pets VALUES ('Iguana, green');
INSERT INTO data_pets VALUES ('Lizard, collared');
INSERT INTO data_pets VALUES ('Lizard, curly tail');
INSERT INTO data_pets VALUES ('Lizard, longtail');
INSERT INTO data_pets VALUES ('Lizard, long-tailed grass');
INSERT INTO data_pets VALUES ('Lizard, mountain horned');
INSERT INTO data_pets VALUES ('Lizard, savannah monitor');
INSERT INTO data_pets VALUES ('Llama');
INSERT INTO data_pets VALUES ('Lory/lorikeet');
INSERT INTO data_pets VALUES ('Lovebird');
INSERT INTO data_pets VALUES ('Macaw');
INSERT INTO data_pets VALUES ('Mouse, fancy');
INSERT INTO data_pets VALUES ('Ostrich');
INSERT INTO data_pets VALUES ('Parakeet');
INSERT INTO data_pets VALUES ('Parrot');
INSERT INTO data_pets VALUES ('Parrot, companion');
INSERT INTO data_pets VALUES ('Peacock/pea fowl');
INSERT INTO data_pets VALUES ('Pheasant');
INSERT INTO data_pets VALUES ('Pig');
INSERT INTO data_pets VALUES ('Pig, guinea');
INSERT INTO data_pets VALUES ('Pigeon');
INSERT INTO data_pets VALUES ('Python, ball');
INSERT INTO data_pets VALUES ('Quail');
INSERT INTO data_pets VALUES ('Rabbit');
INSERT INTO data_pets VALUES ('Rat, fancy');
INSERT INTO data_pets VALUES ('Runner, steppe');
INSERT INTO data_pets VALUES ('Salamander, tiger');
INSERT INTO data_pets VALUES ('Scorpion');
INSERT INTO data_pets VALUES ('Sheep');
INSERT INTO data_pets VALUES ('Skink');
INSERT INTO data_pets VALUES ('Skink, blue tongue');
INSERT INTO data_pets VALUES ('Skink, prehensile tailed');
INSERT INTO data_pets VALUES ('Snake, corn');
INSERT INTO data_pets VALUES ('Snake, garter');
INSERT INTO data_pets VALUES ('Snake, king');
INSERT INTO data_pets VALUES ('Snake, milk');
INSERT INTO data_pets VALUES ('Spider');
INSERT INTO data_pets VALUES ('Swan');
INSERT INTO data_pets VALUES ('Tarantula, rose hair');
INSERT INTO data_pets VALUES ('Toad, firebelly');
INSERT INTO data_pets VALUES ('Tortoise');
INSERT INTO data_pets VALUES ('Tortoise, red foot');
INSERT INTO data_pets VALUES ('Tortoise, russian & greek');
INSERT INTO data_pets VALUES ('Toucan');
INSERT INTO data_pets VALUES ('Turkey');
INSERT INTO data_pets VALUES ('Turtle');
INSERT INTO data_pets VALUES ('Turtle, aquatic');
INSERT INTO data_pets VALUES ('Turtle, box');
INSERT INTO data_pets VALUES ('Uromastyx');
INSERT INTO data_pets VALUES ('Uromastyx, mali');
