CREATE TABLE data_tvshows (
    `Column_1` VARCHAR(141) CHARACTER SET utf8
);
INSERT INTO data_tvshows VALUES ('24');
INSERT INTO data_tvshows VALUES ('10 Things I Hate About You');
INSERT INTO data_tvshows VALUES ('2 Broke Girls');
INSERT INTO data_tvshows VALUES ('30 Rock');
INSERT INTO data_tvshows VALUES ('3rd Rock from the Sun');
INSERT INTO data_tvshows VALUES ('4400, The');
INSERT INTO data_tvshows VALUES ('60 Minutes');
INSERT INTO data_tvshows VALUES ('7th Heaven');
INSERT INTO data_tvshows VALUES ('8 Simple Rules (aka 8 Simple Rules for Dating My Teenage Daughter)');
INSERT INTO data_tvshows VALUES ('A Team, The');
INSERT INTO data_tvshows VALUES ('A.N.T. Farm');
INSERT INTO data_tvshows VALUES ('Aaahh!!! Real Monsters');
INSERT INTO data_tvshows VALUES ('Absolutely Fabulous');
INSERT INTO data_tvshows VALUES ('Addams Family, The');
INSERT INTO data_tvshows VALUES ('Adventure Time');
INSERT INTO data_tvshows VALUES ('Adventures of Jimmy Neutron: Boy Genius, The');
INSERT INTO data_tvshows VALUES ('Adventures of Lano and Woodley, The');
INSERT INTO data_tvshows VALUES ('Adventures of Rocky and Bullwinkle and Friends, The');
INSERT INTO data_tvshows VALUES ('Adventures of Sir Lancelot, The');
INSERT INTO data_tvshows VALUES ('Agents of S.H.I.E.L.D.');
INSERT INTO data_tvshows VALUES ('ALF');
INSERT INTO data_tvshows VALUES ('Alias');
INSERT INTO data_tvshows VALUES ('All Grown Up');
INSERT INTO data_tvshows VALUES ('All in the Family');
INSERT INTO data_tvshows VALUES ('All That');
INSERT INTO data_tvshows VALUES ('Ally McBeal');
INSERT INTO data_tvshows VALUES ('Almost Heroes');
INSERT INTO data_tvshows VALUES ('Almost Human');
INSERT INTO data_tvshows VALUES ('Alvin and the Chipmunks');
INSERT INTO data_tvshows VALUES ('Amanda Show, The');
INSERT INTO data_tvshows VALUES ('Amazing Race');
INSERT INTO data_tvshows VALUES ('Amazing World of Gumball, The');
INSERT INTO data_tvshows VALUES ('American Dad!');
INSERT INTO data_tvshows VALUES ('American Dragon: Jake Long');
INSERT INTO data_tvshows VALUES ('American Dreams');
INSERT INTO data_tvshows VALUES ('American Horror Story');
INSERT INTO data_tvshows VALUES ('America''s Next Top Model');
INSERT INTO data_tvshows VALUES ('Ancient Impossible');
INSERT INTO data_tvshows VALUES ('Andromeda');
INSERT INTO data_tvshows VALUES ('Andy Barker, P.I.');
INSERT INTO data_tvshows VALUES ('Andy Griffith Show, The');
INSERT INTO data_tvshows VALUES ('Angel');
INSERT INTO data_tvshows VALUES ('Angel Beats!');
INSERT INTO data_tvshows VALUES ('Animaniacs');
INSERT INTO data_tvshows VALUES ('Aqua Teen Hunger Force');
INSERT INTO data_tvshows VALUES ('Archer');
INSERT INTO data_tvshows VALUES ('Are You Being Served?');
INSERT INTO data_tvshows VALUES ('Are You There, Chelsea?');
INSERT INTO data_tvshows VALUES ('Army Wives');
INSERT INTO data_tvshows VALUES ('Arrested Development');
INSERT INTO data_tvshows VALUES ('Arrow');
INSERT INTO data_tvshows VALUES ('Arthur');
INSERT INTO data_tvshows VALUES ('Ash vs. Evil Dead');
INSERT INTO data_tvshows VALUES ('Ashes to Ashes');
INSERT INTO data_tvshows VALUES ('Atom Ant Show, The');
INSERT INTO data_tvshows VALUES ('Atomic Betty');
INSERT INTO data_tvshows VALUES ('Auf Wiedersehen, Pet');
INSERT INTO data_tvshows VALUES ('Austin & Ally');
INSERT INTO data_tvshows VALUES ('Avatar: The Last Airbender');
INSERT INTO data_tvshows VALUES ('Awkward');
INSERT INTO data_tvshows VALUES ('Axe Cop');
INSERT INTO data_tvshows VALUES ('Babylon 5');
INSERT INTO data_tvshows VALUES ('Back at the Barnyard');
INSERT INTO data_tvshows VALUES ('Bananaman');
INSERT INTO data_tvshows VALUES ('Band of Brothers');
INSERT INTO data_tvshows VALUES ('Barney & Friends');
INSERT INTO data_tvshows VALUES ('Barney Miller');
INSERT INTO data_tvshows VALUES ('Batman (1966)');
INSERT INTO data_tvshows VALUES ('Batman: The Animated Series');
INSERT INTO data_tvshows VALUES ('Battlestar Galactica (1978)');
INSERT INTO data_tvshows VALUES ('Battlestar Galactica (2003)');
INSERT INTO data_tvshows VALUES ('Beast Wars');
INSERT INTO data_tvshows VALUES ('Beauty and the Beast (1987)');
INSERT INTO data_tvshows VALUES ('Beauty and the Geek');
INSERT INTO data_tvshows VALUES ('Beavis and Butt-head');
INSERT INTO data_tvshows VALUES ('Becker');
INSERT INTO data_tvshows VALUES ('Beetlejuice');
INSERT INTO data_tvshows VALUES ('Being Erica');
INSERT INTO data_tvshows VALUES ('Being Human');
INSERT INTO data_tvshows VALUES ('Ben 10');
INSERT INTO data_tvshows VALUES ('Berserk');
INSERT INTO data_tvshows VALUES ('Beverly Hills, 90210');
INSERT INTO data_tvshows VALUES ('Beware the Batman');
INSERT INTO data_tvshows VALUES ('Bewitched');
INSERT INTO data_tvshows VALUES ('Big Bang Theory, The');
INSERT INTO data_tvshows VALUES ('Big Love');
INSERT INTO data_tvshows VALUES ('Big Shots');
INSERT INTO data_tvshows VALUES ('Bill Engvall Show, The');
INSERT INTO data_tvshows VALUES ('Bill Nye the Science Guy');
INSERT INTO data_tvshows VALUES ('Birds of a Feather');
INSERT INTO data_tvshows VALUES ('Bit Of Fry And Laurie, A');
INSERT INTO data_tvshows VALUES ('Black Books');
INSERT INTO data_tvshows VALUES ('Black Butler');
INSERT INTO data_tvshows VALUES ('Black Donnellys, The');
INSERT INTO data_tvshows VALUES ('Blackadder');
INSERT INTO data_tvshows VALUES ('Blake''s 7');
INSERT INTO data_tvshows VALUES ('Bleach');
INSERT INTO data_tvshows VALUES ('Blue Bloods');
INSERT INTO data_tvshows VALUES ('Blue Heelers');
INSERT INTO data_tvshows VALUES ('Boardwalk Empire');
INSERT INTO data_tvshows VALUES ('Bob the Builder');
INSERT INTO data_tvshows VALUES ('Bob''s Burgers');
INSERT INTO data_tvshows VALUES ('Bogan Hunters');
INSERT INTO data_tvshows VALUES ('BoJack Horseman');
INSERT INTO data_tvshows VALUES ('Bones');
INSERT INTO data_tvshows VALUES ('Boondocks, The');
INSERT INTO data_tvshows VALUES ('Boston Legal');
INSERT INTO data_tvshows VALUES ('Boston Public');
INSERT INTO data_tvshows VALUES ('Bottom');
INSERT INTO data_tvshows VALUES ('Boy Meets World');
INSERT INTO data_tvshows VALUES ('Boys Over Flowers');
INSERT INTO data_tvshows VALUES ('Brady Bunch, The');
INSERT INTO data_tvshows VALUES ('Brainiac: Science Abuse');
INSERT INTO data_tvshows VALUES ('Brass Eye');
INSERT INTO data_tvshows VALUES ('Breaking Bad');
INSERT INTO data_tvshows VALUES ('Bridge, The (2013)');
INSERT INTO data_tvshows VALUES ('Brooklyn Nine-Nine');
INSERT INTO data_tvshows VALUES ('Brotherhood (2006)');
INSERT INTO data_tvshows VALUES ('Brothers & Sisters(2006)');
INSERT INTO data_tvshows VALUES ('Buffy the Vampire Slayer');
INSERT INTO data_tvshows VALUES ('Bunheads');
INSERT INTO data_tvshows VALUES ('Burn Notice');
INSERT INTO data_tvshows VALUES ('Buzz Lightyear of Star Command');
INSERT INTO data_tvshows VALUES ('Californication');
INSERT INTO data_tvshows VALUES ('Camelot');
INSERT INTO data_tvshows VALUES ('Cardcaptor Sakura');
INSERT INTO data_tvshows VALUES ('Care Bears, The');
INSERT INTO data_tvshows VALUES ('Carnivàle');
INSERT INTO data_tvshows VALUES ('Castle');
INSERT INTO data_tvshows VALUES ('ChalkZone');
INSERT INTO data_tvshows VALUES ('Chappelle''s Show');
INSERT INTO data_tvshows VALUES ('Charlie Brown and Snoopy Show, The');
INSERT INTO data_tvshows VALUES ('Charmed');
INSERT INTO data_tvshows VALUES ('Chaser''s War On Everything, The');
INSERT INTO data_tvshows VALUES ('Cheap Seats');
INSERT INTO data_tvshows VALUES ('Cheers');
INSERT INTO data_tvshows VALUES ('Chef!');
INSERT INTO data_tvshows VALUES ('Chicago Fire');
INSERT INTO data_tvshows VALUES ('China Beach');
INSERT INTO data_tvshows VALUES ('Chip ''n Dale Rescue Rangers');
INSERT INTO data_tvshows VALUES ('Chowder');
INSERT INTO data_tvshows VALUES ('Chuck');
INSERT INTO data_tvshows VALUES ('Class, The');
INSERT INTO data_tvshows VALUES ('Clerks: The Animated Series');
INSERT INTO data_tvshows VALUES ('Cleveland Show, The');
INSERT INTO data_tvshows VALUES ('Clone High');
INSERT INTO data_tvshows VALUES ('Closer, The');
INSERT INTO data_tvshows VALUES ('Code Geass');
INSERT INTO data_tvshows VALUES ('Code Lyoko');
INSERT INTO data_tvshows VALUES ('Codename: Kids Next Door');
INSERT INTO data_tvshows VALUES ('Colbert Report, The');
INSERT INTO data_tvshows VALUES ('Cold Case');
INSERT INTO data_tvshows VALUES ('Columbo');
INSERT INTO data_tvshows VALUES ('Community');
INSERT INTO data_tvshows VALUES ('Corner Gas');
INSERT INTO data_tvshows VALUES ('Coronation Street');
INSERT INTO data_tvshows VALUES ('Cosby Show, The');
INSERT INTO data_tvshows VALUES ('Cosmos: A Spacetime Odyssey');
INSERT INTO data_tvshows VALUES ('Cougar Town');
INSERT INTO data_tvshows VALUES ('Count Duckula');
INSERT INTO data_tvshows VALUES ('Coupling');
INSERT INTO data_tvshows VALUES ('Courage the Cowardly Dog');
INSERT INTO data_tvshows VALUES ('Covert Affairs');
INSERT INTO data_tvshows VALUES ('Cow and Chicken');
INSERT INTO data_tvshows VALUES ('Cowboy Bebop');
INSERT INTO data_tvshows VALUES ('Crayon Shin-chan');
INSERT INTO data_tvshows VALUES ('Crazy Ones, The');
INSERT INTO data_tvshows VALUES ('Criminal Minds');
INSERT INTO data_tvshows VALUES ('Crossing Jordan');
INSERT INTO data_tvshows VALUES ('Crusade');
INSERT INTO data_tvshows VALUES ('CSI: Crime Scene Investigation');
INSERT INTO data_tvshows VALUES ('CSI: Miami');
INSERT INTO data_tvshows VALUES ('CSI: NY');
INSERT INTO data_tvshows VALUES ('Cupid');
INSERT INTO data_tvshows VALUES ('Curb Your Enthusiasm');
INSERT INTO data_tvshows VALUES ('Da Vinci''s Demons');
INSERT INTO data_tvshows VALUES ('Dad''s Army');
INSERT INTO data_tvshows VALUES ('Daily Show, The');
INSERT INTO data_tvshows VALUES ('Dallas (2012)');
INSERT INTO data_tvshows VALUES ('Damages');
INSERT INTO data_tvshows VALUES ('Danger Mouse');
INSERT INTO data_tvshows VALUES ('Danny Phantom');
INSERT INTO data_tvshows VALUES ('Daredevil');
INSERT INTO data_tvshows VALUES ('Daria');
INSERT INTO data_tvshows VALUES ('Dark Angel');
INSERT INTO data_tvshows VALUES ('Dark Shadows (1991)');
INSERT INTO data_tvshows VALUES ('Darkwing Duck');
INSERT INTO data_tvshows VALUES ('Dave the Barbarian');
INSERT INTO data_tvshows VALUES ('Dawson''s Creek');
INSERT INTO data_tvshows VALUES ('Day Today, The');
INSERT INTO data_tvshows VALUES ('Dead Like Me');
INSERT INTO data_tvshows VALUES ('Dead Ringers');
INSERT INTO data_tvshows VALUES ('Deadwood');
INSERT INTO data_tvshows VALUES ('Death Note');
INSERT INTO data_tvshows VALUES ('Degrassi: The Next Generation');
INSERT INTO data_tvshows VALUES ('Dennis the Menace');
INSERT INTO data_tvshows VALUES ('Designing Women');
INSERT INTO data_tvshows VALUES ('Desperate Housewives');
INSERT INTO data_tvshows VALUES ('Detective Conan');
INSERT INTO data_tvshows VALUES ('Detention');
INSERT INTO data_tvshows VALUES ('Dexter');
INSERT INTO data_tvshows VALUES ('Dharma & Greg');
INSERT INTO data_tvshows VALUES ('Dick Van Dyke Show, The');
INSERT INTO data_tvshows VALUES ('Digimon');
INSERT INTO data_tvshows VALUES ('Dilbert');
INSERT INTO data_tvshows VALUES ('Dinosaurs');
INSERT INTO data_tvshows VALUES ('Dirty Jobs');
INSERT INTO data_tvshows VALUES ('Dirty Sexy Money');
INSERT INTO data_tvshows VALUES ('Disney''s Adventures of the Gummi Bears');
INSERT INTO data_tvshows VALUES ('Doctor Who');
INSERT INTO data_tvshows VALUES ('Dollhouse');
INSERT INTO data_tvshows VALUES ('Donkey Kong Country');
INSERT INTO data_tvshows VALUES ('Don''t Trust the B---- in Apartment 23');
INSERT INTO data_tvshows VALUES ('Doogie Howser, M.D.');
INSERT INTO data_tvshows VALUES ('Doug');
INSERT INTO data_tvshows VALUES ('Downton Abbey');
INSERT INTO data_tvshows VALUES ('Dr. Quinn, Medicine Woman');
INSERT INTO data_tvshows VALUES ('Dragnet');
INSERT INTO data_tvshows VALUES ('Dragon Ball');
INSERT INTO data_tvshows VALUES ('Dragon Ball GT');
INSERT INTO data_tvshows VALUES ('Dragon Ball Z');
INSERT INTO data_tvshows VALUES ('Drake & Josh');
INSERT INTO data_tvshows VALUES ('Drawn Together');
INSERT INTO data_tvshows VALUES ('Drew Carey Show, The');
INSERT INTO data_tvshows VALUES ('Duck Dodgers');
INSERT INTO data_tvshows VALUES ('Duckman');
INSERT INTO data_tvshows VALUES ('DuckTales');
INSERT INTO data_tvshows VALUES ('Due South');
INSERT INTO data_tvshows VALUES ('Duel Masters');
INSERT INTO data_tvshows VALUES ('Dukes of Hazzard, The');
INSERT INTO data_tvshows VALUES ('Dungeons & Dragons');
INSERT INTO data_tvshows VALUES ('Durarara!!');
INSERT INTO data_tvshows VALUES ('Earth 2');
INSERT INTO data_tvshows VALUES ('Earthworm Jim');
INSERT INTO data_tvshows VALUES ('Eastbound & Down');
INSERT INTO data_tvshows VALUES ('Ed, Edd, ''n Eddy');
INSERT INTO data_tvshows VALUES ('Eek! the Cat');
INSERT INTO data_tvshows VALUES ('Eerie, Indiana');
INSERT INTO data_tvshows VALUES ('Elementary');
INSERT INTO data_tvshows VALUES ('Ellen');
INSERT INTO data_tvshows VALUES ('Entourage');
INSERT INTO data_tvshows VALUES ('ER');
INSERT INTO data_tvshows VALUES ('Eureka');
INSERT INTO data_tvshows VALUES ('Eureka Seven');
INSERT INTO data_tvshows VALUES ('Eve (U.S.)');
INSERT INTO data_tvshows VALUES ('Event, The');
INSERT INTO data_tvshows VALUES ('Everwood');
INSERT INTO data_tvshows VALUES ('Everybody Hates Chris');
INSERT INTO data_tvshows VALUES ('Everybody Loves Raymond');
INSERT INTO data_tvshows VALUES ('Exosquad');
INSERT INTO data_tvshows VALUES ('Extras');
INSERT INTO data_tvshows VALUES ('Fairly OddParents, The');
INSERT INTO data_tvshows VALUES ('Falling Skies');
INSERT INTO data_tvshows VALUES ('Family Guy');
INSERT INTO data_tvshows VALUES ('Family Ties');
INSERT INTO data_tvshows VALUES ('Father Ted');
INSERT INTO data_tvshows VALUES ('Fawlty Towers');
INSERT INTO data_tvshows VALUES ('Felicity');
INSERT INTO data_tvshows VALUES ('Fillmore!');
INSERT INTO data_tvshows VALUES ('Firefly');
INSERT INTO data_tvshows VALUES ('FLCL');
INSERT INTO data_tvshows VALUES ('Flight of the Conchords');
INSERT INTO data_tvshows VALUES ('Flintstones, The');
INSERT INTO data_tvshows VALUES ('Forever Knight');
INSERT INTO data_tvshows VALUES ('Forgotten, The');
INSERT INTO data_tvshows VALUES ('Foster''s Home for Imaginary Friends');
INSERT INTO data_tvshows VALUES ('Four Star Playhouse');
INSERT INTO data_tvshows VALUES ('Frasier');
INSERT INTO data_tvshows VALUES ('Freakazoid!');
INSERT INTO data_tvshows VALUES ('Freaks and Geeks');
INSERT INTO data_tvshows VALUES ('Fresh Prince of Bel-Air, The');
INSERT INTO data_tvshows VALUES ('Friday Night Lights');
INSERT INTO data_tvshows VALUES ('Fridays');
INSERT INTO data_tvshows VALUES ('Friends');
INSERT INTO data_tvshows VALUES ('Fringe');
INSERT INTO data_tvshows VALUES ('Frisky Dingo');
INSERT INTO data_tvshows VALUES ('Frontline');
INSERT INTO data_tvshows VALUES ('Fruits Basket');
INSERT INTO data_tvshows VALUES ('Full House');
INSERT INTO data_tvshows VALUES ('Fullmetal Alchemist');
INSERT INTO data_tvshows VALUES ('Futurama');
INSERT INTO data_tvshows VALUES ('G.I. Joe Extreme');
INSERT INTO data_tvshows VALUES ('Game of Thrones');
INSERT INTO data_tvshows VALUES ('Garfield and Friends');
INSERT INTO data_tvshows VALUES ('Gargoyles');
INSERT INTO data_tvshows VALUES ('Gavin & Stacey');
INSERT INTO data_tvshows VALUES ('Generation Kill');
INSERT INTO data_tvshows VALUES ('Generator Rex');
INSERT INTO data_tvshows VALUES ('George Lopez');
INSERT INTO data_tvshows VALUES ('Get Smart');
INSERT INTO data_tvshows VALUES ('Ghost Adventures');
INSERT INTO data_tvshows VALUES ('Ghost Hunters');
INSERT INTO data_tvshows VALUES ('Ghost in the Shell: Stand Alone Complex');
INSERT INTO data_tvshows VALUES ('Ghost Whisperer');
INSERT INTO data_tvshows VALUES ('Ghostbusters');
INSERT INTO data_tvshows VALUES ('Gilligan''s Island');
INSERT INTO data_tvshows VALUES ('Gilmore Girls');
INSERT INTO data_tvshows VALUES ('Gimme Gimme Gimme');
INSERT INTO data_tvshows VALUES ('Gin Tama');
INSERT INTO data_tvshows VALUES ('Girlfriends');
INSERT INTO data_tvshows VALUES ('Glee');
INSERT INTO data_tvshows VALUES ('Golden Girls, The');
INSERT INTO data_tvshows VALUES ('Golden Palace, The');
INSERT INTO data_tvshows VALUES ('Good Luck Charlie');
INSERT INTO data_tvshows VALUES ('Good Wife, The');
INSERT INTO data_tvshows VALUES ('Goodies, The');
INSERT INTO data_tvshows VALUES ('Goodness Gracious Me');
INSERT INTO data_tvshows VALUES ('Goof Troop');
INSERT INTO data_tvshows VALUES ('Gossip Girl');
INSERT INTO data_tvshows VALUES ('Gravity Falls');
INSERT INTO data_tvshows VALUES ('Great Expectations');
INSERT INTO data_tvshows VALUES ('Great Teacher Onizuka (GTO)');
INSERT INTO data_tvshows VALUES ('Greek');
INSERT INTO data_tvshows VALUES ('Green Wing');
INSERT INTO data_tvshows VALUES ('Greg the Bunny');
INSERT INTO data_tvshows VALUES ('Grey''s Anatomy');
INSERT INTO data_tvshows VALUES ('Grim Adventures of Billy & Mandy, The');
INSERT INTO data_tvshows VALUES ('Grimm');
INSERT INTO data_tvshows VALUES ('Grounded for Life');
INSERT INTO data_tvshows VALUES ('Guinevere Jones');
INSERT INTO data_tvshows VALUES ('Gundam Seed');
INSERT INTO data_tvshows VALUES ('Gundam Wing');
INSERT INTO data_tvshows VALUES ('Gunsmoke');
INSERT INTO data_tvshows VALUES ('H2O: Just Add Water');
INSERT INTO data_tvshows VALUES ('Hancock''s Half Hour');
INSERT INTO data_tvshows VALUES ('Hangin'' with Mr. Cooper');
INSERT INTO data_tvshows VALUES ('Hannah Montana');
INSERT INTO data_tvshows VALUES ('Hannibal (TV series)');
INSERT INTO data_tvshows VALUES ('Happy Days');
INSERT INTO data_tvshows VALUES ('Harvey Birdman, Attorney at Law');
INSERT INTO data_tvshows VALUES ('Haven');
INSERT INTO data_tvshows VALUES ('Hawaii Five-0');
INSERT INTO data_tvshows VALUES ('Hawaii Five-O');
INSERT INTO data_tvshows VALUES ('Hellcats');
INSERT INTO data_tvshows VALUES ('Hell''s Kitchen');
INSERT INTO data_tvshows VALUES ('Hercules');
INSERT INTO data_tvshows VALUES ('Here Comes Honey Boo Boo');
INSERT INTO data_tvshows VALUES ('Herman''s Head');
INSERT INTO data_tvshows VALUES ('Heroes');
INSERT INTO data_tvshows VALUES ('Hetalia - Axis Powers');
INSERT INTO data_tvshows VALUES ('Hey Arnold!');
INSERT INTO data_tvshows VALUES ('Highlander: The Series');
INSERT INTO data_tvshows VALUES ('Hill Street Blues');
INSERT INTO data_tvshows VALUES ('Histeria!');
INSERT INTO data_tvshows VALUES ('History''s Strongest Disciple: Kenichi');
INSERT INTO data_tvshows VALUES ('Hitchhiker''s Guide to the Galaxy');
INSERT INTO data_tvshows VALUES ('Hogan''s Heroes');
INSERT INTO data_tvshows VALUES ('Holby City');
INSERT INTO data_tvshows VALUES ('Hollywood 7');
INSERT INTO data_tvshows VALUES ('Home and Away');
INSERT INTO data_tvshows VALUES ('Home Improvement');
INSERT INTO data_tvshows VALUES ('Home Movies');
INSERT INTO data_tvshows VALUES ('Homeland');
INSERT INTO data_tvshows VALUES ('Homicide: Life on the Street');
INSERT INTO data_tvshows VALUES ('Honeymooners, The');
INSERT INTO data_tvshows VALUES ('Hot in Cleveland');
INSERT INTO data_tvshows VALUES ('Hotel Hell');
INSERT INTO data_tvshows VALUES ('House');
INSERT INTO data_tvshows VALUES ('House of Cards (trilogy) (House of Cards, To Play the King, and The Final Cut)');
INSERT INTO data_tvshows VALUES ('House of Lies');
INSERT INTO data_tvshows VALUES ('How I Met Your Mother');
INSERT INTO data_tvshows VALUES ('Human Giant');
INSERT INTO data_tvshows VALUES ('Human Target');
INSERT INTO data_tvshows VALUES ('Hustle');
INSERT INTO data_tvshows VALUES ('I Dream of Jeannie');
INSERT INTO data_tvshows VALUES ('I Love Lucy');
INSERT INTO data_tvshows VALUES ('iCarly');
INSERT INTO data_tvshows VALUES ('In Plain Sight');
INSERT INTO data_tvshows VALUES ('In Treatment');
INSERT INTO data_tvshows VALUES ('Inbetweeners, The');
INSERT INTO data_tvshows VALUES ('Inspector Gadget');
INSERT INTO data_tvshows VALUES ('Inspector Morse');
INSERT INTO data_tvshows VALUES ('Instant Star');
INSERT INTO data_tvshows VALUES ('Intelligence');
INSERT INTO data_tvshows VALUES ('InuYasha');
INSERT INTO data_tvshows VALUES ('Invader Zim');
INSERT INTO data_tvshows VALUES ('Invasion America');
INSERT INTO data_tvshows VALUES ('Iron Chef');
INSERT INTO data_tvshows VALUES ('Iron Man: Armored Adventures');
INSERT INTO data_tvshows VALUES ('IT Crowd, The');
INSERT INTO data_tvshows VALUES ('It''s Always Sunny in Philadelphia');
INSERT INTO data_tvshows VALUES ('iZombie');
INSERT INTO data_tvshows VALUES ('JAG');
INSERT INTO data_tvshows VALUES ('Jeeves and Wooster');
INSERT INTO data_tvshows VALUES ('Jekyll');
INSERT INTO data_tvshows VALUES ('Jeopardy!');
INSERT INTO data_tvshows VALUES ('Jericho');
INSERT INTO data_tvshows VALUES ('Jersey Shore');
INSERT INTO data_tvshows VALUES ('Jessica Jones');
INSERT INTO data_tvshows VALUES ('Jessie');
INSERT INTO data_tvshows VALUES ('Jetsons, The');
INSERT INTO data_tvshows VALUES ('Jim Henson Hour, ''The');
INSERT INTO data_tvshows VALUES ('Joan of Arcadia');
INSERT INTO data_tvshows VALUES ('John Adams');
INSERT INTO data_tvshows VALUES ('Johnny Bravo');
INSERT INTO data_tvshows VALUES ('Johnny Test');
INSERT INTO data_tvshows VALUES ('JoJo''s Bizarre Adventure');
INSERT INTO data_tvshows VALUES ('Jonathan Creek');
INSERT INTO data_tvshows VALUES ('Jonny Quest');
INSERT INTO data_tvshows VALUES ('Josie and the Pussycats');
INSERT INTO data_tvshows VALUES ('Journeyman');
INSERT INTO data_tvshows VALUES ('jPod');
INSERT INTO data_tvshows VALUES ('Judge Judy');
INSERT INTO data_tvshows VALUES ('Justice League');
INSERT INTO data_tvshows VALUES ('Justified');
INSERT INTO data_tvshows VALUES ('Kablam!');
INSERT INTO data_tvshows VALUES ('Kappa Mikey');
INSERT INTO data_tvshows VALUES ('Kate & Allie');
INSERT INTO data_tvshows VALUES ('Kath & Kim');
INSERT INTO data_tvshows VALUES ('Keeping Up Appearances');
INSERT INTO data_tvshows VALUES ('Kenan & Kel');
INSERT INTO data_tvshows VALUES ('Kids'' Court');
INSERT INTO data_tvshows VALUES ('Kids in the Hall, The');
INSERT INTO data_tvshows VALUES ('Kim Possible');
INSERT INTO data_tvshows VALUES ('King of Queens');
INSERT INTO data_tvshows VALUES ('King of the Hill');
INSERT INTO data_tvshows VALUES ('Kingdom Hospital');
INSERT INTO data_tvshows VALUES ('Kirby: Right Back At Ya!');
INSERT INTO data_tvshows VALUES ('Kitchen Nightmares');
INSERT INTO data_tvshows VALUES ('Knight Rider');
INSERT INTO data_tvshows VALUES ('Knights of Prosperity, The');
INSERT INTO data_tvshows VALUES ('Krod Mandoon and the Flaming Sword of Fire');
INSERT INTO data_tvshows VALUES ('Kung Fu');
INSERT INTO data_tvshows VALUES ('Kyle XY');
INSERT INTO data_tvshows VALUES ('L Word, The');
INSERT INTO data_tvshows VALUES ('L.A. 7');
INSERT INTO data_tvshows VALUES ('La Femme Nikita');
INSERT INTO data_tvshows VALUES ('Laguna Beach: The Real Orange County');
INSERT INTO data_tvshows VALUES ('Larry Sanders Show, The');
INSERT INTO data_tvshows VALUES ('Las Vegas');
INSERT INTO data_tvshows VALUES ('Last of the Summer Wine');
INSERT INTO data_tvshows VALUES ('Late Night with Conan O''Brien');
INSERT INTO data_tvshows VALUES ('Laverne & Shirley');
INSERT INTO data_tvshows VALUES ('Law & Order');
INSERT INTO data_tvshows VALUES ('Law & Order: Criminal Intent');
INSERT INTO data_tvshows VALUES ('Law & Order: Special Victims Unit');
INSERT INTO data_tvshows VALUES ('Law & Order: UK');
INSERT INTO data_tvshows VALUES ('League, The');
INSERT INTO data_tvshows VALUES ('Leave it to Beaver');
INSERT INTO data_tvshows VALUES ('Legend of Korra, The');
INSERT INTO data_tvshows VALUES ('Legend of the Seeker');
INSERT INTO data_tvshows VALUES ('Legend Of Zelda, The');
INSERT INTO data_tvshows VALUES ('Legends of the Hidden Temple');
INSERT INTO data_tvshows VALUES ('Leverage');
INSERT INTO data_tvshows VALUES ('Lexx');
INSERT INTO data_tvshows VALUES ('Lie to Me');
INSERT INTO data_tvshows VALUES ('Life');
INSERT INTO data_tvshows VALUES ('Life and Times of Juniper Lee, The');
INSERT INTO data_tvshows VALUES ('Life of Ryan');
INSERT INTO data_tvshows VALUES ('Life on a Stick');
INSERT INTO data_tvshows VALUES ('Life on Mars (UK TV series)');
INSERT INTO data_tvshows VALUES ('Life Unexpected');
INSERT INTO data_tvshows VALUES ('Life With Derek');
INSERT INTO data_tvshows VALUES ('Lincoln Heights');
INSERT INTO data_tvshows VALUES ('Little Britain');
INSERT INTO data_tvshows VALUES ('Little Miss Jocelyn');
INSERT INTO data_tvshows VALUES ('Little Mosque on the Prairie');
INSERT INTO data_tvshows VALUES ('Look Around You');
INSERT INTO data_tvshows VALUES ('Looney Tunes Show, The');
INSERT INTO data_tvshows VALUES ('Loop, The');
INSERT INTO data_tvshows VALUES ('Lost');
INSERT INTO data_tvshows VALUES ('Lost Girl');
INSERT INTO data_tvshows VALUES ('Lost in Space');
INSERT INTO data_tvshows VALUES ('Louie');
INSERT INTO data_tvshows VALUES ('Love Hina');
INSERT INTO data_tvshows VALUES ('Lucifer');
INSERT INTO data_tvshows VALUES ('Lucky Louie');
INSERT INTO data_tvshows VALUES ('Lucy, the Daughter of the Devil');
INSERT INTO data_tvshows VALUES ('Luther');
INSERT INTO data_tvshows VALUES ('M*A*S*H');
INSERT INTO data_tvshows VALUES ('MacGyver');
INSERT INTO data_tvshows VALUES ('Mad Men');
INSERT INTO data_tvshows VALUES ('Magical Project S');
INSERT INTO data_tvshows VALUES ('Magnum, P.I.');
INSERT INTO data_tvshows VALUES ('Maid Marian and Her Merry Men');
INSERT INTO data_tvshows VALUES ('Make It or Break It');
INSERT INTO data_tvshows VALUES ('Malcolm in the Middle');
INSERT INTO data_tvshows VALUES ('Mama''s Family');
INSERT INTO data_tvshows VALUES ('Man To Man With Dean Learner');
INSERT INTO data_tvshows VALUES ('Married... with Children');
INSERT INTO data_tvshows VALUES ('Marsupilami');
INSERT INTO data_tvshows VALUES ('Martin');
INSERT INTO data_tvshows VALUES ('Marvelous Misadventures of Flapjack, The');
INSERT INTO data_tvshows VALUES ('MasterChef');
INSERT INTO data_tvshows VALUES ('Max Headroom');
INSERT INTO data_tvshows VALUES ('Megas XLR');
INSERT INTO data_tvshows VALUES ('Melrose Place');
INSERT INTO data_tvshows VALUES ('Melrose Place (2009)');
INSERT INTO data_tvshows VALUES ('Men Behaving Badly');
INSERT INTO data_tvshows VALUES ('Men in Trees');
INSERT INTO data_tvshows VALUES ('Mentalist, The');
INSERT INTO data_tvshows VALUES ('Merlin');
INSERT INTO data_tvshows VALUES ('Metalocalypse');
INSERT INTO data_tvshows VALUES ('Miami 7');
INSERT INTO data_tvshows VALUES ('Miami Vice');
INSERT INTO data_tvshows VALUES ('Mighty B!, The');
INSERT INTO data_tvshows VALUES ('Mighty Boosh, The');
INSERT INTO data_tvshows VALUES ('Mighty Morphin Power Rangers');
INSERT INTO data_tvshows VALUES ('Mind of Mencia');
INSERT INTO data_tvshows VALUES ('Mindy Project, The');
INSERT INTO data_tvshows VALUES ('Misfits');
INSERT INTO data_tvshows VALUES ('Mobile Suit Gundam 00');
INSERT INTO data_tvshows VALUES ('Modern Family');
INSERT INTO data_tvshows VALUES ('Monk');
INSERT INTO data_tvshows VALUES ('Monkey');
INSERT INTO data_tvshows VALUES ('Monty Python''s Flying Circus');
INSERT INTO data_tvshows VALUES ('Moonbeam City');
INSERT INTO data_tvshows VALUES ('Moonlight');
INSERT INTO data_tvshows VALUES ('Moonlighting');
INSERT INTO data_tvshows VALUES ('Moral Orel');
INSERT INTO data_tvshows VALUES ('Mork and Mindy');
INSERT INTO data_tvshows VALUES ('Most Hated Family in America, The');
INSERT INTO data_tvshows VALUES ('Mr. Bean');
INSERT INTO data_tvshows VALUES ('Mr. Show');
INSERT INTO data_tvshows VALUES ('Munsters, The');
INSERT INTO data_tvshows VALUES ('Muppet Show, The');
INSERT INTO data_tvshows VALUES ('Muppets Tonight');
INSERT INTO data_tvshows VALUES ('Muppets, The');
INSERT INTO data_tvshows VALUES ('Murder One');
INSERT INTO data_tvshows VALUES ('Mutant X');
INSERT INTO data_tvshows VALUES ('My Boys');
INSERT INTO data_tvshows VALUES ('My Family');
INSERT INTO data_tvshows VALUES ('My Hero');
INSERT INTO data_tvshows VALUES ('My Life as a Teenage Robot');
INSERT INTO data_tvshows VALUES ('My Little Pony: Friendship is Magic');
INSERT INTO data_tvshows VALUES ('My Name Is Earl');
INSERT INTO data_tvshows VALUES ('My So-Called Life');
INSERT INTO data_tvshows VALUES ('Mystery Science Theater 3000');
INSERT INTO data_tvshows VALUES ('Mythbusters');
INSERT INTO data_tvshows VALUES ('Nanny, The');
INSERT INTO data_tvshows VALUES ('Naruto');
INSERT INTO data_tvshows VALUES ('Naruto: Shippuden');
INSERT INTO data_tvshows VALUES ('NCIS');
INSERT INTO data_tvshows VALUES ('NCIS: Los Angeles');
INSERT INTO data_tvshows VALUES ('Ned''s Declassified School Survival Guide');
INSERT INTO data_tvshows VALUES ('Neighbours');
INSERT INTO data_tvshows VALUES ('Neon Genesis Evangelion');
INSERT INTO data_tvshows VALUES ('Never Mind the Buzzcocks');
INSERT INTO data_tvshows VALUES ('New Adventures of Old Christine, The');
INSERT INTO data_tvshows VALUES ('New Girl');
INSERT INTO data_tvshows VALUES ('NewsRadio');
INSERT INTO data_tvshows VALUES ('Newsroom, The');
INSERT INTO data_tvshows VALUES ('Night Court');
INSERT INTO data_tvshows VALUES ('Nikita');
INSERT INTO data_tvshows VALUES ('Nip/Tuck');
INSERT INTO data_tvshows VALUES ('No Ordinary Family');
INSERT INTO data_tvshows VALUES ('Northern Exposure');
INSERT INTO data_tvshows VALUES ('Not the Nine O''Clock News');
INSERT INTO data_tvshows VALUES ('Note: this poorly-constructed page allegedly contains quotes from the comic books, the 1994 animated series, and the 2001 live-action series.');
INSERT INTO data_tvshows VALUES ('Numb3rs');
INSERT INTO data_tvshows VALUES ('Nurse Jackie');
INSERT INTO data_tvshows VALUES ('NYPD Blue');
INSERT INTO data_tvshows VALUES ('O.C., The');
INSERT INTO data_tvshows VALUES ('Oblongs, The');
INSERT INTO data_tvshows VALUES ('October Road');
INSERT INTO data_tvshows VALUES ('Odd Couple, The');
INSERT INTO data_tvshows VALUES ('Office, The (UK) (United Kingdom)');
INSERT INTO data_tvshows VALUES ('Office, The (US) (United States)');
INSERT INTO data_tvshows VALUES ('Once Upon a Time (TV series)');
INSERT INTO data_tvshows VALUES ('One Foot In The Grave');
INSERT INTO data_tvshows VALUES ('One on One');
INSERT INTO data_tvshows VALUES ('One Piece (Anime, Japanese version)');
INSERT INTO data_tvshows VALUES ('One Tree Hill');
INSERT INTO data_tvshows VALUES ('Only Fools and Horses');
INSERT INTO data_tvshows VALUES ('Open All Hours');
INSERT INTO data_tvshows VALUES ('Orphan Black');
INSERT INTO data_tvshows VALUES ('Osomatsu-san (Anime)');
INSERT INTO data_tvshows VALUES ('Ouran High School Host Club (Anime and manga)');
INSERT INTO data_tvshows VALUES ('Out Of Control');
INSERT INTO data_tvshows VALUES ('Outlaw Star (Anime)');
INSERT INTO data_tvshows VALUES ('Outnumbered');
INSERT INTO data_tvshows VALUES ('Oz');
INSERT INTO data_tvshows VALUES ('Pacific, The');
INSERT INTO data_tvshows VALUES ('Pac-Man');
INSERT INTO data_tvshows VALUES ('Parks and Recreation');
INSERT INTO data_tvshows VALUES ('Party Down');
INSERT INTO data_tvshows VALUES ('Party of Five');
INSERT INTO data_tvshows VALUES ('Peaky Blinders');
INSERT INTO data_tvshows VALUES ('Peep Show');
INSERT INTO data_tvshows VALUES ('Pee-wee''s Playhouse');
INSERT INTO data_tvshows VALUES ('Penguins of Madagascar, The');
INSERT INTO data_tvshows VALUES ('Penn & Teller: Bullshit!');
INSERT INTO data_tvshows VALUES ('Penny Dreadful');
INSERT INTO data_tvshows VALUES ('Pepper Ann');
INSERT INTO data_tvshows VALUES ('Perfect Strangers');
INSERT INTO data_tvshows VALUES ('Person of Interest');
INSERT INTO data_tvshows VALUES ('Phil of the Future');
INSERT INTO data_tvshows VALUES ('Phineas and Ferb');
INSERT INTO data_tvshows VALUES ('Pillars of the Earth, The');
INSERT INTO data_tvshows VALUES ('Pinky and the Brain');
INSERT INTO data_tvshows VALUES ('Point Pleasant');
INSERT INTO data_tvshows VALUES ('Pokémon');
INSERT INTO data_tvshows VALUES ('Powerpuff Girls, The');
INSERT INTO data_tvshows VALUES ('Practice, The');
INSERT INTO data_tvshows VALUES ('Press Gang');
INSERT INTO data_tvshows VALUES ('Pretty Little Liars');
INSERT INTO data_tvshows VALUES ('Price Is Right, The');
INSERT INTO data_tvshows VALUES ('Prime Suspect (U.S. TV series)');
INSERT INTO data_tvshows VALUES ('Primeval');
INSERT INTO data_tvshows VALUES ('Prison Break');
INSERT INTO data_tvshows VALUES ('Private Practice');
INSERT INTO data_tvshows VALUES ('Privileged (TV series)');
INSERT INTO data_tvshows VALUES ('Profit');
INSERT INTO data_tvshows VALUES ('Project Runway');
INSERT INTO data_tvshows VALUES ('Psych');
INSERT INTO data_tvshows VALUES ('Pushing Daisies');
INSERT INTO data_tvshows VALUES ('QI');
INSERT INTO data_tvshows VALUES ('Quantum Leap');
INSERT INTO data_tvshows VALUES ('Queer as Folk (United Kingdom)');
INSERT INTO data_tvshows VALUES ('Queer as Folk (United States)');
INSERT INTO data_tvshows VALUES ('Queer Eye (aka Queer Eye for the Straight Guy)');
INSERT INTO data_tvshows VALUES ('Raccoons, The');
INSERT INTO data_tvshows VALUES ('RahXephon');
INSERT INTO data_tvshows VALUES ('Rainbow Brite');
INSERT INTO data_tvshows VALUES ('Raising Hope');
INSERT INTO data_tvshows VALUES ('Ramsay''s Kitchen Nightmares');
INSERT INTO data_tvshows VALUES ('Randall and Hopkirk (Deceased)');
INSERT INTO data_tvshows VALUES ('Ranma 1/2');
INSERT INTO data_tvshows VALUES ('Raw Toonage');
INSERT INTO data_tvshows VALUES ('Real Time with Bill Maher');
INSERT INTO data_tvshows VALUES ('Reba');
INSERT INTO data_tvshows VALUES ('ReBoot');
INSERT INTO data_tvshows VALUES ('Reborn!');
INSERT INTO data_tvshows VALUES ('Recess');
INSERT INTO data_tvshows VALUES ('Red Dwarf');
INSERT INTO data_tvshows VALUES ('Red Green Show, The');
INSERT INTO data_tvshows VALUES ('Red vs Blue');
INSERT INTO data_tvshows VALUES ('Regular Show');
INSERT INTO data_tvshows VALUES ('Related');
INSERT INTO data_tvshows VALUES ('Remington Steele');
INSERT INTO data_tvshows VALUES ('Ren & Stimpy Show, The');
INSERT INTO data_tvshows VALUES ('Reno 911!');
INSERT INTO data_tvshows VALUES ('Replacements, The');
INSERT INTO data_tvshows VALUES ('Rescue Me');
INSERT INTO data_tvshows VALUES ('Restaurant Stakeout');
INSERT INTO data_tvshows VALUES ('Revenge');
INSERT INTO data_tvshows VALUES ('Revolution');
INSERT INTO data_tvshows VALUES ('Revolutionary Girl Utena');
INSERT INTO data_tvshows VALUES ('Rick and Morty');
INSERT INTO data_tvshows VALUES ('Ringer');
INSERT INTO data_tvshows VALUES ('Rizzoli & Isles');
INSERT INTO data_tvshows VALUES ('Road Rovers');
INSERT INTO data_tvshows VALUES ('Robin Hood (2006 TV series)');
INSERT INTO data_tvshows VALUES ('Robot Chicken');
INSERT INTO data_tvshows VALUES ('Robot Wars');
INSERT INTO data_tvshows VALUES ('Robotech');
INSERT INTO data_tvshows VALUES ('Rock Profile');
INSERT INTO data_tvshows VALUES ('Rocket Power');
INSERT INTO data_tvshows VALUES ('Rockford Files, The');
INSERT INTO data_tvshows VALUES ('Rocko''s Modern Life');
INSERT INTO data_tvshows VALUES ('Roger Ramjet');
INSERT INTO data_tvshows VALUES ('Rome');
INSERT INTO data_tvshows VALUES ('Rookie Blue');
INSERT INTO data_tvshows VALUES ('Roseanne');
INSERT INTO data_tvshows VALUES ('Roswell');
INSERT INTO data_tvshows VALUES ('Rove');
INSERT INTO data_tvshows VALUES ('Royle Family, The');
INSERT INTO data_tvshows VALUES ('Rubicon');
INSERT INTO data_tvshows VALUES ('Ruby Gloom');
INSERT INTO data_tvshows VALUES ('Rugrats');
INSERT INTO data_tvshows VALUES ('Runaway');
INSERT INTO data_tvshows VALUES ('Sabrina, the Teenage Witch');
INSERT INTO data_tvshows VALUES ('Sailor Moon');
INSERT INTO data_tvshows VALUES ('Salem''s Lot (1979 miniseries)');
INSERT INTO data_tvshows VALUES ('Salute Your Shorts');
INSERT INTO data_tvshows VALUES ('Sam & Cat');
INSERT INTO data_tvshows VALUES ('Samantha Who?');
INSERT INTO data_tvshows VALUES ('Samurai Jack');
INSERT INTO data_tvshows VALUES ('Samurai Pizza Cats');
INSERT INTO data_tvshows VALUES ('Samuraï X');
INSERT INTO data_tvshows VALUES ('Sanctuary');
INSERT INTO data_tvshows VALUES ('Saturday Night Live');
INSERT INTO data_tvshows VALUES ('Saved by the Bell');
INSERT INTO data_tvshows VALUES ('Saved by the Bell: The College Years');
INSERT INTO data_tvshows VALUES ('Scandal');
INSERT INTO data_tvshows VALUES ('Scarecrow and Mrs. King');
INSERT INTO data_tvshows VALUES ('Schoolhouse Rock!');
INSERT INTO data_tvshows VALUES ('Scooby-Doo (includes Scooby-Doo, Where Are You!, What''s New, Scooby-Doo?)');
INSERT INTO data_tvshows VALUES ('Scorpion');
INSERT INTO data_tvshows VALUES ('Scream Queens');
INSERT INTO data_tvshows VALUES ('Scrubs');
INSERT INTO data_tvshows VALUES ('SCTV');
INSERT INTO data_tvshows VALUES ('Sea Patrol');
INSERT INTO data_tvshows VALUES ('SeaChange''');
INSERT INTO data_tvshows VALUES ('Sealab 2021''');
INSERT INTO data_tvshows VALUES ('Secret Diary of a Call Girl');
INSERT INTO data_tvshows VALUES ('Secret Life of the American Teenager, The');
INSERT INTO data_tvshows VALUES ('Secret World of Alex Mack, The');
INSERT INTO data_tvshows VALUES ('Seinfeld');
INSERT INTO data_tvshows VALUES ('Sesame Street');
INSERT INTO data_tvshows VALUES ('Sex and the City');
INSERT INTO data_tvshows VALUES ('Shake It Up');
INSERT INTO data_tvshows VALUES ('Shaman King');
INSERT INTO data_tvshows VALUES ('Shameless (U.S.)');
INSERT INTO data_tvshows VALUES ('Shark');
INSERT INTO data_tvshows VALUES ('Sharpe');
INSERT INTO data_tvshows VALUES ('Sheep in the Big City');
INSERT INTO data_tvshows VALUES ('Sherlock');
INSERT INTO data_tvshows VALUES ('Shield, The');
INSERT INTO data_tvshows VALUES ('Shuffle!');
INSERT INTO data_tvshows VALUES ('Silver Spoons');
INSERT INTO data_tvshows VALUES ('Simpsons, The');
INSERT INTO data_tvshows VALUES ('Six Feet Under');
INSERT INTO data_tvshows VALUES ('Skins');
INSERT INTO data_tvshows VALUES ('Sledge Hammer!');
INSERT INTO data_tvshows VALUES ('Sleepy Hollow');
INSERT INTO data_tvshows VALUES ('Sliders');
INSERT INTO data_tvshows VALUES ('Smallville');
INSERT INTO data_tvshows VALUES ('Soap');
INSERT INTO data_tvshows VALUES ('Sonic X');
INSERT INTO data_tvshows VALUES ('Sonny With A Chance');
INSERT INTO data_tvshows VALUES ('Sons of Anarchy');
INSERT INTO data_tvshows VALUES ('Sopranos, The');
INSERT INTO data_tvshows VALUES ('Soul Eater');
INSERT INTO data_tvshows VALUES ('South Park');
INSERT INTO data_tvshows VALUES ('Space: Above and Beyond');
INSERT INTO data_tvshows VALUES ('Spaced');
INSERT INTO data_tvshows VALUES ('Spartacus: Blood and Sand');
INSERT INTO data_tvshows VALUES ('Spartacus: Gods of the Arena');
INSERT INTO data_tvshows VALUES ('Special Unit 2');
INSERT INTO data_tvshows VALUES ('Spin City');
INSERT INTO data_tvshows VALUES ('SpongeBob SquarePants');
INSERT INTO data_tvshows VALUES ('Spooks');
INSERT INTO data_tvshows VALUES ('Sports Night');
INSERT INTO data_tvshows VALUES ('Square One Television');
INSERT INTO data_tvshows VALUES ('Squidbillies');
INSERT INTO data_tvshows VALUES ('St. Elsewhere');
INSERT INTO data_tvshows VALUES ('Stand, The (miniseries)');
INSERT INTO data_tvshows VALUES ('Star Trek');
INSERT INTO data_tvshows VALUES ('Star Trek: Deep Space Nine');
INSERT INTO data_tvshows VALUES ('Star Wars: The Clone Wars (2008)');
INSERT INTO data_tvshows VALUES ('Stargate Atlantis''');
INSERT INTO data_tvshows VALUES ('Stargate SG-1');
INSERT INTO data_tvshows VALUES ('Stargate Universe');
INSERT INTO data_tvshows VALUES ('Stella');
INSERT INTO data_tvshows VALUES ('Steve Harvey Show, The');
INSERT INTO data_tvshows VALUES ('Steven Universe');
INSERT INTO data_tvshows VALUES ('Still Game');
INSERT INTO data_tvshows VALUES ('Stingers');
INSERT INTO data_tvshows VALUES ('Storm Hawks');
INSERT INTO data_tvshows VALUES ('Strangers with Candy');
INSERT INTO data_tvshows VALUES ('Stripperella');
INSERT INTO data_tvshows VALUES ('Studio 60 on the Sunset Strip');
INSERT INTO data_tvshows VALUES ('Sue Thomas: F.B.Eye');
INSERT INTO data_tvshows VALUES ('Suite Life of Zack and Cody, The');
INSERT INTO data_tvshows VALUES ('Suite Life on Deck, The');
INSERT INTO data_tvshows VALUES ('Suits (TV series)');
INSERT INTO data_tvshows VALUES ('Summer Heights High');
INSERT INTO data_tvshows VALUES ('Summerland');
INSERT INTO data_tvshows VALUES ('Super Mario World');
INSERT INTO data_tvshows VALUES ('Super WHY!');
INSERT INTO data_tvshows VALUES ('Superman: The Animated Series (aka Superman)');
INSERT INTO data_tvshows VALUES ('Supernatural (U.S.)');
INSERT INTO data_tvshows VALUES ('Survivor (U.S.)');
INSERT INTO data_tvshows VALUES ('SWAT Kats: The Radical Squadron (aka SWAT Kats)');
INSERT INTO data_tvshows VALUES ('Sweeney, The');
INSERT INTO data_tvshows VALUES ('Taken');
INSERT INTO data_tvshows VALUES ('Takin'' Over the Asylum');
INSERT INTO data_tvshows VALUES ('TaleSpin');
INSERT INTO data_tvshows VALUES ('TalkAbout');
INSERT INTO data_tvshows VALUES ('Taz-Mania');
INSERT INTO data_tvshows VALUES ('Teachers');
INSERT INTO data_tvshows VALUES ('Teen Titans');
INSERT INTO data_tvshows VALUES ('Teen Wolf (2011)');
INSERT INTO data_tvshows VALUES ('Teenage Mutant Ninja Turtles (1987)');
INSERT INTO data_tvshows VALUES ('Teenage Mutant Ninja Turtles (2003)');
INSERT INTO data_tvshows VALUES ('Teenage Mutant Ninja Turtles (2012)');
INSERT INTO data_tvshows VALUES ('Tenacious D');
INSERT INTO data_tvshows VALUES ('Tengen Toppa Gurren Lagann');
INSERT INTO data_tvshows VALUES ('Terminator: The Sarah Connor Chronicles');
INSERT INTO data_tvshows VALUES ('Texhnolyze');
INSERT INTO data_tvshows VALUES ('That ''70s Show');
INSERT INTO data_tvshows VALUES ('That''s So Raven');
INSERT INTO data_tvshows VALUES ('The Adventures of the Little Prince');
INSERT INTO data_tvshows VALUES ('The Flash (2014)');
INSERT INTO data_tvshows VALUES ('The Hills');
INSERT INTO data_tvshows VALUES ('The Persuaders!');
INSERT INTO data_tvshows VALUES ('The Vampire Diaries');
INSERT INTO data_tvshows VALUES ('The Virginian');
INSERT INTO data_tvshows VALUES ('The X''s');
INSERT INTO data_tvshows VALUES ('Thick Of It');
INSERT INTO data_tvshows VALUES ('Think Fast');
INSERT INTO data_tvshows VALUES ('Third Watch');
INSERT INTO data_tvshows VALUES ('Thomas and Friends');
INSERT INTO data_tvshows VALUES ('Three''s Company');
INSERT INTO data_tvshows VALUES ('Through the Wormhole');
INSERT INTO data_tvshows VALUES ('Thunderbirds');
INSERT INTO data_tvshows VALUES ('Tick, The (1994, animated)');
INSERT INTO data_tvshows VALUES ('Tick, The (2001, live-action)');
INSERT INTO data_tvshows VALUES ('Tim and Eric Awesome Show, Great Job!');
INSERT INTO data_tvshows VALUES ('Tiny Toon Adventures');
INSERT INTO data_tvshows VALUES ('Titus');
INSERT INTO data_tvshows VALUES ('Tom Goes to the Mayor');
INSERT INTO data_tvshows VALUES ('Top Chef');
INSERT INTO data_tvshows VALUES ('Top Gear');
INSERT INTO data_tvshows VALUES ('Torchwood');
INSERT INTO data_tvshows VALUES ('Total Drama Action');
INSERT INTO data_tvshows VALUES ('Total Drama Island');
INSERT INTO data_tvshows VALUES ('Touch');
INSERT INTO data_tvshows VALUES ('Touched By An Angel');
INSERT INTO data_tvshows VALUES ('Trailer Park Boys');
INSERT INTO data_tvshows VALUES ('Transformers Animated');
INSERT INTO data_tvshows VALUES ('Transformers Prime');
INSERT INTO data_tvshows VALUES ('Transformers: Robots in Disguise (2015)');
INSERT INTO data_tvshows VALUES ('Tribe, The');
INSERT INTO data_tvshows VALUES ('Trigun');
INSERT INTO data_tvshows VALUES ('Tru Calling');
INSERT INTO data_tvshows VALUES ('True Blood');
INSERT INTO data_tvshows VALUES ('Tsubasa RESERVoir CHRoNiCLE');
INSERT INTO data_tvshows VALUES ('Tudors, The');
INSERT INTO data_tvshows VALUES ('Twilight Zone, The (1959 series)');
INSERT INTO data_tvshows VALUES ('Twilight Zone, The (1985 series)');
INSERT INTO data_tvshows VALUES ('Twin Peaks');
INSERT INTO data_tvshows VALUES ('Two and a Half Men');
INSERT INTO data_tvshows VALUES ('Two Ronnies, The');
INSERT INTO data_tvshows VALUES ('Ugly Americans');
INSERT INTO data_tvshows VALUES ('Ugly Betty');
INSERT INTO data_tvshows VALUES ('Undeclared');
INSERT INTO data_tvshows VALUES ('Underdog');
INSERT INTO data_tvshows VALUES ('Unit, The');
INSERT INTO data_tvshows VALUES ('United States of Tara');
INSERT INTO data_tvshows VALUES ('Upright Citizens Brigade');
INSERT INTO data_tvshows VALUES ('Urusei Yatsura');
INSERT INTO data_tvshows VALUES ('Utopia (UK TV series)');
INSERT INTO data_tvshows VALUES ('V (TV series)');
INSERT INTO data_tvshows VALUES ('Veep');
INSERT INTO data_tvshows VALUES ('VeggieTales');
INSERT INTO data_tvshows VALUES ('Venture Bros., The');
INSERT INTO data_tvshows VALUES ('Veronica Mars');
INSERT INTO data_tvshows VALUES ('Very British Coup, A');
INSERT INTO data_tvshows VALUES ('Vicar of Dibley, The');
INSERT INTO data_tvshows VALUES ('Victorious');
INSERT INTO data_tvshows VALUES ('Viva La Bam');
INSERT INTO data_tvshows VALUES ('Voltron: Defender of the Universe');
INSERT INTO data_tvshows VALUES ('W.I.T.C.H. (TV series)');
INSERT INTO data_tvshows VALUES ('Walking Dead, The');
INSERT INTO data_tvshows VALUES ('Wanted');
INSERT INTO data_tvshows VALUES ('War at Home');
INSERT INTO data_tvshows VALUES ('War of the Worlds');
INSERT INTO data_tvshows VALUES ('Warehouse 13');
INSERT INTO data_tvshows VALUES ('Waterloo Road');
INSERT INTO data_tvshows VALUES ('WCW Monday Nitro');
INSERT INTO data_tvshows VALUES ('We Can Be Heroes');
INSERT INTO data_tvshows VALUES ('Weeds');
INSERT INTO data_tvshows VALUES ('Weekenders, The');
INSERT INTO data_tvshows VALUES ('Welcome Back, Kotter');
INSERT INTO data_tvshows VALUES ('West Wing, The');
INSERT INTO data_tvshows VALUES ('What I Like About You');
INSERT INTO data_tvshows VALUES ('What''s Happening!!');
INSERT INTO data_tvshows VALUES ('Wheel of Fortune');
INSERT INTO data_tvshows VALUES ('Where in the World is Carmen Sandiego?');
INSERT INTO data_tvshows VALUES ('White Collar');
INSERT INTO data_tvshows VALUES ('Whose Line Is It Anyway? (United States and United Kingdom)');
INSERT INTO data_tvshows VALUES ('Wild, Wild West');
INSERT INTO data_tvshows VALUES ('Wildfire');
INSERT INTO data_tvshows VALUES ('Will & Grace');
INSERT INTO data_tvshows VALUES ('Winx Club');
INSERT INTO data_tvshows VALUES ('Wire in the Blood');
INSERT INTO data_tvshows VALUES ('Wire, The');
INSERT INTO data_tvshows VALUES ('Without a Trace');
INSERT INTO data_tvshows VALUES ('Wizards of Waverly Place');
INSERT INTO data_tvshows VALUES ('WKRP in Cincinnati');
INSERT INTO data_tvshows VALUES ('Wonder Showzen');
INSERT INTO data_tvshows VALUES ('Wonder Years, The');
INSERT INTO data_tvshows VALUES ('Wonderfalls');
INSERT INTO data_tvshows VALUES ('Workaholics');
INSERT INTO data_tvshows VALUES ('World at War, The');
INSERT INTO data_tvshows VALUES ('WWE Championship Wrestling');
INSERT INTO data_tvshows VALUES ('WWE Raw');
INSERT INTO data_tvshows VALUES ('WWE Superstars of Wrestling');
INSERT INTO data_tvshows VALUES ('Xavier, Renegade Angel');
INSERT INTO data_tvshows VALUES ('Xena: Warrior Princess');
INSERT INTO data_tvshows VALUES ('X-Files, The');
INSERT INTO data_tvshows VALUES ('X-Men (TV series)');
INSERT INTO data_tvshows VALUES ('X-Men: Evolution');
INSERT INTO data_tvshows VALUES ('xxx HOLiC');
INSERT INTO data_tvshows VALUES ('Yes, Minister');
INSERT INTO data_tvshows VALUES ('Yes, Prime Minister');
INSERT INTO data_tvshows VALUES ('Yo soy Bea');
INSERT INTO data_tvshows VALUES ('You Can''t Do That on Television');
INSERT INTO data_tvshows VALUES ('Young Justice');
INSERT INTO data_tvshows VALUES ('Young Ones, The');
INSERT INTO data_tvshows VALUES ('Yu Yu Hakusho');
INSERT INTO data_tvshows VALUES ('Yu-Gi-Oh GX');
INSERT INTO data_tvshows VALUES ('Yu-Gi-Oh!');
INSERT INTO data_tvshows VALUES ('Zatch Bell!');
INSERT INTO data_tvshows VALUES ('Zoey 101');
