CREATE TABLE data_sportsTeam (
    `Sport` VARCHAR(10) CHARACTER SET utf8,
    `League` VARCHAR(28) CHARACTER SET utf8,
    `Team` VARCHAR(31) CHARACTER SET utf8,
    `Country` VARCHAR(3) CHARACTER SET utf8
);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Anaheim Ducks',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Boston Bruins',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Buffalo Sabres',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Calgary Flames',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Carolina Hurricanes',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Chicago Blackhawks',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Colorado Avalanche',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Columbus Blue Jackets',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Dallas Stars',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Detroit Red Wings',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Edmonton Oilers',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Florida Panthers',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Los Angeles Kings',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Minnesota Wild',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Montreal Canadiens',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Nashville Predators',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','New Jersey Devils',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','New York Islanders',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','New York Rangers',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Ottawa Senators',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Philadelphia Flyers',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Phoenix Coyotes',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Pittsburgh Penguins',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Saint Louis Blues',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','San Jose Sharks',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Tampa Bay Lighting',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Toronto Maple Leafs',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Vancouver Canucks',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Washington Capitals',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','NHL','Winnipeg Jets',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Arizona Diamondbacks',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Atlanta Braves',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Baltimore Orioles',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Boston Red Sox',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Chicago Cubs',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Chicago White Sox',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Cincinnati Reds',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Cleveland Indians',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Colorado Rockies',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Detroit Tigers',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Houston Astros',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Kansas City Royals',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Los Angeles Angels of Anaheim',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Los Angeles Dodgers',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Miami Marlins',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Milwaukee Brewers',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Minnesota Twins',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','New York Mets',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','New York Yankees',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Oakland Athletics',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Philadelphia Phillies',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Pittsburgh Pirates',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','St. Louis Cardinals',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','San Diego Padres',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','San Francisco Giants',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Seattle Mariners',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Tampa Bay Rays',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Texas Rangers',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Toronto Blue Jays',NULL);
INSERT INTO data_sportsTeam VALUES ('Baseball','MLB','Washington Nationals',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Atlanta Hawks',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Boston Celtics',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Brooklyn Nets',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Charlotte Hornets',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Chicago Bulls',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Cleveland Cavaliers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Dallas Mavericks',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Denver Nuggets',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Detroit Pistons',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Golden State Warriors',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Houston Rockets',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Indiana Pacers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Los Angeles Clippers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Los Angeles Lakers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Memphis Grizzlies',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Miami Heat',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Milwaukee Bucks',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Minnesota Timberwolves',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','New Orleans Pelicans',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','New York Knicks',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Oklahoma City Thunder',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Orlando Magic',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Philadelphia 76ers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Phoenix Suns',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Portland Trail Blazers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Sacramento Kings',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','San Antonio Spurs',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Toronto Raptors',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Utah Jazz',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NBA','Washington Wizards',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Akron Zips ',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Alabama Crimson Tide ',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Appalachian State Mountaineers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Arizona State Sun Devils ',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Arizona Wildcats ',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Arkansas Razorbacks ',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Army Black Knights ',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Auburn Tigers ',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Ball State Cardinals',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Baylor Bears',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Boise State Broncos',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Boston College Eagles',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Boston Terriers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','BYU Cougars',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Cal Golden Bears',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Cal State Fullerton Titans',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Cincinnati Bearcats',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Clemson Tigers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Colorado Buffaloes',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Colorado State Rams',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Connecticut Huskies',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Cornell Big Red',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Dartmouth Big Green',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Dayton Flyers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Duke Blue Devils',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','E. Tenn. St. Buccaneers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','East Carolina Pirates',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Florida Gators',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Florida State Seminoles',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Fresno State Bulldogs ',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Georgia Tech Yellow Jackets',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Georgetown Hoyas',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Georgia Bulldogs',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Georgia Southern Eagles',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Gonzaga Bulldogs',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Harvard Crimson',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Hawaii Warriors',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Houston Cougars',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Idaho Vandals',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Illinois Fighting Illini',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Indiana Hoosiers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Iowa Hawkeyes',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Iowa State Cyclones',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','JU Dolphins',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Kansas Jayhawks',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Kansas State Wildcats',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Kent State Golden Flashes',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Kentucky Wildcats',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Louisville Cardinals',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','LSU Tigers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Marquette Golden Eagles',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Marshall Thundering Herd',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Maryland Terrapins',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Memphis Tigers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Miami Hurricanes',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Miami University RedHawks',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Michigan State Spartans',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Michigan Wolverines',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Mid. Tenn. St. Blue Raiders',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Minnesota Golden Gophers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Mississippi State Bulldogs',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Missouri Tigers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Montana Grizzlies ',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Navy Midshipmen',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','NC State Wolfpack',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Nebraska Cornhuskers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','New Mexico Lobos',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','North Carolina Tar Heels',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','North Dakota State Bison',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Northern Iowa Panthers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Northwestern Wildcats',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Notre Dame Fighting Irish',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Ohio State Buckeyes',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Oklahoma Sooners',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Oklahoma State Cowboys',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Ole Miss Rebels',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Oregon Ducks',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Oregon State Beavers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Penn State Nittany Lions',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Pitt Panthers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Portland State Vikings',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Purdue Boilermakers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Rice Owls',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Rutgers Scarlet Knights',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','San Diego State Aztecs',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','South Carolina Gamecocks',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','South Florida Bulls',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Southern Miss Golden Eagles',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Stanford Cardinal',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Syracuse Orange ',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','TCU Horned Frogs',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Temple Owl',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Tennessee Volunteers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Texas A&M Aggies',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Texas Longhorns',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Texas Tech Red Raiders',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Troy University Trojans',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Tulsa Golden Hurricane',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','UCF Knights',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','UCLA Bruins',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','UNLV Runnin Rebels',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','USC Trojans',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Utah State Aggies',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Utah Utes',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','UTEP Miners',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Vanderbilt Commodores',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Villanova Wildcats',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Virginia Cavaliers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Virginia Tech Hokies',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Wake Forest Demon Deacons',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Washington Huskies',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Washington State Cougars',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','West Virginia Mountaineers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Western Kentucky Hilltoppers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Wichita State Shockers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Wisconsin Badgers',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Wyoming Cowboys',NULL);
INSERT INTO data_sportsTeam VALUES ('Basketball','NCAA','Xavier Musketeers',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Arizona Cardinals ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Atlanta Falcons ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Baltimore Ravens ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Buffalo Bills ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Carolina Panthers ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Chicago Bears ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Cincinnati Bengals ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Cleveland Browns ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Dallas Cowboys ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Denver Broncos ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Detroit Lions ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Green Bay Packers ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Houston Texans ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Indianapolis Colts ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Jacksonville Jaguars ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Kansas City Chiefs ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Miami Dolphins ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Minnesota Vikings ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','New England Patriots ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','New Orleans Saints ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','New York Giants ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','New York Jets ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Oakland Raiders ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Philadelphia Eagles ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Pittsburgh Steelers ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','San Diego Chargers ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','San Francisco 49ers ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Seattle Seahawks ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','St. Louis Rams ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Tampa Bay Buccaneers ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Tennessee Titans ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','NFL','Washington Redskins ',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','CFL','Hamilton Tiger-Cats',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','CFL','Montreal Alouettes',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','CFL','Ottawa Redblacks',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','CFL','Toronto Argonauts',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','CFL','BC Lions',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','CFL','Calgary Stampeders',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','CFL','Edmonton Eskimos',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','CFL','Saskatchewan Roughriders',NULL);
INSERT INTO data_sportsTeam VALUES ('Football','CFL','Winnipeg Blue Bombers',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Major League Soccer','Chicago Fire',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Major League Soccer','Columbus Crew SC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Major League Soccer','D.C. United',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Major League Soccer','Montreal Impact',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Major League Soccer','New England Revolution',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Major League Soccer','New York City FC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Major League Soccer','New York Red Bulls',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Major League Soccer','Orlando City SC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Major League Soccer','Philadelphia Union',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Major League Soccer','Toronto FC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Major League Soccer','Colorado Rapids',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Major League Soccer','FC Dallas',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Major League Soccer','Houston Dynamo',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Major League Soccer','LA Galaxy',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Major League Soccer','Portland Timbers',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Major League Soccer','Real Salt Lake',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Major League Soccer','San Jose Earthquakes',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Major League Soccer','Seattle Sounders FC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Major League Soccer','Sporting Kansas City',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Major League Soccer','Vancouver Whitecaps FC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','Bethlehem Steel FC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','Charleston Battery',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','Charlotte Independence',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','FC Cincinnati',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','Harrisburg City Islanders',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','Louisville City FC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','FC Montreal',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','New York Red Bulls II',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','Orlando City B',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','Pittsburgh Riverhounds',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','Richmond Kickers',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','Rochester Rhinos',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','Toronto FC II',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','Wilmington Hammerheads',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','Arizona United SC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','Colorado Springs Switchbacks FC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','LA Galaxy II',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','Oklahoma City Energy FC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','Orange County Blues FC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','Portland Timbers 2',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','Real Monarchs SLC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','Rio Grande Valley FC Toros',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','Sacramento Republic FC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','Saint Louis FC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','San Antonio FC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','Seattle Sounders FC 2',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','Swope Park Rangers',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','Tulsa Roughnecks FC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','United Soccer League','Vancouver Whitecaps FC 2',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','North American Soccer League','Carolina RailHawks',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','North American Soccer League','FC Edmonton',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','North American Soccer League','Fort Lauderdale Strikers',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','North American Soccer League','Indy Eleven',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','North American Soccer League','Jacksonville Armada FC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','North American Soccer League','Miami FC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','North American Soccer League','Minnesota United FC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','North American Soccer League','New York Cosmos',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','North American Soccer League','Ottawa Fury FC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','North American Soccer League','Puerto Rico FC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','North American Soccer League','Rayo OKC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','North American Soccer League','Tampa Bay Rowdies',NULL);
INSERT INTO data_sportsTeam VALUES ('Lacrosse','National Lacrosse League','Buffalo Bandits',NULL);
INSERT INTO data_sportsTeam VALUES ('Lacrosse','National Lacrosse League','Georgia Swarm',NULL);
INSERT INTO data_sportsTeam VALUES ('Lacrosse','National Lacrosse League','New England Black Wolves',NULL);
INSERT INTO data_sportsTeam VALUES ('Lacrosse','National Lacrosse League','Rochester Knighthawks',NULL);
INSERT INTO data_sportsTeam VALUES ('Lacrosse','National Lacrosse League','Toronto Rock',NULL);
INSERT INTO data_sportsTeam VALUES ('Lacrosse','National Lacrosse League','Calgary Roughnecks',NULL);
INSERT INTO data_sportsTeam VALUES ('Lacrosse','National Lacrosse League','Colorado Mammoth',NULL);
INSERT INTO data_sportsTeam VALUES ('Lacrosse','National Lacrosse League','Saskatchewan Rush',NULL);
INSERT INTO data_sportsTeam VALUES ('Lacrosse','National Lacrosse League','Vancouver Stealth',NULL);
INSERT INTO data_sportsTeam VALUES ('Lacrosse','Major League Lacrosse','Atlanta Blaze',NULL);
INSERT INTO data_sportsTeam VALUES ('Lacrosse','Major League Lacrosse','Boston Cannons',NULL);
INSERT INTO data_sportsTeam VALUES ('Lacrosse','Major League Lacrosse','Charlotte Hounds',NULL);
INSERT INTO data_sportsTeam VALUES ('Lacrosse','Major League Lacrosse','Chesapeake Bayhawks',NULL);
INSERT INTO data_sportsTeam VALUES ('Lacrosse','Major League Lacrosse','Denver Outlaws',NULL);
INSERT INTO data_sportsTeam VALUES ('Lacrosse','Major League Lacrosse','Florida Launch',NULL);
INSERT INTO data_sportsTeam VALUES ('Lacrosse','Major League Lacrosse','New York Lizards',NULL);
INSERT INTO data_sportsTeam VALUES ('Lacrosse','Major League Lacrosse','Ohio Machine',NULL);
INSERT INTO data_sportsTeam VALUES ('Lacrosse','Major League Lacrosse','Rochester Rattlers',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Bridgeport Sound Tigers',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Hartford Wolf Pack',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Hershey Bears',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Lehigh Valley Phantoms',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Providence Bruins',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Springfield Thunderbirds',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Wilkes-Barre/Scranton Penguins',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Albany Devils',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Binghamton Senators',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Rochester Americans',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','St. John''s IceCaps',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Syracuse Crunch',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Toronto Marlies',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Utica Comets',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Charlotte Checkers',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Chicago Wolves',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Grand Rapids Griffins',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Iowa Wild',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Lake Erie Monsters',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Manitoba Moose',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Milwaukee Admirals',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Rockford IceHogs',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Bakersfield Condors',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Ontario Reign',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','San Antonio Rampage',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','San Diego Gulls',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','San Jose Barracuda',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Stockton Heat',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Texas Stars',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','American Hockey League','Tucson Roadrunners',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Adirondack Thunder',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Brampton Beast',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Elmira Jackals',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Manchester Monarchs',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Reading Royals',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Wheeling Nailers',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Atlanta Gladiators',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Cincinnati Cyclones',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Florida Everblades',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Greenville Swamp Rabbits',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Norfolk Admirals',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Orlando Solar Bears',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','South Carolina Stingrays',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Fort Wayne Komets',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Indy Fuel',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Kalamazoo Wings',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Quad City Mallards',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Toledo Walleye',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Tulsa Oilers',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Wichita Thunder',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Alaska Aces',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Allen Americans',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Colorado Eagles',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Idaho Steelheads',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Missouri Mavericks',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Rapid City Rush',NULL);
INSERT INTO data_sportsTeam VALUES ('Hockey','ECHL','Utah Grizzlies',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Ajax','NED');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','APOEL','CYP');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Arsenal','ENG');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Astana','KAZ');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Atlético','ESP');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','B36','FRO');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Barcelona','ESP');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Basel','SUI');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','BATE','BLR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Bayern','GER');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Benfica','POR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Celtic','SCO');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Chelsea','ENG');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Club Brugge','BEL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Crusaders','NIR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','CSKA Moskva','RUS');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Dila','GEO');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Dinamo Zagreb','CRO');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Dundalk','IRL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Dynamo Kyiv','UKR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','FC Santa Coloma','AND');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Fenerbahçe','TUR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Fola','LUX');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Folgore','SAN');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Galatasaray','TUR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Gent','BEL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Hibernians','MAL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','HJK','FIN');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Juventus','ITA');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Lazio','ITA');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Lech','POL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Levadia','EST');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Leverkusen','GER');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Lincoln','GIB');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Ludogorets','BUL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Lyon','FRA');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','M. Tel-Aviv','ISR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Malmö','SWE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Man. City','ENG');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Man. United','ENG');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Maribor','SVN');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Midtjylland','DEN');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Milsami','MOL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Molde','NOR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Monaco','FRA');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Mönchengladbach','GER');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Olympiacos','GRE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Panathinaikos','GRE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Paris','FRA');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Partizan','SBA');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Plzeň','CZE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Porto','POR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','PSV','NED');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Pyunik','ARM');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Qarabağ','AZE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Rapid Wien','AUS');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Real Madrid','ESP');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Roma','ITA');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Rudar Pljevlja','MON');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Salzburg','AUS');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Sarajevo','BOS');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Sevilla','ESP');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Shakhtar Donetsk','UKR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Skënderbeu','ALB');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Sparta Praha','CZE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Sporting CP','POR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Steaua','ROU');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Stjarnan','ICE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','TNS','WAL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Trenčín','SLO');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Valencia','ESP');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Vardar','MKD');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Ventspils','LAT');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Videoton','HUN');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Wolfsburg','GER');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Young Boys','SUI');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Žalgiris','LIT');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Champions League','Zenit','RUS');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Aberdeen','SCO');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Admira','AUT');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','AEK','GRE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','AEK Larnaca','CYP');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','AIK','SWE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Aktobe','KAZ');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Apollon','CYP');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Arouca','POR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Athletic','ESP');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Atlantas','LTU');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Austria Wien','AUT');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','AZ','NED');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Bala','WAL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Balzan','MLT');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Banants','ARM');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Beitar Jerusalem','ISR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Beroe','BUL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Birkirkara','MLT');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Bokelj','MNE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Braga','POR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Breidablik','ISL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Brøndby','DEN');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Budućnost Podgorica','MNE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Celta','ESP');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Chikhura','GEO');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Cliftonville','NIR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Connah''s Quay','WAL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Cork','IRL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Cracovia','POL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','CSMS laşi','ROU');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Čukarički','SRB');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Dacia','MDA');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Debrecen','HUN');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Differdange','LUX');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Dila','GEO');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Dinamo Minsk','BLR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Domžale','SVN');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Europa','GIB');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','FCI Tallinn','EST');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Feyenoord','NED');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Fiorentina','ITA');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Fola','LUX');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Folgore','SMR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Genk','BEL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Gent','BEL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Giannina','GRE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Glenavon','NIR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Gorica','SVN');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Göteborg','SWE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Grasshoppers','SUI');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Häcken','SWE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Hajduk Split','CRO');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','HB','FRO');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Hearts','SCO');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Heracles','NED');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Hertha','GER');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Hibernian','SCO');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Hibernians','MLT');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','HJK','FIN');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Internazionale','ITA');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','İstanbul Başakşehir','TUR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Jelgava','LVA');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Jeunesse Esch','LUX');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Kairat','KAZ');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Kalju','EST');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Käpäz','AZE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Konyaspor','TUR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','KR','ISL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Krasnodar','RUS');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Kukës','ALB');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','La Fiorita','SMR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Levadia','EST');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Levski','BUL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Liberec','CZE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Linfield','NIR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Llandudno Town','WAL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Lokomotiva Zagreb','CRO');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','LOSC','FRA');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Lusitans','AND');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Luzern','SUI');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','M. Haifa','ISR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','M. Tel-Aviv','ISR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Mainz','GER');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Man. United','ENG');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Maribor','SVN');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Mariehamn','FIN');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Midtjylland','DEN');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Mladá Boleslav','CZE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','MTK','HUN');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Neftçi','AZE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Nice','FRA');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','NSÍ','FRO');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Odd','NOR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Olexandriya','UKR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Omonia','CYP');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Ordabasy','KAZ');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Osmanlıspor','TUR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Panathinaikos','GRE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Pandurii','ROU');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Partizan','SRB');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Partizani','ALB');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Piast','POL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Pyunik','ARM');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Qäbälä','AZE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Rabotnicki','MKD');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Radnik','BIH');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Rapid Wien','AUT');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Rijeka','CRO');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Rio Ave','POR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','RoPS','FIN');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Rudar Pljevlja','MNE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Samtredia','GEO');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Sassuolo','ITA');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Schalke','GER');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Shakhtyor','BLR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Shamrock Rovers','IRL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Shirak','ARM');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Shkëndija','MKD');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Sileks','MKD');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Široki Brijeg','BIH');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Slavia Praha','CZE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Slavia Sofia','BUL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Sloboda','BIH');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Slovan Bratislava','SVK');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','SønderjyskE','DEN');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Southampton','ENG');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Spartak Moskva','RUS');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Spartak Myjava','SVK');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Spartak Trnava','SVK');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Spartaks Jūrmala','LVA');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','St Patrick''s','IRL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Stabæk','NOR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Standard Liège','BEL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','St-Étienne','FRA');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Strømsgodset','NOR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Sūduva','LTU');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Teuta','ALB');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Torpedo Zhodino','BLR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Trakai','LTU');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','UE Santa Coloma','AND');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Vaduz','LIE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Valur','ISL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Ventspils','LVA');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Videoton','HUN');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Viitorul','ROU');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Vikingur','FRO');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Vojvodina','SRB');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Vorskla','UKR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','West Ham','ENG');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Zagłębie','POL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Zaria Balti','MDA');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Zenit','RUS');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Zimbru','MDA');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Zorya','UKR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA Europa League','Zürich','SUI');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Albania','ALB');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Andorra','AND');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Armenia','ARM');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Austria','AUT');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Azerbaijan','AZE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Belarus','BLR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Belgium','BEL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Bosnia and Herzegovina','BIH');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Bulgaria','BUL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Croatia','CRO');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Cyprus','CYP');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Czech Republic','CZE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Denmark','DEN');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','England','ENG');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Estonia','EST');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Faroe Islands','FRO');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Finland','FIN');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','France','FRA');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','FYR Macedonia','MKD');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Georgia','GEO');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Germany','GER');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Gibraltar','GIB');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Greece','GRE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Hungary','HUN');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Iceland','ISL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Israel','ISR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Italy','ITA');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Kazakhstan','KAZ');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Latvia','LVA');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Liechtenstein','LIE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Lithuania','LTU');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Luxembourg','LUX');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Malta','MLT');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Moldova','MDA');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Montenegro','MNE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Netherlands','NED');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Northern Ireland','NIR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Norway','NOR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Poland','POL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Portugal','POR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Republic of Ireland','IRL');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Romania','ROU');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Russia','RUS');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','San Marino','SMR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Scotland','SCO');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Serbia','SRB');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Slovakia','SVK');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Slovenia','SVN');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Spain','ESP');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Sweden','SWE');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Switzerland','SUI');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Turkey','TUR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Ukraine','UKR');
INSERT INTO data_sportsTeam VALUES ('Soccer','UEFA EURO','Wales','WAL');
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Albania',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Andorra',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Armenia',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Austria',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Azerbaijan',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Belarus',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Belgium',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Bosnia and Herzegovina',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Bulgaria',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Croatia',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Cyprus',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Czech Republic',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Denmark',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','England',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Estonia',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Faroe Islands',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Finland',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','France',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','FYR Macedonia',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Georgia',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Germany',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Gibraltar',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Greece',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Hungary',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Iceland',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Israel',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Italy',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Kazakhstan',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Kosovo',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Latvia',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Liechtenstein',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Lithuania',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Luxembourg',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Malta',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Moldova',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Montenegro',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Netherlands',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Northern Ireland',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Norway',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Poland',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Portugal',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Republic of Ireland',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Romania',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Russia',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','San Marino',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Scotland',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Serbia',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Slovakia',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Slovenia',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Spain',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Sweden',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Switzerland',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Turkey',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Ukraine',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','FIFA World Cup','Wales',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','Wacker',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','Bayer Leverkusen',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','Dortmund',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','Monchengladbach',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','Eintracht Frankfurt',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','FC Augsburg',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','Bayern Munich',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','FC Cologne',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','Ingolstadt',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','FSV Mainz 05',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','Hamburg SV',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','Hertha BSC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','Leipzig',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','SC Freiburg',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','SC Paderborn 07',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','Neustadt',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','Altach',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','Sturm',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','Darmstadt',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','Ried',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','Schalke 04',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','TSG Hoffenheim',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','VfL Wolfsburg',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','Werder Bremen',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Bundesliga','Wolfsberger',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Liga','Almería',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Liga','Athletic Bilbao',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Liga','Atletico Madrid',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Liga','Alaves',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Liga','Leganes',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Liga','Celta de Vigo',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Liga','Deportivo La Coruña',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Liga','Elche CF',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Liga','FC Barcelona',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Liga','Granada',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Liga','Las Palmas',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Liga','Malaga',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Liga','Espanyol',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Liga','Real Betis',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Liga','Real Madrid',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Liga','Real Sociedad',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Liga','Sevilla',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Liga','Sporting Gijon',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Liga','Valencia',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Liga','Villarreal',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','Lille OSC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','AS Monaco',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','AS Nancy',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','AS Saint-Étienne',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','Caen',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','Dijon',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','Guingamp',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','Evian',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','FC Girondins de Bordeaux',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','FC Lorient',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','Nantes',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','Sochaux',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','Sochaux',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','FC Sochaux-Montbéliard',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','Lille OSC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','Metz',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','Montpellier Hérault SC',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','OGC Nice',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','Olympique Lyonnais',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','Olympique de Marseille',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','Paris Saint-Germain',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','Rennes',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','Bastia',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','Stade Rennais',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','Reims',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','Toulouse',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Ligue 1','Valenciennes',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','English Premier League','Bournemouth',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','English Premier League','Leicester City',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','English Premier League','Watford',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','English Premier League','Arsenal',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','English Premier League','Bournemouth',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','English Premier League','Burnley',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','English Premier League','Chelsea',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','English Premier League','Crystal Palace',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','English Premier League','Everton',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','English Premier League','Hull City',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','English Premier League','Leicester City',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','English Premier League','Liverpool',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','English Premier League','Man City',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','English Premier League','Man Utd',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','English Premier League','Middlesbrough',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','English Premier League','Southampton',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','English Premier League','Stoke City',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','English Premier League','Sunderland',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','English Premier League','Swansea City',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','English Premier League','Spurs',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','English Premier League','Watford',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','English Premier League','West Brom',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','English Premier League','West Ham',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Serie A','AC Milan',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Serie A','AS Roma',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Serie A','Atalanta',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Serie A','Bologna',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Serie A','Cagliari',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Serie A','Chievo Verona',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Serie A','Empoli',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Serie A','Crotone',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Serie A','Fiorentina',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Serie A','Genoa',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Serie A','Inter Milan',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Serie A','Juventus',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Serie A','Lazio',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Serie A','Napoli',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Serie A','Palermo',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Serie A','Pescara',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Serie A','Sampdoria',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Serie A','Sassuolo',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Serie A','Torino',NULL);
INSERT INTO data_sportsTeam VALUES ('Soccer','Serie A','Udinese',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Champions League Twenty20','Auckland Aces ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Champions League Twenty20','Barbados Tridents ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Champions League Twenty20','Brisbane Heat ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Champions League Twenty20','Cape Cobras ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Champions League Twenty20','Central Districts Stags ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Champions League Twenty20','Chennai Super Kings ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Champions League Twenty20','Delhi Daredevils ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Champions League Twenty20','Diamond Eagles ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Champions League Twenty20','Dolphins cricket team ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Champions League Twenty20','Highveld Lions ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Champions League Twenty20','Hobart Hurricanes ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Champions League Twenty20','Kings XI Punjab ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Champions League Twenty20','Kolkata Knight Riders ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Champions League Twenty20','Lahore Lions ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Champions League Twenty20','Mumbai Indians ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Champions League Twenty20','Northern Knights ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Champions League Twenty20','Otago Volts ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Champions League Twenty20','Perth Scorchers ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Champions League Twenty20','Rajasthan Royals ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Champions League Twenty20','Royal Challengers Bangalore ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Champions League Twenty20','Sunrisers Hyderabad ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Champions League Twenty20','Sydney Sixers ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Champions League Twenty20','Titans ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Champions League Twenty20','Warriors ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC Champions Trophy','Afghanistan',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC Champions Trophy','Australia',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC Champions Trophy','Bangladesh',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC Champions Trophy','England',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC Champions Trophy','India',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC Champions Trophy','Ireland',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC Champions Trophy','New Zealand',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC Champions Trophy','Pakistan',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC Champions Trophy','South Africa',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC Champions Trophy','Sri Lanka',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC Champions Trophy','West Indies',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC Champions Trophy','Zimbabwe',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC World Cricket League','Afghanistan',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC World Cricket League','Bermuda',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC World Cricket League','Canada',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC World Cricket League','Denmark',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC World Cricket League','Guernsey',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC World Cricket League','Hong Kong',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC World Cricket League','Ireland',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC World Cricket League','Italy',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC World Cricket League','Jersey',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC World Cricket League','Kenya',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC World Cricket League','Malaysia',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC World Cricket League','Namibia',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC World Cricket League','Nepal',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC World Cricket League','Netherlands',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC World Cricket League','Oman',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC World Cricket League','Papua New Guinea',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC World Cricket League','Scotland',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC World Cricket League','Singapore',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC World Cricket League','Uganda',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC World Cricket League','United Arab Emirates',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','ICC World Cricket League','United States',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Indian Premier League (T20)','Delhi Daredevils ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Indian Premier League (T20)','Gujarat Lions ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Indian Premier League (T20)','Kings XI Punjab ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Indian Premier League (T20)','Kolkata Knight Riders ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Indian Premier League (T20)','Mumbai Indians ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Indian Premier League (T20)','Rising Pune Supergiants ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Indian Premier League (T20)','Royal Challengers Bangalore ',NULL);
INSERT INTO data_sportsTeam VALUES ('Cricket','Indian Premier League (T20)','Sunrisers Hyderabad ',NULL);
INSERT INTO data_sportsTeam VALUES ('Rugby','International competition','Argentina',NULL);
INSERT INTO data_sportsTeam VALUES ('Rugby','International competition','Australia',NULL);
INSERT INTO data_sportsTeam VALUES ('Rugby','International competition','Brazil',NULL);
INSERT INTO data_sportsTeam VALUES ('Rugby','International competition','England',NULL);
INSERT INTO data_sportsTeam VALUES ('Rugby','International competition','France',NULL);
INSERT INTO data_sportsTeam VALUES ('Rugby','International competition','Fuji',NULL);
INSERT INTO data_sportsTeam VALUES ('Rugby','International competition','Georgia',NULL);
INSERT INTO data_sportsTeam VALUES ('Rugby','International competition','Ireland',NULL);
INSERT INTO data_sportsTeam VALUES ('Rugby','International competition','Italy',NULL);
INSERT INTO data_sportsTeam VALUES ('Rugby','International competition','Japan',NULL);
INSERT INTO data_sportsTeam VALUES ('Rugby','International competition','Kenya',NULL);
INSERT INTO data_sportsTeam VALUES ('Rugby','International competition','New Zealand',NULL);
INSERT INTO data_sportsTeam VALUES ('Rugby','International competition','Scotland',NULL);
INSERT INTO data_sportsTeam VALUES ('Rugby','International competition','South Africa',NULL);
INSERT INTO data_sportsTeam VALUES ('Rugby','International competition','Spain',NULL);
INSERT INTO data_sportsTeam VALUES ('Rugby','International competition','United States',NULL);
INSERT INTO data_sportsTeam VALUES ('Rugby','International competition','Wales',NULL);
