CREATE TABLE data_charities (
    `CHARITIES` VARCHAR(69) CHARACTER SET utf8
);
INSERT INTO data_charities VALUES ('1MISSION');
INSERT INTO data_charities VALUES ('416 Community Support for Women');
INSERT INTO data_charities VALUES ('A Glimmer of Hope Foundation');
INSERT INTO data_charities VALUES ('AARP');
INSERT INTO data_charities VALUES ('AARP Foundation');
INSERT INTO data_charities VALUES ('Abaana');
INSERT INTO data_charities VALUES ('Acadia University');
INSERT INTO data_charities VALUES ('ACCESS College Foundation');
INSERT INTO data_charities VALUES ('Accion International');
INSERT INTO data_charities VALUES ('Acclaim Health');
INSERT INTO data_charities VALUES ('Accuracy in Media');
INSERT INTO data_charities VALUES ('ACET (AIDS charity)');
INSERT INTO data_charities VALUES ('Achilles International');
INSERT INTO data_charities VALUES ('Acid Survivors Trust International');
INSERT INTO data_charities VALUES ('ACLU');
INSERT INTO data_charities VALUES ('Acorns Children''s Hospice');
INSERT INTO data_charities VALUES ('Action Africa');
INSERT INTO data_charities VALUES ('Action Against Hunger');
INSERT INTO data_charities VALUES ('ActionAid');
INSERT INTO data_charities VALUES ('Acumen');
INSERT INTO data_charities VALUES ('Acumen (organization)');
INSERT INTO data_charities VALUES ('Adelson Foundation');
INSERT INTO data_charities VALUES ('Adopt a Platoon');
INSERT INTO data_charities VALUES ('Adopt a Revolution');
INSERT INTO data_charities VALUES ('Adopt-A-Minefield');
INSERT INTO data_charities VALUES ('ADRA Canada');
INSERT INTO data_charities VALUES ('Advancing Girls’ Education in Africa');
INSERT INTO data_charities VALUES ('Adventist Development and Relief Agency');
INSERT INTO data_charities VALUES ('Aerospace Heritage Foundation of Canada');
INSERT INTO data_charities VALUES ('Afghan Connection');
INSERT INTO data_charities VALUES ('Afghanaid');
INSERT INTO data_charities VALUES ('Africa and Middle East Refugee Assistance');
INSERT INTO data_charities VALUES ('Africa Classroom Connection');
INSERT INTO data_charities VALUES ('Africa Development Corps');
INSERT INTO data_charities VALUES ('Africa-America Institute');
INSERT INTO data_charities VALUES ('African Aid Organization');
INSERT INTO data_charities VALUES ('African Children''s Choir');
INSERT INTO data_charities VALUES ('African Childrens Haven');
INSERT INTO data_charities VALUES ('African Food and Peace Foundation');
INSERT INTO data_charities VALUES ('African Rainforest Conservancy');
INSERT INTO data_charities VALUES ('African Rural Development and Sustainability Organization');
INSERT INTO data_charities VALUES ('African Services Committee');
INSERT INTO data_charities VALUES ('African Solutions to African Problems');
INSERT INTO data_charities VALUES ('African Studies Association');
INSERT INTO data_charities VALUES ('African Wildlife Foundation');
INSERT INTO data_charities VALUES ('Africare');
INSERT INTO data_charities VALUES ('AFS USA');
INSERT INTO data_charities VALUES ('Aga Khan Foundation Canada');
INSERT INTO data_charities VALUES ('Age Concern');
INSERT INTO data_charities VALUES ('Age NI');
INSERT INTO data_charities VALUES ('Age UK');
INSERT INTO data_charities VALUES ('Agence Ometz');
INSERT INTO data_charities VALUES ('Agincourt Community Services Association');
INSERT INTO data_charities VALUES ('Agros International');
INSERT INTO data_charities VALUES ('Aid for Africa');
INSERT INTO data_charities VALUES ('Aide médicale internationale');
INSERT INTO data_charities VALUES ('AIDS Research Alliance');
INSERT INTO data_charities VALUES ('Air Force Aid Society');
INSERT INTO data_charities VALUES ('Akilah Institute for Women');
INSERT INTO data_charities VALUES ('Al Birr Foundation');
INSERT INTO data_charities VALUES ('Åland Islands Peace Institute');
INSERT INTO data_charities VALUES ('Aleh Negev');
INSERT INTO data_charities VALUES ('Alexander S. Onassis Foundation');
INSERT INTO data_charities VALUES ('Alex''s Lemonade Stand Foundation');
INSERT INTO data_charities VALUES ('Alfanar');
INSERT INTO data_charities VALUES ('Al-Haramain Foundation');
INSERT INTO data_charities VALUES ('Alice Housing');
INSERT INTO data_charities VALUES ('Al-Khair Foundation');
INSERT INTO data_charities VALUES ('All God''s Children');
INSERT INTO data_charities VALUES ('Allegheny Foundation');
INSERT INTO data_charities VALUES ('Alley Cat Allies');
INSERT INTO data_charities VALUES ('Alliance for African Assistance');
INSERT INTO data_charities VALUES ('Alliance for Aging Research');
INSERT INTO data_charities VALUES ('Alpha Sigma Tau National Foundation, Inc.');
INSERT INTO data_charities VALUES ('ALS Association');
INSERT INTO data_charities VALUES ('ALS BC');
INSERT INTO data_charities VALUES ('ALS Society of Canada');
INSERT INTO data_charities VALUES ('Alzheimer''s Association');
INSERT INTO data_charities VALUES ('Amazon Conservation Team');
INSERT INTO data_charities VALUES ('American Academy in Rome');
INSERT INTO data_charities VALUES ('American Action Fund for Blind Children and Adults');
INSERT INTO data_charities VALUES ('American Association for the Prevention of Cruelty to Animals (ASPCA)');
INSERT INTO data_charities VALUES ('American Association of State Troopers');
INSERT INTO data_charities VALUES ('American Association of the Deaf-Blind');
INSERT INTO data_charities VALUES ('American Brain Tumor Association');
INSERT INTO data_charities VALUES ('American Cancer Society');
INSERT INTO data_charities VALUES ('American Civil Liberties Union');
INSERT INTO data_charities VALUES ('American Diabetes Association');
INSERT INTO data_charities VALUES ('American Enterprise Institute');
INSERT INTO data_charities VALUES ('American Farmland Trust');
INSERT INTO data_charities VALUES ('American Federation of Police and Concerned Citizens');
INSERT INTO data_charities VALUES ('American Forests');
INSERT INTO data_charities VALUES ('American Foundation for Disabled Children');
INSERT INTO data_charities VALUES ('American Heart Association');
INSERT INTO data_charities VALUES ('American Himalayan Foundation');
INSERT INTO data_charities VALUES ('American Humane Association');
INSERT INTO data_charities VALUES ('American India Foundation');
INSERT INTO data_charities VALUES ('American Indian College Fund');
INSERT INTO data_charities VALUES ('American Jewish Joint Distribution Committee');
INSERT INTO data_charities VALUES ('American Jewish World Service');
INSERT INTO data_charities VALUES ('American Kidney Fund');
INSERT INTO data_charities VALUES ('American Leprosy Missions');
INSERT INTO data_charities VALUES ('American Liver Foundation');
INSERT INTO data_charities VALUES ('American Lung Association');
INSERT INTO data_charities VALUES ('American Museum of Natural History');
INSERT INTO data_charities VALUES ('American National Red Cross');
INSERT INTO data_charities VALUES ('American Near East Refugee Aid');
INSERT INTO data_charities VALUES ('American Parkinson Disease Association');
INSERT INTO data_charities VALUES ('American Red Cross');
INSERT INTO data_charities VALUES ('American Refugee Committee');
INSERT INTO data_charities VALUES ('American Rivers');
INSERT INTO data_charities VALUES ('American Society for the Prevention of Cruelty to Animals (ASPCA)');
INSERT INTO data_charities VALUES ('American Stroke Association');
INSERT INTO data_charities VALUES ('Americans United');
INSERT INTO data_charities VALUES ('AmeriCares');
INSERT INTO data_charities VALUES ('AmeriCares Foundation');
INSERT INTO data_charities VALUES ('Amici Camping Charity');
INSERT INTO data_charities VALUES ('Amici del Mondo World Friends Onlus');
INSERT INTO data_charities VALUES ('Amnesty International');
INSERT INTO data_charities VALUES ('Amnesty International - Canadian Section');
INSERT INTO data_charities VALUES ('Amnesty International USA');
INSERT INTO data_charities VALUES ('Amref Health Africa');
INSERT INTO data_charities VALUES ('AMVETS National Service Foundation');
INSERT INTO data_charities VALUES ('Andrew W. Mellon Foundation');
INSERT INTO data_charities VALUES ('Animal Legal Defense Fund');
INSERT INTO data_charities VALUES ('Animal Welfare Institute');
INSERT INTO data_charities VALUES ('Anishinabek Nation 7th Generation Charity');
INSERT INTO data_charities VALUES ('Anti-Defamation League');
INSERT INTO data_charities VALUES ('Appalachian Trail Conservancy');
INSERT INTO data_charities VALUES ('Arlington Academy of Hope');
INSERT INTO data_charities VALUES ('Armed Services YMCA');
INSERT INTO data_charities VALUES ('Army Emergency Relief');
INSERT INTO data_charities VALUES ('Art Gallery of Ontario');
INSERT INTO data_charities VALUES ('Art Institute of Chicago');
INSERT INTO data_charities VALUES ('Artforum Culture Foundation');
INSERT INTO data_charities VALUES ('Arthritis Foundation');
INSERT INTO data_charities VALUES ('Arthritis Research Canada');
INSERT INTO data_charities VALUES ('Arthritis Research Institute of America');
INSERT INTO data_charities VALUES ('Arthritis Society - Ontario Division');
INSERT INTO data_charities VALUES ('Artists For World Peace');
INSERT INTO data_charities VALUES ('Asante Africa Foundation');
INSERT INTO data_charities VALUES ('Asbestos Disease Awareness Organization');
INSERT INTO data_charities VALUES ('Ashesi University Foundation');
INSERT INTO data_charities VALUES ('Ashoka');
INSERT INTO data_charities VALUES ('Asia Society');
INSERT INTO data_charities VALUES ('Asian-German Sports Exchange Program');
INSERT INTO data_charities VALUES ('Aspen Family and Community Network Society');
INSERT INTO data_charities VALUES ('Assiniboine Park Conservancy Inc.');
INSERT INTO data_charities VALUES ('Association for Firefighters and Paramedics');
INSERT INTO data_charities VALUES ('Association L''APPEL');
INSERT INTO data_charities VALUES ('Association of Gospel Rescue Missions');
INSERT INTO data_charities VALUES ('Association on American Indian Affairs');
INSERT INTO data_charities VALUES ('Atlantic Council of Canada / NATO Association of Canada');
INSERT INTO data_charities VALUES ('Atlantic Philanthropies');
INSERT INTO data_charities VALUES ('Atlantic Salmon Federation');
INSERT INTO data_charities VALUES ('AUMOHD');
INSERT INTO data_charities VALUES ('Aunt Leah''s');
INSERT INTO data_charities VALUES ('Australian Doctors for Africa');
INSERT INTO data_charities VALUES ('Autism Speaks');
INSERT INTO data_charities VALUES ('Autism Speaks Canada');
INSERT INTO data_charities VALUES ('AVERT');
INSERT INTO data_charities VALUES ('Avon Foundation');
INSERT INTO data_charities VALUES ('Azim Premji Foundation');
INSERT INTO data_charities VALUES ('Baan Gerda');
INSERT INTO data_charities VALUES ('Bailey House');
INSERT INTO data_charities VALUES ('Banff Centre');
INSERT INTO data_charities VALUES ('BAPS Charities');
INSERT INTO data_charities VALUES ('Barbra Schlifer Commemorative Clinic');
INSERT INTO data_charities VALUES ('Baycrest Centre Foundation');
INSERT INTO data_charities VALUES ('BC Cancer Foundation');
INSERT INTO data_charities VALUES ('BC Children''s Hospital Foundation');
INSERT INTO data_charities VALUES ('BC SPCA');
INSERT INTO data_charities VALUES ('BEADS for Education');
INSERT INTO data_charities VALUES ('Beautiful Store');
INSERT INTO data_charities VALUES ('Beaverbrook Art Gallery');
INSERT INTO data_charities VALUES ('Benevolence International Foundation');
INSERT INTO data_charities VALUES ('Best Friends Animal Society');
INSERT INTO data_charities VALUES ('Beyond Pesticides');
INSERT INTO data_charities VALUES ('Bharat Sevashram Sangha');
INSERT INTO data_charities VALUES ('Big Brothers Big Sisters of America');
INSERT INTO data_charities VALUES ('Big Brothers Big Sisters of Canada');
INSERT INTO data_charities VALUES ('Big Brothers Big Sisters of New York City');
INSERT INTO data_charities VALUES ('Big Brothers Big Sisters Toronto');
INSERT INTO data_charities VALUES ('Big Cat Rescue');
INSERT INTO data_charities VALUES ('Bill & Melinda Gates Foundation');
INSERT INTO data_charities VALUES ('Billy Graham Evangelistic Association');
INSERT INTO data_charities VALUES ('Bishop Strachan School Foundation');
INSERT INTO data_charities VALUES ('Blinded Veterans Association');
INSERT INTO data_charities VALUES ('Bloomberg Philanthropies');
INSERT INTO data_charities VALUES ('Blue Ocean Institute');
INSERT INTO data_charities VALUES ('Blue Sea Philanthropy');
INSERT INTO data_charities VALUES ('Book Aid International');
INSERT INTO data_charities VALUES ('Books For Africa');
INSERT INTO data_charities VALUES ('Borderless World Volunteers');
INSERT INTO data_charities VALUES ('Born Free USA');
INSERT INTO data_charities VALUES ('Born This Way Foundation');
INSERT INTO data_charities VALUES ('Boundless School');
INSERT INTO data_charities VALUES ('Bowery Residents'' Committee');
INSERT INTO data_charities VALUES ('Boy Scouts of America');
INSERT INTO data_charities VALUES ('Boys & Girls Clubs');
INSERT INTO data_charities VALUES ('Boys and Girls Clubs of America');
INSERT INTO data_charities VALUES ('Brain and Behavior Research Foundation');
INSERT INTO data_charities VALUES ('Brain Tumour Foundation of Canada');
INSERT INTO data_charities VALUES ('Brandaid');
INSERT INTO data_charities VALUES ('Brantford Public Library');
INSERT INTO data_charities VALUES ('Bread for the World');
INSERT INTO data_charities VALUES ('Breadline Africa');
INSERT INTO data_charities VALUES ('Breakfast Club of Canada');
INSERT INTO data_charities VALUES ('Breakfast for Learning');
INSERT INTO data_charities VALUES ('Breast Cancer Research Foundation');
INSERT INTO data_charities VALUES ('Breast Cancer Society of Canada');
INSERT INTO data_charities VALUES ('BreastCancer.org');
INSERT INTO data_charities VALUES ('Bremen Overseas Research and Development Association');
INSERT INTO data_charities VALUES ('Bridge2Rwanda');
INSERT INTO data_charities VALUES ('Bridgepoint Foundation');
INSERT INTO data_charities VALUES ('Brien Holden Vision Institute');
INSERT INTO data_charities VALUES ('Bright Focus Foundation');
INSERT INTO data_charities VALUES ('British Columbia Lung Association');
INSERT INTO data_charities VALUES ('British Heart Foundation');
INSERT INTO data_charities VALUES ('Brother''s Brother Foundation');
INSERT INTO data_charities VALUES ('Bruce Trail Conservancy');
INSERT INTO data_charities VALUES ('Buddy Bear Help');
INSERT INTO data_charities VALUES ('Building Educated Leaders for Life (BELL)');
INSERT INTO data_charities VALUES ('Burrito Project');
INSERT INTO data_charities VALUES ('Burroughs Wellcome Fund');
INSERT INTO data_charities VALUES ('Bush Foundation');
INSERT INTO data_charities VALUES ('Cabbagetown Community Arts Centre');
INSERT INTO data_charities VALUES ('CAFOD');
INSERT INTO data_charities VALUES ('Calcutta Rescue');
INSERT INTO data_charities VALUES ('Calouste Gulbenkian Foundation');
INSERT INTO data_charities VALUES ('Camara (social enterprise)');
INSERT INTO data_charities VALUES ('Cambodian Children''s Fund');
INSERT INTO data_charities VALUES ('Cambridge Food Bank');
INSERT INTO data_charities VALUES ('Camp Kirk');
INSERT INTO data_charities VALUES ('Camp Oochigeas');
INSERT INTO data_charities VALUES ('Camp Quality Canada');
INSERT INTO data_charities VALUES ('Camp Trillium');
INSERT INTO data_charities VALUES ('Campaign for Access to Essential Medicines');
INSERT INTO data_charities VALUES ('Campaign for Liberty');
INSERT INTO data_charities VALUES ('Campfire USA');
INSERT INTO data_charities VALUES ('Canadian Bible Society');
INSERT INTO data_charities VALUES ('Canadian Breast Cancer Foundation');
INSERT INTO data_charities VALUES ('Canadian Cancer Society');
INSERT INTO data_charities VALUES ('Canadian Catholic Organization for Development and Peace');
INSERT INTO data_charities VALUES ('Canadian Charity Impact Fund');
INSERT INTO data_charities VALUES ('Canadian Cosmetic Toiletry and Fragrance Association Foundation');
INSERT INTO data_charities VALUES ('Canadian Council of the Blind');
INSERT INTO data_charities VALUES ('Canadian Diabetes Association');
INSERT INTO data_charities VALUES ('Canadian Digestive Health Foundation');
INSERT INTO data_charities VALUES ('Canadian Feed the Children');
INSERT INTO data_charities VALUES ('Canadian Food For Children');
INSERT INTO data_charities VALUES ('Canadian Foodgrains Bank');
INSERT INTO data_charities VALUES ('Canadian Friends of Hebrew University');
INSERT INTO data_charities VALUES ('Canadian Friends of Pearl Children');
INSERT INTO data_charities VALUES ('Canadian Guide Dogs for the Blind');
INSERT INTO data_charities VALUES ('Canadian Hard of Hearing Association Newfoundland and Labrador');
INSERT INTO data_charities VALUES ('Canadian Hearing Society');
INSERT INTO data_charities VALUES ('Canadian Liver Foundation');
INSERT INTO data_charities VALUES ('Canadian Lung Association');
INSERT INTO data_charities VALUES ('Canadian Lutheran World Relief');
INSERT INTO data_charities VALUES ('Canadian Malayalee Association');
INSERT INTO data_charities VALUES ('Canadian Mental Health Association');
INSERT INTO data_charities VALUES ('Canadian National Institute for the Blind');
INSERT INTO data_charities VALUES ('Canadian Olympic Foundation');
INSERT INTO data_charities VALUES ('Canadian Parks and Wilderness Society');
INSERT INTO data_charities VALUES ('Canadian Physicians for Aid and Relief');
INSERT INTO data_charities VALUES ('Canadian Red Cross');
INSERT INTO data_charities VALUES ('Canadian Society for the Prevention of Cruelty to Animals');
INSERT INTO data_charities VALUES ('Canadian Stage');
INSERT INTO data_charities VALUES ('Canadian Tire Jumpstart');
INSERT INTO data_charities VALUES ('Canadian Wildlife Federation');
INSERT INTO data_charities VALUES ('Canadian Women for Women in Afghanistan');
INSERT INTO data_charities VALUES ('Canadian Women''s Foundation');
INSERT INTO data_charities VALUES ('Cancer and Careers');
INSERT INTO data_charities VALUES ('Cancer Federation');
INSERT INTO data_charities VALUES ('Cancer Fund of America');
INSERT INTO data_charities VALUES ('Cancer Recovery Foundation');
INSERT INTO data_charities VALUES ('Cancer Research Institute');
INSERT INTO data_charities VALUES ('Cancer Research Society');
INSERT INTO data_charities VALUES ('Cancer Research UK');
INSERT INTO data_charities VALUES ('CancerCare');
INSERT INTO data_charities VALUES ('CancerCare Manitoba Foundation');
INSERT INTO data_charities VALUES ('Canine Companions for Independence');
INSERT INTO data_charities VALUES ('CanTeen');
INSERT INTO data_charities VALUES ('Canuck Place Children''s Hospice');
INSERT INTO data_charities VALUES ('Canucks for Kids Fund');
INSERT INTO data_charities VALUES ('Carbon Fund');
INSERT INTO data_charities VALUES ('Cardiac Risk in the Young');
INSERT INTO data_charities VALUES ('CARE');
INSERT INTO data_charities VALUES ('Care');
INSERT INTO data_charities VALUES ('CaringBridge');
INSERT INTO data_charities VALUES ('Caritas');
INSERT INTO data_charities VALUES ('Carolina for Kibera');
INSERT INTO data_charities VALUES ('Carter Center');
INSERT INTO data_charities VALUES ('Carthage Foundation');
INSERT INTO data_charities VALUES ('Casa Pia');
INSERT INTO data_charities VALUES ('Catalyst');
INSERT INTO data_charities VALUES ('Catholic Charities USA');
INSERT INTO data_charities VALUES ('Catholic Medical Mission Board');
INSERT INTO data_charities VALUES ('Catholic Medical Missions Board');
INSERT INTO data_charities VALUES ('Catholic Relief Services');
INSERT INTO data_charities VALUES ('CCIVS');
INSERT INTO data_charities VALUES ('CD Howe Institute');
INSERT INTO data_charities VALUES ('Cedars Homes for Children');
INSERT INTO data_charities VALUES ('Center for Biological Diversity');
INSERT INTO data_charities VALUES ('Center for Community Change');
INSERT INTO data_charities VALUES ('Center for Constitutional Rights');
INSERT INTO data_charities VALUES ('Center for Effective Government');
INSERT INTO data_charities VALUES ('Center for Responsive Politics');
INSERT INTO data_charities VALUES ('Centraide of Greater Montreal (United Way Montreal)');
INSERT INTO data_charities VALUES ('Centraide Outaouais');
INSERT INTO data_charities VALUES ('Centraide Quebec et Chaudiere-Appalaches');
INSERT INTO data_charities VALUES ('Central Toronto Community Health Centres');
INSERT INTO data_charities VALUES ('Centre de la Petite Enfance Vire-Crêpe');
INSERT INTO data_charities VALUES ('Centre for Addiction and Mental Health Foundation');
INSERT INTO data_charities VALUES ('Centre for Affordable Water and Sanitation Technology');
INSERT INTO data_charities VALUES ('Centre for International Governance Innovation');
INSERT INTO data_charities VALUES ('Cesvi');
INSERT INTO data_charities VALUES ('Chab Dai');
INSERT INTO data_charities VALUES ('Chabad Lubavitch Youth Organization');
INSERT INTO data_charities VALUES ('Chalice Canada');
INSERT INTO data_charities VALUES ('Charitable Society of the Natives from Catalonia');
INSERT INTO data_charities VALUES ('Charity Intelligence');
INSERT INTO data_charities VALUES ('Charity: Water');
INSERT INTO data_charities VALUES ('Chasdei Tovim Meoros');
INSERT INTO data_charities VALUES ('Chesapeake Bay Foundation');
INSERT INTO data_charities VALUES ('CHF (Canadian Hunger Foundation)');
INSERT INTO data_charities VALUES ('Child Development Institute');
INSERT INTO data_charities VALUES ('Child Find of America');
INSERT INTO data_charities VALUES ('Child Haven International');
INSERT INTO data_charities VALUES ('Child In Need Institute');
INSERT INTO data_charities VALUES ('Child Watch Phuket');
INSERT INTO data_charities VALUES ('Child Welfare League of America');
INSERT INTO data_charities VALUES ('ChildFund');
INSERT INTO data_charities VALUES ('ChildFund International');
INSERT INTO data_charities VALUES ('Childhood Cancer Canada Foundation');
INSERT INTO data_charities VALUES ('Children at Risk');
INSERT INTO data_charities VALUES ('Children in Need');
INSERT INTO data_charities VALUES ('Children International');
INSERT INTO data_charities VALUES ('Children of Peace International');
INSERT INTO data_charities VALUES ('Children of Songea Trust');
INSERT INTO data_charities VALUES ('Children of Uganda');
INSERT INTO data_charities VALUES ('Children''s Aid Foundation');
INSERT INTO data_charities VALUES ('Children''s Book Bank');
INSERT INTO data_charities VALUES ('Children''s Cancer and Blood Foundation');
INSERT INTO data_charities VALUES ('Children''s Cancer Research Fund');
INSERT INTO data_charities VALUES ('Children''s Care International');
INSERT INTO data_charities VALUES ('Children''s Cottage Society of Calgary');
INSERT INTO data_charities VALUES ('Children''s Defense Fund');
INSERT INTO data_charities VALUES ('Children''s Development Trust');
INSERT INTO data_charities VALUES ('Children''s Disaster Services');
INSERT INTO data_charities VALUES ('Children''s Health Foundation');
INSERT INTO data_charities VALUES ('Children''s Hunger Fund');
INSERT INTO data_charities VALUES ('Children''s Liver Disease Foundation');
INSERT INTO data_charities VALUES ('Children''s Miracle Network Hospitals');
INSERT INTO data_charities VALUES ('Children''s National Medical Center');
INSERT INTO data_charities VALUES ('Children''s Wish Foundation Of Canada');
INSERT INTO data_charities VALUES ('Child''s Dream');
INSERT INTO data_charities VALUES ('Child''s Play');
INSERT INTO data_charities VALUES ('ChildVoice International');
INSERT INTO data_charities VALUES ('Choices for Youth');
INSERT INTO data_charities VALUES ('Christian African Relief Trust');
INSERT INTO data_charities VALUES ('Christian Aid');
INSERT INTO data_charities VALUES ('Christian Appalachian Project');
INSERT INTO data_charities VALUES ('Christian Blind Mission');
INSERT INTO data_charities VALUES ('Christian Care Foundation for Children with Disabilities');
INSERT INTO data_charities VALUES ('Christian Children''s Fund of Canada');
INSERT INTO data_charities VALUES ('Christian Foundation for Children and Aging (CFCA)');
INSERT INTO data_charities VALUES ('Christian Mission Service');
INSERT INTO data_charities VALUES ('Christian Relief Services');
INSERT INTO data_charities VALUES ('Christie Refugee Welcome Centre');
INSERT INTO data_charities VALUES ('Christopher and Dana Reeve Foundation');
INSERT INTO data_charities VALUES ('Church World Service');
INSERT INTO data_charities VALUES ('CHUS Foundation');
INSERT INTO data_charities VALUES ('Citizens Advice International');
INSERT INTO data_charities VALUES ('Citizens Against Government Waste');
INSERT INTO data_charities VALUES ('City Harvest');
INSERT INTO data_charities VALUES ('City of Hope/Beckman Research Institute');
INSERT INTO data_charities VALUES ('City Year');
INSERT INTO data_charities VALUES ('CityKidz');
INSERT INTO data_charities VALUES ('CKUA Radio Foundation');
INSERT INTO data_charities VALUES ('Cleft Lip and Palate Association');
INSERT INTO data_charities VALUES ('Cleveland Clinic Foundation');
INSERT INTO data_charities VALUES ('Clinton Foundation');
INSERT INTO data_charities VALUES ('Club des Petits Dejeuners du Quebec (Breakfast Club of Quebec)');
INSERT INTO data_charities VALUES ('Coalition for the Homeless');
INSERT INTO data_charities VALUES ('Coalition to Stop Gun Violence');
INSERT INTO data_charities VALUES ('Coast to Coast Against Cancer');
INSERT INTO data_charities VALUES ('CODE');
INSERT INTO data_charities VALUES ('Collectif Paris-Africa');
INSERT INTO data_charities VALUES ('Colon Cancer Canada');
INSERT INTO data_charities VALUES ('Colorectal Cancer Association of Canada');
INSERT INTO data_charities VALUES ('Comenius Foundation for Child Development');
INSERT INTO data_charities VALUES ('Comic Relief');
INSERT INTO data_charities VALUES ('Committee for Missing Children');
INSERT INTO data_charities VALUES ('Committee to Protect Journalists');
INSERT INTO data_charities VALUES ('Common Cause');
INSERT INTO data_charities VALUES ('Community Care of St. Catharines and Thorold');
INSERT INTO data_charities VALUES ('Community Foundation of Ottawa');
INSERT INTO data_charities VALUES ('Community Living Toronto');
INSERT INTO data_charities VALUES ('Community Network Projects');
INSERT INTO data_charities VALUES ('Compassion Canada');
INSERT INTO data_charities VALUES ('Compassion International');
INSERT INTO data_charities VALUES ('Concern Universal');
INSERT INTO data_charities VALUES ('Concern Worldwide');
INSERT INTO data_charities VALUES ('Conductors Without Borders');
INSERT INTO data_charities VALUES ('Confederation Centre of The Arts');
INSERT INTO data_charities VALUES ('Conservation International Foundation');
INSERT INTO data_charities VALUES ('Coral Reef Alliance');
INSERT INTO data_charities VALUES ('Cornwall Alternative School');
INSERT INTO data_charities VALUES ('Council on Foreign Relations');
INSERT INTO data_charities VALUES ('Counterpart International');
INSERT INTO data_charities VALUES ('Cousteau Society');
INSERT INTO data_charities VALUES ('Covenant House');
INSERT INTO data_charities VALUES ('Creative Commons');
INSERT INTO data_charities VALUES ('Credit Valley Hospital Foundation');
INSERT INTO data_charities VALUES ('Crohn''s & Colitis');
INSERT INTO data_charities VALUES ('Cross International');
INSERT INTO data_charities VALUES ('Crossroads Christian Communications');
INSERT INTO data_charities VALUES ('Crossroads Foundation');
INSERT INTO data_charities VALUES ('Cru');
INSERT INTO data_charities VALUES ('CURE International');
INSERT INTO data_charities VALUES ('Cuso International');
INSERT INTO data_charities VALUES ('Cystic Fibrosis Canada');
INSERT INTO data_charities VALUES ('Cystic Fibrosis Foundation');
INSERT INTO data_charities VALUES ('D.E.L.T.A. Rescue');
INSERT INTO data_charities VALUES ('Daily Bread Food Bank');
INSERT INTO data_charities VALUES ('Daiwa Anglo-Japanese Foundation');
INSERT INTO data_charities VALUES ('Dalai Lama Center for Peace and Education');
INSERT INTO data_charities VALUES ('Dalhousie Medical Research Foundation');
INSERT INTO data_charities VALUES ('Dana-Farber Cancer Institute');
INSERT INTO data_charities VALUES ('Danish Committee for Aid to Afghan Refugees');
INSERT INTO data_charities VALUES ('Danish Refugee Council');
INSERT INTO data_charities VALUES ('Dans La Rue');
INSERT INTO data_charities VALUES ('David and Lucile Packard Foundation');
INSERT INTO data_charities VALUES ('David Foster Foundation');
INSERT INTO data_charities VALUES ('David Suzuki Foundation');
INSERT INTO data_charities VALUES ('Defenders of Wildlife');
INSERT INTO data_charities VALUES ('Delisle Youth Services');
INSERT INTO data_charities VALUES ('DEMIRA');
INSERT INTO data_charities VALUES ('Determined to Develop');
INSERT INTO data_charities VALUES ('Development in Gardening');
INSERT INTO data_charities VALUES ('Development Media International');
INSERT INTO data_charities VALUES ('Dian Fossey Gorilla Fund International');
INSERT INTO data_charities VALUES ('Direct Relief');
INSERT INTO data_charities VALUES ('Direct Relief International');
INSERT INTO data_charities VALUES ('Disabled American Veterans');
INSERT INTO data_charities VALUES ('Disabled American Veterans Charitable Service Trust');
INSERT INTO data_charities VALUES ('Discovery House');
INSERT INTO data_charities VALUES ('Distress Centre Calgary');
INSERT INTO data_charities VALUES ('Distress Centres of Toronto');
INSERT INTO data_charities VALUES ('Dixon Hall');
INSERT INTO data_charities VALUES ('DKT International');
INSERT INTO data_charities VALUES ('Do Something');
INSERT INTO data_charities VALUES ('DOCARE');
INSERT INTO data_charities VALUES ('Doctors of the World');
INSERT INTO data_charities VALUES ('Doctors Without Borders');
INSERT INTO data_charities VALUES ('Doris Day Animal League');
INSERT INTO data_charities VALUES ('Dr. George-L.-Dumont Hospital Foundation');
INSERT INTO data_charities VALUES ('Dr. H. Bliss Murphy Cancer Care Foundation');
INSERT INTO data_charities VALUES ('Dream Center');
INSERT INTO data_charities VALUES ('Dreams Take Flight Canada');
INSERT INTO data_charities VALUES ('Dress for Success');
INSERT INTO data_charities VALUES ('Drosos Foundation');
INSERT INTO data_charities VALUES ('Ducere Foundation');
INSERT INTO data_charities VALUES ('Ducks Unlimited Canada');
INSERT INTO data_charities VALUES ('Dying With Dignity');
INSERT INTO data_charities VALUES ('Earth Island Institute');
INSERT INTO data_charities VALUES ('Earthjustice');
INSERT INTO data_charities VALUES ('East Africa Medical Assistance Foundation');
INSERT INTO data_charities VALUES ('East African Center for the Empowerment of Women and Children');
INSERT INTO data_charities VALUES ('East Meets West');
INSERT INTO data_charities VALUES ('East York Learning Experience');
INSERT INTO data_charities VALUES ('Easter Seals');
INSERT INTO data_charities VALUES ('EcoAgriculture Partners');
INSERT INTO data_charities VALUES ('Ecojustice');
INSERT INTO data_charities VALUES ('Ecotecture: Centre for Ecological Art & Architecture');
INSERT INTO data_charities VALUES ('Ecotrust Canada');
INSERT INTO data_charities VALUES ('Eden Food for Change');
INSERT INTO data_charities VALUES ('Edhi Foundation');
INSERT INTO data_charities VALUES ('Education For All Children');
INSERT INTO data_charities VALUES ('effect:hope');
INSERT INTO data_charities VALUES ('Elephants');
INSERT INTO data_charities VALUES ('Elizabeth Fry Society of Calgary');
INSERT INTO data_charities VALUES ('Emergency (NGO)');
INSERT INTO data_charities VALUES ('Emergency Nutrition Network');
INSERT INTO data_charities VALUES ('Emmaus (charity)');
INSERT INTO data_charities VALUES ('Endeavour recycled clothing');
INSERT INTO data_charities VALUES ('Engineers Without Borders');
INSERT INTO data_charities VALUES ('Environmental Defence Canada');
INSERT INTO data_charities VALUES ('Environmental Defense');
INSERT INTO data_charities VALUES ('Environmental Defense Fund');
INSERT INTO data_charities VALUES ('EPIC Society');
INSERT INTO data_charities VALUES ('Epilepsy Foundation');
INSERT INTO data_charities VALUES ('Epilepsy Outlook');
INSERT INTO data_charities VALUES ('Eppley Foundation');
INSERT INTO data_charities VALUES ('Equality Now');
INSERT INTO data_charities VALUES ('Equity for Africa');
INSERT INTO data_charities VALUES ('ERDO');
INSERT INTO data_charities VALUES ('Escarpment Biosphere Conservancy');
INSERT INTO data_charities VALUES ('Evangel Hall Mission');
INSERT INTO data_charities VALUES ('Eva''s Initiatives');
INSERT INTO data_charities VALUES ('Evelyn Douglin Center');
INSERT INTO data_charities VALUES ('Evergreen');
INSERT INTO data_charities VALUES ('Evidence Aid');
INSERT INTO data_charities VALUES ('Family Care International');
INSERT INTO data_charities VALUES ('Farm Aid');
INSERT INTO data_charities VALUES ('Farm Radio International');
INSERT INTO data_charities VALUES ('Farm Sanctuary');
INSERT INTO data_charities VALUES ('Farmers and Hunters Feeding the Hungry');
INSERT INTO data_charities VALUES ('Federation CJA');
INSERT INTO data_charities VALUES ('Feed My People');
INSERT INTO data_charities VALUES ('Feed My Starving Children');
INSERT INTO data_charities VALUES ('Feed Nova Scotia');
INSERT INTO data_charities VALUES ('FEED Projects');
INSERT INTO data_charities VALUES ('Feed the Children');
INSERT INTO data_charities VALUES ('Feeding America');
INSERT INTO data_charities VALUES ('FH Canada');
INSERT INTO data_charities VALUES ('Fight Hunger');
INSERT INTO data_charities VALUES ('FilmAid International');
INSERT INTO data_charities VALUES ('FINCA Canada');
INSERT INTO data_charities VALUES ('FINCA International');
INSERT INTO data_charities VALUES ('Firefighters'' Charitable Foundation');
INSERT INTO data_charities VALUES ('Firelight Foundation');
INSERT INTO data_charities VALUES ('First Candle');
INSERT INTO data_charities VALUES ('Fistula Foundation');
INSERT INTO data_charities VALUES ('Focus Humanitarian Assistance');
INSERT INTO data_charities VALUES ('Focus On The Family Canada');
INSERT INTO data_charities VALUES ('Fondation 24H Tremblant');
INSERT INTO data_charities VALUES ('Fondation Charles-Bruneau');
INSERT INTO data_charities VALUES ('Fondation CHU Sainte-Justine (Sainte-Justine UHC Foundation)');
INSERT INTO data_charities VALUES ('Fondation de l''Hôpital Maisonneuve-Rosemont');
INSERT INTO data_charities VALUES ('Fondation des Étoiles');
INSERT INTO data_charities VALUES ('Fondation du CHUM (Centre Hospitalier de l''Université de Montréal)');
INSERT INTO data_charities VALUES ('Fondation du CHUQ');
INSERT INTO data_charities VALUES ('Fondation du CSSS de Gatineau');
INSERT INTO data_charities VALUES ('Fondation MIRA');
INSERT INTO data_charities VALUES ('Fondation Québécoise du Cancer');
INSERT INTO data_charities VALUES ('Food & Water Watch');
INSERT INTO data_charities VALUES ('Food Allergy Initiative');
INSERT INTO data_charities VALUES ('Food Bank for New York City');
INSERT INTO data_charities VALUES ('Food Banks Canada');
INSERT INTO data_charities VALUES ('Food Depot Alimentaire');
INSERT INTO data_charities VALUES ('Food for Life Canada');
INSERT INTO data_charities VALUES ('Food for the Hungry');
INSERT INTO data_charities VALUES ('Food for the Poor');
INSERT INTO data_charities VALUES ('FoodShare');
INSERT INTO data_charities VALUES ('Ford Foundation');
INSERT INTO data_charities VALUES ('Fort York Food Bank');
INSERT INTO data_charities VALUES ('Foundation Fighting Blindness');
INSERT INTO data_charities VALUES ('Foundation for Child Development');
INSERT INTO data_charities VALUES ('Foundation for International Medical Relief of Children');
INSERT INTO data_charities VALUES ('Fraser Institute');
INSERT INTO data_charities VALUES ('Fred Victor Centre');
INSERT INTO data_charities VALUES ('Free the Children');
INSERT INTO data_charities VALUES ('Fremont Area Community Foundation');
INSERT INTO data_charities VALUES ('Fresh Start Recovery Centre');
INSERT INTO data_charities VALUES ('Friedrich Ebert Stiftung');
INSERT INTO data_charities VALUES ('Friends of Animals');
INSERT INTO data_charities VALUES ('Friends of Conservation – Friends of the Masai Mara');
INSERT INTO data_charities VALUES ('Friends of the Canadian Museum for Human Rights');
INSERT INTO data_charities VALUES ('Friends of the Moncton Hospital Foundation');
INSERT INTO data_charities VALUES ('Friends-International');
INSERT INTO data_charities VALUES ('Fritt Ord');
INSERT INTO data_charities VALUES ('Frontier College');
INSERT INTO data_charities VALUES ('Fund for Reconciliation and Development');
INSERT INTO data_charities VALUES ('Fundación El Hacedor');
INSERT INTO data_charities VALUES ('Fundacion Manantiales');
INSERT INTO data_charities VALUES ('Fung Loy Kok Institute of Taoism');
INSERT INTO data_charities VALUES ('Furniture Bank');
INSERT INTO data_charities VALUES ('G(irls)20');
INSERT INTO data_charities VALUES ('Garfield Weston Foundation');
INSERT INTO data_charities VALUES ('Gates of Mercy');
INSERT INTO data_charities VALUES ('GEFEK');
INSERT INTO data_charities VALUES ('George Brown College Foundation');
INSERT INTO data_charities VALUES ('George Hull Centre');
INSERT INTO data_charities VALUES ('George S. and Dolores Dore Eccles Foundation');
INSERT INTO data_charities VALUES ('Georgian Bay Land Trust');
INSERT INTO data_charities VALUES ('German Foundation for World Population');
INSERT INTO data_charities VALUES ('Ghanaian Mothers’ Hope');
INSERT INTO data_charities VALUES ('Gideons International In Canada');
INSERT INTO data_charities VALUES ('Gill Foundation');
INSERT INTO data_charities VALUES ('Girl Scouts');
INSERT INTO data_charities VALUES ('Girl Scouts of the USA');
INSERT INTO data_charities VALUES ('GiveIndia');
INSERT INTO data_charities VALUES ('Glenbow Museum');
INSERT INTO data_charities VALUES ('Glenbow Ranch Park Foundation');
INSERT INTO data_charities VALUES ('Global Brigades');
INSERT INTO data_charities VALUES ('Global Classrooms');
INSERT INTO data_charities VALUES ('Global Footsteps');
INSERT INTO data_charities VALUES ('Global Fund for Women');
INSERT INTO data_charities VALUES ('Global Greengrants Fund');
INSERT INTO data_charities VALUES ('Global Medic');
INSERT INTO data_charities VALUES ('Global Sanitation Fund');
INSERT INTO data_charities VALUES ('Global Village Foundation');
INSERT INTO data_charities VALUES ('GlobalGiving');
INSERT INTO data_charities VALUES ('Golden West Humanitarian Foundation');
INSERT INTO data_charities VALUES ('Good 360');
INSERT INTO data_charities VALUES ('Good Samaritan Society');
INSERT INTO data_charities VALUES ('Good Shepherd Centre Hamilton');
INSERT INTO data_charities VALUES ('Good Shepherd Ministries');
INSERT INTO data_charities VALUES ('GoodWeave International');
INSERT INTO data_charities VALUES ('Goodwill');
INSERT INTO data_charities VALUES ('Goodwill Industries');
INSERT INTO data_charities VALUES ('Gordon and Betty Moore Foundation');
INSERT INTO data_charities VALUES ('Gorilla Doctors');
INSERT INTO data_charities VALUES ('Gospel For Asia');
INSERT INTO data_charities VALUES ('Government Accountability Project');
INSERT INTO data_charities VALUES ('Grand Défi Pierre Lavoie');
INSERT INTO data_charities VALUES ('Grand Falls Regional Food Bank');
INSERT INTO data_charities VALUES ('Grassroots Business Fund');
INSERT INTO data_charities VALUES ('Green Belt Movement International');
INSERT INTO data_charities VALUES ('Greenpeace');
INSERT INTO data_charities VALUES ('Grocery Foundation');
INSERT INTO data_charities VALUES ('Group Seven Children''s Foundation');
INSERT INTO data_charities VALUES ('H2O for Life');
INSERT INTO data_charities VALUES ('Habitat for Humanity');
INSERT INTO data_charities VALUES ('Halton Learning Foundation');
INSERT INTO data_charities VALUES ('Hamilton Health Sciences Foundation');
INSERT INTO data_charities VALUES ('Hammer Band - From Violence to Violins');
INSERT INTO data_charities VALUES ('Handicap International');
INSERT INTO data_charities VALUES ('Hands on Network');
INSERT INTO data_charities VALUES ('Hands on Tzedakah');
INSERT INTO data_charities VALUES ('Hare Krishna Food for Life');
INSERT INTO data_charities VALUES ('Harvest House Ministries');
INSERT INTO data_charities VALUES ('HEAL Africa USA');
INSERT INTO data_charities VALUES ('Heal the World Foundation');
INSERT INTO data_charities VALUES ('Health Care Foundation of St. John''s');
INSERT INTO data_charities VALUES ('Health Partners International of Canada');
INSERT INTO data_charities VALUES ('Health Sciences Centre Foundation');
INSERT INTO data_charities VALUES ('HealthCare Volunteer');
INSERT INTO data_charities VALUES ('Healthy Minds Canada');
INSERT INTO data_charities VALUES ('Hearing Health Foundation');
INSERT INTO data_charities VALUES ('Heart and Stroke Foundation');
INSERT INTO data_charities VALUES ('Heart to Heart International');
INSERT INTO data_charities VALUES ('Heartbeat International (charity)');
INSERT INTO data_charities VALUES ('Heifer International');
INSERT INTO data_charities VALUES ('Helen Keller International');
INSERT INTO data_charities VALUES ('Help Eliminate Disease and Addiction Canada');
INSERT INTO data_charities VALUES ('HELP Lesotho');
INSERT INTO data_charities VALUES ('HelpAge International');
INSERT INTO data_charities VALUES ('Helping Children Worldwide');
INSERT INTO data_charities VALUES ('HELVETAS Swiss Intercooperation');
INSERT INTO data_charities VALUES ('Heritage Action');
INSERT INTO data_charities VALUES ('Heritage for the Blind');
INSERT INTO data_charities VALUES ('Hispanic Scholarship Fund');
INSERT INTO data_charities VALUES ('Hockey Hall of Fame');
INSERT INTO data_charities VALUES ('Holland Bloorview Kids Rehabilitation Hospital Foundation');
INSERT INTO data_charities VALUES ('Holt International Children''s Services');
INSERT INTO data_charities VALUES ('Homes First Society - Foundation');
INSERT INTO data_charities VALUES ('Homeshare');
INSERT INTO data_charities VALUES ('Hope Air');
INSERT INTO data_charities VALUES ('HOPE International Development Agency');
INSERT INTO data_charities VALUES ('Hope Mission');
INSERT INTO data_charities VALUES ('Hope Through Health');
INSERT INTO data_charities VALUES ('Horizon Housing Society');
INSERT INTO data_charities VALUES ('Howard Hughes Medical Institute');
INSERT INTO data_charities VALUES ('Human Concern International');
INSERT INTO data_charities VALUES ('Human Rights Campaign');
INSERT INTO data_charities VALUES ('Human Rights Watch');
INSERT INTO data_charities VALUES ('Human Rights Watch (HRW)');
INSERT INTO data_charities VALUES ('Humane Farming Association');
INSERT INTO data_charities VALUES ('Humane Society of the United States');
INSERT INTO data_charities VALUES ('Humanitarian Coalition');
INSERT INTO data_charities VALUES ('Humanity First');
INSERT INTO data_charities VALUES ('Hungry For Life International');
INSERT INTO data_charities VALUES ('Huntington Society of Canada');
INSERT INTO data_charities VALUES ('Huntington''s Disease Society of America');
INSERT INTO data_charities VALUES ('IHH (Turkish NGO)');
INSERT INTO data_charities VALUES ('Illinois Prairie Community Foundation');
INSERT INTO data_charities VALUES ('Imagine No Malaria');
INSERT INTO data_charities VALUES ('Imam Khomeini Relief Foundation');
INSERT INTO data_charities VALUES ('IMPACT (organisation)');
INSERT INTO data_charities VALUES ('Impact Society');
INSERT INTO data_charities VALUES ('Indego Africa Project');
INSERT INTO data_charities VALUES ('Indspire');
INSERT INTO data_charities VALUES ('Ingamo Hall Friendship Centre');
INSERT INTO data_charities VALUES ('Inn From The Cold Society');
INSERT INTO data_charities VALUES ('Inner City Home of Sudbury');
INSERT INTO data_charities VALUES ('Inter Pares');
INSERT INTO data_charities VALUES ('InterHealth');
INSERT INTO data_charities VALUES ('International Alert');
INSERT INTO data_charities VALUES ('International Centre of Insect Physiology and Ecology');
INSERT INTO data_charities VALUES ('International Childcare Trust');
INSERT INTO data_charities VALUES ('International Children Assistance Network');
INSERT INTO data_charities VALUES ('International Crane Foundation');
INSERT INTO data_charities VALUES ('International Development and Relief Foundation');
INSERT INTO data_charities VALUES ('International Federation of Red Cross and Red Crescent Societies');
INSERT INTO data_charities VALUES ('International Fellowship of Christians and Jews of Canada');
INSERT INTO data_charities VALUES ('International Foundation for Electoral Systems');
INSERT INTO data_charities VALUES ('International Fund for Animal Welfare');
INSERT INTO data_charities VALUES ('International Humanitarian City');
INSERT INTO data_charities VALUES ('International Literacy Foundation');
INSERT INTO data_charities VALUES ('International Marinelife Alliance');
INSERT INTO data_charities VALUES ('International Medical Corps');
INSERT INTO data_charities VALUES ('International Planned Parenthood Federation');
INSERT INTO data_charities VALUES ('International Republican Institute');
INSERT INTO data_charities VALUES ('International Rescue Committee');
INSERT INTO data_charities VALUES ('International Rescue Corps');
INSERT INTO data_charities VALUES ('International Resources for the Improvement of Sight');
INSERT INTO data_charities VALUES ('International Social Service');
INSERT INTO data_charities VALUES ('International Trachoma Initiative');
INSERT INTO data_charities VALUES ('International Union for Conservation of Nature');
INSERT INTO data_charities VALUES ('International Work Group for Indigenous Affairs');
INSERT INTO data_charities VALUES ('Interval House');
INSERT INTO data_charities VALUES ('Invisible Children');
INSERT INTO data_charities VALUES ('IRCOM');
INSERT INTO data_charities VALUES ('Islamic Relief');
INSERT INTO data_charities VALUES ('Islamic Relief Canada');
INSERT INTO data_charities VALUES ('ISSO Seva');
INSERT INTO data_charities VALUES ('IWK Health Centre Foundation');
INSERT INTO data_charities VALUES ('J. Paul Getty Trust');
INSERT INTO data_charities VALUES ('Jain Foundation');
INSERT INTO data_charities VALUES ('Jane Goodall Institute');
INSERT INTO data_charities VALUES ('Janeway Children''s Hospital Foundation');
INSERT INTO data_charities VALUES ('Jays Care Foundation');
INSERT INTO data_charities VALUES ('JEN (charity)');
INSERT INTO data_charities VALUES ('Jesse''s Journey');
INSERT INTO data_charities VALUES ('Jessie''s, The June Callwood Centre');
INSERT INTO data_charities VALUES ('Jesuit Refugee Service');
INSERT INTO data_charities VALUES ('Jewish National Fund of Canada');
INSERT INTO data_charities VALUES ('JFK Center for Performing Arts');
INSERT INTO data_charities VALUES ('Jimmy Fund (Dana-Farber Cancer Institute)');
INSERT INTO data_charities VALUES ('John A. Hartford Foundation');
INSERT INTO data_charities VALUES ('John D. and Catherine T. MacArthur Foundation');
INSERT INTO data_charities VALUES ('John Dau Foundation');
INSERT INTO data_charities VALUES ('Judicial Watch');
INSERT INTO data_charities VALUES ('Jump Math');
INSERT INTO data_charities VALUES ('Junior Achievement');
INSERT INTO data_charities VALUES ('Junior Achievement Canada');
INSERT INTO data_charities VALUES ('Just a Drop');
INSERT INTO data_charities VALUES ('Just for Kids Foundation');
INSERT INTO data_charities VALUES ('Juvenile Diabetes Research Foundation');
INSERT INTO data_charities VALUES ('Juvenile Diabetes Research Foundation Canada');
INSERT INTO data_charities VALUES ('KaBoom!');
INSERT INTO data_charities VALUES ('Kahrizak Charity Foundation');
INSERT INTO data_charities VALUES ('Kamehameha Schools');
INSERT INTO data_charities VALUES ('Kawartha Food Share');
INSERT INTO data_charities VALUES ('Keep America Beautiful');
INSERT INTO data_charities VALUES ('Kennedy House Youth Services');
INSERT INTO data_charities VALUES ('Kenora Fellowship Centre');
INSERT INTO data_charities VALUES ('Kensington Foundation');
INSERT INTO data_charities VALUES ('Kenya Education Fund');
INSERT INTO data_charities VALUES ('Khemara (NGO)');
INSERT INTO data_charities VALUES ('KickStart International');
INSERT INTO data_charities VALUES ('Kidney Foundation of Canada');
INSERT INTO data_charities VALUES ('Kids Help Phone');
INSERT INTO data_charities VALUES ('Kids.Now');
INSERT INTO data_charities VALUES ('KidsRights Foundation');
INSERT INTO data_charities VALUES ('Kimmie Weeks');
INSERT INTO data_charities VALUES ('Kin Canada');
INSERT INTO data_charities VALUES ('Kinderstern');
INSERT INTO data_charities VALUES ('Kinsmen Care Foundation');
INSERT INTO data_charities VALUES ('Kinsmen Foundation');
INSERT INTO data_charities VALUES ('Kisumu Rendezvous SUPAKEN');
INSERT INTO data_charities VALUES ('Kiva');
INSERT INTO data_charities VALUES ('Knut and Alice Wallenberg Foundation');
INSERT INTO data_charities VALUES ('Konrad Adenauer Foundation');
INSERT INTO data_charities VALUES ('Kupas Hachesed Meoroth');
INSERT INTO data_charities VALUES ('La Caixa');
INSERT INTO data_charities VALUES ('Laidlaw Foundation');
INSERT INTO data_charities VALUES ('Lanckoronski Foundation');
INSERT INTO data_charities VALUES ('Landesa');
INSERT INTO data_charities VALUES ('Langham Partnership');
INSERT INTO data_charities VALUES ('Last Mile Health');
INSERT INTO data_charities VALUES ('Lattitude Global Volunteering');
INSERT INTO data_charities VALUES ('Law Enforcement Legal Defense Fund');
INSERT INTO data_charities VALUES ('LDS Humanitarian Services');
INSERT INTO data_charities VALUES ('League of Women Voters');
INSERT INTO data_charities VALUES ('Learning Enrichment Foundation');
INSERT INTO data_charities VALUES ('Learning for Life UK');
INSERT INTO data_charities VALUES ('Legal Education Foundation');
INSERT INTO data_charities VALUES ('Lepra');
INSERT INTO data_charities VALUES ('Leprosy Relief Canada');
INSERT INTO data_charities VALUES ('Les Grands Ballets Canadiens de Montreal');
INSERT INTO data_charities VALUES ('Leucan');
INSERT INTO data_charities VALUES ('Leukemia & Lymphoma Society');
INSERT INTO data_charities VALUES ('Leukemia & Lymphoma Society of Canada');
INSERT INTO data_charities VALUES ('Lewa Wildlife Conservancy USA');
INSERT INTO data_charities VALUES ('Li Ka Shing Foundation');
INSERT INTO data_charities VALUES ('Libra Foundation');
INSERT INTO data_charities VALUES ('Life Outreach International');
INSERT INTO data_charities VALUES ('Lifeline Express');
INSERT INTO data_charities VALUES ('Lilly Endowment');
INSERT INTO data_charities VALUES ('Lions Clubs International');
INSERT INTO data_charities VALUES ('Lions Foundation of Canada Dog Guides');
INSERT INTO data_charities VALUES ('Lions Gate Hospital Foundation');
INSERT INTO data_charities VALUES ('List of charities accused of ties to terrorism');
INSERT INTO data_charities VALUES ('Little Baby Face Foundation');
INSERT INTO data_charities VALUES ('Little Warriors');
INSERT INTO data_charities VALUES ('Livestrong');
INSERT INTO data_charities VALUES ('Lloydminster Region Health Foundation');
INSERT INTO data_charities VALUES ('L''Oeuvre Léger');
INSERT INTO data_charities VALUES ('London Health Sciences Foundation');
INSERT INTO data_charities VALUES ('Lookout Emergency Aid Society');
INSERT INTO data_charities VALUES ('Loran Scholars Foundation');
INSERT INTO data_charities VALUES ('LPGA (Ladies Professional Golf Association)');
INSERT INTO data_charities VALUES ('Lubuto Library Partners');
INSERT INTO data_charities VALUES ('Lupus Research Institute');
INSERT INTO data_charities VALUES ('Lutheran Services in America');
INSERT INTO data_charities VALUES ('Lutheran World Relief');
INSERT INTO data_charities VALUES ('Luz A Salento Foundation');
INSERT INTO data_charities VALUES ('Lymphoma Canada');
INSERT INTO data_charities VALUES ('Maasai Girls Education Fund');
INSERT INTO data_charities VALUES ('MADA Community Center');
INSERT INTO data_charities VALUES ('Maimonides Educational Foundation');
INSERT INTO data_charities VALUES ('Make-A-Wish Foundation');
INSERT INTO data_charities VALUES ('Malteser International');
INSERT INTO data_charities VALUES ('Malvern Rouge Valley Youth Services');
INSERT INTO data_charities VALUES ('Mangrove Fund');
INSERT INTO data_charities VALUES ('Manning Foundation');
INSERT INTO data_charities VALUES ('MAP International');
INSERT INTO data_charities VALUES ('March of Dimes');
INSERT INTO data_charities VALUES ('March of Dimes Canada');
INSERT INTO data_charities VALUES ('Marie Stopes International');
INSERT INTO data_charities VALUES ('Marine Mammal Center');
INSERT INTO data_charities VALUES ('Marine Toys for Tots Foundation');
INSERT INTO data_charities VALUES ('Markham Stouffville Hospital Foundation');
INSERT INTO data_charities VALUES ('MaRS Discovery District');
INSERT INTO data_charities VALUES ('Maryland Salem Children''s Trust');
INSERT INTO data_charities VALUES ('Massoud Foundation');
INSERT INTO data_charities VALUES ('Material World Charitable Foundation');
INSERT INTO data_charities VALUES ('Matthews House Hospice');
INSERT INTO data_charities VALUES ('Maybach Foundation');
INSERT INTO data_charities VALUES ('Mayo Clinic');
INSERT INTO data_charities VALUES ('Mayo Foundation');
INSERT INTO data_charities VALUES ('Mazon Canada');
INSERT INTO data_charities VALUES ('McGill University');
INSERT INTO data_charities VALUES ('McGill University Health Centre Foundation');
INSERT INTO data_charities VALUES ('McKnight Foundation');
INSERT INTO data_charities VALUES ('McMaster University');
INSERT INTO data_charities VALUES ('MDG Achievement Fund');
INSERT INTO data_charities VALUES ('Meal-a-Day Fund');
INSERT INTO data_charities VALUES ('Médecins du Monde');
INSERT INTO data_charities VALUES ('Médecins Sans Frontières (Doctors Without Borders)');
INSERT INTO data_charities VALUES ('Media Research');
INSERT INTO data_charities VALUES ('Medical Bridges');
INSERT INTO data_charities VALUES ('Medical camp in the remote village of Jharkhand, India');
INSERT INTO data_charities VALUES ('Medical Care Development International');
INSERT INTO data_charities VALUES ('Medical Education for South African Blacks');
INSERT INTO data_charities VALUES ('Medical Missions for Children');
INSERT INTO data_charities VALUES ('Medical Teams International');
INSERT INTO data_charities VALUES ('Medicine for Mali');
INSERT INTO data_charities VALUES ('Medicus Mundi International');
INSERT INTO data_charities VALUES ('Memorial Sloan Kettering Cancer Center');
INSERT INTO data_charities VALUES ('Memorial University of Newfoundland');
INSERT INTO data_charities VALUES ('Mercy Corps');
INSERT INTO data_charities VALUES ('Mercy International Foundation');
INSERT INTO data_charities VALUES ('Mercy Ships');
INSERT INTO data_charities VALUES ('Mercy Ships Canada');
INSERT INTO data_charities VALUES ('Meri Toksave');
INSERT INTO data_charities VALUES ('Metropolitan Museum of Art');
INSERT INTO data_charities VALUES ('Michael and Susan Dell Foundation');
INSERT INTO data_charities VALUES ('Mines Advisory Group');
INSERT INTO data_charities VALUES ('miraclefeet');
INSERT INTO data_charities VALUES ('Mississauga Food Bank');
INSERT INTO data_charities VALUES ('MLSE Foundation');
INSERT INTO data_charities VALUES ('Modest Needs');
INSERT INTO data_charities VALUES ('Mohammed bin Rashid Al Maktoum Foundation');
INSERT INTO data_charities VALUES ('Moisson Montreal');
INSERT INTO data_charities VALUES ('Momentum Community Economic Development Society');
INSERT INTO data_charities VALUES ('Monterey Bay Aquarium');
INSERT INTO data_charities VALUES ('Moorelands Community Services');
INSERT INTO data_charities VALUES ('Mother Teresa Middle School');
INSERT INTO data_charities VALUES ('Mothers Against Drunk Driving (MADD Canada)');
INSERT INTO data_charities VALUES ('Mothers'' Union');
INSERT INTO data_charities VALUES ('Mothers2mothers');
INSERT INTO data_charities VALUES ('mothers2mothers International');
INSERT INTO data_charities VALUES ('Motorcycle Outreach');
INSERT INTO data_charities VALUES ('Mount Sinai');
INSERT INTO data_charities VALUES ('Movember');
INSERT INTO data_charities VALUES ('Movimento Sviluppo e Pace');
INSERT INTO data_charities VALUES ('Moyer Foundation');
INSERT INTO data_charities VALUES ('Mozilla');
INSERT INTO data_charities VALUES ('Msizi Africa');
INSERT INTO data_charities VALUES ('Mukti');
INSERT INTO data_charities VALUES ('Multiple Sclerosis Society of Canada');
INSERT INTO data_charities VALUES ('Murchison Foundation');
INSERT INTO data_charities VALUES ('Muscular Dystrophy Canada');
INSERT INTO data_charities VALUES ('Museum for African Art');
INSERT INTO data_charities VALUES ('Museum of Fine Arts, Boston');
INSERT INTO data_charities VALUES ('Museum of Modern Art');
INSERT INTO data_charities VALUES ('Musicians without Borders');
INSERT INTO data_charities VALUES ('Musikhjälpen');
INSERT INTO data_charities VALUES ('Muslim Aid');
INSERT INTO data_charities VALUES ('NAACP');
INSERT INTO data_charities VALUES ('Nanny Angel Network');
INSERT INTO data_charities VALUES ('National 4-H Council');
INSERT INTO data_charities VALUES ('National Arts Centre Foundation');
INSERT INTO data_charities VALUES ('National Audubon Society');
INSERT INTO data_charities VALUES ('National Ballet of Canada');
INSERT INTO data_charities VALUES ('National Center for Missing and Exploited Children');
INSERT INTO data_charities VALUES ('National Children''s Cancer Society');
INSERT INTO data_charities VALUES ('National Council of YMCAs of the USA');
INSERT INTO data_charities VALUES ('National Council on Aging');
INSERT INTO data_charities VALUES ('National Fallen Firefighters Foundation');
INSERT INTO data_charities VALUES ('National FFA Foundation');
INSERT INTO data_charities VALUES ('National Geographic Society');
INSERT INTO data_charities VALUES ('National Law Enforcement Officers Memorial Fund');
INSERT INTO data_charities VALUES ('National Multiple Sclerosis Society');
INSERT INTO data_charities VALUES ('National Network to End Domestic Violence');
INSERT INTO data_charities VALUES ('National Organization for Women');
INSERT INTO data_charities VALUES ('National Park Foundation');
INSERT INTO data_charities VALUES ('National Public Radio - NPR');
INSERT INTO data_charities VALUES ('National Relief Charities');
INSERT INTO data_charities VALUES ('National Service Dogs');
INSERT INTO data_charities VALUES ('Natural Resources Defense Council');
INSERT INTO data_charities VALUES ('Nature Canada');
INSERT INTO data_charities VALUES ('Nature Conservancy');
INSERT INTO data_charities VALUES ('Near East Foundation');
INSERT INTO data_charities VALUES ('Nelson Mandela Children''s Fund');
INSERT INTO data_charities VALUES ('Nemours Foundation');
INSERT INTO data_charities VALUES ('Nepal Youth Foundation');
INSERT INTO data_charities VALUES ('Netherlands Leprosy Relief');
INSERT INTO data_charities VALUES ('Network for Good');
INSERT INTO data_charities VALUES ('New Circles Community Services');
INSERT INTO data_charities VALUES ('New York Public Library');
INSERT INTO data_charities VALUES ('Newfoundland and Labrador Lung Association');
INSERT INTO data_charities VALUES ('Nimmagadda Foundation');
INSERT INTO data_charities VALUES ('Nippon Foundation');
INSERT INTO data_charities VALUES ('Nobel Foundation');
INSERT INTO data_charities VALUES ('Norwegian Mission Alliance');
INSERT INTO data_charities VALUES ('Nothing But Nets');
INSERT INTO data_charities VALUES ('NPH USA');
INSERT INTO data_charities VALUES ('Nurturing Minds');
INSERT INTO data_charities VALUES ('NYRR Foundation');
INSERT INTO data_charities VALUES ('Oaktree (foundation)');
INSERT INTO data_charities VALUES ('Oakville Hospital Foundation');
INSERT INTO data_charities VALUES ('OASIS Institute');
INSERT INTO data_charities VALUES ('Ocean Conservancy');
INSERT INTO data_charities VALUES ('Oceana');
INSERT INTO data_charities VALUES ('Omar-Sultan Foundation');
INSERT INTO data_charities VALUES ('ONE');
INSERT INTO data_charities VALUES ('One Drop Foundation');
INSERT INTO data_charities VALUES ('ONS Foundation');
INSERT INTO data_charities VALUES ('Ontario Society for the Prevention of Cruelty to Animals');
INSERT INTO data_charities VALUES ('Opera Atelier');
INSERT INTO data_charities VALUES ('Operation Blessing International');
INSERT INTO data_charities VALUES ('Operation Blessing International Relief');
INSERT INTO data_charities VALUES ('Operation Blessing International Relief & Development');
INSERT INTO data_charities VALUES ('Opération Enfant Soleil');
INSERT INTO data_charities VALUES ('Operation Eyesight Universal');
INSERT INTO data_charities VALUES ('Operation Smile');
INSERT INTO data_charities VALUES ('Operation USA');
INSERT INTO data_charities VALUES ('Opportunities for the Disabled Foundation');
INSERT INTO data_charities VALUES ('Opportunity International');
INSERT INTO data_charities VALUES ('Opportunity International Canada');
INSERT INTO data_charities VALUES ('Orbis Canada');
INSERT INTO data_charities VALUES ('Orbis International');
INSERT INTO data_charities VALUES ('Orchestre Symphonique de Montreal');
INSERT INTO data_charities VALUES ('Orchestre Symphonique De Quebec');
INSERT INTO data_charities VALUES ('Ormiston Trust');
INSERT INTO data_charities VALUES ('Orphans International');
INSERT INTO data_charities VALUES ('Osteoporosis Canada');
INSERT INTO data_charities VALUES ('Ottawa Food Bank');
INSERT INTO data_charities VALUES ('Ottawa Hospital Foundation');
INSERT INTO data_charities VALUES ('Ottawa Regional Cancer Foundation');
INSERT INTO data_charities VALUES ('Ovarian Cancer Canada');
INSERT INTO data_charities VALUES ('Oxfam');
INSERT INTO data_charities VALUES ('Oxfam International');
INSERT INTO data_charities VALUES ('Pacific Assistance Dogs Society');
INSERT INTO data_charities VALUES ('Pacific Coast Public Television Association');
INSERT INTO data_charities VALUES ('Pacific Salmon Foundation');
INSERT INTO data_charities VALUES ('Pancreatic Cancer Canada');
INSERT INTO data_charities VALUES ('Panthera');
INSERT INTO data_charities VALUES ('Paralyzed Veterans of America');
INSERT INTO data_charities VALUES ('Parkinson Society Canada');
INSERT INTO data_charities VALUES ('Partners In Development, Inc.');
INSERT INTO data_charities VALUES ('Partners in Mission Food Bank');
INSERT INTO data_charities VALUES ('Pathways Clubhouse');
INSERT INTO data_charities VALUES ('Pathways to Education');
INSERT INTO data_charities VALUES ('Patient Access Network Foundation');
INSERT INTO data_charities VALUES ('Payasos Sin Fronteras');
INSERT INTO data_charities VALUES ('Peace Arch Hospital Foundation');
INSERT INTO data_charities VALUES ('Peace Dividend Trust');
INSERT INTO data_charities VALUES ('Peace Parks Foundation');
INSERT INTO data_charities VALUES ('Peace Players International');
INSERT INTO data_charities VALUES ('Pearl Initiative');
INSERT INTO data_charities VALUES ('Penal Reform International');
INSERT INTO data_charities VALUES ('Pencils of Promise');
INSERT INTO data_charities VALUES ('Pentecostal Assemblies of Canada');
INSERT INTO data_charities VALUES ('Performing Animal Welfare Society (P.A.W.S.)');
INSERT INTO data_charities VALUES ('Personal Energy Transportation');
INSERT INTO data_charities VALUES ('Pet Partners');
INSERT INTO data_charities VALUES ('Petits Freres des Pauvres');
INSERT INTO data_charities VALUES ('Philip Aziz Centre for Hospice Care');
INSERT INTO data_charities VALUES ('Pine River Institute');
INSERT INTO data_charities VALUES ('Pin-ups for Vets');
INSERT INTO data_charities VALUES ('Plan');
INSERT INTO data_charities VALUES ('Plan (aid organisation)');
INSERT INTO data_charities VALUES ('PLAN Canada');
INSERT INTO data_charities VALUES ('Plan UK');
INSERT INTO data_charities VALUES ('Plan USA');
INSERT INTO data_charities VALUES ('Planned Parenthood Federation of America');
INSERT INTO data_charities VALUES ('Pod Volunteer');
INSERT INTO data_charities VALUES ('Pollution Probe Foundation');
INSERT INTO data_charities VALUES ('Population Services International');
INSERT INTO data_charities VALUES ('Portland Hotel Society');
INSERT INTO data_charities VALUES ('Potential Place Society');
INSERT INTO data_charities VALUES ('Power To Change Ministries');
INSERT INTO data_charities VALUES ('President''s Choice Children''s Charity');
INSERT INTO data_charities VALUES ('Primate''s World Relief and Development Fund');
INSERT INTO data_charities VALUES ('Prince County Hospital Foundation');
INSERT INTO data_charities VALUES ('Princess Margaret Cancer Foundation');
INSERT INTO data_charities VALUES ('Progressio Ireland');
INSERT INTO data_charities VALUES ('Project HOPE');
INSERT INTO data_charities VALUES ('Project Sunshine');
INSERT INTO data_charities VALUES ('Prostate Cancer Canada');
INSERT INTO data_charities VALUES ('Prostate Cancer Fight Foundation');
INSERT INTO data_charities VALUES ('Public Broadcasting Service');
INSERT INTO data_charities VALUES ('Pump Aid');
INSERT INTO data_charities VALUES ('Ratanak International');
INSERT INTO data_charities VALUES ('Realdania');
INSERT INTO data_charities VALUES ('Red Deer Hospice');
INSERT INTO data_charities VALUES ('Red Deer Regional Health Foundation');
INSERT INTO data_charities VALUES ('Red Door Family Shelter');
INSERT INTO data_charities VALUES ('Redress (charitable organisation)');
INSERT INTO data_charities VALUES ('RedRover');
INSERT INTO data_charities VALUES ('RefugePoint');
INSERT INTO data_charities VALUES ('Regent Park School of Music');
INSERT INTO data_charities VALUES ('Reggio Children Foundation');
INSERT INTO data_charities VALUES ('REHASWISS');
INSERT INTO data_charities VALUES ('Renascent Fellowship');
INSERT INTO data_charities VALUES ('RFDA of Northwestern Ontario');
INSERT INTO data_charities VALUES ('Rick Hansen Foundation');
INSERT INTO data_charities VALUES ('Rick Hansen Institute');
INSERT INTO data_charities VALUES ('Ride for Refuge');
INSERT INTO data_charities VALUES ('Right to Play');
INSERT INTO data_charities VALUES ('Ripple Effect project');
INSERT INTO data_charities VALUES ('RISE International');
INSERT INTO data_charities VALUES ('Rivershed Society of British Columbia');
INSERT INTO data_charities VALUES ('Robb Nash Project');
INSERT INTO data_charities VALUES ('Robert Bosch Foundation');
INSERT INTO data_charities VALUES ('Robert Bosch Stiftung');
INSERT INTO data_charities VALUES ('Robert Wood Johnson Foundation');
INSERT INTO data_charities VALUES ('Rockefeller Brothers Fund');
INSERT INTO data_charities VALUES ('Rockefeller Foundation');
INSERT INTO data_charities VALUES ('Romero House');
INSERT INTO data_charities VALUES ('Ronald McDonald House Charities');
INSERT INTO data_charities VALUES ('Rotary Foundation');
INSERT INTO data_charities VALUES ('Rotary Foundation Canada');
INSERT INTO data_charities VALUES ('Rotary Foundation of Rotary International');
INSERT INTO data_charities VALUES ('Royal Alexandra Hospital Foundation');
INSERT INTO data_charities VALUES ('Royal Canadian Legion Branch Poppy Fund');
INSERT INTO data_charities VALUES ('Royal Columbian Hospital Foundation');
INSERT INTO data_charities VALUES ('Royal Flying Doctor Service of Australia');
INSERT INTO data_charities VALUES ('Royal London Society for Blind People');
INSERT INTO data_charities VALUES ('Royal Ontario Museum');
INSERT INTO data_charities VALUES ('Royal Society for the Prevention of Cruelty to Animals');
INSERT INTO data_charities VALUES ('Royal Society for the Protection of Birds');
INSERT INTO data_charities VALUES ('Royal University Hospital Foundation');
INSERT INTO data_charities VALUES ('Royal Victoria Hospital Foundation');
INSERT INTO data_charities VALUES ('SADD');
INSERT INTO data_charities VALUES ('Safe Kids Worldwide');
INSERT INTO data_charities VALUES ('Safe Water Network');
INSERT INTO data_charities VALUES ('Sail Training International');
INSERT INTO data_charities VALUES ('Saint Camillus Foundation');
INSERT INTO data_charities VALUES ('Saint John Regional Hospital Foundation');
INSERT INTO data_charities VALUES ('Salvation Army');
INSERT INTO data_charities VALUES ('Samaritan''s Purse');
INSERT INTO data_charities VALUES ('Samaritan''s Purse Canada');
INSERT INTO data_charities VALUES ('Samsara Foundation');
INSERT INTO data_charities VALUES ('Sanctuary Ministries of Toronto');
INSERT INTO data_charities VALUES ('Santa Casa da Misericórdia');
INSERT INTO data_charities VALUES ('Santé Diabète');
INSERT INTO data_charities VALUES ('Santropol Roulant');
INSERT INTO data_charities VALUES ('Save A Family Plan');
INSERT INTO data_charities VALUES ('Save the Children');
INSERT INTO data_charities VALUES ('Save the Manatee Club');
INSERT INTO data_charities VALUES ('Scaife Family Foundation');
INSERT INTO data_charities VALUES ('Scarborough Hospital Foundation');
INSERT INTO data_charities VALUES ('Scarborough Women''s Centre');
INSERT INTO data_charities VALUES ('SCARE for a CURE');
INSERT INTO data_charities VALUES ('Schizophrenia Society of Ontario');
INSERT INTO data_charities VALUES ('Scholarship America');
INSERT INTO data_charities VALUES ('Schowalter Foundation');
INSERT INTO data_charities VALUES ('Scientists Without Borders');
INSERT INTO data_charities VALUES ('Scott Mission');
INSERT INTO data_charities VALUES ('Scottish Catholic International Aid Fund');
INSERT INTO data_charities VALUES ('Second Harvest');
INSERT INTO data_charities VALUES ('Secours populaire français');
INSERT INTO data_charities VALUES ('SEMAFO Foundation');
INSERT INTO data_charities VALUES ('Seniors Coalition');
INSERT INTO data_charities VALUES ('Sens Foundation');
INSERT INTO data_charities VALUES ('Servants Anonymous Society of Calgary');
INSERT INTO data_charities VALUES ('SEVA Canada Society');
INSERT INTO data_charities VALUES ('SHARELIFE');
INSERT INTO data_charities VALUES ('Shaw Festival Theatre');
INSERT INTO data_charities VALUES ('Sheena''s Place');
INSERT INTO data_charities VALUES ('ShelterBox');
INSERT INTO data_charities VALUES ('Shock Trauma Air Rescue Society');
INSERT INTO data_charities VALUES ('Shriners Hospitals for Children');
INSERT INTO data_charities VALUES ('SickKids Foundation');
INSERT INTO data_charities VALUES ('Sierra Club');
INSERT INTO data_charities VALUES ('Sierra Club BC');
INSERT INTO data_charities VALUES ('Sierra Club of Canada Foundation');
INSERT INTO data_charities VALUES ('Silicon Valley Community Foundation');
INSERT INTO data_charities VALUES ('Siloam Mission');
INSERT INTO data_charities VALUES ('Simon Fraser University');
INSERT INTO data_charities VALUES ('Simon House');
INSERT INTO data_charities VALUES ('Simone and Cino Del Duca Foundation');
INSERT INTO data_charities VALUES ('Sinai Health Foundation');
INSERT INTO data_charities VALUES ('Sir Dorabji Tata and Allied Trusts');
INSERT INTO data_charities VALUES ('Sistering - A Woman''s Place');
INSERT INTO data_charities VALUES ('SKETCH');
INSERT INTO data_charities VALUES ('SKIP of New York');
INSERT INTO data_charities VALUES ('Sleeping Children Around the World');
INSERT INTO data_charities VALUES ('Smile Train');
INSERT INTO data_charities VALUES ('Smithsonian Institute');
INSERT INTO data_charities VALUES ('Society of Saint Vincent de Paul');
INSERT INTO data_charities VALUES ('Society of St. Andrew');
INSERT INTO data_charities VALUES ('Society of Typographic Aficionados');
INSERT INTO data_charities VALUES ('Solar Cookers International');
INSERT INTO data_charities VALUES ('Solar Sister');
INSERT INTO data_charities VALUES ('Solidarités international');
INSERT INTO data_charities VALUES ('Somaly Mam Foundation');
INSERT INTO data_charities VALUES ('SOS Children''s Villages');
INSERT INTO data_charities VALUES ('Soul Action');
INSERT INTO data_charities VALUES ('Soulpepper Theatre Company');
INSERT INTO data_charities VALUES ('South Africa Partners');
INSERT INTO data_charities VALUES ('South Saskatchewan Community Foundation');
INSERT INTO data_charities VALUES ('Southern Alberta Land Trust Society');
INSERT INTO data_charities VALUES ('Southlake Regional Health Centre Foundation');
INSERT INTO data_charities VALUES ('Sparebankstiftelsen DnB');
INSERT INTO data_charities VALUES ('Speroway');
INSERT INTO data_charities VALUES ('Spina Bifida & Hydrocephalus Association of Ontario');
INSERT INTO data_charities VALUES ('Spread the Net');
INSERT INTO data_charities VALUES ('Stand Up To Cancer (Entertainment Industry Foundation)');
INSERT INTO data_charities VALUES ('Starlight Children''s Foundation');
INSERT INTO data_charities VALUES ('Steering Committee for Humanitarian Response');
INSERT INTO data_charities VALUES ('Step Up for Students');
INSERT INTO data_charities VALUES ('Stephen Lewis Foundation');
INSERT INTO data_charities VALUES ('Sterling Hall School');
INSERT INTO data_charities VALUES ('Stevenson Memorial Hospital Foundation');
INSERT INTO data_charities VALUES ('Stichting INGKA Foundation');
INSERT INTO data_charities VALUES ('Stollery Children''s Hospital Foundation');
INSERT INTO data_charities VALUES ('Stop the Traffik');
INSERT INTO data_charities VALUES ('Stratford Festival');
INSERT INTO data_charities VALUES ('Street Haven');
INSERT INTO data_charities VALUES ('Street Kids International');
INSERT INTO data_charities VALUES ('Street To Trail Association');
INSERT INTO data_charities VALUES ('Streetohome Foundation');
INSERT INTO data_charities VALUES ('Students Helping Honduras');
INSERT INTO data_charities VALUES ('Sulaiman Abdul Aziz Al Rajhi');
INSERT INTO data_charities VALUES ('Sunnybrook Foundation');
INSERT INTO data_charities VALUES ('Sunshine');
INSERT INTO data_charities VALUES ('Surdna Foundation');
INSERT INTO data_charities VALUES ('Survival International');
INSERT INTO data_charities VALUES ('Survivor Corps');
INSERT INTO data_charities VALUES ('Susan G Komen Breast Cancer Foundation');
INSERT INTO data_charities VALUES ('Sustainable Organic Integrated Livelihoods');
INSERT INTO data_charities VALUES ('SystemX');
INSERT INTO data_charities VALUES ('Tanzania Education Fund');
INSERT INTO data_charities VALUES ('Taproot Foundation');
INSERT INTO data_charities VALUES ('Task Force for Global Health');
INSERT INTO data_charities VALUES ('TB Vets');
INSERT INTO data_charities VALUES ('Teach for America');
INSERT INTO data_charities VALUES ('TeachAIDS');
INSERT INTO data_charities VALUES ('Tearfund');
INSERT INTO data_charities VALUES ('TechnoServe');
INSERT INTO data_charities VALUES ('Ted Talks');
INSERT INTO data_charities VALUES ('Teen Challenge');
INSERT INTO data_charities VALUES ('Telangana Development Forum');
INSERT INTO data_charities VALUES ('TELUS Spark');
INSERT INTO data_charities VALUES ('Template:Serious Request');
INSERT INTO data_charities VALUES ('Terre des hommes');
INSERT INTO data_charities VALUES ('Terry Fox Foundation');
INSERT INTO data_charities VALUES ('The Albert Schweitzer Fellowship');
INSERT INTO data_charities VALUES ('The Alliance for Safe Children');
INSERT INTO data_charities VALUES ('The ARC');
INSERT INTO data_charities VALUES ('The Arthritis Society');
INSERT INTO data_charities VALUES ('The Asia Foundation');
INSERT INTO data_charities VALUES ('The Aspinall Foundation');
INSERT INTO data_charities VALUES ('The BOMA Project');
INSERT INTO data_charities VALUES ('The California Endowment');
INSERT INTO data_charities VALUES ('The Canadian International Learning Foundation');
INSERT INTO data_charities VALUES ('The Carter Center');
INSERT INTO data_charities VALUES ('The Center for Global Ministries');
INSERT INTO data_charities VALUES ('The Center for Strategic and International Studies');
INSERT INTO data_charities VALUES ('The Center for Victims of Torture');
INSERT INTO data_charities VALUES ('The Children''s Investment Fund Foundation');
INSERT INTO data_charities VALUES ('The Church Commissioners for England');
INSERT INTO data_charities VALUES ('The Citizens Foundation');
INSERT INTO data_charities VALUES ('The Crohn''s and Colitis Foundation of Canada');
INSERT INTO data_charities VALUES ('The Duke Endowment');
INSERT INTO data_charities VALUES ('The Earth Institute at Columbia University');
INSERT INTO data_charities VALUES ('The Elephant Sanctuary in Tennessee');
INSERT INTO data_charities VALUES ('The Foundation for a Better Life');
INSERT INTO data_charities VALUES ('The Fred Hollows Foundation');
INSERT INTO data_charities VALUES ('The Fregenet Foundation');
INSERT INTO data_charities VALUES ('The Global Fund to Fight AIDS, Tuberculosis and Malaria');
INSERT INTO data_charities VALUES ('The Heritage Foundation');
INSERT INTO data_charities VALUES ('The Humanitarian Forum');
INSERT INTO data_charities VALUES ('The Hunger Project');
INSERT INTO data_charities VALUES ('The Kresge Foundation');
INSERT INTO data_charities VALUES ('The Lawrence Foundation');
INSERT INTO data_charities VALUES ('The Learning Partnership');
INSERT INTO data_charities VALUES ('The Leona M. and Harry B. Helmsley Charitable Trust');
INSERT INTO data_charities VALUES ('The Library Project');
INSERT INTO data_charities VALUES ('The MasterCard Foundation');
INSERT INTO data_charities VALUES ('The Memory Project');
INSERT INTO data_charities VALUES ('The Mustard Seed');
INSERT INTO data_charities VALUES ('The New Brunswick Innovation Foundation');
INSERT INTO data_charities VALUES ('The Oaktree Foundation');
INSERT INTO data_charities VALUES ('The Pew Charitable Trusts');
INSERT INTO data_charities VALUES ('The Redwood');
INSERT INTO data_charities VALUES ('The Rendezvous Society');
INSERT INTO data_charities VALUES ('The Rooms Corporation of Newfoundland and Labrador');
INSERT INTO data_charities VALUES ('The Stop Community Food Centre');
INSERT INTO data_charities VALUES ('The Sunshine Kids');
INSERT INTO data_charities VALUES ('The Trevor Project');
INSERT INTO data_charities VALUES ('The University of Ottawa Heart Institute Foundation');
INSERT INTO data_charities VALUES ('The W. Garfield Weston Foundation');
INSERT INTO data_charities VALUES ('The Walter and Duncan Gordon Foundation');
INSERT INTO data_charities VALUES ('The Weston Foundation');
INSERT INTO data_charities VALUES ('The Winnipeg Foundation');
INSERT INTO data_charities VALUES ('Theatre Calgary');
INSERT INTO data_charities VALUES ('Thrive Africa');
INSERT INTO data_charities VALUES ('Tides Canada Foundation');
INSERT INTO data_charities VALUES ('Tim Horton Children''s Foundation');
INSERT INTO data_charities VALUES ('Toc H');
INSERT INTO data_charities VALUES ('Tom Joyner Foundation');
INSERT INTO data_charities VALUES ('Toronto Humane Society');
INSERT INTO data_charities VALUES ('Toronto Symphony Orchestra');
INSERT INTO data_charities VALUES ('Tostan');
INSERT INTO data_charities VALUES ('Touch Foundation');
INSERT INTO data_charities VALUES ('Toys for Tots');
INSERT INTO data_charities VALUES ('Traffic');
INSERT INTO data_charities VALUES ('Trans Canada Trail');
INSERT INTO data_charities VALUES ('Transatlantic Partners Against AIDS');
INSERT INTO data_charities VALUES ('Transforming Faces');
INSERT INTO data_charities VALUES ('Trees for the Future');
INSERT INTO data_charities VALUES ('Trent University');
INSERT INTO data_charities VALUES ('Trillium Health Partners Foundation');
INSERT INTO data_charities VALUES ('Tropenbos International');
INSERT INTO data_charities VALUES ('Tropicana Community Services Organization');
INSERT INTO data_charities VALUES ('Trout Unlimited Canada');
INSERT INTO data_charities VALUES ('True Patriot Love Foundation');
INSERT INTO data_charities VALUES ('Tulsa Community Foundation');
INSERT INTO data_charities VALUES ('Ubuntu Education Fund');
INSERT INTO data_charities VALUES ('UforChange Movement');
INSERT INTO data_charities VALUES ('Uganda Christian University Partners');
INSERT INTO data_charities VALUES ('Ulster Project');
INSERT INTO data_charities VALUES ('UNICEF');
INSERT INTO data_charities VALUES ('Union Gospel Mission');
INSERT INTO data_charities VALUES ('United Israel Appeal of Canada');
INSERT INTO data_charities VALUES ('United Jewish Appeal of Greater Toronto');
INSERT INTO data_charities VALUES ('United Jewish Welfare Fund of Toronto');
INSERT INTO data_charities VALUES ('United Methodist Committee on Relief');
INSERT INTO data_charities VALUES ('United Nations Children''s Fund (UNICEF)');
INSERT INTO data_charities VALUES ('United Nations Foundation');
INSERT INTO data_charities VALUES ('United Nations High Commissioner for Refugees');
INSERT INTO data_charities VALUES ('United Nations Office for Partnerships');
INSERT INTO data_charities VALUES ('United Spinal Association');
INSERT INTO data_charities VALUES ('United States Artists');
INSERT INTO data_charities VALUES ('United States Fund for UNICEF');
INSERT INTO data_charities VALUES ('United Way');
INSERT INTO data_charities VALUES ('UNITY Charity');
INSERT INTO data_charities VALUES ('Urgenta Foundation');
INSERT INTO data_charities VALUES ('USC Canada');
INSERT INTO data_charities VALUES ('User:Chriz the wiz/Sustainable Development Goals Fund');
INSERT INTO data_charities VALUES ('Vaad Mishmeres Mitzvos Committee to Observe The Torah Laws');
INSERT INTO data_charities VALUES ('Vancouver Symphony Society');
INSERT INTO data_charities VALUES ('Variety, the Children''s Charity');
INSERT INTO data_charities VALUES ('Varkey Foundation');
INSERT INTO data_charities VALUES ('Vietnam Children''s Fund');
INSERT INTO data_charities VALUES ('Vietnam Veterans Memorial Fund');
INSERT INTO data_charities VALUES ('Vietnam Veterans of America Foundation');
INSERT INTO data_charities VALUES ('Village Enterprise');
INSERT INTO data_charities VALUES ('Village Health Works');
INSERT INTO data_charities VALUES ('VillageReach');
INSERT INTO data_charities VALUES ('Virtu Foundation');
INSERT INTO data_charities VALUES ('Vision Aid Overseas');
INSERT INTO data_charities VALUES ('VOCM Cares');
INSERT INTO data_charities VALUES ('Voluntary Service Overseas');
INSERT INTO data_charities VALUES ('Volunteers of America');
INSERT INTO data_charities VALUES ('W. K. Kellogg Foundation');
INSERT INTO data_charities VALUES ('War Amps of Canada');
INSERT INTO data_charities VALUES ('War Child');
INSERT INTO data_charities VALUES ('War Child Canada');
INSERT INTO data_charities VALUES ('Waste No Food');
INSERT INTO data_charities VALUES ('Watch Tower Bible and Tract Society of Canada');
INSERT INTO data_charities VALUES ('Water Agriculture and Health in Tropical Area');
INSERT INTO data_charities VALUES ('Water to Thrive');
INSERT INTO data_charities VALUES ('Water.org');
INSERT INTO data_charities VALUES ('WaterAid');
INSERT INTO data_charities VALUES ('WaterAid Canada');
INSERT INTO data_charities VALUES ('WaterPartners');
INSERT INTO data_charities VALUES ('WAVE Trust');
INSERT INTO data_charities VALUES ('Weengushk Film Institute');
INSERT INTO data_charities VALUES ('Welcome Hall Mission');
INSERT INTO data_charities VALUES ('Wellcome Trust');
INSERT INTO data_charities VALUES ('Wellspring Cancer Support Foundation');
INSERT INTO data_charities VALUES ('Weston King Neighbourhood Centre');
INSERT INTO data_charities VALUES ('Wetlands International');
INSERT INTO data_charities VALUES ('WikiLeaks');
INSERT INTO data_charities VALUES ('Wikimedia Foundation');
INSERT INTO data_charities VALUES ('WildAid');
INSERT INTO data_charities VALUES ('Wilderness Committee');
INSERT INTO data_charities VALUES ('Wildlife Conservation Network');
INSERT INTO data_charities VALUES ('Wildlife Conservation Society');
INSERT INTO data_charities VALUES ('Wildlife Preservation Canada');
INSERT INTO data_charities VALUES ('Wilfrid Laurier University');
INSERT INTO data_charities VALUES ('William and Flora Hewlett Foundation');
INSERT INTO data_charities VALUES ('William Osler Health System Foundation');
INSERT INTO data_charities VALUES ('Windfall Clothing');
INSERT INTO data_charities VALUES ('Wings of Hope');
INSERT INTO data_charities VALUES ('WISH Drop-In Centre Society');
INSERT INTO data_charities VALUES ('Women Employed');
INSERT INTO data_charities VALUES ('Women’s Microfinance Initiative');
INSERT INTO data_charities VALUES ('WoodGreen Community Services');
INSERT INTO data_charities VALUES ('Woodrow Wilson National Fellowship Foundation');
INSERT INTO data_charities VALUES ('Working Bikes');
INSERT INTO data_charities VALUES ('World Animal Protection');
INSERT INTO data_charities VALUES ('World Assembly of Muslim Youth');
INSERT INTO data_charities VALUES ('World Association of Girl Guides and Girl Scouts');
INSERT INTO data_charities VALUES ('World Bicycle Relief');
INSERT INTO data_charities VALUES ('World Computer Exchange');
INSERT INTO data_charities VALUES ('World Concern');
INSERT INTO data_charities VALUES ('World Federation of United Nations Associations');
INSERT INTO data_charities VALUES ('World Food Program USA');
INSERT INTO data_charities VALUES ('World Hope International');
INSERT INTO data_charities VALUES ('World Literacy Foundation');
INSERT INTO data_charities VALUES ('World Medical Relief');
INSERT INTO data_charities VALUES ('World Relief');
INSERT INTO data_charities VALUES ('World Renew');
INSERT INTO data_charities VALUES ('World Scout Foundation');
INSERT INTO data_charities VALUES ('World Transformation Movement');
INSERT INTO data_charities VALUES ('World University Service of Canada');
INSERT INTO data_charities VALUES ('World Villages for Children');
INSERT INTO data_charities VALUES ('World Vision');
INSERT INTO data_charities VALUES ('World Vision USA');
INSERT INTO data_charities VALUES ('World Wide Fund for Nature');
INSERT INTO data_charities VALUES ('World Wildlife Fund');
INSERT INTO data_charities VALUES ('World Wildlife Fund Canada');
INSERT INTO data_charities VALUES ('Worldwide Fistula Fund');
INSERT INTO data_charities VALUES ('Wounded Warrior Project');
INSERT INTO data_charities VALUES ('Wycliffe');
INSERT INTO data_charities VALUES ('Wyoming Wildlife Federation');
INSERT INTO data_charities VALUES ('Yellow Brick House');
INSERT INTO data_charities VALUES ('Yellowknife Community Foundation');
INSERT INTO data_charities VALUES ('YMCA');
INSERT INTO data_charities VALUES ('Yonge Street Mission');
INSERT INTO data_charities VALUES ('York University');
INSERT INTO data_charities VALUES ('Young Adult Cancer Canada');
INSERT INTO data_charities VALUES ('Young Heroes Foundation');
INSERT INTO data_charities VALUES ('Young Lives');
INSERT INTO data_charities VALUES ('Youth Emergency Shelter Society');
INSERT INTO data_charities VALUES ('Youth Employment Services YES');
INSERT INTO data_charities VALUES ('Youth Fusion/Fusion Jeunesse');
INSERT INTO data_charities VALUES ('Youth With A Mission');
INSERT INTO data_charities VALUES ('Youth Without Shelter');
INSERT INTO data_charities VALUES ('YouthBuild');
INSERT INTO data_charities VALUES ('Yukon Hospital Foundation');
INSERT INTO data_charities VALUES ('Yunnan Institute of Development');
INSERT INTO data_charities VALUES ('Yunus Social Business – Global Initiatives');
INSERT INTO data_charities VALUES ('YWCA');
INSERT INTO data_charities VALUES ('Zareinu Educational Centre of Metropolitan Toronto');
