CREATE TABLE Project_Dropdown_Task_FINAL_Ver_1_11_1_1 (
    `Column_1` VARCHAR(80) CHARACTER SET utf8
);
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Disorder name ');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('18p deletion syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('1p36 deletion syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('21-hydroxylase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('47,XXX');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('47,XXY');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('5-ALA dehydratase-deficient porphyria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('5-aminolaevulinic dehydratase deficiency porphyria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('5p deletion syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('5p- syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('AAT');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Aceruloplasminemia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('ACG2');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('ACH');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Achondrogenesis type II');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Achondroplasia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Acid beta-glucosidase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Acrocephalosyndactyly (Apert)');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Acrocephalosyndactyly, type V');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Acrocephaly');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Acute cerebral Gaucher''s disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Acute intermittent porphyria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('ACY2 deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('AD');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Adelaide-type craniosynostosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Adenomatous Polyposis Coli');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Adenomatous Polyposis of the Colon');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Adenylosuccinate lyase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('ADP');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Adrenal gland disorders');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Adrenogenital syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Adrenoleukodystrophy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('AIP');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('AIS');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('AKU');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('ALA dehydratase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('ALA dehydratase porphyria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('ALA-D porphyria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Alagille syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Albinism');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Alcaptonuria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Alexander disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Alkaptonuria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Alkaptonuric ochronosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Alpha 1-antitrypsin deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Alpha-1 proteinase inhibitor');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Alpha-1 related emphysema');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Alpha-galactosidase A deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('ALS');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Alström syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('ALX');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Alzheimer''s disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Amelogenesis imperfecta');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Amino levulinic acid dehydratase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Aminoacylase 2 deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Amyotrophic lateral sclerosis (ALS)');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Anderson-Fabry disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Androgen insensitivity syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Anemia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Anemia, hereditary sideroblastic');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Anemia, splenic, familial');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Angelman syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Angiokeratoma Corporis Diffusum');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Angiokeratoma diffuse');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Angiomatosis retinae');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('APC resistance, Leiden type');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Apert syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('AR deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Arachnodactyly');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('AR-CMT2');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('ARNSHL');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Arthrochalasis multiplex congenita');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Arthro-ophthalmopathy, hereditary progressive');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('AS');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Asp deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Aspa deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Aspartoacylase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('A-T');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Ataxia telangiectasia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Autism-Dementia-Ataxia-Loss of Purposeful Hand Use syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Autosomal dominant juvenile ALS');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Autosomal dominant opitz G/BBB syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Autosomal recessive form of juvenile ALS type 3');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Autosomal recessive nonsyndromic hearing loss');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Autosomal Recessive Sensorineural Hearing Impairment and Goiter');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('AxD');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Ayerza syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Bvariant of the Hexosaminidase GM2 gangliosidosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Bardet–Biedl syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('BANF');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Beare-Stevenson cutis gyrata syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Benign paroxysmal peritonitis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Benjamin syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Beta-thalassemia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('BH4 Deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Bilateral Acoustic Neurofibromatosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Biotinidase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Birt–Hogg–Dubé syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Bladder cancer');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Bleeding disorders');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Bloch-Sulzberger syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Bloom syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Bone diseases');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Bourneville disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Brain diseases');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Breast cancer');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Brittle bone disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Broad Thumb-Hallux syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Bronze Diabetes');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Bronzed cirrhosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Bulbospinal muscular atrophy, X-linked');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Burger-Grutz syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('CADASIL syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Campomelic dysplasia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Canavan disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Cancer');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Cancer Family syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Cancer of breast');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Cancer of the bladder');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Carboxylase Deficiency, Multiple, Late-Onset');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Cat cry syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Caused by mutations in the PHF8 gene');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Caylor cardiofacial syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Ceramide trihexosidase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Cerebelloretinal Angiomatosis, familial');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Cerebral arteriopathy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Cerebral autosomal dominant ateriopathy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Cerebroatrophic Hyperammonemia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Cerebroside Lipidosis syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('CF');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('CGD Chronic granulomatous disorder');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Charcot disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Charcot-Marie-Tooth disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('CHARGE syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Chondrodystrophia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Chondrodystrophy syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Chondrodystrophy with sensorineural deafness');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Chondrogenesis imperfecta');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Choreoathetosis self-mutilation hyperuricemia syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Classic Galactosemia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Classical Ehlers–Danlos syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Classical Phenylketonuria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Cleft lip and palate');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Cloverleaf skull with thanatophoric dwarfism');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('CLS');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('CMT');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Cockayne syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Coffin-Lowry syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Collagenopathy, types II and XI');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Colon cancer, familial');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Colon Cancer, familial Nonpolyposis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Colorectal cancer[1]');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Complete HPRT deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Complete hypoxanthine-guanine phosphoribosyltransferase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Compression neuropathy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Connective tissue disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Conotruncal anomaly face syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Cooley''s Anemia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Copper storage disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Copper transport disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Coproporphyria, hereditary');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Coproporphyrinogen oxidase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Cowden syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('CPO deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('CPRO deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('CPX deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Craniofacial dysarthrosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Craniofacial Dysostosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Cri du chat');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Crohn''s disease, fibrostenosing');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Crouzon syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Crouzon syndrome with acanthosis nigricans');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Crouzonodermoskeletal syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('CS');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Curschmann-Batten-Steinert syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Cutis gyrata syndrome of Beare-Stevenson');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Dappled metaphysis syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('DAT - Dementia Alzheimer''s type');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('DBMD');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('De Grouchy syndrome 1');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Deafness with goiter');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Deafness-retinitis pigmentosa syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Deficiency disease, Phenylalanine Hydroxylase');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Degenerative nerve diseases');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Dejerine-Sottas syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Delta-aminolevulinate dehydratase deficiency porphyria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Dementia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Demyelinogenic leukodystrophy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Dermatosparactic type of Ehlers–Danlos syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Dermatosparaxis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Developmental disabilities');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('D-glycerate dehydrogenase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('DHMN');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('DHMN-V');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('DHTR deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Di George''s syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Diffuse Globoid Body Sclerosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Dihydrotestosterone receptor deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Distal hereditary motor neuropathy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('DM1');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('DM2');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('DSMAV');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('DSN');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('DSS');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Duchenne/Becker muscular dystrophy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Dwarf, achondroplastic');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Dwarf, thanatophoric');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Dwarfism');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Dwarfism-retinal atrophy-deafness syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Dysmyelinogenic leukodystrophy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Dystrophia myotonica');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Dystrophia retinae pigmentosa-dysostosis syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Early-Onset familial alzheimer disease (EOFAD)');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('EDS');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Ehlers–Danlos syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Ekman-Lobstein disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Entrapment neuropathy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('EPP');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Erythroblastic anemia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Erythrohepatic protoporphyria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Erythroid 5-aminolevulinate synthetase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Erythropoietic protoporphyria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Eye cancer');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('FA');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Fabry disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Facial injuries and disorders');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Factor V Leiden thrombophilia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('FALS');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Familial acoustic neuroma');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Familial adenomatous polyposis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Familial Alzheimer disease (FAD)');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Familial amyotrophic lateral sclerosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Familial dysautonomia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Familial fat-induced hypertriglyceridemia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Familial hemochromatosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Familial LPL deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Familial nonpolyposis colon cancer');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Familial paroxysmal polyserositis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Familial PCT');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Familial pressure-sensitive neuropathy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Familial primary pulmonary hypertension (FPPH)');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Familial vascular leukoencephalopathy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('FAP');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('FD');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Ferrochelatase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Ferroportin disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Fever');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('FG syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('FGFR3-associated coronal synostosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Fibrinoid degeneration of astrocytes');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Fibrocystic disease of the pancreas');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('FMF');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Folling disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Fra(X) syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Fragile X syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Fragilitas ossium');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('FRAXA syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('FRDA');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Friedreich''s ataxia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('FXS');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('G6PD deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Galactokinase deficiency disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Galactose-1-phosphate uridyl-transferase deficiency disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Galactosemia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Galactosylceramidase deficiency disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Galactosylceramide lipidosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Galactosylcerebrosidase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Galactosylsphingosine lipidosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('GALC deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('GALT deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Gaucher disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Gaucher-like disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('GBA deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('GD');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Genetic brain disorders');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Genetic emphysema');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Genetic hemochromatosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Genetic hypercalciuria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Giant cell hepatitis, neonatal');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('GLA deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Glioblastoma, retinal');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Glioma, retinal');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Globoid cell leukodystrophy (GCL, GLD)');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Globoid cell leukoencephalopathy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Glucocerebrosidase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Glucocerebrosidosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Glucosyl cerebroside lipidosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Glucosylceramidase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Glucosylceramide beta-glucosidase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Glucosylceramide lipidosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Glyceric aciduria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Glycine encephalopathy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Glycolic aciduria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('GM2 gangliosidosis, type 1');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Goiter-deafness syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Graefe-Usher syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Gronblad-Strandberg syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Haemochromatosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hallgren syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Harlequin type ichthyosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hb S disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('HCH');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('HCP');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Head and brain malformations');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hearing disorders and deafness');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hearing problems in children');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('HEF2A');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('HEF2B');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hematoporphyria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Heme synthetase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hemochromatoses');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hemochromatosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hemoglobin M disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hemoglobin S disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hemophilia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('HEP');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hepatic AGT deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hepatoerythropoietic porphyria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hepatolenticular degeneration syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hereditary arthro-ophthalmopathy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hereditary coproporphyria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hereditary dystopic lipidosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hereditary hemochromatosis (HHC)');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hereditary hemorrhagic telangiectasia (HHT)');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hereditary Inclusion Body Myopathy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hereditary iron-loading anemia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hereditary motor and sensory neuropathy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hereditary motor neuronopathy, type V');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hereditary multiple exostoses');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hereditary nonpolyposis colorectal cancer');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hereditary periodic fever syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hereditary Polyposis Coli');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hereditary pulmonary emphysema');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hereditary resistance to activated protein C');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hereditary sensory and autonomic neuropathy type III');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hereditary spastic paraplegia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hereditary spinal ataxia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hereditary spinal sclerosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Herrick''s anemia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Heterozygous OSMED');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Heterozygous otospondylomegaepiphyseal dysplasia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('HexA deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hexosaminidase A deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hexosaminidase alpha-subunit deficiency (variant B)');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('HFE-associated hemochromatosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('HGPS');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hippel-Lindau disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('HLAH');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('HMN V');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('HMSN');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('HNPCC');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('HNPP');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Homocystinuria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Homogentisic acid oxidase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Homogentisic acidura');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Homozygous porphyria cutanea tarda');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('HP1');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('HP2');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('HPA');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('HPRT - Hypoxanthine-guanine phosphoribosyltransferase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('HSAN type III');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('HSAN3');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('HSN-III');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Human dermatosparaxis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Huntington''s disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hutchinson-Gilford progeria syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hyperandrogenism, nonclassic type, due to 21-hydroxylase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hyperchylomicronemia, familial');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hyperglycinemia with ketoacidosis and leukopenia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hyperlipoproteinemia type I');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hyperoxaluria, primary');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hyperphenylalaninaemia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hyperphenylalaninemia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hypochondrodysplasia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hypochondrogenesis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hypochondroplasia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hypochromic anemia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Hypoxanthine phosphoribosyltransferse (HPRT) deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('IAHSP');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('ICF syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Idiopathic hemochromatosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Idiopathic neonatal hemochromatosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Idiopathic pulmonary hypertension');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Immune system disorders');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Incontinentia pigmenti');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Infantile cerebral Gaucher''s disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Infantile Gaucher disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Infantile-onset ascending hereditary spastic paralysis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Infertility');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Inherited emphysema');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Inherited tendency to pressure palsies');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Insley-Astley syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Intermittent acute porphyria syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Intestinal polyposis-cutaneous pigmentation syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('IP');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Iron storage disorder');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Irritable bowel syndrome (IBS)');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Isodicentric 15');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Isolated deafness');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Jackson-Weiss syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('JH');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Joubert syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('JPLS');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Juvenile amyotrophic lateral sclerosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Juvenile gout, choreoathetosis, mental retardation syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Juvenile hyperuricemia syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('JWS');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('KD');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Kennedy disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Kennedy spinal and bulbar muscular atrophy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Kerasin histiocytosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Kerasin lipoidosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Kerasin thesaurismosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Ketotic glycinemia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Ketotic hyperglycinemia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Kidney diseases');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Klinefelter syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Kniest dysplasia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Krabbe disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Kugelberg–Welander disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Lacunar dementia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Langer-Saldino achondrogenesis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Langer-Saldino dysplasia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Late-onset Alzheimer disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Late-onset familial Alzheimer disease (AD2)');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Late-onset Krabbe disease (LOKD)');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Laurence–Moon syndrome (LMS)');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Learning Disorders');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Lentiginosis, perioral');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Lesch-Nyhan syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Leukodystrophies');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Leukodystrophy with Rosenthal fibers');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Leukodystrophy, spongiform');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('LFS');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Li-Fraumeni syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Lipase D deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('LIPD deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Lipidosis, cerebroside');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Lipidosis, ganglioside, infantile');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Lipoid histiocytosis (kerasin type)');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Lipoprotein lipase deficiency, familial');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Liver diseases');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Lou Gehrig disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Louis-Bar syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Lynch syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Lysyl-hydroxylase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Machado-Joseph disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Male breast cancer');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Male genital disorders');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Malignant neoplasm of breast');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Malignant tumor of breast');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Malignant tumor of urinary bladder');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Mammary cancer');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Marfan syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Marker X syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Martin-Bell syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('McCune–Albright syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('McLeod syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Mediterranean Anemia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Mediterranean fever, familial');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('MEDNIK[2][3]');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Mega-epiphyseal dwarfism');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Menkea syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Menkes disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Mental retardation with osteocartilaginous abnormalities');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Metabolic disorders');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Metatropic dwarfism, type II');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Metatropic dysplasia type II');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Methemoglobinemia#beta-globin type');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Methylmalonic acidemia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('MFS');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('MHAM');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Micro syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Microcephaly');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('MK');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('MMA');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('MNK');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Monosomy 1p36 syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Motor neuron disease, amyotrophic lateral sclerosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Movement disorders');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Mowat-Wilson syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Mucopolysaccharidosis (MPS I)');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Mucoviscidosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Muenke syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Multi-Infarct dementia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Multiple carboxylase deficiency, late-onset');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Multiple hamartoma syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Multiple neurofibromatosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Muscular dystrophy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Muscular dystrophy, Duchenne and Becker type');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Myotonia atrophica');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Myotonia dystrophica');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Myotonic dystrophy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Nance-Insley syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Nance-Sweeney chondrodysplasia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('NBIA1');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Neill-Dingwall syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Neuroblastoma, retinal');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Neurodegeneration with brain iron accumulation type 1');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Neurofibromatosis type I');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Neurofibromatosis type II');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Neurologic diseases');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Neuromuscular disorders');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Neuronopathy, distal hereditary motor, type V');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Neuronopathy, distal hereditary motor, with pyramidal features');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Niemann-Pick');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Noack syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Nonketotic hyperglycinemia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Non-neuronopathic Gaucher disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Non-phenylketonuric hyperphenylalaninemia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Nonsyndromic deafness');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Noonan syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Norrbottnian Gaucher disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Ochronosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Ochronotic arthritis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Ogden syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('OI');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Or substitution');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Osler-Weber-Rendu disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('OSMED');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Osteogenesis imperfecta');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Osteopsathyrosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Osteosclerosis congenita');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Oto-spondylo-megaepiphyseal dysplasia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Otospondylomegaepiphyseal dysplasia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Oxalosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Oxaluria, primary');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Pantothenate kinase-associated neurodegeneration');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Patau Syndrome (Trisomy 13)');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('PBGD deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('PCC deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('PCT');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('PDM');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Pendred syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Periodic disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Periodic peritonitis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Periorificial lentiginosis syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Peripheral nerve disorders');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Peripheral neurofibromatosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Peroneal muscular atrophy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Peroxisomal alanine:glyoxylate aminotransferase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Peutz-Jeghers syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Pfeiffer syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Phenylalanine hydroxylase deficiency disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Phenylketonuria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Pheochromocytoma');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Pierre Robin syndrome with fetal chondrodysplasia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Pigmentary cirrhosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('PJS');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('PKAN');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('PKU');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Plumboporphyria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('PMA');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Polycystic kidney disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Polyostotic fibrous dysplasia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Polyposis coli');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Polyposis, hamartomatous intestinal');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Polyposis, intestinal, II');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Polyps-and-spots syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Porphobilinogen synthase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Porphyria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Porphyrin disorder');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('PPH');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('PPOX deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Prader-Labhart-Willi syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Prader-Willi syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Presenile and senile dementia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Primary ciliary dyskinesia (PCD)');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Primary hemochromatosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Primary hyperuricemia syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Primary pulmonary hypertension');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Primary senile degenerative dementia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Procollagen type EDS VII, mutant');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Progeria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Progeria-like syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Progeroid nanism');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Progressive chorea, chronic hereditary (Huntington)');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Progressively deforming osteogenesis imperfecta with normal sclerae');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('PROMM');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Propionic acidemia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Propionyl-CoA carboxylase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Protein C deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Protein S deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Protoporphyria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Protoporphyrinogen oxidase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Proximal myotonic dystrophy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Proximal myotonic myopathy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Pseudo-Gaucher disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Pseudoxanthoma elasticum');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Psychosine lipidosis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Pulmonary arterial hypertension');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Pulmonary hypertension');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('PWS');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('PXE - pseudoxanthoma elasticum');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Rb');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Recklinghausen disease, nerve');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Recurrent polyserositis');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Retinal disorders');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Retinitis pigmentosa-deafness syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Retinoblastoma');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Rett syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('RFALS type 3');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Ricker syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Riley-Day syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Roussy-Levy syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('RSTS');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('RTS');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('RTT');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Rubinstein-Taybi syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Sack-Barabas syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('SADDAN');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Sarcoma family syndrome of Li and Fraumeni');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Sarcoma, breast, leukemia, and adrenal gland (SBLA) syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('SBLA syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('SBMA');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('SCD');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Schwannoma, acoustic, bilateral');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Schwartz–Jampel syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('SCIDX1');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('SDAT');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('SED congenita');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('SED Strudwick');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('SEDc');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('SEMD, Strudwick type');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Senile dementia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Severe achondroplasia with developmental delay and acanthosis nigricans');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Shprintzen syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Sickle cell anemia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Siderius X-linked mental retardation syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Skeleton-skin-brain syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Skin pigmentation disorders');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('SMA');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('SMED, Strudwick type');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('SMED, type I');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Smith Magenis Syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Smith-Lemli-Opitz syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('South-African genetic porphyria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Spastic paralysis, infantile onset ascending');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Speech and communication disorders');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Sphingolipidosis, Tay-Sachs');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Sphingomyelin phosphodiesterase 1');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Spinal and bulbar muscular atrophy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Spinal muscular atrophy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Spinal muscular atrophy, distal type V');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Spinal muscular atrophy, distal, with upper limb predominance');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Spinocerebellar ataxia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Spondyloepimetaphyseal dysplasia, Strudwick type');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Spondyloepiphyseal dysplasia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Spondyloepiphyseal dysplasia congenita');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Spondylometaepiphyseal dysplasia congenita, Strudwick type');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Spondylometaphyseal dysplasia (SMD)');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Spondylometaphyseal dysplasia, Strudwick type');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Spongy degeneration of central nervous system');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Spongy degeneration of the brain');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Spongy degeneration of white matter in infancy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Sporadic primary pulmonary hypertension');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('SSB syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Steely hair syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Steinert disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Steinert myotonic dystrophy syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Stickler syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Stroke');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Strudwick syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Subacute neuronopathic Gaucher disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Swedish genetic porphyria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Swedish porphyria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Swiss cheese cartilage dysplasia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Tay-Sachs disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('TD - thanatophoric dwarfism');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('TD with straight femurs and cloverleaf skull');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Telangiectasia, cerebello-oculocutaneous');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Testicular feminization syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Tetrahydrobiopterin deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('TFM - testicular feminization syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Thalassemia intermedia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Thalassemia Major');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Thanatophoric dysplasia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Thrombophilia due to deficiency of cofactor for activated protein C, Leiden type');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Thyroid disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Tomaculous neuropathy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Total HPRT deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Total hypoxanthine-guanine phosphoribosyl transferase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Treacher Collins syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Trias fragilitis ossium');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Triple X syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Triplo X syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Trisomy 21');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Trisomy X');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Troisier-Hanot-Chauffard syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('TSD');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Tuberous Sclerosis Complex (TSC)');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Turner-like syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Turner''s syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Type 2 Gaucher disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Type 3 Gaucher disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('UDP glucose 4-epimerase deficiency disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('UDP glucose hexose-1-phosphate uridylyltransferase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('UDP-galactose-4-epimerase deficiency disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Undifferentiated deafness');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('UPS deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Urinary bladder cancer');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('UROD deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Uroporphyrinogen decarboxylase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Uroporphyrinogen synthase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Usher syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('UTP hexose-1-phosphate uridylyltransferase deficiency');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Van Bogaert-Bertrand syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Van der Hoeve syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Variegate porphyria');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Velocardiofacial syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('VHL syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Vision impairment and blindness');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Von Bogaert-Bertrand disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Von Hippel-Lindau disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Von Recklenhausen-Applebaum disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Von Recklinghausen disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('VP');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Vrolik disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Waardenburg syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Warburg Sjo Fledelius Syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('WD');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Weissenbacher-Zweymüller syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Werdnig–Hoffmann disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Williams Syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Wilson disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Wilson''s disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Wolff Periodic disease');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Wolf–Hirschhorn syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('WZS');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('Xeroderma pigmentosum');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('X-linked mental retardation and macroorchidism');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('X-linked primary hyperuricemia');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('X-linked severe combined immunodeficiency ');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('X-linked sideroblastic anemia ');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('X-linked spinal-bulbar muscle atrophy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('X-linked uric aciduria enzyme defect');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('XLSA');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('XSCID');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('X-SCID');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('XXX syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('XXXX syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('XXXXX syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('XXY syndrome');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('XXY trisomy');
INSERT INTO Project_Dropdown_Task_FINAL_Ver_1_11_1_1 VALUES ('XYY syndrome');
