CREATE TABLE data_sports (
    `Column_1` VARCHAR(64) CHARACTER SET utf8
);
INSERT INTO data_sports VALUES ('10k run');
INSERT INTO data_sports VALUES ('16-inch softball');
INSERT INTO data_sports VALUES ('5k run');
INSERT INTO data_sports VALUES ('Abseiling');
INSERT INTO data_sports VALUES ('Adventure racing');
INSERT INTO data_sports VALUES ('Aerobatics');
INSERT INTO data_sports VALUES ('Aid climbing');
INSERT INTO data_sports VALUES ('Aikido');
INSERT INTO data_sports VALUES ('Aiki-jujutsu');
INSERT INTO data_sports VALUES ('Air racing');
INSERT INTO data_sports VALUES ('Air sports');
INSERT INTO data_sports VALUES ('Airsoft');
INSERT INTO data_sports VALUES ('All-terrain vehicle competition');
INSERT INTO data_sports VALUES ('Alpine skiing');
INSERT INTO data_sports VALUES ('Amateur pankration');
INSERT INTO data_sports VALUES ('Amateur wrestling');
INSERT INTO data_sports VALUES ('American flag rugby');
INSERT INTO data_sports VALUES ('American football');
INSERT INTO data_sports VALUES ('American handball');
INSERT INTO data_sports VALUES ('American snooker');
INSERT INTO data_sports VALUES ('Ancient games');
INSERT INTO data_sports VALUES ('Angling');
INSERT INTO data_sports VALUES ('Apnoea finswimming');
INSERT INTO data_sports VALUES ('Aquathlon (underwater wrestling)');
INSERT INTO data_sports VALUES ('Aquatic & paddle sports');
INSERT INTO data_sports VALUES ('Aquatic ball sports');
INSERT INTO data_sports VALUES ('Archery');
INSERT INTO data_sports VALUES ('Arena football');
INSERT INTO data_sports VALUES ('Artistic billiards');
INSERT INTO data_sports VALUES ('Artistic cycling');
INSERT INTO data_sports VALUES ('Artistic gymnastics');
INSERT INTO data_sports VALUES ('Artistic pool');
INSERT INTO data_sports VALUES ('Association football');
INSERT INTO data_sports VALUES ('ATV racing');
INSERT INTO data_sports VALUES ('Australian football');
INSERT INTO data_sports VALUES ('Australian handball');
INSERT INTO data_sports VALUES ('Austus');
INSERT INTO data_sports VALUES ('Auto race');
INSERT INTO data_sports VALUES ('Auto racing');
INSERT INTO data_sports VALUES ('Autocross (aka slalom)');
INSERT INTO data_sports VALUES ('Autograss');
INSERT INTO data_sports VALUES ('Axe throwing');
INSERT INTO data_sports VALUES ('Ba game');
INSERT INTO data_sports VALUES ('Backpacking (wilderness)');
INSERT INTO data_sports VALUES ('Backstroke');
INSERT INTO data_sports VALUES ('Badminton');
INSERT INTO data_sports VALUES ('Bagatelle');
INSERT INTO data_sports VALUES ('Baguazhang');
INSERT INTO data_sports VALUES ('Balance beam');
INSERT INTO data_sports VALUES ('Balkline and straight rail');
INSERT INTO data_sports VALUES ('Ball');
INSERT INTO data_sports VALUES ('Ball badminton');
INSERT INTO data_sports VALUES ('Ball hockey');
INSERT INTO data_sports VALUES ('Ballooning');
INSERT INTO data_sports VALUES ('Ball-over-net games');
INSERT INTO data_sports VALUES ('Bando');
INSERT INTO data_sports VALUES ('Bandy');
INSERT INTO data_sports VALUES ('Banger racing');
INSERT INTO data_sports VALUES ('Bank pool');
INSERT INTO data_sports VALUES ('Banzai skydiving');
INSERT INTO data_sports VALUES ('Bar billiards');
INSERT INTO data_sports VALUES ('Bareback bronc riding');
INSERT INTO data_sports VALUES ('Barrel racing');
INSERT INTO data_sports VALUES ('Bartitsu');
INSERT INTO data_sports VALUES ('Base jumping');
INSERT INTO data_sports VALUES ('Baseball');
INSERT INTO data_sports VALUES ('Baseball pocket billiards');
INSERT INTO data_sports VALUES ('Basketball');
INSERT INTO data_sports VALUES ('Basketball family');
INSERT INTO data_sports VALUES ('Basque pelota');
INSERT INTO data_sports VALUES ('Basque traditional weightlifting');
INSERT INTO data_sports VALUES ('Bat and trap');
INSERT INTO data_sports VALUES ('Bat-and-ball (safe haven)');
INSERT INTO data_sports VALUES ('Baton twirling');
INSERT INTO data_sports VALUES ('Battojutsu');
INSERT INTO data_sports VALUES ('Beach basketball');
INSERT INTO data_sports VALUES ('Beach handball');
INSERT INTO data_sports VALUES ('Beach rugby');
INSERT INTO data_sports VALUES ('Beach soccer');
INSERT INTO data_sports VALUES ('Beach tennis');
INSERT INTO data_sports VALUES ('Beach ultimate');
INSERT INTO data_sports VALUES ('Beach volleyball');
INSERT INTO data_sports VALUES ('Beagling');
INSERT INTO data_sports VALUES ('Benchrest shooting');
INSERT INTO data_sports VALUES ('Biathlon');
INSERT INTO data_sports VALUES ('Bicycle');
INSERT INTO data_sports VALUES ('Bicycle polo');
INSERT INTO data_sports VALUES ('Bifins (finswimming)');
INSERT INTO data_sports VALUES ('Big game fishing');
INSERT INTO data_sports VALUES ('Big game hunting');
INSERT INTO data_sports VALUES ('Biribol');
INSERT INTO data_sports VALUES ('Blackball (a.k.a. British eight-ball pool)');
INSERT INTO data_sports VALUES ('Bmx');
INSERT INTO data_sports VALUES ('Board sports');
INSERT INTO data_sports VALUES ('Board track racing');
INSERT INTO data_sports VALUES ('Bobsleigh');
INSERT INTO data_sports VALUES ('Bodyboarding');
INSERT INTO data_sports VALUES ('Bodybuilding');
INSERT INTO data_sports VALUES ('Boffer fighting');
INSERT INTO data_sports VALUES ('Bokator');
INSERT INTO data_sports VALUES ('Boli khela');
INSERT INTO data_sports VALUES ('Bossaball');
INSERT INTO data_sports VALUES ('Bottle pool');
INSERT INTO data_sports VALUES ('Bouldering');
INSERT INTO data_sports VALUES ('Bowlliards');
INSERT INTO data_sports VALUES ('Box lacrosse');
INSERT INTO data_sports VALUES ('Boxing');
INSERT INTO data_sports VALUES ('Brännboll - four bases');
INSERT INTO data_sports VALUES ('Brazilian jiu-jitsu');
INSERT INTO data_sports VALUES ('Break-away roping');
INSERT INTO data_sports VALUES ('Breaststroke');
INSERT INTO data_sports VALUES ('British baseball - four posts');
INSERT INTO data_sports VALUES ('British bulldogs (american eagle)');
INSERT INTO data_sports VALUES ('Bronc riding');
INSERT INTO data_sports VALUES ('Broomball');
INSERT INTO data_sports VALUES ('Bucketball');
INSERT INTO data_sports VALUES ('Bujinkan');
INSERT INTO data_sports VALUES ('Bullriding');
INSERT INTO data_sports VALUES ('Bumper pool');
INSERT INTO data_sports VALUES ('Bushwhacking');
INSERT INTO data_sports VALUES ('Butterfly stroke');
INSERT INTO data_sports VALUES ('Butts up');
INSERT INTO data_sports VALUES ('Buzkashi');
INSERT INTO data_sports VALUES ('Caid');
INSERT INTO data_sports VALUES ('Calcio fiorentino');
INSERT INTO data_sports VALUES ('Calf roping');
INSERT INTO data_sports VALUES ('Cammag');
INSERT INTO data_sports VALUES ('Camogie');
INSERT INTO data_sports VALUES ('Campdrafting');
INSERT INTO data_sports VALUES ('Camping (game)');
INSERT INTO data_sports VALUES ('Canadian football');
INSERT INTO data_sports VALUES ('Canoe polo');
INSERT INTO data_sports VALUES ('Canoeing');
INSERT INTO data_sports VALUES ('Canyoning');
INSERT INTO data_sports VALUES ('Canyoning (canyoneering)');
INSERT INTO data_sports VALUES ('Capoeira');
INSERT INTO data_sports VALUES ('Capture the flag');
INSERT INTO data_sports VALUES ('Card stacking');
INSERT INTO data_sports VALUES ('Carom billiards');
INSERT INTO data_sports VALUES ('Casterboarding');
INSERT INTO data_sports VALUES ('Casting');
INSERT INTO data_sports VALUES ('Catch games');
INSERT INTO data_sports VALUES ('Catch wrestling');
INSERT INTO data_sports VALUES ('Cestoball');
INSERT INTO data_sports VALUES ('Charreada');
INSERT INTO data_sports VALUES ('Cheerleading');
INSERT INTO data_sports VALUES ('Chester-le-street');
INSERT INTO data_sports VALUES ('Chicago');
INSERT INTO data_sports VALUES ('Chilean rodeo');
INSERT INTO data_sports VALUES ('Chinese handball');
INSERT INTO data_sports VALUES ('Chinlone');
INSERT INTO data_sports VALUES ('Choi kwang-do');
INSERT INTO data_sports VALUES ('Cirit');
INSERT INTO data_sports VALUES ('Clay pigeon shooting');
INSERT INTO data_sports VALUES ('Climbing');
INSERT INTO data_sports VALUES ('Club');
INSERT INTO data_sports VALUES ('Cluster ballooning');
INSERT INTO data_sports VALUES ('Cnapan');
INSERT INTO data_sports VALUES ('Coastal and ocean rowing');
INSERT INTO data_sports VALUES ('Coasteering');
INSERT INTO data_sports VALUES ('Cockfighting');
INSERT INTO data_sports VALUES ('Color guard (flag spinning)');
INSERT INTO data_sports VALUES ('Combat sports: wrestling and martial arts');
INSERT INTO data_sports VALUES ('Competitive cheerleading');
INSERT INTO data_sports VALUES ('Competitive dance');
INSERT INTO data_sports VALUES ('Competitive swimming');
INSERT INTO data_sports VALUES ('Composite rules shinty-hurling');
INSERT INTO data_sports VALUES ('Corkball - four bases (no base-running)');
INSERT INTO data_sports VALUES ('Cornish hurling');
INSERT INTO data_sports VALUES ('Cowboy');
INSERT INTO data_sports VALUES ('Cowboy action shooting');
INSERT INTO data_sports VALUES ('Cowboy polo');
INSERT INTO data_sports VALUES ('Creeking');
INSERT INTO data_sports VALUES ('Cribbage (pool)');
INSERT INTO data_sports VALUES ('Cricket - two creases');
INSERT INTO data_sports VALUES ('Cross country');
INSERT INTO data_sports VALUES ('Cross-country mountain biking');
INSERT INTO data_sports VALUES ('Cross-country rally');
INSERT INTO data_sports VALUES ('Cross-country running');
INSERT INTO data_sports VALUES ('Cross-country skiing');
INSERT INTO data_sports VALUES ('Cue sports');
INSERT INTO data_sports VALUES ('Cuju');
INSERT INTO data_sports VALUES ('Curling');
INSERT INTO data_sports VALUES ('Cushion caroms');
INSERT INTO data_sports VALUES ('Cutthroat');
INSERT INTO data_sports VALUES ('Cutting');
INSERT INTO data_sports VALUES ('Cycle polo');
INSERT INTO data_sports VALUES ('Cycle speedway');
INSERT INTO data_sports VALUES ('Cycling');
INSERT INTO data_sports VALUES ('Cyclo-cross');
INSERT INTO data_sports VALUES ('Czech handball');
INSERT INTO data_sports VALUES ('Dance');
INSERT INTO data_sports VALUES ('Dance marathon');
INSERT INTO data_sports VALUES ('Danish longball');
INSERT INTO data_sports VALUES ('Deaf basketball');
INSERT INTO data_sports VALUES ('Decathlon');
INSERT INTO data_sports VALUES ('Deep-water soloing');
INSERT INTO data_sports VALUES ('Deer hunting');
INSERT INTO data_sports VALUES ('Demolition derby');
INSERT INTO data_sports VALUES ('Desert racing');
INSERT INTO data_sports VALUES ('Dice stacking');
INSERT INTO data_sports VALUES ('Dinghy sailing');
INSERT INTO data_sports VALUES ('Dirt jumping');
INSERT INTO data_sports VALUES ('Dirt track racing');
INSERT INTO data_sports VALUES ('Disc dog');
INSERT INTO data_sports VALUES ('Disc golf');
INSERT INTO data_sports VALUES ('Disc golf (urban)');
INSERT INTO data_sports VALUES ('Diving');
INSERT INTO data_sports VALUES ('Dodge disc');
INSERT INTO data_sports VALUES ('Dodgeball');
INSERT INTO data_sports VALUES ('Double disc court');
INSERT INTO data_sports VALUES ('Downhill mountain biking');
INSERT INTO data_sports VALUES ('Drag boat racing');
INSERT INTO data_sports VALUES ('Drag racing');
INSERT INTO data_sports VALUES ('Dragon boat racing');
INSERT INTO data_sports VALUES ('Dressage');
INSERT INTO data_sports VALUES ('Drifting');
INSERT INTO data_sports VALUES ('Duathlon');
INSERT INTO data_sports VALUES ('Dumog');
INSERT INTO data_sports VALUES ('Egyptian stick fencing');
INSERT INTO data_sports VALUES ('Eight-ball');
INSERT INTO data_sports VALUES ('Eight-man football');
INSERT INTO data_sports VALUES ('Elephant polo');
INSERT INTO data_sports VALUES ('Endurance');
INSERT INTO data_sports VALUES ('Endurance racing');
INSERT INTO data_sports VALUES ('Endurance riding');
INSERT INTO data_sports VALUES ('Enduro');
INSERT INTO data_sports VALUES ('English billiards');
INSERT INTO data_sports VALUES ('English pleasure');
INSERT INTO data_sports VALUES ('English school games');
INSERT INTO data_sports VALUES ('Episkyros');
INSERT INTO data_sports VALUES ('Equestrian vaulting');
INSERT INTO data_sports VALUES ('Equine sports');
INSERT INTO data_sports VALUES ('Equitation');
INSERT INTO data_sports VALUES ('Eskrima');
INSERT INTO data_sports VALUES ('Eton fives');
INSERT INTO data_sports VALUES ('Eton wall game');
INSERT INTO data_sports VALUES ('Eventing');
INSERT INTO data_sports VALUES ('F1 powerboat racing');
INSERT INTO data_sports VALUES ('Fastnet');
INSERT INTO data_sports VALUES ('Fast-pitch softball');
INSERT INTO data_sports VALUES ('Fencing');
INSERT INTO data_sports VALUES ('Field archery');
INSERT INTO data_sports VALUES ('Field game');
INSERT INTO data_sports VALUES ('Field handball');
INSERT INTO data_sports VALUES ('Field hockey');
INSERT INTO data_sports VALUES ('Field lacrosse');
INSERT INTO data_sports VALUES ('Field target');
INSERT INTO data_sports VALUES ('Figure skating');
INSERT INTO data_sports VALUES ('Fire baton twirling');
INSERT INTO data_sports VALUES ('Fishing');
INSERT INTO data_sports VALUES ('Fistball');
INSERT INTO data_sports VALUES ('Five-a-side football');
INSERT INTO data_sports VALUES ('Five-pins');
INSERT INTO data_sports VALUES ('Fives');
INSERT INTO data_sports VALUES ('Flag football');
INSERT INTO data_sports VALUES ('Flight archery');
INSERT INTO data_sports VALUES ('Floor');
INSERT INTO data_sports VALUES ('Floorball');
INSERT INTO data_sports VALUES ('Flutterguts');
INSERT INTO data_sports VALUES ('Fly fishing');
INSERT INTO data_sports VALUES ('Flyak');
INSERT INTO data_sports VALUES ('Flying disc sports');
INSERT INTO data_sports VALUES ('Flying trapeze');
INSERT INTO data_sports VALUES ('Folk wrestling');
INSERT INTO data_sports VALUES ('Folkrace');
INSERT INTO data_sports VALUES ('Footbag net');
INSERT INTO data_sports VALUES ('Football');
INSERT INTO data_sports VALUES ('Football tennis');
INSERT INTO data_sports VALUES ('Footvolley');
INSERT INTO data_sports VALUES ('Formula libre');
INSERT INTO data_sports VALUES ('Formula racing');
INSERT INTO data_sports VALUES ('Formula student');
INSERT INTO data_sports VALUES ('Four square');
INSERT INTO data_sports VALUES ('Four-ball (yotsudama)');
INSERT INTO data_sports VALUES ('Fox hunting');
INSERT INTO data_sports VALUES ('Free running');
INSERT INTO data_sports VALUES ('Freeboard (skateboard)');
INSERT INTO data_sports VALUES ('Freeboating');
INSERT INTO data_sports VALUES ('Freediving');
INSERT INTO data_sports VALUES ('Freeride skiing');
INSERT INTO data_sports VALUES ('Freestyle');
INSERT INTO data_sports VALUES ('Freestyle bmx');
INSERT INTO data_sports VALUES ('Freestyle competition');
INSERT INTO data_sports VALUES ('Freestyle footbag');
INSERT INTO data_sports VALUES ('Freestyle football');
INSERT INTO data_sports VALUES ('Free-style moto');
INSERT INTO data_sports VALUES ('Freestyle motocross');
INSERT INTO data_sports VALUES ('Freestyle skiing');
INSERT INTO data_sports VALUES ('Freestyle swimming');
INSERT INTO data_sports VALUES ('Freestyle wrestling');
INSERT INTO data_sports VALUES ('Fricket (aka disc cricket, cups, suzy sticks and crispy wickets)');
INSERT INTO data_sports VALUES ('Frisian handball');
INSERT INTO data_sports VALUES ('Frontenis');
INSERT INTO data_sports VALUES ('Fujian white crane');
INSERT INTO data_sports VALUES ('Fullbore target rifle');
INSERT INTO data_sports VALUES ('Futebol de salão');
INSERT INTO data_sports VALUES ('Futsal');
INSERT INTO data_sports VALUES ('Gaelic football');
INSERT INTO data_sports VALUES ('Gaelic handball');
INSERT INTO data_sports VALUES ('Ga-ga');
INSERT INTO data_sports VALUES ('Gatka');
INSERT INTO data_sports VALUES ('Geocaching');
INSERT INTO data_sports VALUES ('Gig racing');
INSERT INTO data_sports VALUES ('Gliding');
INSERT INTO data_sports VALUES ('Glima');
INSERT INTO data_sports VALUES ('Goalball');
INSERT INTO data_sports VALUES ('Goaltimate');
INSERT INTO data_sports VALUES ('Goat tying');
INSERT INTO data_sports VALUES ('Golf');
INSERT INTO data_sports VALUES ('Grand prix motorcycle racing');
INSERT INTO data_sports VALUES ('Grappling');
INSERT INTO data_sports VALUES ('Grasstrack');
INSERT INTO data_sports VALUES ('Greco-roman wrestling');
INSERT INTO data_sports VALUES ('Greek wrestling');
INSERT INTO data_sports VALUES ('Gridiron football');
INSERT INTO data_sports VALUES ('Gungdo');
INSERT INTO data_sports VALUES ('Guts');
INSERT INTO data_sports VALUES ('Gymkhana');
INSERT INTO data_sports VALUES ('Gymnastics');
INSERT INTO data_sports VALUES ('Hala');
INSERT INTO data_sports VALUES ('Half marathon');
INSERT INTO data_sports VALUES ('Hana ichi monme');
INSERT INTO data_sports VALUES ('Handball family');
INSERT INTO data_sports VALUES ('Hang gliding');
INSERT INTO data_sports VALUES ('Hapkido');
INSERT INTO data_sports VALUES ('Hapsagai');
INSERT INTO data_sports VALUES ('Hardball squash');
INSERT INTO data_sports VALUES ('Hardcourt bike polo');
INSERT INTO data_sports VALUES ('Hare coursing');
INSERT INTO data_sports VALUES ('Harness racing');
INSERT INTO data_sports VALUES ('Harpastum');
INSERT INTO data_sports VALUES ('Harrow football');
INSERT INTO data_sports VALUES ('Haxey hood');
INSERT INTO data_sports VALUES ('Heptathlon');
INSERT INTO data_sports VALUES ('Hide and seek');
INSERT INTO data_sports VALUES ('High bar');
INSERT INTO data_sports VALUES ('High power rifle');
INSERT INTO data_sports VALUES ('Hiking');
INSERT INTO data_sports VALUES ('Hillclimbing');
INSERT INTO data_sports VALUES ('Hockey');
INSERT INTO data_sports VALUES ('Hojojutsu');
INSERT INTO data_sports VALUES ('Hoop');
INSERT INTO data_sports VALUES ('Hooverball');
INSERT INTO data_sports VALUES ('Hopper ballooning');
INSERT INTO data_sports VALUES ('Hornussen');
INSERT INTO data_sports VALUES ('Horse polo');
INSERT INTO data_sports VALUES ('Horse racing');
INSERT INTO data_sports VALUES ('Horseball');
INSERT INTO data_sports VALUES ('Hot box');
INSERT INTO data_sports VALUES ('Human powered aircraft');
INSERT INTO data_sports VALUES ('Hunter');
INSERT INTO data_sports VALUES ('Hunter-jumpers');
INSERT INTO data_sports VALUES ('Hunting');
INSERT INTO data_sports VALUES ('Hurdles');
INSERT INTO data_sports VALUES ('Hurling');
INSERT INTO data_sports VALUES ('Hurling and shinty');
INSERT INTO data_sports VALUES ('Hwa rang do');
INSERT INTO data_sports VALUES ('Hybrid carom–pocket games');
INSERT INTO data_sports VALUES ('Hybrid codes');
INSERT INTO data_sports VALUES ('Hydroplane racing');
INSERT INTO data_sports VALUES ('Iaido');
INSERT INTO data_sports VALUES ('Iaijutsu');
INSERT INTO data_sports VALUES ('Ice climbing');
INSERT INTO data_sports VALUES ('Ice fishing');
INSERT INTO data_sports VALUES ('Ice hockey');
INSERT INTO data_sports VALUES ('Ice racing');
INSERT INTO data_sports VALUES ('Ice speedway');
INSERT INTO data_sports VALUES ('Ice sports');
INSERT INTO data_sports VALUES ('Ice yachting');
INSERT INTO data_sports VALUES ('Icosathlon');
INSERT INTO data_sports VALUES ('Immersion finswimming');
INSERT INTO data_sports VALUES ('Individual medley');
INSERT INTO data_sports VALUES ('Indoor archery');
INSERT INTO data_sports VALUES ('Indoor cricket');
INSERT INTO data_sports VALUES ('Indoor enduro');
INSERT INTO data_sports VALUES ('Indoor field hockey');
INSERT INTO data_sports VALUES ('Indoor football');
INSERT INTO data_sports VALUES ('Indoor netball');
INSERT INTO data_sports VALUES ('Indoor percussion');
INSERT INTO data_sports VALUES ('Indoor soccer');
INSERT INTO data_sports VALUES ('Inline hockey');
INSERT INTO data_sports VALUES ('Intercrosse');
INSERT INTO data_sports VALUES ('International fronton');
INSERT INTO data_sports VALUES ('International rules football');
INSERT INTO data_sports VALUES ('Jai alai');
INSERT INTO data_sports VALUES ('Jeet kune do');
INSERT INTO data_sports VALUES ('Jet sprint boat racing');
INSERT INTO data_sports VALUES ('Jeu de paume');
INSERT INTO data_sports VALUES ('Jodo');
INSERT INTO data_sports VALUES ('Jogo do pau');
INSERT INTO data_sports VALUES ('Jorkyball');
INSERT INTO data_sports VALUES ('Jousting');
INSERT INTO data_sports VALUES ('Judo');
INSERT INTO data_sports VALUES ('Jugger');
INSERT INTO data_sports VALUES ('Juggling');
INSERT INTO data_sports VALUES ('Jujutsu');
INSERT INTO data_sports VALUES ('Jukendo');
INSERT INTO data_sports VALUES ('Juttejutsu');
INSERT INTO data_sports VALUES ('Kabaddi');
INSERT INTO data_sports VALUES ('Kajukenbo');
INSERT INTO data_sports VALUES ('Kalarippayattu');
INSERT INTO data_sports VALUES ('Karate');
INSERT INTO data_sports VALUES ('Kart racing');
INSERT INTO data_sports VALUES ('Kayaking');
INSERT INTO data_sports VALUES ('Keep away');
INSERT INTO data_sports VALUES ('Keepie uppie');
INSERT INTO data_sports VALUES ('Kelly pool');
INSERT INTO data_sports VALUES ('Kemari');
INSERT INTO data_sports VALUES ('Kendo');
INSERT INTO data_sports VALUES ('Kenjutsu');
INSERT INTO data_sports VALUES ('Kenpo');
INSERT INTO data_sports VALUES ('Kho kho');
INSERT INTO data_sports VALUES ('Kick the can');
INSERT INTO data_sports VALUES ('Kickball');
INSERT INTO data_sports VALUES ('Kickboxing');
INSERT INTO data_sports VALUES ('Kilikiti');
INSERT INTO data_sports VALUES ('Killer');
INSERT INTO data_sports VALUES ('Kin-ball');
INSERT INTO data_sports VALUES ('Kindred activities');
INSERT INTO data_sports VALUES ('Kinomichi');
INSERT INTO data_sports VALUES ('Ki-o-rahi');
INSERT INTO data_sports VALUES ('Kite buggy');
INSERT INTO data_sports VALUES ('Kite fighting');
INSERT INTO data_sports VALUES ('Kite landboarding');
INSERT INTO data_sports VALUES ('Kite sports');
INSERT INTO data_sports VALUES ('Kiteboarding');
INSERT INTO data_sports VALUES ('Kitesurfing');
INSERT INTO data_sports VALUES ('Knattleikr');
INSERT INTO data_sports VALUES ('Kneeboarding');
INSERT INTO data_sports VALUES ('Korfball');
INSERT INTO data_sports VALUES ('Krabi-krabong');
INSERT INTO data_sports VALUES ('Krav maga');
INSERT INTO data_sports VALUES ('Kronum');
INSERT INTO data_sports VALUES ('Kuk sool won');
INSERT INTO data_sports VALUES ('Kumdo');
INSERT INTO data_sports VALUES ('Kung fu');
INSERT INTO data_sports VALUES ('Kurash');
INSERT INTO data_sports VALUES ('Kyudo');
INSERT INTO data_sports VALUES ('Kyujutsu');
INSERT INTO data_sports VALUES ('La soule');
INSERT INTO data_sports VALUES ('Lacrosse');
INSERT INTO data_sports VALUES ('Ladies'' gaelic football');
INSERT INTO data_sports VALUES ('Lancashire wrestling');
INSERT INTO data_sports VALUES ('Land sailing');
INSERT INTO data_sports VALUES ('Land speed records');
INSERT INTO data_sports VALUES ('Land windsurfing');
INSERT INTO data_sports VALUES ('Lapta – two salos (bases)');
INSERT INTO data_sports VALUES ('Laser tag');
INSERT INTO data_sports VALUES ('Legends car racing');
INSERT INTO data_sports VALUES ('Lelo burti');
INSERT INTO data_sports VALUES ('Lethwei');
INSERT INTO data_sports VALUES ('Letterboxing');
INSERT INTO data_sports VALUES ('Limited overs cricket');
INSERT INTO data_sports VALUES ('Longboarding');
INSERT INTO data_sports VALUES ('Luge');
INSERT INTO data_sports VALUES ('Malla-yuddha');
INSERT INTO data_sports VALUES ('Marathon');
INSERT INTO data_sports VALUES ('Marching band');
INSERT INTO data_sports VALUES ('Marker sports');
INSERT INTO data_sports VALUES ('Marn grook');
INSERT INTO data_sports VALUES ('Masters football');
INSERT INTO data_sports VALUES ('Masters rugby league');
INSERT INTO data_sports VALUES ('Matball');
INSERT INTO data_sports VALUES ('Match play');
INSERT INTO data_sports VALUES ('Mcmap');
INSERT INTO data_sports VALUES ('Medieval football');
INSERT INTO data_sports VALUES ('Medley relay');
INSERT INTO data_sports VALUES ('Metallic silhouette');
INSERT INTO data_sports VALUES ('Metallic silhouette shooting');
INSERT INTO data_sports VALUES ('Metro footy');
INSERT INTO data_sports VALUES ('Midget car racing');
INSERT INTO data_sports VALUES ('Mini footy');
INSERT INTO data_sports VALUES ('Mini rugby');
INSERT INTO data_sports VALUES ('Miniature golf');
INSERT INTO data_sports VALUES ('Mixed climbing');
INSERT INTO data_sports VALUES ('Mixed discipline');
INSERT INTO data_sports VALUES ('Mixed martial arts');
INSERT INTO data_sports VALUES ('Mixed or hybrid');
INSERT INTO data_sports VALUES ('Mob football');
INSERT INTO data_sports VALUES ('Mod league');
INSERT INTO data_sports VALUES ('Model aerobatics');
INSERT INTO data_sports VALUES ('Model aircraft');
INSERT INTO data_sports VALUES ('Modern arnis');
INSERT INTO data_sports VALUES ('Modern pentathlon');
INSERT INTO data_sports VALUES ('Mongolian wrestling');
INSERT INTO data_sports VALUES ('Monster truck');
INSERT INTO data_sports VALUES ('Moscow broomball');
INSERT INTO data_sports VALUES ('Motocross');
INSERT INTO data_sports VALUES ('Motorboat racing');
INSERT INTO data_sports VALUES ('Motorcycle drag racing');
INSERT INTO data_sports VALUES ('Motorcycle racing');
INSERT INTO data_sports VALUES ('Motorcycle speedway');
INSERT INTO data_sports VALUES ('Motorized sports');
INSERT INTO data_sports VALUES ('Mountain unicycling');
INSERT INTO data_sports VALUES ('Mountainboarding');
INSERT INTO data_sports VALUES ('Mountaineering');
INSERT INTO data_sports VALUES ('Muay thai');
INSERT INTO data_sports VALUES ('Mud bogging');
INSERT INTO data_sports VALUES ('Musical sports');
INSERT INTO data_sports VALUES ('Naginatajutsu');
INSERT INTO data_sports VALUES ('Netball');
INSERT INTO data_sports VALUES ('Newcomb ball');
INSERT INTO data_sports VALUES ('Nguni stick-fighting');
INSERT INTO data_sports VALUES ('Nine-a-side footy');
INSERT INTO data_sports VALUES ('Nine-ball');
INSERT INTO data_sports VALUES ('Nine-man football');
INSERT INTO data_sports VALUES ('Ninjutsu');
INSERT INTO data_sports VALUES ('Noodling');
INSERT INTO data_sports VALUES ('Nordic combined');
INSERT INTO data_sports VALUES ('Nordic skiing');
INSERT INTO data_sports VALUES ('Northern praying mantis');
INSERT INTO data_sports VALUES ('Novuss (and cued forms of carrom)');
INSERT INTO data_sports VALUES ('Obstacle variations');
INSERT INTO data_sports VALUES ('Off-road racing');
INSERT INTO data_sports VALUES ('Off-roading');
INSERT INTO data_sports VALUES ('Offshore powerboat racing');
INSERT INTO data_sports VALUES ('Oina');
INSERT INTO data_sports VALUES ('Okinawan kobudo');
INSERT INTO data_sports VALUES ('Old cat – variable');
INSERT INTO data_sports VALUES ('Olympic weightlifting');
INSERT INTO data_sports VALUES ('One day international');
INSERT INTO data_sports VALUES ('One-pocket');
INSERT INTO data_sports VALUES ('Orienteering');
INSERT INTO data_sports VALUES ('Orienteering family');
INSERT INTO data_sports VALUES ('Other');
INSERT INTO data_sports VALUES ('Other paddling sports');
INSERT INTO data_sports VALUES ('Outrigger canoeing');
INSERT INTO data_sports VALUES ('Over-the-line – qv');
INSERT INTO data_sports VALUES ('Oztag');
INSERT INTO data_sports VALUES ('Paintball');
INSERT INTO data_sports VALUES ('Palant');
INSERT INTO data_sports VALUES ('Paleta frontón');
INSERT INTO data_sports VALUES ('Palla');
INSERT INTO data_sports VALUES ('Pankration');
INSERT INTO data_sports VALUES ('Papi fut');
INSERT INTO data_sports VALUES ('Parachuting');
INSERT INTO data_sports VALUES ('Paragliding');
INSERT INTO data_sports VALUES ('Parallel bars');
INSERT INTO data_sports VALUES ('Paralympic football');
INSERT INTO data_sports VALUES ('Paralympic volleyball');
INSERT INTO data_sports VALUES ('Paramotoring');
INSERT INTO data_sports VALUES ('Parasailing');
INSERT INTO data_sports VALUES ('Parkour');
INSERT INTO data_sports VALUES ('Patball');
INSERT INTO data_sports VALUES ('Pato');
INSERT INTO data_sports VALUES ('Pehlwani');
INSERT INTO data_sports VALUES ('Pelota mixteca');
INSERT INTO data_sports VALUES ('Pencak silat');
INSERT INTO data_sports VALUES ('Pentathlon');
INSERT INTO data_sports VALUES ('Personal water craft');
INSERT INTO data_sports VALUES ('Pesäpallo – four bases');
INSERT INTO data_sports VALUES ('Peteca');
INSERT INTO data_sports VALUES ('Pickleball');
INSERT INTO data_sports VALUES ('Pickup truck racing');
INSERT INTO data_sports VALUES ('Pilota family');
INSERT INTO data_sports VALUES ('Piton');
INSERT INTO data_sports VALUES ('Platform tennis');
INSERT INTO data_sports VALUES ('Pocket billiards (pool)');
INSERT INTO data_sports VALUES ('Pole bending');
INSERT INTO data_sports VALUES ('Pole climbing');
INSERT INTO data_sports VALUES ('Polo');
INSERT INTO data_sports VALUES ('Polocrosse');
INSERT INTO data_sports VALUES ('Pommel horse');
INSERT INTO data_sports VALUES ('Pond hockey');
INSERT INTO data_sports VALUES ('Popinjay');
INSERT INTO data_sports VALUES ('Power hockey');
INSERT INTO data_sports VALUES ('Powerbocking');
INSERT INTO data_sports VALUES ('Powerchair football');
INSERT INTO data_sports VALUES ('Powered hang glider');
INSERT INTO data_sports VALUES ('Powered paragliding');
INSERT INTO data_sports VALUES ('Powerlifting');
INSERT INTO data_sports VALUES ('Practical shooting');
INSERT INTO data_sports VALUES ('Pradal serey');
INSERT INTO data_sports VALUES ('Production car racing');
INSERT INTO data_sports VALUES ('Professional wrestling');
INSERT INTO data_sports VALUES ('Punchball');
INSERT INTO data_sports VALUES ('Qianball');
INSERT INTO data_sports VALUES ('Quidditch');
INSERT INTO data_sports VALUES ('Race of champions');
INSERT INTO data_sports VALUES ('Racewalking');
INSERT INTO data_sports VALUES ('Racketlon');
INSERT INTO data_sports VALUES ('Racquet (or racket) sports');
INSERT INTO data_sports VALUES ('Racquetball');
INSERT INTO data_sports VALUES ('Racquets');
INSERT INTO data_sports VALUES ('Rafting');
INSERT INTO data_sports VALUES ('Rally raid');
INSERT INTO data_sports VALUES ('Rallycross');
INSERT INTO data_sports VALUES ('Rallying');
INSERT INTO data_sports VALUES ('Rc racing');
INSERT INTO data_sports VALUES ('Real tennis');
INSERT INTO data_sports VALUES ('Rec footy');
INSERT INTO data_sports VALUES ('Red rover');
INSERT INTO data_sports VALUES ('Reduced variants');
INSERT INTO data_sports VALUES ('Regularity rally');
INSERT INTO data_sports VALUES ('Reining');
INSERT INTO data_sports VALUES ('Remote control');
INSERT INTO data_sports VALUES ('Rhythmic gymnastics');
INSERT INTO data_sports VALUES ('Ribbon');
INSERT INTO data_sports VALUES ('Ringball');
INSERT INTO data_sports VALUES ('Ringette');
INSERT INTO data_sports VALUES ('Ringo');
INSERT INTO data_sports VALUES ('Rink bandy');
INSERT INTO data_sports VALUES ('Riverboarding');
INSERT INTO data_sports VALUES ('Road bicycle racing');
INSERT INTO data_sports VALUES ('Road racing');
INSERT INTO data_sports VALUES ('Road running');
INSERT INTO data_sports VALUES ('Robot combat');
INSERT INTO data_sports VALUES ('Rock climbing');
INSERT INTO data_sports VALUES ('Rock fishing');
INSERT INTO data_sports VALUES ('Rodeo');
INSERT INTO data_sports VALUES ('Rodeo-originated');
INSERT INTO data_sports VALUES ('Rogaining');
INSERT INTO data_sports VALUES ('Roller hockey');
INSERT INTO data_sports VALUES ('Roller hockey (quad)');
INSERT INTO data_sports VALUES ('Rope');
INSERT INTO data_sports VALUES ('Rope climbing');
INSERT INTO data_sports VALUES ('Rope jumping');
INSERT INTO data_sports VALUES ('Roping');
INSERT INTO data_sports VALUES ('Rossall hockey');
INSERT INTO data_sports VALUES ('Rotation');
INSERT INTO data_sports VALUES ('Rounders – four bases or posts');
INSERT INTO data_sports VALUES ('Rowing');
INSERT INTO data_sports VALUES ('Rowing (sport)');
INSERT INTO data_sports VALUES ('Royaking');
INSERT INTO data_sports VALUES ('Royal shrovetide football');
INSERT INTO data_sports VALUES ('Rugby fives');
INSERT INTO data_sports VALUES ('Rugby football');
INSERT INTO data_sports VALUES ('Rugby league');
INSERT INTO data_sports VALUES ('Rugby league nines');
INSERT INTO data_sports VALUES ('Rugby league sevens');
INSERT INTO data_sports VALUES ('Rugby sevens');
INSERT INTO data_sports VALUES ('Rugby tens');
INSERT INTO data_sports VALUES ('Rugby union');
INSERT INTO data_sports VALUES ('Rundown (aka pickle)');
INSERT INTO data_sports VALUES ('Running');
INSERT INTO data_sports VALUES ('Russian pyramid');
INSERT INTO data_sports VALUES ('Saddle bronc riding');
INSERT INTO data_sports VALUES ('Sailing');
INSERT INTO data_sports VALUES ('Sambo (martial art)');
INSERT INTO data_sports VALUES ('Samoa rules');
INSERT INTO data_sports VALUES ('San shou');
INSERT INTO data_sports VALUES ('Sandboarding');
INSERT INTO data_sports VALUES ('Sanshou');
INSERT INTO data_sports VALUES ('Savate');
INSERT INTO data_sports VALUES ('Schwingen');
INSERT INTO data_sports VALUES ('Scootering');
INSERT INTO data_sports VALUES ('Scrub baseball – four bases (not a team game per se)');
INSERT INTO data_sports VALUES ('Scuba diving');
INSERT INTO data_sports VALUES ('Sea kayaking');
INSERT INTO data_sports VALUES ('Segway polo');
INSERT INTO data_sports VALUES ('Sepak takraw');
INSERT INTO data_sports VALUES ('Seven-ball');
INSERT INTO data_sports VALUES ('Shaolin kung fu');
INSERT INTO data_sports VALUES ('Shidokan karate');
INSERT INTO data_sports VALUES ('Shinty');
INSERT INTO data_sports VALUES ('Shoot boxing');
INSERT INTO data_sports VALUES ('Shootfighting');
INSERT INTO data_sports VALUES ('Shooting sports');
INSERT INTO data_sports VALUES ('Shorinji kempo');
INSERT INTO data_sports VALUES ('Shorin-ryu shidokan');
INSERT INTO data_sports VALUES ('Short track motor racing');
INSERT INTO data_sports VALUES ('Shotgun start');
INSERT INTO data_sports VALUES ('Show jumping');
INSERT INTO data_sports VALUES ('Shuai jiao');
INSERT INTO data_sports VALUES ('Shurikenjutsu');
INSERT INTO data_sports VALUES ('Sikaran');
INSERT INTO data_sports VALUES ('Silambam');
INSERT INTO data_sports VALUES ('Silat');
INSERT INTO data_sports VALUES ('Single scull');
INSERT INTO data_sports VALUES ('Sinuca brasileira');
INSERT INTO data_sports VALUES ('Sipa');
INSERT INTO data_sports VALUES ('Six-man football');
INSERT INTO data_sports VALUES ('Six-red snooker');
INSERT INTO data_sports VALUES ('Skateboarding');
INSERT INTO data_sports VALUES ('Skater hockey');
INSERT INTO data_sports VALUES ('Skeet shooting');
INSERT INTO data_sports VALUES ('Skeleton');
INSERT INTO data_sports VALUES ('Ski jumping');
INSERT INTO data_sports VALUES ('Ski touring');
INSERT INTO data_sports VALUES ('Skibob');
INSERT INTO data_sports VALUES ('Skibobbing');
INSERT INTO data_sports VALUES ('Skiing');
INSERT INTO data_sports VALUES ('Skijoring');
INSERT INTO data_sports VALUES ('Skimboarding');
INSERT INTO data_sports VALUES ('Skins game');
INSERT INTO data_sports VALUES ('Skirmish');
INSERT INTO data_sports VALUES ('Skydiving');
INSERT INTO data_sports VALUES ('Skysurfing');
INSERT INTO data_sports VALUES ('Slacklining');
INSERT INTO data_sports VALUES ('Slamball');
INSERT INTO data_sports VALUES ('Sled sports');
INSERT INTO data_sports VALUES ('Sledge hockey');
INSERT INTO data_sports VALUES ('Slot car racing');
INSERT INTO data_sports VALUES ('Slow pitch');
INSERT INTO data_sports VALUES ('Snail racing');
INSERT INTO data_sports VALUES ('Snooker');
INSERT INTO data_sports VALUES ('Snooker plus');
INSERT INTO data_sports VALUES ('Snorkelling');
INSERT INTO data_sports VALUES ('Snow kiting');
INSERT INTO data_sports VALUES ('Snow rugby');
INSERT INTO data_sports VALUES ('Snow sports');
INSERT INTO data_sports VALUES ('Snowboarding');
INSERT INTO data_sports VALUES ('Snowkiting');
INSERT INTO data_sports VALUES ('Snowmobile racing');
INSERT INTO data_sports VALUES ('Soft tennis');
INSERT INTO data_sports VALUES ('Softball');
INSERT INTO data_sports VALUES ('Sojutsu');
INSERT INTO data_sports VALUES ('Spearfishing');
INSERT INTO data_sports VALUES ('Speed golf');
INSERT INTO data_sports VALUES ('Speed pool');
INSERT INTO data_sports VALUES ('Speed skiing');
INSERT INTO data_sports VALUES ('Speedball');
INSERT INTO data_sports VALUES ('Speed-ball');
INSERT INTO data_sports VALUES ('Speedminton');
INSERT INTO data_sports VALUES ('Spongee');
INSERT INTO data_sports VALUES ('Sport climbing');
INSERT INTO data_sports VALUES ('Sport diving (sport)');
INSERT INTO data_sports VALUES ('Sport fishing');
INSERT INTO data_sports VALUES ('Sport kite (stunt kite)');
INSERT INTO data_sports VALUES ('Sport stacking');
INSERT INTO data_sports VALUES ('Sporting clays');
INSERT INTO data_sports VALUES ('Sports acrobatics');
INSERT INTO data_sports VALUES ('Sports aerobics');
INSERT INTO data_sports VALUES ('Sports car racing');
INSERT INTO data_sports VALUES ('Sprint');
INSERT INTO data_sports VALUES ('Sprint car racing');
INSERT INTO data_sports VALUES ('Sprint football');
INSERT INTO data_sports VALUES ('Squash');
INSERT INTO data_sports VALUES ('Squash tennis');
INSERT INTO data_sports VALUES ('Squirt boating');
INSERT INTO data_sports VALUES ('Ssireum');
INSERT INTO data_sports VALUES ('Stacking');
INSERT INTO data_sports VALUES ('Stand up paddle boarding');
INSERT INTO data_sports VALUES ('Static trapeze');
INSERT INTO data_sports VALUES ('Steeplechase');
INSERT INTO data_sports VALUES ('Steer wrestling');
INSERT INTO data_sports VALUES ('Steinstossen');
INSERT INTO data_sports VALUES ('Stick and ball games');
INSERT INTO data_sports VALUES ('Stickball – variable');
INSERT INTO data_sports VALUES ('Stické');
INSERT INTO data_sports VALUES ('Stihl timbersports series');
INSERT INTO data_sports VALUES ('Still rings');
INSERT INTO data_sports VALUES ('Stock car racing');
INSERT INTO data_sports VALUES ('Stool ball – two stools');
INSERT INTO data_sports VALUES ('Straight pool (14.1 continuous)');
INSERT INTO data_sports VALUES ('Street football');
INSERT INTO data_sports VALUES ('Street football (american)');
INSERT INTO data_sports VALUES ('Street hockey');
INSERT INTO data_sports VALUES ('Street racing');
INSERT INTO data_sports VALUES ('Street sports');
INSERT INTO data_sports VALUES ('Streetball');
INSERT INTO data_sports VALUES ('Streetboarding');
INSERT INTO data_sports VALUES ('Streetluge');
INSERT INTO data_sports VALUES ('Strength athletics (strongman)');
INSERT INTO data_sports VALUES ('Striking');
INSERT INTO data_sports VALUES ('Stroke play');
INSERT INTO data_sports VALUES ('Subak');
INSERT INTO data_sports VALUES ('Subsurface and recreational');
INSERT INTO data_sports VALUES ('Suicide (game)');
INSERT INTO data_sports VALUES ('Sumo');
INSERT INTO data_sports VALUES ('Superbike racing');
INSERT INTO data_sports VALUES ('Supercross');
INSERT INTO data_sports VALUES ('Supermoto');
INSERT INTO data_sports VALUES ('Superside');
INSERT INTO data_sports VALUES ('Supersport racing');
INSERT INTO data_sports VALUES ('Surf fishing');
INSERT INTO data_sports VALUES ('Surf kayaking');
INSERT INTO data_sports VALUES ('Surface');
INSERT INTO data_sports VALUES ('Surface finswimming');
INSERT INTO data_sports VALUES ('Surfboat');
INSERT INTO data_sports VALUES ('Surfing');
INSERT INTO data_sports VALUES ('Swamp football');
INSERT INTO data_sports VALUES ('Sword fighting');
INSERT INTO data_sports VALUES ('Synchronized swimming');
INSERT INTO data_sports VALUES ('Systema');
INSERT INTO data_sports VALUES ('Taekkyeon');
INSERT INTO data_sports VALUES ('Taekwondo');
INSERT INTO data_sports VALUES ('Tag');
INSERT INTO data_sports VALUES ('Tag games');
INSERT INTO data_sports VALUES ('Tag rugby');
INSERT INTO data_sports VALUES ('T''ai chi ch''uan');
INSERT INTO data_sports VALUES ('Taido');
INSERT INTO data_sports VALUES ('Tang soo do');
INSERT INTO data_sports VALUES ('Target archery');
INSERT INTO data_sports VALUES ('Target shooting');
INSERT INTO data_sports VALUES ('Tchoukball');
INSERT INTO data_sports VALUES ('Team handball');
INSERT INTO data_sports VALUES ('Team penning');
INSERT INTO data_sports VALUES ('Team play');
INSERT INTO data_sports VALUES ('Team roping');
INSERT INTO data_sports VALUES ('Tee-ball');
INSERT INTO data_sports VALUES ('Telemark skiing');
INSERT INTO data_sports VALUES ('Ten-ball');
INSERT INTO data_sports VALUES ('Tennis');
INSERT INTO data_sports VALUES ('Tent pegging');
INSERT INTO data_sports VALUES ('Test cricket');
INSERT INTO data_sports VALUES ('Tetrathlon');
INSERT INTO data_sports VALUES ('The massachusetts game – four bases');
INSERT INTO data_sports VALUES ('Three sided football');
INSERT INTO data_sports VALUES ('Three-ball');
INSERT INTO data_sports VALUES ('Three-cushion');
INSERT INTO data_sports VALUES ('Throwball');
INSERT INTO data_sports VALUES ('Time attack');
INSERT INTO data_sports VALUES ('Toboggan');
INSERT INTO data_sports VALUES ('Torball');
INSERT INTO data_sports VALUES ('Touch football');
INSERT INTO data_sports VALUES ('Touch rugby');
INSERT INTO data_sports VALUES ('Touring car racing');
INSERT INTO data_sports VALUES ('Tower running');
INSERT INTO data_sports VALUES ('Town ball – variable');
INSERT INTO data_sports VALUES ('Track cycling');
INSERT INTO data_sports VALUES ('Track racing');
INSERT INTO data_sports VALUES ('Tractor pulling');
INSERT INTO data_sports VALUES ('Traditional climbing');
INSERT INTO data_sports VALUES ('Trampolining');
INSERT INTO data_sports VALUES ('Trap shooting');
INSERT INTO data_sports VALUES ('Trapeze');
INSERT INTO data_sports VALUES ('Trial');
INSERT INTO data_sports VALUES ('Triathlon');
INSERT INTO data_sports VALUES ('Trick shot competition');
INSERT INTO data_sports VALUES ('Truck racing');
INSERT INTO data_sports VALUES ('Tt racing');
INSERT INTO data_sports VALUES ('Tumbling');
INSERT INTO data_sports VALUES ('Twenty20');
INSERT INTO data_sports VALUES ('Ultimate');
INSERT INTO data_sports VALUES ('Ultralight aviation');
INSERT INTO data_sports VALUES ('Ultramarathon');
INSERT INTO data_sports VALUES ('Underwater');
INSERT INTO data_sports VALUES ('Underwater cycling');
INSERT INTO data_sports VALUES ('Underwater football');
INSERT INTO data_sports VALUES ('Underwater hockey');
INSERT INTO data_sports VALUES ('Underwater ice hockey');
INSERT INTO data_sports VALUES ('Underwater orienteering');
INSERT INTO data_sports VALUES ('Underwater photography (sport)');
INSERT INTO data_sports VALUES ('Underwater rugby');
INSERT INTO data_sports VALUES ('Underwater target shooting');
INSERT INTO data_sports VALUES ('Uneven bars');
INSERT INTO data_sports VALUES ('Unicycle');
INSERT INTO data_sports VALUES ('Unicycle basketball');
INSERT INTO data_sports VALUES ('Unicycle hockey');
INSERT INTO data_sports VALUES ('Unicycle trials');
INSERT INTO data_sports VALUES ('Unicycling');
INSERT INTO data_sports VALUES ('Universal football');
INSERT INTO data_sports VALUES ('Uppies and downies');
INSERT INTO data_sports VALUES ('Vajra-mushti');
INSERT INTO data_sports VALUES ('Vale tudo');
INSERT INTO data_sports VALUES ('Valencian frontó');
INSERT INTO data_sports VALUES ('Valencian pilota');
INSERT INTO data_sports VALUES ('Varzesh-e pahlavani');
INSERT INTO data_sports VALUES ('Vault');
INSERT INTO data_sports VALUES ('Vigoro – two wickets');
INSERT INTO data_sports VALUES ('Vintage racing');
INSERT INTO data_sports VALUES ('Volata');
INSERT INTO data_sports VALUES ('Volleyball');
INSERT INTO data_sports VALUES ('Vovinam');
INSERT INTO data_sports VALUES ('Waboba');
INSERT INTO data_sports VALUES ('Wakeboarding');
INSERT INTO data_sports VALUES ('Wakesurfing');
INSERT INTO data_sports VALUES ('Walking');
INSERT INTO data_sports VALUES ('Wall game');
INSERT INTO data_sports VALUES ('Wall-and-ball');
INSERT INTO data_sports VALUES ('Wallball');
INSERT INTO data_sports VALUES ('Wallyball');
INSERT INTO data_sports VALUES ('Water basketball');
INSERT INTO data_sports VALUES ('Water polo');
INSERT INTO data_sports VALUES ('Water volleyball');
INSERT INTO data_sports VALUES ('Waymarking');
INSERT INTO data_sports VALUES ('Weapons');
INSERT INTO data_sports VALUES ('Weightlifting');
INSERT INTO data_sports VALUES ('Western pleasure');
INSERT INTO data_sports VALUES ('Wheelchair basketball');
INSERT INTO data_sports VALUES ('Wheelchair rugby league');
INSERT INTO data_sports VALUES ('Wheelstand competition');
INSERT INTO data_sports VALUES ('White water rafting');
INSERT INTO data_sports VALUES ('Whitewater kayaking');
INSERT INTO data_sports VALUES ('Wiffleball');
INSERT INTO data_sports VALUES ('Windsurfing');
INSERT INTO data_sports VALUES ('Wing chun');
INSERT INTO data_sports VALUES ('Wingsuit flying');
INSERT INTO data_sports VALUES ('Wireball');
INSERT INTO data_sports VALUES ('Woggabaliri');
INSERT INTO data_sports VALUES ('Wolf hunting');
INSERT INTO data_sports VALUES ('Women''s lacrosse');
INSERT INTO data_sports VALUES ('Woodsman');
INSERT INTO data_sports VALUES ('Wrestling');
INSERT INTO data_sports VALUES ('Wushu');
INSERT INTO data_sports VALUES ('Xare');
INSERT INTO data_sports VALUES ('Xingyiquan');
INSERT INTO data_sports VALUES ('Yagli güres');
INSERT INTO data_sports VALUES ('Yak polo');
INSERT INTO data_sports VALUES ('Yubi lakpi');
INSERT INTO data_sports VALUES ('Yukigassen');
INSERT INTO data_sports VALUES ('Zui quan');
