CREATE TABLE data_books (
    `Las_Trinas_Cuadras_by_Javier_Enr_quez_Serralde` VARCHAR(87) CHARACTER SET utf8,
    `Las_Trinas_Cuadras` VARCHAR(61) CHARACTER SET utf8,
    `Javier_Enr_quez_Serralde` VARCHAR(37) CHARACTER SET utf8,
    `Javier` VARCHAR(12) CHARACTER SET utf8,
    `Serralde` VARCHAR(13) CHARACTER SET utf8,
    `Column_6` VARCHAR(11) CHARACTER SET utf8,
    `Column_7` VARCHAR(9) CHARACTER SET utf8
);
INSERT INTO data_books VALUES ('1001 Nights','1001 Nights','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('11/22/63 by Stephen King','11/22/63','Stephen King','Stephen','King',NULL,NULL);
INSERT INTO data_books VALUES ('1984 by George Orwell','1984','George Orwell','George','Orwell',NULL,NULL);
INSERT INTO data_books VALUES ('A Canticle for Leibowitz by Walter M. Miller, Jr','A Canticle for Leibowitz','Walter M. Miller, Jr','Walter','Miller',NULL,NULL);
INSERT INTO data_books VALUES ('A Child''s History of England by Charles Dickens','A Child''s History of England','Charles Dickens','Charles','Dickens',NULL,NULL);
INSERT INTO data_books VALUES ('A Christmas Carol by Charles Dickens','A Christmas Carol','Charles Dickens','Charles','Dickens',NULL,NULL);
INSERT INTO data_books VALUES ('A Drink Before the War by Dennis Lehane','A Drink Before the War','Dennis Lehane','Dennis','Lehane',NULL,NULL);
INSERT INTO data_books VALUES ('A History of East Africa','A History of East Africa','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('A Long Way Gone by Ishmael Beah','A Long Way Gone','Ishmael Beah','Ishmael','Beah',NULL,NULL);
INSERT INTO data_books VALUES ('A Midsummer Night''s Dream by William Shakespeare','A Midsummer Night''s Dream','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('A Million Little Pieces by James Frey','A Million Little Pieces','James Frey','James','Frey',NULL,NULL);
INSERT INTO data_books VALUES ('A Portrait of the Artist as a Young Man by James Joyce','A Portrait of the Artist as a Young Man','James Joyce','James','Joyce',NULL,NULL);
INSERT INTO data_books VALUES ('A Tale of Two Cities by Charles Dickens','A Tale of Two Cities','Charles Dickens','Charles','Dickens',NULL,NULL);
INSERT INTO data_books VALUES ('A Walk to Remember by Nicholas Sparks','A Walk to Remember','Nicholas Sparks','Nicholas','Sparks',NULL,NULL);
INSERT INTO data_books VALUES ('Abyss, The by Marguerite Yourcenar','Abyss, The','Marguerite Yourcenar','Marguerite','Yourcenar',NULL,NULL);
INSERT INTO data_books VALUES ('Across the River and Into the Trees by Ernest Hemingway','Across the River and Into the Trees','Ernest Hemingway','Ernest','Hemingway',NULL,NULL);
INSERT INTO data_books VALUES ('Africa and Africans by Paul Bohannan and Philip Curtin','Africa and Africans','Paul Bohannan and Philip Curtin','Paul','Bohannan','Philip','Curtin');
INSERT INTO data_books VALUES ('Alex Rider by Anthony Horowitz','Alex Rider','Anthony Horowitz','Anthony','Horowitz',NULL,NULL);
INSERT INTO data_books VALUES ('Alexis by Marguerite Yourcenar','Alexis','Marguerite Yourcenar','Marguerite','Yourcenar',NULL,NULL);
INSERT INTO data_books VALUES ('Alice''s Adventures in Wonderland by Lewis Carroll','Alice''s Adventures in Wonderland','Lewis Carroll','Lewis','Carroll',NULL,NULL);
INSERT INTO data_books VALUES ('All Families Are Psychotic by Douglas Coupland','All Families Are Psychotic','Douglas Coupland','Douglas','Coupland',NULL,NULL);
INSERT INTO data_books VALUES ('All the Names by José Saramago','All the Names','José Saramago','José','Saramago',NULL,NULL);
INSERT INTO data_books VALUES ('All''s Well That Ends Well by William Shakespeare','All''s Well That Ends Well','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('American Gods by Neil Gaiman','American Gods','Neil Gaiman','Neil','Gaiman',NULL,NULL);
INSERT INTO data_books VALUES ('American Scene, The by Henry James','American Scene, The','Henry James','Henry','James',NULL,NULL);
INSERT INTO data_books VALUES ('An Essay on Criticism by Alexander Pope','An Essay on Criticism','Alexander Pope','Alexander','Pope',NULL,NULL);
INSERT INTO data_books VALUES ('An Essay on Man by Alexander Pope','An Essay on Man','Alexander Pope','Alexander','Pope',NULL,NULL);
INSERT INTO data_books VALUES ('An Inspector Calls by J. B. Priestley','An Inspector Calls','J. B. Priestley','J. B. ','Priestley',NULL,NULL);
INSERT INTO data_books VALUES ('Anansi Boys by Neil Gaiman','Anansi Boys','Neil Gaiman','Neil','Gaiman',NULL,NULL);
INSERT INTO data_books VALUES ('Ancrene Wisse','Ancrene Wisse','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('Angels & Demons by Dan Brown','Angels & Demons','Dan Brown','Dan','Brown',NULL,NULL);
INSERT INTO data_books VALUES ('Anglo-Saxon Chronicle','Anglo-Saxon Chronicle','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('Animal Farm by George Orwell','Animal Farm','George Orwell','George','Orwell',NULL,NULL);
INSERT INTO data_books VALUES ('Animorphs by K. A. Applegate','Animorphs','K. A. Applegate','K. A. ','Applegate',NULL,NULL);
INSERT INTO data_books VALUES ('Anne of Avonlea by L. M. Montgomery','Anne of Avonlea','L. M. Montgomery','L. M.','Montgomery',NULL,NULL);
INSERT INTO data_books VALUES ('Anne of Green Gables by L. M. Montgomery','Anne of Green Gables','L. M. Montgomery','L. M.','Montgomery',NULL,NULL);
INSERT INTO data_books VALUES ('Anne of the Island by L.M. Montgomery','Anne of the Island','L. M. Montgomery','L. M.','Montgomery',NULL,NULL);
INSERT INTO data_books VALUES ('Anne of Windy Poplars by L.M. Montgomery','Anne of Windy Poplars','L. M. Montgomery','L. M.','Montgomery',NULL,NULL);
INSERT INTO data_books VALUES ('Antichrist, The by Friedrich Nietzsche','Antichrist, The','Friedrich Nietzsche','Friedrich','Nietzsche',NULL,NULL);
INSERT INTO data_books VALUES ('Antony and Cleopatra by William Shakespeare','Antony and Cleopatra','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Apprenticeship of Duddy Kravitz, The Mordecai Richler','Apprenticeship of Duddy Kravitz','Mordecai Richler','Mordecai','Richler',NULL,NULL);
INSERT INTO data_books VALUES ('Areopagitica by John Milton','Areopagitica','John Milton','John','Milton',NULL,NULL);
INSERT INTO data_books VALUES ('Arrow of God by Chinua Achebe','Arrow of God','Chinua Achebe','Chinua','Achebe',NULL,NULL);
INSERT INTO data_books VALUES ('As You Like It by William Shakespeare','As You Like It','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Atlas Shrugged by Ayn Rand','Atlas Shrugged','Ayn Rand','Ayn','Rand',NULL,NULL);
INSERT INTO data_books VALUES ('Aucassin and Nicolette','Aucassin and Nicolette','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('Autobiography of William Butler Yeats, The by William Butler Yeats','Autobiography of William Butler Yeats, The','William Butler Yeats','William','Yeats',NULL,NULL);
INSERT INTO data_books VALUES ('Awakening, The by Kate Chopin','Awakening, The','Kate Chopin','Kate','Chopin',NULL,NULL);
INSERT INTO data_books VALUES ('Bangkok Haunts by John Burdett','Bangkok Haunts','John Burdett','John','Burdett',NULL,NULL);
INSERT INTO data_books VALUES ('Barney Version Mordecai Richler','Barney Vision ','Mordecai Richler','Mordecai','Richler',NULL,NULL);
INSERT INTO data_books VALUES ('Bartimaeus Trilogy: The Amulet of Samarkand, The by Jonathan Stroud','Bartimaeus Trilogy: The Amulet of Samarkand, The','Jonathan Stroud','Jonathan','Stroud',NULL,NULL);
INSERT INTO data_books VALUES ('Bartleby, the Scrivener by Herman Melville','Bartleby, the Scrivener','Herman Melville','Herman','Melville',NULL,NULL);
INSERT INTO data_books VALUES ('Batman by various authors','Batman','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('Battle Pieces: And Aspects of the War by Herman Melville','Battle Pieces: And Aspects of the War','Herman Melville','Herman','Melville',NULL,NULL);
INSERT INTO data_books VALUES ('Beak of the Finch by Jonathan Weiner','Beak of the Finch','Jonathan Weiner','Jonathan','Weiner',NULL,NULL);
INSERT INTO data_books VALUES ('Beautiful Disaster by Jamie McGuier','Beautiful Disaster','Jamie McGuier','Jamie','McGuier',NULL,NULL);
INSERT INTO data_books VALUES ('Bec by Darren Shan','Bec','Darren Shan','Darren','Shan',NULL,NULL);
INSERT INTO data_books VALUES ('Becoming Light: Poems New and Selected by Erica Jong','Becoming Light: Poems New and Selected','Erica Jong','Erica','Jong',NULL,NULL);
INSERT INTO data_books VALUES ('Beowulf','Beowulf','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('Beyond Good and Evil by Friedrich Nietzsche','Beyond Good and Evil','Friedrich Nietzsche','Friedrich','Nietzsche',NULL,NULL);
INSERT INTO data_books VALUES ('Billy Budd by Herman Melville','Billy Budd','Herman Melville','Herman','Melville',NULL,NULL);
INSERT INTO data_books VALUES ('Birds of America by Lorrie Moore','Birds of America','Lorrie Moore','Lorrie','Moore',NULL,NULL);
INSERT INTO data_books VALUES ('Birdsong by Sebastian Faulks','Birdsong','Sebastian Faulks','Sebastian','Faulks',NULL,NULL);
INSERT INTO data_books VALUES ('Blind Man''s Bluff by Sherry Sontag and Christopher Drew','Blind Man''s Bluff','Sherry Sontag and Christopher Drew','Sherry','Sontag','Christopher','Drew');
INSERT INTO data_books VALUES ('Blood Beast by Darren Shan','Blood Beast','Darren Shan','Darren','Shan',NULL,NULL);
INSERT INTO data_books VALUES ('Bloodlines by Richelle Mead','Bloodlines','Richelle Mead','Richelle','Mead',NULL,NULL);
INSERT INTO data_books VALUES ('Blue Crow by Michael Spring','Blue Crow','Michael Spring','Michael','Spring',NULL,NULL);
INSERT INTO data_books VALUES ('Brave New World by Aldous Huxley','Brave New World','Aldous Huxley','Aldous','Huxley',NULL,NULL);
INSERT INTO data_books VALUES ('Brisingr by Christopher Paolini','Brisingr','Christopher Paolini','Christopher','Paolini',NULL,NULL);
INSERT INTO data_books VALUES ('Burn Down the Night by Graig Lee Street','Burn Down the Night','Graig Lee Street','Graig','Street',NULL,NULL);
INSERT INTO data_books VALUES ('Burning Plain, The by Michael Nava','Burning Plain, The','Michael Nava','Michael','Nava',NULL,NULL);
INSERT INTO data_books VALUES ('Cain''s Book by Alexander Trocchi','Cain''s Book','Alexander Trocchi','Alexander','Trocchi',NULL,NULL);
INSERT INTO data_books VALUES ('Candide by Voltaire','Candide','Voltaire',NULL,'Voltaire',NULL,NULL);
INSERT INTO data_books VALUES ('Canto General by Pablo Neruda','Canto General','Pablo Neruda','Pablo','Neruda',NULL,NULL);
INSERT INTO data_books VALUES ('Carmina Burana','Carmina Burana','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('Carrie by Stephen King','Carrie','Stephen King','Stephen','King',NULL,NULL);
INSERT INTO data_books VALUES ('Carter Finally Gets It by Brent Crawford','Carter Finally Gets It','Brent Crawford','Brent','Crawford',NULL,NULL);
INSERT INTO data_books VALUES ('Carter''s Big Break by Brent Crawford','Carter''s Big Break','Brent Crawford','Brent','Crawford',NULL,NULL);
INSERT INTO data_books VALUES ('Catch-22 by Joseph Heller','Catch-22','Joseph Heller','Joseph','Heller',NULL,NULL);
INSERT INTO data_books VALUES ('Catching Fire by Suzanne Collins','Catching Fire','Suzanne Collins','Suzanne','Collins',NULL,NULL);
INSERT INTO data_books VALUES ('Cat''s Cradle by Kurt Vonnegut','Cat''s Cradle','Kurt Vonnegut','Kurt','Vonnegut',NULL,NULL);
INSERT INTO data_books VALUES ('Chariots of the Gods? : Unsolved Mysteries of the Past by Erich von Däniken','Chariots of the Gods? : Unsolved Mysteries of the Past','Erich von Däniken','Erich','Däniken',NULL,NULL);
INSERT INTO data_books VALUES ('Chi the book series by A. C. Quinn','Chi the book series','A. C. Quinn','A. C.','Quinn',NULL,NULL);
INSERT INTO data_books VALUES ('Childe Harold''s Pilgrimage by Lord Byron','Childe Harold''s Pilgrimage','Lord Byron','Lord','Byron',NULL,NULL);
INSERT INTO data_books VALUES ('Childhood''s End by Arthur C. Clarke','Childhood''s End','Arthur C. Clarke','Arthur','Clarke',NULL,NULL);
INSERT INTO data_books VALUES ('Chocolat by Joanne Harris','Chocolat','Joanne Harris','Joanne','Harris',NULL,NULL);
INSERT INTO data_books VALUES ('Choke by Chuck Palahniuk','Choke','Chuck Palahniuk','Chuck','Palahniuk',NULL,NULL);
INSERT INTO data_books VALUES ('Civil Disobedience by Henry David Thoreau','Civil Disobedience','Henry David Thoreau','Henry','Thoreau',NULL,NULL);
INSERT INTO data_books VALUES ('Clarissa by Samuel Richardson','Clarissa','Samuel Richardson','Samuel','Richardson',NULL,NULL);
INSERT INTO data_books VALUES ('Clockwork Orange by Anthony Burgess','Clockwork Orange','Anthony Burgess','Anthony','Burgess',NULL,NULL);
INSERT INTO data_books VALUES ('Concluding Unscientific Postscript to Philosophical Fragments by Søren Kierkegaard','Concluding Unscientific Postscript to Philosophical Fragments','Søren Kierkegaard','Søren','Kierkegaard',NULL,NULL);
INSERT INTO data_books VALUES ('Consent to Kill: A Thriller by Vince Flynn','Consent to Kill: A Thriller','Vince Flynn','Vince','Flynn',NULL,NULL);
INSERT INTO data_books VALUES ('Contact by Carl Sagan','Contact','Carl Sagan','Carl','Sagan',NULL,NULL);
INSERT INTO data_books VALUES ('Coriolanus by William Shakespeare','Coriolanus','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Cornish Trilogy by Robertson Davies','Cornish Trilogy','Robertson Davies','Robertson','Davies',NULL,NULL);
INSERT INTO data_books VALUES ('Corpus Juris Civilis','Corpus Juris Civilis','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('Crime and Punishment by Fyodor Dostoevsky','Crime and Punishment','Fyodor Dostoevsky','Fyodor','Dostoevsky',NULL,NULL);
INSERT INTO data_books VALUES ('Cryptonomicon by Neal Stephenson','Cryptonomicon','Neal Stephenson','Neal','Stephenson',NULL,NULL);
INSERT INTO data_books VALUES ('Cursor Mundi','Cursor Mundi','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('Cymbeline by William Shakespeare','Cymbeline','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Cyrano de Bergerac by Edmond Rostand','Cyrano de Bergerac','Edmond Rostand','Edmond','Rostand',NULL,NULL);
INSERT INTO data_books VALUES ('Damned by Chuck Palahniuk','Damned','Chuck Palahniuk','Chuck','Palahniuk',NULL,NULL);
INSERT INTO data_books VALUES ('Danse Macabre by Stephen King','Danse Macabre','Stephen King','Stephen','King',NULL,NULL);
INSERT INTO data_books VALUES ('Dark Calling by Darren Shan','Dark Calling','Darren Shan','Darren','Shan',NULL,NULL);
INSERT INTO data_books VALUES ('Darkly Dreaming Dexter by Jeff Lindsay','Darkly Dreaming Dexter','Jeff Lindsay','Jeff','Lindsay',NULL,NULL);
INSERT INTO data_books VALUES ('Darkness, Take My Hand by Dennis Lehane','Darkness, Take My Hand','Dennis Lehane','Dennis','Lehane',NULL,NULL);
INSERT INTO data_books VALUES ('David Copperfield by Charles Dickens','David Copperfield','Charles Dickens','Charles','Dickens',NULL,NULL);
INSERT INTO data_books VALUES ('Dead Souls by Nikolai Gogol','Dead Souls','Nikolai Gogol','Nikolai','Gogol',NULL,NULL);
INSERT INTO data_books VALUES ('Dearly Devoted Dexter by Jeff Lindsay','Dearly Devoted Dexter','Jeff Lindsay','Jeff','Lindsay',NULL,NULL);
INSERT INTO data_books VALUES ('Death of the Heart, The by Elizabeth Bowen','Death of the Heart, The','Elizabeth Bowen','Elizabeth','Bowen',NULL,NULL);
INSERT INTO data_books VALUES ('Deaths Shadow by Darren Shan','Deaths Shadow','Darren Shan','Darren','Shan',NULL,NULL);
INSERT INTO data_books VALUES ('Demian by Hermann Hesse','Demian','Hermann Hesse','Hermann','Hesse',NULL,NULL);
INSERT INTO data_books VALUES ('Demon Apocalypse by Darren Shan','Demon Apocalypse','Darren Shan','Darren','Shan',NULL,NULL);
INSERT INTO data_books VALUES ('Demon Thief by Darren Shan','Demon Thief','Darren Shan','Darren','Shan',NULL,NULL);
INSERT INTO data_books VALUES ('Deptford Trilogy by Robertson Davies','Deptford Trilogy','Robertson Davies','Robertson','Davies',NULL,NULL);
INSERT INTO data_books VALUES ('Dexter by Design by Jeff Lindsay','Dexter Design','Jeff Lindsay','Jeff','Lindsay',NULL,NULL);
INSERT INTO data_books VALUES ('Dexter in the Dark by Jeff Lindsay','Dexter in the Dark','Jeff Lindsay','Jeff','Lindsay',NULL,NULL);
INSERT INTO data_books VALUES ('Dhammapada, attributed to Siddhartha Gautama','Dhammapada','Siddhartha Gautama','Gautama','Gautama',NULL,NULL);
INSERT INTO data_books VALUES ('Diary by Chuck Palahniuk','Diary','Chuck Palahniuk','Chuck','Palahniuk',NULL,NULL);
INSERT INTO data_books VALUES ('Digital Fortress by Dan Brown','Digital Fortress','Dan Brown','Dan','Brown',NULL,NULL);
INSERT INTO data_books VALUES ('Dirk Gently''s Holistic Detective Agency by Douglas Adams','Dirk Gently''s Holistic Detective Agency','Douglas Adams','Douglas','Adams',NULL,NULL);
INSERT INTO data_books VALUES ('Divergent by Veronica Roth','Divergent','Veronica Roth','Veronica','Roth',NULL,NULL);
INSERT INTO data_books VALUES ('Dragonfly in Amber by Diana Gabaldon','Dragonfly in Amber','Diana Gabaldon','Diana','Gabaldon',NULL,NULL);
INSERT INTO data_books VALUES ('Dragons in Our Midst by Brain Davis','Dragons in Our Midst','Brain Davis','Brain','Davis',NULL,NULL);
INSERT INTO data_books VALUES ('Du Sang sur Le Miroir by Cosmos (Akoete) Eglo','Du Sang sur Le Miroir','Cosmos (Akoete) Eglo','Cosmos','Eglo',NULL,NULL);
INSERT INTO data_books VALUES ('East of Eden by John Steinbeck','East of Eden','John Steinbeck','John','Steinbeck',NULL,NULL);
INSERT INTO data_books VALUES ('Either/Or by Søren Kierkegaard','Either/Or','Søren Kierkegaard','Søren','Kierkegaard',NULL,NULL);
INSERT INTO data_books VALUES ('Eldest by Christopher Paolini','Eldest','Christopher Paolini','Christopher','Paolini',NULL,NULL);
INSERT INTO data_books VALUES ('Ella Enchanted by Gail Carson Levine','Ella Enchanted','Gail Carson Levine','Gail','Levine',NULL,NULL);
INSERT INTO data_books VALUES ('Emma by Jane Austen','Emma','Jane Austen','Jane','Austen',NULL,NULL);
INSERT INTO data_books VALUES ('Empire of Dreams by Giannina Braschi','Empire of Dreams','Giannina Braschi','Giannina','Braschi',NULL,NULL);
INSERT INTO data_books VALUES ('Ender''s Game by Orson Scott Card','Ender''s Game','Orson Scott Card','Orson','Card',NULL,NULL);
INSERT INTO data_books VALUES ('Eragon by Christopher Paolini','Eragon','Christopher Paolini','Christopher','Paolini',NULL,NULL);
INSERT INTO data_books VALUES ('Everyman, anonymous morality play','Everyman, anonymous morality play','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('Extremely Loud & Incredibly Close by Jonathan Safran Foer','Extremely Loud & Incredibly Close','Jonathan Safran Foer','Jonathan','Foer',NULL,NULL);
INSERT INTO data_books VALUES ('Fahrenheit 451 by Ray Bradbury','Fahrenheit 451','Ray Bradbury','Ray','Bradbury',NULL,NULL);
INSERT INTO data_books VALUES ('Fairest by Gail Carson Levine','Fairest','Gail Carson Levine','Gail','Levine',NULL,NULL);
INSERT INTO data_books VALUES ('Faith into Action by Daisaku Ikeda','Faith into Action','Daisaku Ikeda','Daisaku','Ikeda',NULL,NULL);
INSERT INTO data_books VALUES ('Famous Last Words by Timothy Findlay','Famous Last Words','Timothy Findlay','Timothy','Findlay',NULL,NULL);
INSERT INTO data_books VALUES ('Faust by Johann Wolfgang von Goethe','Faust','Johann Wolfgang von Goethe','Johann','Goethe',NULL,NULL);
INSERT INTO data_books VALUES ('Fear and Loathing in Las Vegas by Hunter S. Thompson','Fear and Loathing in Las Vegas','Hunter S. Thompson','Hunter','Thompson',NULL,NULL);
INSERT INTO data_books VALUES ('Fear and Loathing: on the Campaign Trail ''72 by Hunter S. Thompson','Fear and Loathing: on the Campaign Trail ''72','Hunter S. Thompson','Hunter','Thompson',NULL,NULL);
INSERT INTO data_books VALUES ('Fear and Trembling by Søren Kierkegaard','Fear and Trembling','Søren Kierkegaard','Søren','Kierkegaard',NULL,NULL);
INSERT INTO data_books VALUES ('Fear of Flying by Erica Jong','Fear of Flying','Erica Jong','Erica','Jong',NULL,NULL);
INSERT INTO data_books VALUES ('Fierce Invalids Home From Hot Climates by Tom Robbins','Fierce Invalids Home From Hot Climates','Tom Robbins','Tom','Robbins',NULL,NULL);
INSERT INTO data_books VALUES ('Fight Club by Chuck Palahniuk','Fight Club','Chuck Palahniuk','Chuck','Palahniuk',NULL,NULL);
INSERT INTO data_books VALUES ('Finnegans Wake by James Joyce','Finnegans Wake','James Joyce','James','Joyce',NULL,NULL);
INSERT INTO data_books VALUES ('Flesh and Fire by Laura Anne Gilman','Flesh and Fire','Laura Anne Gilman','Laura','Gilman',NULL,NULL);
INSERT INTO data_books VALUES ('Flora & Ulysses by Kate DiCamillo','Flora & Ulysses','Kate DiCamillo','Kate','DiCamillo',NULL,NULL);
INSERT INTO data_books VALUES ('Following the Equator by Mark Twain','Following the Equator','Mark Twain','Mark','Twain',NULL,NULL);
INSERT INTO data_books VALUES ('Foucault''s Pendulum by Umberto Eco','Foucault''s Pendulum','Umberto Eco','Umberto','Eco',NULL,NULL);
INSERT INTO data_books VALUES ('Four Quartets by T. S. Eliot','Four Quartets','T. S. Eliot','T. S.','Eliot',NULL,NULL);
INSERT INTO data_books VALUES ('Francesca Carrara by Letitia Elizabeth Landon','Francesca Carrara','Letitia Elizabeth Landon','Letitia','Landon',NULL,NULL);
INSERT INTO data_books VALUES ('Frankenstein by Mary Shelley','Frankenstein','Mary Shelley','Mary','Shelley',NULL,NULL);
INSERT INTO data_books VALUES ('Full Tilt by Neal Schusterman','Full Tilt','Neal Schusterman','Neal','Schusterman',NULL,NULL);
INSERT INTO data_books VALUES ('Gates of Fire by Steven Pressfield','Gates of Fire','Steven Pressfield','Steven','Pressfield',NULL,NULL);
INSERT INTO data_books VALUES ('Generation X: Tales for an Accelerated Culture by Douglas Coupland','Generation X: Tales for an Accelerated Culture','Douglas Coupland','Douglas','Coupland',NULL,NULL);
INSERT INTO data_books VALUES ('Gesta Romanorum (authors unknown)','Gesta Romanorum (authors unknown)','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('Go Ask Alice by Anonymous','Go Ask Alice','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('Go Down, Moses by William Faulkner','Go Down, Moses','William Faulkner','William','Faulkner',NULL,NULL);
INSERT INTO data_books VALUES ('Gone Baby Gone by Dennis Lehane','Gone Baby Gone','Dennis Lehane','Dennis','Lehane',NULL,NULL);
INSERT INTO data_books VALUES ('Good Omens by Neil Gaiman & Terry Pratchett','Good Omens','Neil Gaiman & Terry Pratchett','Neil','Gaiman','Terry','Pratchett');
INSERT INTO data_books VALUES ('Gospel of Judas (authorship disputed)','Gospel of Judas (authorship disputed)','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('Gotham Central by Greg Rucka and Michael Lark','Gotham Central','Greg Rucka and Michael Lark','Greg','Rucka','Michael','Lark');
INSERT INTO data_books VALUES ('Grain of Wheat, A by Ngugi wa Thiong''o','Grain of Wheat, A','Ngugi wa Thiong''o','Ngugi','Thiong''o',NULL,NULL);
INSERT INTO data_books VALUES ('Great Expectations by Charles Dickens','Great Expectations','Charles Dickens','Charles','Dickens',NULL,NULL);
INSERT INTO data_books VALUES ('Greek myths','Greek myths','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('Gregor the Overlander by Suzanne Collins','Gregor the Overlander','Suzanne Collins','Suzanne','Collins',NULL,NULL);
INSERT INTO data_books VALUES ('Grendel by John Gardner','Grendel','John Gardner','John','Gardner',NULL,NULL);
INSERT INTO data_books VALUES ('Half The Town by Patrick Alcatraz','Half The Town','Patrick Alcatraz','Patrick','Alcatraz',NULL,NULL);
INSERT INTO data_books VALUES ('Hamlet by William Shakespeare','Hamlet','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Haunted by Chuck Palahniuk','Haunted','Chuck Palahniuk','Chuck','Palahniuk',NULL,NULL);
INSERT INTO data_books VALUES ('Havelok the Dane','Havelok the Dane','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('Hellblazer by various authors','Hellblazer','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('Hell''s Heroes by Darren Shan','Hell''s Heroes','Darren Shan','Darren','Shan',NULL,NULL);
INSERT INTO data_books VALUES ('Henry IV, Part 1 by William Shakespeare','Henry IV, Part 1','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Henry IV, Part 2 by William Shakespeare','Henry IV, Part 2','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Henry V by William Shakespeare','Henry V','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Henry VI, Part 1 by William Shakespeare','Henry VI, Part 1','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Henry VI, Part 2 by William Shakespeare','Henry VI, Part 2','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Henry VI, Part 3 by William Shakespeare','Henry VI, Part 3','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Henry VIII by William Shakespeare','Henry VIII','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Historia Brittonum','Historia Brittonum','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('Hostile Environment by Patrick C. Crowell','Hostile Environment','Patrick C. Crowell','Patrick','Crowell',NULL,NULL);
INSERT INTO data_books VALUES ('House of Leaves by Mark Z. Danielewski','House of Leaves','Mark Z. Danielewski','Mark','Danielewski',NULL,NULL);
INSERT INTO data_books VALUES ('How to Save Your Own Life by Erica Jong','How to Save Your Own Life','Erica Jong','Erica','Jong',NULL,NULL);
INSERT INTO data_books VALUES ('Howl''s Moving Castle by Diana Wynne Jones','Howl''s Moving Castle','Diana Wynne Jones','Diana','Jones',NULL,NULL);
INSERT INTO data_books VALUES ('Human, All Too Human by Friedrich Nietzsche','Human, All Too Human','Friedrich Nietzsche','Friedrich','Nietzsche',NULL,NULL);
INSERT INTO data_books VALUES ('I am Legend by Richard Matheson','I am Legend','Richard Matheson','Richard','Matheson',NULL,NULL);
INSERT INTO data_books VALUES ('I Beat the Odds by Michael Oher','I Beat the Odds','Michael Oher','Michael','Oher',NULL,NULL);
INSERT INTO data_books VALUES ('IdleWild by Nick Sagan','IdleWild','Nick Sagan','Nick','Sagan',NULL,NULL);
INSERT INTO data_books VALUES ('Idylls of the King by Alfred, Lord Tennyson','Idylls of the King','Alfred, Lord Tennyson','Alfred','Tennyson',NULL,NULL);
INSERT INTO data_books VALUES ('If Beale Street Could Talk by James Baldwin','If Beale Street Could Talk','James Baldwin','James','Baldwin',NULL,NULL);
INSERT INTO data_books VALUES ('Imitations of Horace by Alexander Pope','Imitations of Horace','Alexander Pope','Alexander','Pope',NULL,NULL);
INSERT INTO data_books VALUES ('Inferno by Dante Alighieri','Inferno','Dante Alighieri','Dante','Alighieri',NULL,NULL);
INSERT INTO data_books VALUES ('Infinite Crisis by various authors','Infinite Crisis','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('Inside The Volcano by Eduardo Paz-Martinez','Inside The Volcano','Eduardo Paz-Martinez','Eduardo','Paz-Martinez',NULL,NULL);
INSERT INTO data_books VALUES ('Invisible Man by Ralph Ellison','Invisible Man','Ralph Ellison','Ralph','Ellison',NULL,NULL);
INSERT INTO data_books VALUES ('Ironside by Holly Black','Ironside','Holly Black','Holly','Black',NULL,NULL);
INSERT INTO data_books VALUES ('Ishmael by Daniel Quinn','Ishmael','Daniel Quinn','Daniel','Quinn',NULL,NULL);
INSERT INTO data_books VALUES ('Jane Eyre by Charlotte Brontë','Jane Eyre','Charlotte Brontë','Charlotte','Brontë',NULL,NULL);
INSERT INTO data_books VALUES ('Job: A Comedy of Justice by Robert A. Heinlein','Job: A Comedy of Justice','Robert A. Heinlein','Robert','Heinlein',NULL,NULL);
INSERT INTO data_books VALUES ('John Dies at the End by David Wong','John Dies at the End','David Wong','David','Wong',NULL,NULL);
INSERT INTO data_books VALUES ('Johnny the Homicidal Maniac by Jhonen Vasquez','Johnny the Homicidal Maniac','Jhonen Vasquez','Jhonen','Vasquez',NULL,NULL);
INSERT INTO data_books VALUES ('Jonathan Livingston Seagull by Richard Bach','Jonathan Livingston Seagull','Richard Bach','Richard','Bach',NULL,NULL);
INSERT INTO data_books VALUES ('Jonathan Strange and Mr Norrell by Susanna Clarke','Jonathan Strange and Mr Norrell','Susanna Clarke','Susanna','Clarke',NULL,NULL);
INSERT INTO data_books VALUES ('Journals of Ayn Rand by Ayn Rand','Journals of Ayn Rand','Ayn Rand','Ayn','Rand',NULL,NULL);
INSERT INTO data_books VALUES ('Journey to the East by Hermann Hesse','Journey to the East','Hermann Hesse','Hermann','Hesse',NULL,NULL);
INSERT INTO data_books VALUES ('Julius Caesar by William Shakespeare','Julius Caesar','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Jurassic Park by Michael Crichton','Jurassic Park','Michael Crichton','Michael','Crichton',NULL,NULL);
INSERT INTO data_books VALUES ('King John by William Shakespeare','King John','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('King Lear by William Shakespeare','King Lear','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Lanark: A Life in Four Books by Alasdair Gray','Lanark: A Life in Four Books','Alasdair Gray','Alasdair','Gray',NULL,NULL);
INSERT INTO data_books VALUES ('Leaves of Grass by Walt Whitman','Leaves of Grass','Walt Whitman','Walt','Whitman',NULL,NULL);
INSERT INTO data_books VALUES ('Les Misérables by Victor Hugo','Les Misérables','Victor Hugo','Victor','Hugo',NULL,NULL);
INSERT INTO data_books VALUES ('Letters from the Earth by Mark Twain','Letters from the Earth','Mark Twain','Mark','Twain',NULL,NULL);
INSERT INTO data_books VALUES ('Life on the Mississippi by Mark Twain','Life on the Mississippi','Mark Twain','Mark','Twain',NULL,NULL);
INSERT INTO data_books VALUES ('Little House on the Prairie by Laura Ingalls Wilder','Little House on the Prairie','Laura Ingalls Wilder','Laura','Wilder',NULL,NULL);
INSERT INTO data_books VALUES ('Living to Tell the Tale by Gabriel García Márquez','Living to Tell the Tale','Gabriel García Márquez','Gabriel','Márquez',NULL,NULL);
INSERT INTO data_books VALUES ('Lolita by Vladimir Nabokov','Lolita','Vladimir Nabokov','Vladimir','Nabokov',NULL,NULL);
INSERT INTO data_books VALUES ('Lord Foul''s Bane by Stephen R. Donaldson','Lord Foul''s Bane','Stephen R. Donaldson','Stephen','Donaldson',NULL,NULL);
INSERT INTO data_books VALUES ('Lord Loss by Darren Shan','Lord Loss','Darren Shan','Darren','Shan',NULL,NULL);
INSERT INTO data_books VALUES ('Lord of the Flies by William Golding','Lord of the Flies','William Golding','William','Golding',NULL,NULL);
INSERT INTO data_books VALUES ('Love''s Labour''s Lost by William Shakespeare','Love''s Labour''s Lost','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Lucifer by Mike Carey','Lucifer','Mike Carey','Mike','Carey',NULL,NULL);
INSERT INTO data_books VALUES ('Lullaby by Chuck Palahniuk','Lullaby','Chuck Palahniuk','Chuck','Palahniuk',NULL,NULL);
INSERT INTO data_books VALUES ('Macbeth by William Shakespeare','Macbeth','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Man and Superman by George Bernard Shaw','Man and Superman','George Bernard Shaw','George','Shaw',NULL,NULL);
INSERT INTO data_books VALUES ('Mansfield Park by Jane Austen','Mansfield Park','Jane Austen','Jane','Austen',NULL,NULL);
INSERT INTO data_books VALUES ('Martin Chuzzlewit by Charles Dickens','Martin Chuzzlewit','Charles Dickens','Charles','Dickens',NULL,NULL);
INSERT INTO data_books VALUES ('Maurice by E.M. Forster','Maurice','E.M. Forster','E.M.','Forster',NULL,NULL);
INSERT INTO data_books VALUES ('Maximum Ride: School''s Out Forever by James Patterson','Maximum Ride: School''s Out Forever','James Patterson','James','Patterson',NULL,NULL);
INSERT INTO data_books VALUES ('Maximum Ride: The Angel Experiment by James Patterson','Maximum Ride: The Angel Experiment','James Patterson','James','Patterson',NULL,NULL);
INSERT INTO data_books VALUES ('Measure for Measure by William Shakespeare','Measure for Measure','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Memoirs of a Geisha (novel) by Arthur Golden','Memoirs of a Geisha (novel)','Arthur Golden','Arthur','Golden',NULL,NULL);
INSERT INTO data_books VALUES ('Memoirs of Hadrian by Marguerite Yourcenar','Memoirs of Hadrian','Marguerite Yourcenar','Marguerite','Yourcenar',NULL,NULL);
INSERT INTO data_books VALUES ('Midnight''s Children by Salman Rushdie','Midnight''s Children','Salman Rushdie','Salman','Rushdie',NULL,NULL);
INSERT INTO data_books VALUES ('Moby-Dick by Herman Melville','Moby-Dick','Herman Melville','Herman','Melville',NULL,NULL);
INSERT INTO data_books VALUES ('Mockingjay by Suzanne Collins','Mockingjay','Suzanne Collins','Suzanne','Collins',NULL,NULL);
INSERT INTO data_books VALUES ('Moral Essays by Alexander Pope','Moral Essays','Alexander Pope','Alexander','Pope',NULL,NULL);
INSERT INTO data_books VALUES ('Much Ado About Nothing by William Shakespeare','Much Ado About Nothing','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Mudsong by Michael Spring','Mudsong','Michael Spring','Michael','Spring',NULL,NULL);
INSERT INTO data_books VALUES ('Mutant Message Down Under by Marlo Morgan','Mutant Message Down Under','Marlo Morgan','Marlo','Morgan',NULL,NULL);
INSERT INTO data_books VALUES ('Mysteries of Pittsburgh, The by Michael Chabon','Mysteries of Pittsburgh, The','Michael Chabon','Michael','Chabon',NULL,NULL);
INSERT INTO data_books VALUES ('Necessary Illusions by Noam Chomsky','Necessary Illusions','Noam Chomsky','Noam','Chomsky',NULL,NULL);
INSERT INTO data_books VALUES ('Never Any End to Paris by Enrique Vila-Matas','Never Any End to Paris','Enrique Vila-Matas','Enrique','Vila-Matas',NULL,NULL);
INSERT INTO data_books VALUES ('Nicholas Nickleby by Charles Dickens','Nicholas Nickleby','Charles Dickens','Charles','Dickens',NULL,NULL);
INSERT INTO data_books VALUES ('Night Shift by Stephen King','Night Shift','Stephen King','Stephen','King',NULL,NULL);
INSERT INTO data_books VALUES ('Nineteen Eighty-Four by George Orwell','Nineteen Eighty-Four','George Orwell','George','Orwell',NULL,NULL);
INSERT INTO data_books VALUES ('No Heroes by Danny O. Coulson and Elaine Shannon','No Heroes','Danny O. Coulson and Elaine Shannon','Danny','Coulson','Elaine','Shannon');
INSERT INTO data_books VALUES ('No Hope for Gomez! by Graham Parke','No Hope for Gomez!','Graham Parke','Graham','Parke',NULL,NULL);
INSERT INTO data_books VALUES ('Noli Me Tangere by Jose Rizal','Noli Me Tangere','Jose Rizal','Jose','Rizal',NULL,NULL);
INSERT INTO data_books VALUES ('Northanger Abbey by Jane Austen','Northanger Abbey','Jane Austen','Jane','Austen',NULL,NULL);
INSERT INTO data_books VALUES ('Notes from the Underground by Fyodor Dostoevsky','Notes from the Underground','Fyodor Dostoevsky','Fyodor','Dostoevsky',NULL,NULL);
INSERT INTO data_books VALUES ('Of Human Bondage by W. Somerset Maugham','Of Human Bondage','W. Somerset Maugham','W. Somerset ','Maugham',NULL,NULL);
INSERT INTO data_books VALUES ('On Moral Fiction by John Gardner','On Moral Fiction','John Gardner','John','Gardner',NULL,NULL);
INSERT INTO data_books VALUES ('On the Road by Jack Kerouac','On the Road','Jack Kerouac','Jack','Kerouac',NULL,NULL);
INSERT INTO data_books VALUES ('On Writing: A Memoir of the Craft by Stephen King','On Writing: A Memoir of the Craft','Stephen King','Stephen','King',NULL,NULL);
INSERT INTO data_books VALUES ('One Hundred Years of Solitude by Gabriel García Márquez','One Hundred Years of Solitude','Gabriel García Márquez','Gabriel','Márquez',NULL,NULL);
INSERT INTO data_books VALUES ('Orlando: A Biography by Virginia Woolf','Orlando: A Biography','Virginia Woolf','Virginia','Woolf',NULL,NULL);
INSERT INTO data_books VALUES ('Oryx and Crake by Margaret Atwood','Oryx and Crake','Margaret Atwood','Margaret','Atwood',NULL,NULL);
INSERT INTO data_books VALUES ('Othello by William Shakespeare','Othello','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Pan Tadeusz by Adam Mickiewicz','Pan Tadeusz','Adam Mickiewicz','Adam','Mickiewicz',NULL,NULL);
INSERT INTO data_books VALUES ('Panchatantra (authors unknown)','Panchatantra','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('Paradise Lost by John Milton','Paradise Lost','John Milton','John','Milton',NULL,NULL);
INSERT INTO data_books VALUES ('Paradise Regained by John Milton','Paradise Regained','John Milton','John','Milton',NULL,NULL);
INSERT INTO data_books VALUES ('Percy Jackson, 1-3 by Rick Riordan','Percy Jackson series','Rick Riordan','Rick','Riordan',NULL,NULL);
INSERT INTO data_books VALUES ('Pericles, Prince of Tyre by William Shakespeare','Pericles, Prince of Tyre','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Persuasion by Jane Austen','Persuasion','Jane Austen','Jane','Austen',NULL,NULL);
INSERT INTO data_books VALUES ('Peter Pan by J.M. Barrie','Peter Pan','J.M. Barrie','J.M.','Barrie',NULL,NULL);
INSERT INTO data_books VALUES ('Phaedo by Plato','Phaedo','Plato','Plato',NULL,NULL,NULL);
INSERT INTO data_books VALUES ('Pickwick Papers by Charles Dickens','Pickwick Papers','Charles Dickens','Charles','Dickens',NULL,NULL);
INSERT INTO data_books VALUES ('Pierre: or, The Ambiguities (1852) by Herman Melville','Pierre: or, The Ambiguities (1852)','Herman Melville','Herman','Melville',NULL,NULL);
INSERT INTO data_books VALUES ('Poor Man''s Pudding and Rich Man''s Crumbs by Herman Melville','Poor Man''s Pudding and Rich Man''s Crumbs','Herman Melville','Herman','Melville',NULL,NULL);
INSERT INTO data_books VALUES ('Pottermore by J. K. Rowling','Pottermore','J. K. Rowling','J. K.','Rowling',NULL,NULL);
INSERT INTO data_books VALUES ('Prayers for Rain by Dennis Lehane','Prayers for Rain','Dennis Lehane','Dennis','Lehane',NULL,NULL);
INSERT INTO data_books VALUES ('Prey by Michael Crichton','Prey','Michael Crichton','Michael','Crichton',NULL,NULL);
INSERT INTO data_books VALUES ('Pride and Prejudice by Jane Austen','Pride and Prejudice','Jane Austen','Jane','Austen',NULL,NULL);
INSERT INTO data_books VALUES ('Principia Discordia','Principia Discordia','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('Ptolemy''s Gate by Jonathan Stroud','Ptolemy''s Gate','Jonathan Stroud','Jonathan','Stroud',NULL,NULL);
INSERT INTO data_books VALUES ('Puckoon by Spike Milligan','Puckoon','Spike Milligan','Spike','Milligan',NULL,NULL);
INSERT INTO data_books VALUES ('Pudd''nhead Wilson by Mark Twain','Pudd''nhead Wilson','Mark Twain','Mark','Twain',NULL,NULL);
INSERT INTO data_books VALUES ('Queen of the Damned by Anne Rice','Queen of the Damned','Anne Rice','Anne','Rice',NULL,NULL);
INSERT INTO data_books VALUES ('Race on the Edge of Time, A by David E. Fisher','Race on the Edge of Time, A','David E. Fisher','David','Fisher',NULL,NULL);
INSERT INTO data_books VALUES ('Rain In Spain, The By Eduardo Paz-Martinez','Rain In Spain, The','Eduardo Paz-Martinez','Eduardo','Paz-Martinez',NULL,NULL);
INSERT INTO data_books VALUES ('Rainbow Six by Tom Clancy','Rainbow Six','Tom Clancy','Tom','Clancy',NULL,NULL);
INSERT INTO data_books VALUES ('Razor Wire Pubic Hair by Carlton Mellick III','Razor Wire Pubic Hair','Carlton Mellick III','Carlton','Mellick',NULL,NULL);
INSERT INTO data_books VALUES ('Ready Player One by Ernest Cline','Ready Player One','Ernest Cline','Ernest','Cline',NULL,NULL);
INSERT INTO data_books VALUES ('Red Seas Under Red Skies by Scott Lynch','Red Seas Under Red Skies','Scott Lynch','Scott','Lynch',NULL,NULL);
INSERT INTO data_books VALUES ('Redwall by Brian Jacques','Redwall','Brian Jacques','Brian','Jacques',NULL,NULL);
INSERT INTO data_books VALUES ('Reliques of Ancient English Poetry edited by Thomas Percy','Reliques of Ancient English Poetry edited','Thomas Percy','Thomas','Percy',NULL,NULL);
INSERT INTO data_books VALUES ('Return of the King, The by J. R. R. Tolkien','Return of the King, The','J. R. R. Tolkien','J. R. R.','Tolkien',NULL,NULL);
INSERT INTO data_books VALUES ('Richard II by William Shakespeare','Richard II','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Richard III by William Shakespeare','Richard III','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Road, The by Cormac McCarthy','Road, The','Cormac McCarthy','Cormac','McCarthy',NULL,NULL);
INSERT INTO data_books VALUES ('Romance and Reality by Letitia Elizabeth Landon','Romance and Reality','Letitia Elizabeth Landon','Letitia','Landon',NULL,NULL);
INSERT INTO data_books VALUES ('Romeo and Juliet by William Shakespeare','Romeo and Juliet','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Romulus, My Father by Raimond Gaita','Romulus, My Father','Raimond Gaita','Raimond','Gaita',NULL,NULL);
INSERT INTO data_books VALUES ('Run by Ann Patchett','Run','Ann Patchett','Ann','Patchett',NULL,NULL);
INSERT INTO data_books VALUES ('Sacred by Dennis Lehane','Sacred','Dennis Lehane','Dennis','Lehane',NULL,NULL);
INSERT INTO data_books VALUES ('Saint Genet: Actor and Martyr by Jean-Paul Sartre','Saint Genet: Actor and Martyr','Jean-Paul Sartre','Jean-Paul','Sartre',NULL,NULL);
INSERT INTO data_books VALUES ('Salem''s Lot by Stephen King','Salem''s Lot','Stephen King','Stephen','King',NULL,NULL);
INSERT INTO data_books VALUES ('Salterton Trilogy by Robertson Davies','Salterton Trilogy','Robertson Davies','Robertson','Davies',NULL,NULL);
INSERT INTO data_books VALUES ('Samson Agonistes by John Milton','Samson Agonistes','John Milton','John','Milton',NULL,NULL);
INSERT INTO data_books VALUES ('Sandman, The by Neil Gaiman','Sandman, The','Neil Gaiman','Neil','Gaiman',NULL,NULL);
INSERT INTO data_books VALUES ('Scarlet Pimpernel, The by Baroness Emmuska Orczy','Scarlet Pimpernel, The','Baroness Emmuska Orczy','Baroness','Orczy',NULL,NULL);
INSERT INTO data_books VALUES ('Seafarer, The','Seafarer, The','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('Secret Garden, The by Frances Hodgson Burnett','Secret Garden, The','Frances Hodgson Burnett','Frances','Burnett',NULL,NULL);
INSERT INTO data_books VALUES ('Sense and Sensibility by Jane Austen','Sense and Sensibility','Jane Austen','Jane','Austen',NULL,NULL);
INSERT INTO data_books VALUES ('Series of Unfortunate Events, A by Lemony Snicket','Series of Unfortunate Events, A','Lemony Snicket','Lemony','Snicket',NULL,NULL);
INSERT INTO data_books VALUES ('Shantaram by David Gregory Roberts','Shantaram','David Gregory Roberts','David','Roberts',NULL,NULL);
INSERT INTO data_books VALUES ('Shogun (1975) by James Clavell','Shogun (1975)','James Clavell','James','Clavell',NULL,NULL);
INSERT INTO data_books VALUES ('Showdown at Two-Bit Creek (2003) by Ralph Compton & Joseph A. West','Showdown at Two-Bit Creek (2003)','Ralph Compton & Joseph A. West','Ralph','Compton','Joseph','West');
INSERT INTO data_books VALUES ('Shutter Island by Dennis Lehane','Shutter Island','Dennis Lehane','Dennis','Lehane',NULL,NULL);
INSERT INTO data_books VALUES ('Sickness Unto Death, The by Søren Kierkegaard','Sickness Unto Death, The','Søren Kierkegaard','Søren','Kierkegaard',NULL,NULL);
INSERT INTO data_books VALUES ('Silence Speaks (1977) by Baba Hari Dass','Silence Speaks (1977)','Baba Hari Dass','Baba','Dass',NULL,NULL);
INSERT INTO data_books VALUES ('Silmarillion, The (1977) by J. R. R. Tolkien','Silmarillion, The (1977)','J. R. R. Tolkien','J. R. R.','Tolkien',NULL,NULL);
INSERT INTO data_books VALUES ('Sisterhood of the Traveling Pants, The by Ann Brashares','Sisterhood of the Traveling Pants, The','Ann Brashares','Ann','Brashares',NULL,NULL);
INSERT INTO data_books VALUES ('Slaughterhouse-Five by Kurt Vonnegut','Slaughterhouse-Five','Kurt Vonnegut','Kurt','Vonnegut',NULL,NULL);
INSERT INTO data_books VALUES ('Slawter by Darren Shan','Slawter','Darren Shan','Darren','Shan',NULL,NULL);
INSERT INTO data_books VALUES ('Snow Crash by Neal Stephenson','Snow Crash','Neal Stephenson','Neal','Stephenson',NULL,NULL);
INSERT INTO data_books VALUES ('Something Happened by Joseph Heller','Something Happened','Joseph Heller','Joseph','Heller',NULL,NULL);
INSERT INTO data_books VALUES ('Soon I Will Be Invincible by Austin Grossman','Soon I Will Be Invincible','Austin Grossman','Austin','Grossman',NULL,NULL);
INSERT INTO data_books VALUES ('Star Wars series by George Lucas','Star Wars series','George Lucas','George','Lucas',NULL,NULL);
INSERT INTO data_books VALUES ('Starship Troopers (1959) by Robert A. Heinlein','Starship Troopers (1959)','Robert A. Heinlein','Robert','Heinlein',NULL,NULL);
INSERT INTO data_books VALUES ('Strange Meeting (book) by Susan Hill','Strange Meeting (book)','Susan Hill','Susan','Hill',NULL,NULL);
INSERT INTO data_books VALUES ('Stranger in a Strange Land (1961) by Robert A. Heinlein','Stranger in a Strange Land (1961)','Robert A. Heinlein','Robert','Heinlein',NULL,NULL);
INSERT INTO data_books VALUES ('Success Through a Positive Mental Attitude (1960) by Napoleon Hill and W. Clement Stone','Success Through a Positive Mental Attitude (1960)','Napoleon Hill and W. Clement Stone','Napoleon','Hill','W. Clement','Stone');
INSERT INTO data_books VALUES ('Summer Book, A by Tove Jansson','Summer Book, A','Tove Jansson','Tove','Jansson',NULL,NULL);
INSERT INTO data_books VALUES ('Survivor by Chuck Palahniuk','Survivor','Chuck Palahniuk','Chuck','Palahniuk',NULL,NULL);
INSERT INTO data_books VALUES ('Sybil (1845) by Benjamin Disraeli','Sybil (1845)','Benjamin Disraeli','Benjamin','Disraeli',NULL,NULL);
INSERT INTO data_books VALUES ('Tender is the Night by F. Scott Fitzgerald','Tender is the Night','F. Scott Fitzgerald','F. Scott','Fitzgerald',NULL,NULL);
INSERT INTO data_books VALUES ('That Hideous Strength by C.S. Lewis','That Hideous Strength','C.S. Lewis','C.S.','Lewis',NULL,NULL);
INSERT INTO data_books VALUES ('The Art Of Racing In The Rain by Garth Stein','The Art Of Racing In The Rain','Garth Stein','Garth','Stein',NULL,NULL);
INSERT INTO data_books VALUES ('The Ballad of the White Horse by G. K. Chesterton','The Ballad of the White Horse','G. K. Chesterton','G. K.','Chesterton',NULL,NULL);
INSERT INTO data_books VALUES ('The Battle of Malden by an unknown poet','The Battle of Malden','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('The Battle of the Labyrinth by Rick Riordan','The Battle of the Labyrinth','Rick Riordan','Rick','Riordan',NULL,NULL);
INSERT INTO data_books VALUES ('The Beekeeper''s Apprentice by Laurie R. King','The Beekeeper''s Apprentice','Laurie R. King','Laurie','King',NULL,NULL);
INSERT INTO data_books VALUES ('The Bible','The Bible','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('The Book of Mormon by various authors','The Book of Mormon','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('The Book of the New Sun by Gene Wolfe','The Book of the New Sun','Gene Wolfe','Gene','Wolfe',NULL,NULL);
INSERT INTO data_books VALUES ('The Book Thief by Markus Zusak','The Book Thief','Markus Zusak','Markus','Zusak',NULL,NULL);
INSERT INTO data_books VALUES ('The Books of Magic by Neil Gaiman','The Books of Magic','Neil Gaiman','Neil','Gaiman',NULL,NULL);
INSERT INTO data_books VALUES ('The Catcher in the Rye by J. D. Salinger','The Catcher in the Rye','J. D. Salinger','J. D.','Salinger',NULL,NULL);
INSERT INTO data_books VALUES ('The Children of Húrin by J.R.R. Tolkien','The Children of Húrin','J.R.R. Tolkien','J. R. R.','Tolkien',NULL,NULL);
INSERT INTO data_books VALUES ('The Chomsky Reader by Noam Chomsky','The Chomsky Reader','Noam Chomsky','Noam','Chomsky',NULL,NULL);
INSERT INTO data_books VALUES ('The Chronicles of Narnia by C. S. Lewis','The Chronicles of Narnia','C. S. Lewis','C.S.','Lewis',NULL,NULL);
INSERT INTO data_books VALUES ('The Cloud of Unknowing','The Cloud of Unknowing','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('The Comedy of Errors by William Shakespeare','The Comedy of Errors','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('The Conan the Barbarian series by various authors.','The Conan the Barbarian series','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('The Confidence-Man by Herman Melville','The Confidence-Man','Herman Melville','Herman','Melville',NULL,NULL);
INSERT INTO data_books VALUES ('The Count of Monte Cristo by Alexandre Dumas','The Count of Monte Cristo','Alexandre Dumas','Alexandre','Dumas',NULL,NULL);
INSERT INTO data_books VALUES ('The Country Wife by William Wycherley','The Country Wife','William Wycherley','William','Wycherley',NULL,NULL);
INSERT INTO data_books VALUES ('The Demonata by Darren Shan','The Demonata','Darren Shan','Darren','Shan',NULL,NULL);
INSERT INTO data_books VALUES ('The Dharma Bums by Jack Kerouac','The Dharma Bums','Jack Kerouac','Jack','Kerouac',NULL,NULL);
INSERT INTO data_books VALUES ('The Diamond Age by Neal Stephenson','The Diamond Age','Neal Stephenson','Neal','Stephenson',NULL,NULL);
INSERT INTO data_books VALUES ('The Discworld Novels by Terry Pratchett','The Discworld Novels','Terry Pratchett','Terry','Pratchett',NULL,NULL);
INSERT INTO data_books VALUES ('The Dispossessed by Ursula K. Le Guin','The Dispossessed','Ursula K. Le Guin','Ursula','Guin',NULL,NULL);
INSERT INTO data_books VALUES ('The Dunciad by Alexander Pope','The Dunciad','Alexander Pope','Alexander','Pope',NULL,NULL);
INSERT INTO data_books VALUES ('The DUNE Chronicles by Frank Herbert','The DUNE Chronicles','Frank Herbert','Frank','Herbert',NULL,NULL);
INSERT INTO data_books VALUES ('The Elements of Style by William Strunk, Jr. and E. B. White','The Elements of Style','William Strunk, Jr. and E. B. White','William','Strunk','E. B.','White');
INSERT INTO data_books VALUES ('The Encantadas Herman Melville','The Encantadas ','Herman Melville','Herman','Melville',NULL,NULL);
INSERT INTO data_books VALUES ('The Fellowship of the Ring by J. R. R. Tolkien','The Fellowship of the Ring','J. R. R. Tolkien','J. R. R.','Tolkien',NULL,NULL);
INSERT INTO data_books VALUES ('The Filth by Grant Morrison','The Filth','Grant Morrison','Grant','Morrison',NULL,NULL);
INSERT INTO data_books VALUES ('The Fixer by Bernard Malamud','The Fixer','Bernard Malamud','Bernard','Malamud',NULL,NULL);
INSERT INTO data_books VALUES ('The Foundation Series by Isaac Asimov','The Foundation Series','Isaac Asimov','Isaac','Asimov',NULL,NULL);
INSERT INTO data_books VALUES ('The Fountainhead by Ayn Rand','The Fountainhead','Ayn Rand','Ayn','Rand',NULL,NULL);
INSERT INTO data_books VALUES ('The Giver by Lois Lowry','The Giver','Lois Lowry','Lois','Lowry',NULL,NULL);
INSERT INTO data_books VALUES ('The God of Small Things by Arundhati Roy','The God of Small Things','Arundhati Roy','Arundhati','Roy',NULL,NULL);
INSERT INTO data_books VALUES ('The Golem''s Eye by Jonathan Stroud','The Golem''s Eye','Jonathan Stroud','Jonathan','Stroud',NULL,NULL);
INSERT INTO data_books VALUES ('The Grapes of Wrath by John Steinbeck','The Grapes of Wrath','John Steinbeck','John','Steinbeck',NULL,NULL);
INSERT INTO data_books VALUES ('The Great Gatsby by F. Scott Fitzgerald','The Great Gatsby','F. Scott Fitzgerald','F. Scott','Fitzgerald',NULL,NULL);
INSERT INTO data_books VALUES ('The Gunslinger by Stephen King','The Gunslinger','Stephen King','Stephen','King',NULL,NULL);
INSERT INTO data_books VALUES ('The Harry Potter series by J.K. Rowling','The Harry Potter series','J.K. Rowling','J.K.','Rowling',NULL,NULL);
INSERT INTO data_books VALUES ('The Help by Kathyrn Stockett','The Help','Kathyrn Stockett','Kathyrn','Stockett',NULL,NULL);
INSERT INTO data_books VALUES ('The History of the Decline and Fall of the Roman Empire by Edward Gibbon','The History of the Decline and Fall of the Roman Empire','Edward Gibbon','Edward','Gibbon',NULL,NULL);
INSERT INTO data_books VALUES ('The Hitchhiker''s Guide to the Galaxy by Douglas Adams','The Hitchhiker''s Guide to the Galaxy','Douglas Adams','Douglas','Adams',NULL,NULL);
INSERT INTO data_books VALUES ('The Hobbit by J.R.R. Tolkien','The Hobbit','J.R.R. Tolkien','J. R. R.','Tolkien',NULL,NULL);
INSERT INTO data_books VALUES ('The Hours by Michael Cunningham','The Hours','Michael Cunningham','Michael','Cunningham',NULL,NULL);
INSERT INTO data_books VALUES ('The House in Paris by Elizabeth Bowen','The House in Paris','Elizabeth Bowen','Elizabeth','Bowen',NULL,NULL);
INSERT INTO data_books VALUES ('The House of God by Samuel Shem','The House of God','Samuel Shem','Samuel','Shem',NULL,NULL);
INSERT INTO data_books VALUES ('The Human Stain by Philip Roth','The Human Stain','Philip Roth','Philip','Roth',NULL,NULL);
INSERT INTO data_books VALUES ('The Humanoids by Jack Williamson','The Humanoids','Jack Williamson','Jack','Williamson',NULL,NULL);
INSERT INTO data_books VALUES ('The Hunchback of Notre Dame by Victor Hugo','The Hunchback of Notre Dame','Victor Hugo','Victor','Hugo',NULL,NULL);
INSERT INTO data_books VALUES ('The Iliad of Homer by Alexander Pope','The Iliad of Homer','Alexander Pope','Alexander','Pope',NULL,NULL);
INSERT INTO data_books VALUES ('The Invisibles by Grant Morrison','The Invisibles','Grant Morrison','Grant','Morrison',NULL,NULL);
INSERT INTO data_books VALUES ('The Jungle by Upton Sinclair','The Jungle','Upton Sinclair','Upton','Sinclair',NULL,NULL);
INSERT INTO data_books VALUES ('The Kalevala','The Kalevala','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('The Kite Runner by Khaled Hosseini','The Kite Runner','Khaled Hosseini','Khaled','Hosseini',NULL,NULL);
INSERT INTO data_books VALUES ('The Last September by Elizabeth Bowen','The Last September','Elizabeth Bowen','Elizabeth','Bowen',NULL,NULL);
INSERT INTO data_books VALUES ('The Last Summer (of You and Me) by Ann Brashares','The Last Summer (of You and Me)','Ann Brashares','Ann','Brashares',NULL,NULL);
INSERT INTO data_books VALUES ('The Last Unicorn by Peter S. Beagle','The Last Unicorn','Peter S. Beagle','Peter','Beagle',NULL,NULL);
INSERT INTO data_books VALUES ('The Lightning Thief by Rick Riordan','The Lightning Thief','Rick Riordan','Rick','Riordan',NULL,NULL);
INSERT INTO data_books VALUES ('The Little Golden Calf, by Ilf and Petrov','The Little Golden Calf','Ilf and Petrov',NULL,'Ilf',NULL,'Petrov');
INSERT INTO data_books VALUES ('The Little Prince by Antoine de Saint-Exupéry','The Little Prince','Antoine de Saint-Exupéry','Antoine','Saint-Exupéry',NULL,NULL);
INSERT INTO data_books VALUES ('The Lord of the Rings by J.R.R. Tolkien','The Lord of the Rings','J.R.R. Tolkien','J. R. R.','Tolkien',NULL,NULL);
INSERT INTO data_books VALUES ('The Lost World by Michael Crichton','The Lost World','Michael Crichton','Michael','Crichton',NULL,NULL);
INSERT INTO data_books VALUES ('The Lovely Bones by Alice Sebold','The Lovely Bones','Alice Sebold','Alice','Sebold',NULL,NULL);
INSERT INTO data_books VALUES ('The Mabinogion','The Mabinogion','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('The Malazan Book of the Fallen by Steven Erikson','The Malazan Book of the Fallen','Steven Erikson','Steven','Erikson',NULL,NULL);
INSERT INTO data_books VALUES ('The Man Who Was Thursday by G.K. Chesterton','The Man Who Was Thursday','G.K. Chesterton','G.K.','Chesterton',NULL,NULL);
INSERT INTO data_books VALUES ('The Maze Runner by James Dashner','The Maze Runner','James Dashner','James','Dashner',NULL,NULL);
INSERT INTO data_books VALUES ('The Mediator Series by Meg Cabot','The Mediator Series','Meg Cabot','Meg','Cabot',NULL,NULL);
INSERT INTO data_books VALUES ('The Merchant of Venice by William Shakespeare','The Merchant of Venice','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('The Merry Wives of Windsor by William Shakespeare','The Merry Wives of Windsor','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('The Moon Is a Harsh Mistress by Robert A. Heinlein','The Moon Is a Harsh Mistress','Robert A. Heinlein','Robert','Heinlein',NULL,NULL);
INSERT INTO data_books VALUES ('The Nero Wolfe corpus by Rex Stout','The Nero Wolfe corpus','Rex Stout','Rex','Stout',NULL,NULL);
INSERT INTO data_books VALUES ('The Nibelungenlied','The Nibelungenlied','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('The Night World Series by Lisa Jane Smith','The Night World Series','Lisa Jane Smith','Lisa','Smith',NULL,NULL);
INSERT INTO data_books VALUES ('The Ninth Gate by Arturo Pérez-Reverte','The Ninth Gate','Arturo Pérez-Reverte','Arturo','Pérez-Reverte',NULL,NULL);
INSERT INTO data_books VALUES ('The Noonday Devil Alan Judd','The Noonday Devil ','Alan Judd','Alan','Judd',NULL,NULL);
INSERT INTO data_books VALUES ('The Odyssey of Homer by Alexander Pope','The Odyssey of Homer','Alexander Pope','Alexander','Pope',NULL,NULL);
INSERT INTO data_books VALUES ('The Old Man and the Sea by Ernest Hemingway','The Old Man and the Sea','Ernest Hemingway','Ernest','Hemingway',NULL,NULL);
INSERT INTO data_books VALUES ('The Once and Future King by T. H. White','The Once and Future King','T. H. White','T. H.','White',NULL,NULL);
INSERT INTO data_books VALUES ('The Owl and the Nightingale','The Owl and the Nightingale','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('The Phantom Tollbooth by Norton Juster','The Phantom Tollbooth','Norton Juster','Norton','Juster',NULL,NULL);
INSERT INTO data_books VALUES ('The Picture of Dorian Gray by Oscar Wilde','The Picture of Dorian Gray','Oscar Wilde','Oscar','Wilde',NULL,NULL);
INSERT INTO data_books VALUES ('The Power Of One by Bryce Courtenay','The Power Of One','Bryce Courtenay','Bryce','Courtenay',NULL,NULL);
INSERT INTO data_books VALUES ('The Prime Minister by Anthony Trollope','The Prime Minister','Anthony Trollope','Anthony','Trollope',NULL,NULL);
INSERT INTO data_books VALUES ('The Prince by Niccolo Machiavelli','The Prince','Niccolo Machiavelli','Niccolo','Machiavelli',NULL,NULL);
INSERT INTO data_books VALUES ('The Princess Bride by William Goldman','The Princess Bride','William Goldman','William','Goldman',NULL,NULL);
INSERT INTO data_books VALUES ('The Prisoner of Zenda by Anthony Hope','The Prisoner of Zenda','Anthony Hope','Anthony','Hope',NULL,NULL);
INSERT INTO data_books VALUES ('The Prophet by Khalil Gibran','The Prophet','Khalil Gibran','Khalil','Gibran',NULL,NULL);
INSERT INTO data_books VALUES ('The Saga of Darren Shan book 1-12 by Darren Shan','The Saga of Darren Shan book 1-12','Darren Shan','Darren','Shan',NULL,NULL);
INSERT INTO data_books VALUES ('The Sea of Monsters by Rick Riordan','The Sea of Monsters','Rick Riordan','Rick','Riordan',NULL,NULL);
INSERT INTO data_books VALUES ('The Sherlock Holmes Series of Stories by Arthur Conan Doyle','The Sherlock Holmes Series of Stories','Arthur Conan Doyle','Arthur','Doyle',NULL,NULL);
INSERT INTO data_books VALUES ('The Shipping News by Annie Proulx','The Shipping News','Annie Proulx','Annie','Proulx',NULL,NULL);
INSERT INTO data_books VALUES ('The Sisters Grimm by Michael Buckley','The Sisters Grimm','Michael Buckley','Michael','Buckley',NULL,NULL);
INSERT INTO data_books VALUES ('The Song of Roland','The Song of Roland','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('The Song of Sin by Phil Duncan','The Song of Sin','Phil Duncan','Phil','Duncan',NULL,NULL);
INSERT INTO data_books VALUES ('The Sonnets by William Shakespeare','The Sonnets','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('The Sorrows of Young Werther by Johann Wolfgang von Goethe','The Sorrows of Young Werther','Johann Wolfgang von Goethe','Johann','Goethe',NULL,NULL);
INSERT INTO data_books VALUES ('The Spiderwick Chronicles by Holly Black','The Spiderwick Chronicles','Holly Black','Holly','Black',NULL,NULL);
INSERT INTO data_books VALUES ('The Stone Carvers by Jane Urquhart','The Stone Carvers','Jane Urquhart','Jane','Urquhart',NULL,NULL);
INSERT INTO data_books VALUES ('The Summoning by Kelley Armstrong','The Summoning','Kelley Armstrong','Kelley','Armstrong',NULL,NULL);
INSERT INTO data_books VALUES ('The Tale of Despereaux by Kate DiCamillo','The Tale of Despereaux','Kate DiCamillo','Kate','DiCamillo',NULL,NULL);
INSERT INTO data_books VALUES ('The Taming of the Shrew by William Shakespeare','The Taming of the Shrew','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('The Telling by Ursula K. Le Guin','The Telling','Ursula K. Le Guin','Ursula','Guin',NULL,NULL);
INSERT INTO data_books VALUES ('The Tempest by William Shakespeare','The Tempest','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('The Time Machine by H. G. Wells','The Time Machine','H. G. Wells','H. G.','Wells',NULL,NULL);
INSERT INTO data_books VALUES ('The Titan''s Curse by Rick Riordan','The Titan''s Curse','Rick Riordan','Rick','Riordan',NULL,NULL);
INSERT INTO data_books VALUES ('The Two Noble Kinsmen by William Shakespeare and John Fletcher','The Two Noble Kinsmen','William Shakespeare and John Fletcher','William','Shakespeare','John','Fletcher');
INSERT INTO data_books VALUES ('The Two Towers by J. R. R. Tolkien','The Two Towers','J. R. R. Tolkien','J. R. R.','Tolkien',NULL,NULL);
INSERT INTO data_books VALUES ('The Waiting Years by Fumiko Enchi','The Waiting Years','Fumiko Enchi','Fumiko','Enchi',NULL,NULL);
INSERT INTO data_books VALUES ('The Walking Drum by Louis L''Amour','The Walking Drum','Louis L''Amour','Louis','L''Amour',NULL,NULL);
INSERT INTO data_books VALUES ('The Warrior Prophet by R. Scott Bakker','The Warrior Prophet','R. Scott Bakker','R. Scott','Bakker',NULL,NULL);
INSERT INTO data_books VALUES ('The Wheel of Time by Robert Jordan','The Wheel of Time','Robert Jordan','Robert','Jordan',NULL,NULL);
INSERT INTO data_books VALUES ('The Wind in the Willows by Kenneth Grahame','The Wind in the Willows','Kenneth Grahame','Kenneth','Grahame',NULL,NULL);
INSERT INTO data_books VALUES ('Things Fall Apart by Chinua Achebe','Things Fall Apart','Chinua Achebe','Chinua','Achebe',NULL,NULL);
INSERT INTO data_books VALUES ('This Other Eden by Ben Elton','This Other Eden','Ben Elton','Ben','Elton',NULL,NULL);
INSERT INTO data_books VALUES ('Through the Looking-Glass by Lewis Carroll','Through the Looking-Glass','Lewis Carroll','Lewis','Carroll',NULL,NULL);
INSERT INTO data_books VALUES ('Thus Spoke Zarathustra by Friedrich Nietzsche','Thus Spoke Zarathustra','Friedrich Nietzsche','Friedrich','Nietzsche',NULL,NULL);
INSERT INTO data_books VALUES ('Timon of Athens by William Shakespeare','Timon of Athens','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Tithe by Holly Black','Tithe','Holly Black','Holly','Black',NULL,NULL);
INSERT INTO data_books VALUES ('Titus Andronicus by William Shakespeare','Titus Andronicus','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('To Charles Fort, With Love (2005) by Caitlín R. Kiernan','To Charles Fort, With Love (2005)','Caitlín R. Kiernan','Caitlín','Kiernan',NULL,NULL);
INSERT INTO data_books VALUES ('To Kill a Mockingbird by Harper Lee','To Kill a Mockingbird','Harper Lee','Harper','Lee',NULL,NULL);
INSERT INTO data_books VALUES ('Tom Brown''s School Days by Thomas Hughes','Tom Brown''s School Days','Thomas Hughes','Thomas','Hughes',NULL,NULL);
INSERT INTO data_books VALUES ('Troilus and Cressida by William Shakespeare','Troilus and Cressida','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Tropic of Cancer by Henry Miller','Tropic of Cancer','Henry Miller','Henry','Miller',NULL,NULL);
INSERT INTO data_books VALUES ('Tuesdays with Morrie by Mitch Albom','Tuesdays with Morrie','Mitch Albom','Mitch','Albom',NULL,NULL);
INSERT INTO data_books VALUES ('Twelfth Night by William Shakespeare','Twelfth Night','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Two Gentlemen of Verona by William Shakespeare','Two Gentlemen of Verona','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Ubu Roi by Alfred Jarry','Ubu Roi','Alfred Jarry','Alfred','Jarry',NULL,NULL);
INSERT INTO data_books VALUES ('Ulysses by James Joyce','Ulysses','James Joyce','James','Joyce',NULL,NULL);
INSERT INTO data_books VALUES ('Uncle Sam by Steve Darnell and Alex Ross','Uncle Sam','Steve Darnell and Alex Ross','Steve','Darnell','Alex','Ross');
INSERT INTO data_books VALUES ('Unwind by Neal Schusterman','Unwind','Neal Schusterman','Neal','Schusterman',NULL,NULL);
INSERT INTO data_books VALUES ('V for Vendetta by Alan Moore','V for Vendetta','Alan Moore','Alan','Moore',NULL,NULL);
INSERT INTO data_books VALUES ('Valiant by Holly Black','Valiant','Holly Black','Holly','Black',NULL,NULL);
INSERT INTO data_books VALUES ('Vanishing Acts by Jodi Picoult','Vanishing Acts','Jodi Picoult','Jodi','Picoult',NULL,NULL);
INSERT INTO data_books VALUES ('Venus and Adonis by William Shakespeare','Venus and Adonis','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Vernon God Little by DBC Pierre','Vernon God Little','DBC Pierre','DBC','Pierre',NULL,NULL);
INSERT INTO data_books VALUES ('Waiting for Godot by Samuel Beckett','Waiting for Godot','Samuel Beckett','Samuel','Beckett',NULL,NULL);
INSERT INTO data_books VALUES ('Walden by Henry David Thoreau','Walden','Henry David Thoreau','Henry','Thoreau',NULL,NULL);
INSERT INTO data_books VALUES ('War and Peace By Leo Tolstoy','War and Peace','Leo Tolstoy','Leo','Tolstoy',NULL,NULL);
INSERT INTO data_books VALUES ('Watchmen by Alan Moore','Watchmen','Alan Moore','Alan','Moore',NULL,NULL);
INSERT INTO data_books VALUES ('Watership Down by Richard Adams','Watership Down','Richard Adams','Richard','Adams',NULL,NULL);
INSERT INTO data_books VALUES ('We are Greeks! by Dimitris Varos','We are Greeks!','Dimitris Varos','Dimitris','Varos',NULL,NULL);
INSERT INTO data_books VALUES ('We by Yevgeny Zamyatin','We','Yevgeny Zamyatin','Yevgeny','Zamyatin',NULL,NULL);
INSERT INTO data_books VALUES ('We Need To Talk About Kevin by Lionel Shriver','We Need To Talk About Kevin','Lionel Shriver','Lionel','Shriver',NULL,NULL);
INSERT INTO data_books VALUES ('We the Living by Ayn Rand','We the Living','Ayn Rand','Ayn','Rand',NULL,NULL);
INSERT INTO data_books VALUES ('Wesele (The Wedding) by Stanislaw Wyspianski','Wesele (The Wedding)','Stanislaw Wyspianski','Stanislaw','Wyspianski',NULL,NULL);
INSERT INTO data_books VALUES ('When Rain Clouds Gather by Bessie Head','When Rain Clouds Gather','Bessie Head','Bessie','Head',NULL,NULL);
INSERT INTO data_books VALUES ('White Fang by Jack London','White Fang','Jack London','Jack','London',NULL,NULL);
INSERT INTO data_books VALUES ('White Noise by Don DeLillo','White Noise','Don DeLillo','Don','DeLillo',NULL,NULL);
INSERT INTO data_books VALUES ('White Oleander by Janet Fitch','White Oleander','Janet Fitch','Janet','Fitch',NULL,NULL);
INSERT INTO data_books VALUES ('White-Jacket by Herman Melville','White-Jacket','Herman Melville','Herman','Melville',NULL,NULL);
INSERT INTO data_books VALUES ('Wicked by Gregory Maguire','Wicked','Gregory Maguire','Gregory','Maguire',NULL,NULL);
INSERT INTO data_books VALUES ('Widsith','Widsith','-',NULL,NULL,NULL,NULL);
INSERT INTO data_books VALUES ('Winnie-the-Pooh by A. A. Milne','Winnie-the-Pooh','A. A. Milne','A. A.','Milne',NULL,NULL);
INSERT INTO data_books VALUES ('Winter''s Tale, The by William Shakespeare','Winter''s Tale, The','William Shakespeare','William','Shakespeare',NULL,NULL);
INSERT INTO data_books VALUES ('Wolf Island by Darren Shan','Wolf Island','Darren Shan','Darren','Shan',NULL,NULL);
INSERT INTO data_books VALUES ('World War Z by Max Brooks','World War Z','Max Brooks','Max','Brooks',NULL,NULL);
INSERT INTO data_books VALUES ('Wuthering Heights by Emily Bronte','Wuthering Heights','Emily Bronte','Emily','Bronte',NULL,NULL);
INSERT INTO data_books VALUES ('Yellow Wallpaper, The by Charlotte Gilman','Yellow Wallpaper, The','Charlotte Gilman','Charlotte','Gilman',NULL,NULL);
INSERT INTO data_books VALUES ('Yo-Yo Boing! by Giannina Braschi','Yo-Yo Boing!','Giannina Braschi','Giannina','Braschi',NULL,NULL);
INSERT INTO data_books VALUES ('Zorba the Greek by Nikos Kazantzakis','Zorba the Greek','Nikos Kazantzakis','Nikos','Kazantzakis',NULL,NULL);
